# Tableau and player form

Here we create a csv file that is used for making further Tableau visualizations.

In [1]:
# recent gameweek
gameweek = 21

In [2]:
# import basic libraries
import pandas as pd
import numpy as np

pd.set_option('max_columns',100)

In [3]:
# fetch player stats data
all_df = pd.read_csv('../data/fpl/data_week1.csv', index_col=0)
all_df['gameweek'] = 1
all_df['xPoints'] = all_df['adjusted points']

for week in range(2,gameweek+1):
    filepath = '../data/fpl/data_week' + str(week) + '.csv'
    df = pd.read_csv(filepath, index_col=0)
    df['gameweek'] = week
    column_name = 'xPoints week ' + str(week)
    df['xPoints'] = df[column_name]
    all_df = all_df.append(df,sort='False')

all_df.shape

(13131, 286)

In [4]:
# calculate player form
for i in [5,10,15,20]:
    gameweeks = np.arange(gameweek-i+1,gameweek+1)
    column_name = 'form ' + str(i)
    all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].count()
    
    #    all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / all_df.loc[(all_df['gameweek']==gameweek),'games played']
    #else:    
    #    all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / (all_df.loc[(all_df['gameweek']==gameweek),'games played'] - all_df.loc[(all_df['gameweek']==gameweek-i),'games played'] )
    
    # dirty fix in case there are inf results
    #all_df.loc[(all_df['gameweek']==gameweek) & np.isinf(all_df[column_name]), column_name] = np.nan

In [5]:
# top form players
all_df[all_df['gameweek']==gameweek][['web_name', 'games played','total_points', 'points_per_game','adjusted points','adjusted points per game',\
                                'form 5', 'form 10', 'form 15', 'form 20']].sort_values(by=['form 5'], ascending=False).head(20)

,web_name,games played,total_points,points_per_game,adjusted points,adjusted points per game,form 5,form 10,form 15,form 20
id,,,,,,,,,,
420,Bowen,21.0,115,5.5,112.317126,5.348435,8.896662,6.243277,6.274292,5.644412
254,Mahrez,16.0,77,4.8,74.454685,4.653418,8.721361,5.860218,5.077239,4.468042
359,Son,17.0,108,6.4,99.803942,5.870820,7.643228,6.931357,6.507269,5.961346
255,Sterling,17.0,77,4.5,84.774415,4.986730,7.255869,7.399744,5.878712,5.014760
40,Watkins,16.0,63,3.9,63.142000,3.946375,6.785500,4.738714,4.153500,3.946375
213,Iheanacho,14.0,44,3.1,42.084000,3.006000,6.721000,3.860500,3.876625,3.160308
341,Ward-Prowse,18.0,77,4.3,70.040745,3.891153,6.512135,4.581782,4.123509,4.061182
588,Emerson Royal,14.0,44,3.1,52.267514,3.733394,6.498662,5.881567,4.753847,4.245430
122,Alonso,15.0,71,4.7,75.133925,5.008928,6.314410,5.024225,5.024225,4.845051
26,Martinelli,13.0,57,4.4,48.471033,3.728541,6.223716,4.839857,3.953623,3.795406
251,De Bruyne,15.0,67,4.5,67.426954,4.495130,6.196853,4.826323,4.701384,4.489816
237,Alexander-Arnold,18.0,132,7.3,122.731975,6.818443,6.189047,7.699710,7.143156,7.286770
357,Kane,17.0,53,3.1,72.791000,4.281824,6.100000,5.528571,5.055917,4.310059
437,Semedo,17.0,66,3.9,65.734880,3.866758,6.014400,4.760405,4.045385,4.149437
408,Fabianski,21.0,78,3.7,83.060502,3.955262,5.981649,4.688369,4.504408,4.289929
431,Saïss,19.0,81,4.3,70.503690,3.710721,5.975372,4.440019,4.072457,4.017189
6,Lacazette,15.0,46,3.1,45.753000,3.050200,5.953250,3.890333,3.265214,3.114200
22,Saka,20.0,93,4.7,79.513512,3.975676,5.891466,4.698285,4.233950,4.200156
367,Sánchez,12.0,63,5.2,48.497012,4.041418,5.830912,5.056358,5.056358,4.452132
234,Robertson,14.0,69,4.9,63.149536,4.510681,5.799906,6.179623,4.893715,4.741970

In [6]:
# save data
filepath = '../data/fpl/all_data.csv'
all_df.to_csv(filepath)

filepath = '../data/fpl/data_week' + str(gameweek) + '.csv'
all_df[all_df['gameweek']==gameweek].to_csv(filepath)