# Tableau and player form

Here we create a csv file that is used for making further Tableau visualizations.

In [1]:
# recent gameweek
gameweek = 38

In [2]:
# import basic libraries
import pandas as pd
import numpy as np

pd.set_option('max_columns',100)

In [3]:
# fetch player stats data
all_df = pd.read_csv('../data/fpl/data_week1.csv', index_col=0)
all_df['gameweek'] = 1
all_df['xPoints'] = all_df['adjusted points']

for week in range(2,gameweek+1):
    filepath = '../data/fpl/data_week' + str(week) + '.csv'
    df = pd.read_csv(filepath, index_col=0)
    df['gameweek'] = week
    column_name = 'xPoints week ' + str(week)
    df['xPoints'] = df[column_name]
    all_df = all_df.append(df,sort='False')

all_df.shape

(25335, 439)

In [4]:
# calculate player form
for i in [5,10,15,20]:
    gameweeks = np.arange(gameweek-i+1,gameweek+1)
    column_name = 'form ' + str(i)
    all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].count()
    
    #    all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / all_df.loc[(all_df['gameweek']==gameweek),'games played']
    #else:    
    #    all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / (all_df.loc[(all_df['gameweek']==gameweek),'games played'] - all_df.loc[(all_df['gameweek']==gameweek-i),'games played'] )
    
    # dirty fix in case there are inf results
    #all_df.loc[(all_df['gameweek']==gameweek) & np.isinf(all_df[column_name]), column_name] = np.nan

In [5]:
# top form players
all_df[all_df['gameweek']==gameweek][['web_name', 'games played','total_points', 'points_per_game','adjusted points','adjusted points per game',\
                                'form 5', 'form 10', 'form 15', 'form 20']].sort_values(by=['form 5'], ascending=False).head(20)

,web_name,games played,total_points,points_per_game,adjusted points,adjusted points per game,form 5,form 10,form 15,form 20
id,,,,,,,,,,
255,Sterling,30.0,163,5.4,168.421182,5.614039,9.155564,8.433661,7.500399,6.950558
359,Son,35.0,258,7.4,221.420042,6.326287,8.793207,8.487269,8.064676,7.945551
251,De Bruyne,30.0,196,6.5,165.332182,5.511073,8.749846,7.295282,6.979250,6.621795
357,Kane,37.0,192,5.2,204.961000,5.539486,8.154200,8.046800,7.989267,7.355500
212,Maddison,35.0,181,5.2,153.910284,4.397437,8.101734,6.512730,5.326382,5.276055
224,Matip,31.0,170,5.5,149.927638,4.836375,8.030110,7.213597,7.129273,6.594391
180,Richarlison,30.0,125,4.2,118.186000,3.939533,7.535500,6.590333,5.256000,5.086500
142,James,26.0,141,5.4,135.966051,5.229463,7.229797,4.684666,5.378836,4.718615
64,Trossard,34.0,141,4.1,137.144603,4.033665,7.160765,6.034362,4.595719,4.415441
447,Welbeck,25.0,89,3.6,83.484000,3.339360,7.156800,5.531556,4.629538,4.228471
122,Alonso,28.0,128,4.6,133.884132,4.781576,6.958867,5.927133,5.407616,5.040767
529,Lukaku,26.0,87,3.3,88.491000,3.403500,6.933333,4.033333,3.400000,3.922583
579,Ronaldo,30.0,159,5.3,154.173000,5.139100,6.766667,6.816667,6.630000,5.844733
236,Minamino,11.0,28,2.5,27.972266,2.542933,6.704837,6.704837,2.901612,3.080967
265,Foden,28.0,137,4.9,144.612570,5.164735,6.695349,5.125417,5.028706,4.851544
263,Jesus,28.0,120,4.3,126.288000,4.510286,6.594200,5.871375,5.330111,4.243923
229,van Dijk,34.0,183,5.4,145.206474,4.270779,6.453228,5.451501,5.481545,4.976780
368,Sessegnon,15.0,56,3.7,57.687357,3.845824,6.393427,6.393427,4.727688,4.254919
26,Martinelli,29.0,110,3.8,111.213560,3.834950,6.227244,5.637278,4.763046,4.650966
205,Vardy,25.0,133,5.3,109.113000,4.364520,6.194200,6.194200,5.663143,5.380250

In [6]:
# save data
filepath = '../data/fpl/all_data.csv'
all_df.to_csv(filepath)

filepath = '../data/fpl/data_week' + str(gameweek) + '.csv'
all_df[all_df['gameweek']==gameweek].to_csv(filepath)