# Tableau and player form

Here we create a csv file that is used for making further Tableau visualizations.

In [1]:
# recent gameweek
gameweek = 18

In [2]:
# import basic libraries
import pandas as pd
import numpy as np

pd.set_option('max_columns',100)

In [3]:
# fetch player stats data
all_df = pd.read_csv('../data/fpl/data_week1.csv', index_col=0)
all_df['gameweek'] = 1
all_df['xPoints'] = all_df['adjusted points']

for week in range(2,gameweek+1):
    filepath = '../data/fpl/data_week' + str(week) + '.csv'
    df = pd.read_csv(filepath, index_col=0)
    df['gameweek'] = week
    column_name = 'xPoints week ' + str(week)
    df['xPoints'] = df[column_name]
    all_df = all_df.append(df,sort='False')

all_df.shape

(11114, 259)

In [4]:
# calculate player form
for i in [5,10,15,20]:
    gameweeks = np.arange(gameweek-i+1,gameweek+1)
    column_name = 'form ' + str(i)
    all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].count()
    
    #    all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / all_df.loc[(all_df['gameweek']==gameweek),'games played']
    #else:    
    #    all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / (all_df.loc[(all_df['gameweek']==gameweek),'games played'] - all_df.loc[(all_df['gameweek']==gameweek-i),'games played'] )
    
    # dirty fix in case there are inf results
    #all_df.loc[(all_df['gameweek']==gameweek) & np.isinf(all_df[column_name]), column_name] = np.nan

In [5]:
# top form players
all_df[all_df['gameweek']==gameweek][['web_name', 'games played','total_points', 'points_per_game','adjusted points','adjusted points per game',\
                                'form 5', 'form 10', 'form 15', 'form 20']].sort_values(by=['form 5'], ascending=False).head(20)

,web_name,games played,total_points,points_per_game,adjusted points,adjusted points per game,form 5,form 10,form 15,form 20
id,,,,,,,,,,
210,Tielemans,12.0,67,5.6,60.715233,5.059603,11.048812,6.389442,5.786124,5.189396
237,Alexander-Arnold,16.0,126,7.9,114.394848,7.149678,8.406651,7.837854,7.412620,7.469069
579,Ronaldo,13.0,67,5.2,66.882000,5.144769,8.100000,5.355250,5.218615,5.218615
359,Son,14.0,88,6.3,78.301701,5.592979,8.045615,5.327465,5.839667,5.627237
255,Sterling,15.0,61,4.1,70.323175,4.688212,8.040801,6.485810,4.694906,4.494093
265,Foden,11.0,61,5.5,67.120928,6.101903,7.481141,7.103641,5.915733,5.915733
233,Salah,18.0,170,9.4,142.226301,7.901461,7.337313,7.676813,7.783280,8.026873
63,Maupay,14.0,55,3.9,52.120000,3.722857,7.100000,3.566667,3.872727,3.757143
259,Laporte,14.0,62,4.4,66.333452,4.738104,7.015474,4.724766,4.400146,4.974318
357,Kane,14.0,39,2.8,59.771000,4.269357,6.800000,4.642857,4.664250,4.269357
256,Cancelo,17.0,109,6.4,107.045191,6.296776,6.709956,6.605213,6.376701,6.411920
363,Dele,9.0,23,2.6,27.112736,3.012526,6.623130,2.874377,2.393903,2.923155
138,Mount,15.0,87,5.8,76.448623,5.096575,6.417302,6.014741,5.061056,5.101567
123,Jorginho,15.0,61,4.1,58.124623,3.874975,6.311937,5.748406,4.413877,4.054357
16,Tierney,12.0,57,4.8,45.015273,3.751273,6.245641,6.245641,4.865430,4.157381
261,Bernardo,17.0,93,5.5,80.942798,4.761341,6.092641,4.988273,5.005264,4.720870
212,Maddison,16.0,69,4.3,63.054977,3.940936,6.047426,5.494106,4.068169,3.898990
264,Zinchenko,6.0,27,4.5,28.042479,4.673747,6.018208,6.018208,6.018208,4.527160
235,Origi,3.0,14,4.7,8.800000,2.933333,6.000000,3.900000,2.933333,2.933333
40,Watkins,15.0,61,4.1,60.742000,4.049467,5.992750,4.519000,4.238714,4.049467

In [6]:
# save data
filepath = '../data/fpl/all_data.csv'
all_df.to_csv(filepath)

filepath = '../data/fpl/data_week' + str(gameweek) + '.csv'
all_df[all_df['gameweek']==gameweek].to_csv(filepath)