In [1]:
# give the number of the latest FPL round
latest_gameweek = 6

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
import json
import requests
import xgboost
import pickle

# allow more data columns to be shown than by default
pd.set_option('max_columns',500)

In [3]:
filepath = Path('../data/fpl/data_week' + str(latest_gameweek) + str('.csv'))
players = pd.read_csv(filepath, index_col=0)
players

,adjusted points,adjusted points per game,assists,assists_week1,assists_week2,assists_week3,assists_week4,assists_week5,assists_week6,bonus,bonus_week1,bonus_week2,bonus_week3,bonus_week4,bonus_week5,bonus_week6,bps,chance_of_playing_next_round,chance_of_playing_this_round,clean_sheet_points,clean_sheets,cleansheet_week1,cleansheet_week2,cleansheet_week3,cleansheet_week4,cleansheet_week5,cleansheet_week6,code,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,creativity,creativity_rank,creativity_rank_type,direct_freekicks_order,direct_freekicks_text,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,form 10,form 15,form 20,form 5,games played,gameweek,gameweek 10 prediction,gameweek 11 prediction,gameweek 12 prediction,gameweek 13 prediction,gameweek 14 prediction,gameweek 15 prediction,gameweek 2 prediction,gameweek 3 prediction,gameweek 4 prediction,gameweek 5 prediction,gameweek 6 prediction,gameweek 7 prediction,gameweek 8 prediction,gameweek 9 prediction,goals_conceded,goals_scored,goals_week1,goals_week2,goals_week3,goals_week4,goals_week5,goals_week6,ict_index,ict_index_rank,ict_index_rank_type,in_dreamteam,influence,influence_rank,influence_rank_type,minutes,news,news_added,now_cost,own_goals,penalties_missed,penalties_order,penalties_saved,penalties_text,photo,points_per_game,red_cards,saves,second_name,selected_by_percent,special,squad_number,status,team,team_code,team_name,threat,threat_rank,threat_rank_type,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value,value form 10,value form 5,valuePoints metric,value_form,value_next10,value_season,web_name,xA,xA_points,xA_week1,xA_week2,xA_week3,xA_week4,xA_week5,xA_week6,xG,xG+xA,xG+xA per game,xGA_week1,xGA_week2,xGA_week3,xGA_week4,xGA_week5,xGA_week6,xG_points,xG_week1,xG_week2,xG_week3,xG_week4,xG_week5,xG_week6,xPoints,xPoints week 1,xPoints week 2,xPoints week 3,xPoints week 4,xPoints week 5,xPoints week 6,xPoints_next10,yellow_cards
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,5.918557,1.972852,0,0.0,0.0,0.0,NaN,NaN,NaN,0,0.0,0.0,0.0,NaN,NaN,NaN,48,NaN,NaN,1.918557,0,0.0,0.0,0.0,0.0,0.0,0.0,80201,NaN,NaN,0,0,-2,2,0.0,541,55,NaN,NaN,0,1,0.5,0.5,0,Bernd,0.0,1.799901,1.799901,1.799901,1.654788,3.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,0,0.0,0.0,0.0,NaN,NaN,NaN,7.9,270,19,False,79.0,146,19,270,NaN,NaN,48,0,0,NaN,0,NaN,80201.jpg,1.3,0,9,Leno,1.3,False,NaN,a,1,3,Arsenal,0.0,521,52,4,51860,1246,133868,7314,NaN,NaN,NaN,NaN,0.0,NaN,0.8,Leno,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,1.3,2.9,3.8,0.7,1.2,1.1,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2.090127,2.220093,1.089483,NaN,NaN,NaN,NaN,0
2,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,115918,NaN,NaN,0,0,0,0,0.0,400,18,NaN,NaN,0,1,0.0,0.0,0,Rúnar Alex,0.0,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,419,37,False,0.0,412,37,0,Joined OH Leuven on a season-long loan - Expec...,2021-08-31T22:00:09.069158Z,40,0,0,NaN,0,NaN,115918.jpg,0.0,0,0,Rúnarsson,1.0,False,NaN,u,1,3,Arsenal,0.0,351,14,0,19017,0,48967,2296,NaN,NaN,NaN,NaN,0.0,NaN,0.0,Rúnarsson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,47431,NaN,NaN,0,0,-2,2,0.0,604,246,NaN,NaN,0,3,0.0,0.0,0,Willian,0.0,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,605,246,False,0.0,605,246,0,Transferred to Corinthians,2021-08-20T09:30:14.065783Z,63,0,0,NaN,0,NaN,47431.jpg,0.0,0,0,Borges Da Silva,0.1,False,NaN,u,1,3,Arsenal,0.0,603,246,0,914,0,19387,219,NaN,NaN,NaN,NaN,0.0,NaN,0.0,Willian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,19.900000,3.980000,0,NaN,0.0,0.0,0.0,0.0,0.0,4,NaN,0.0,0.0,3.0,0.0,1.0,69,100.0,100.0,0.000000,2,NaN,0.0,0.0,1.0,1.0,0.0,54694,NaN,NaN,0,0,-1,1,65.9,104,17,NaN,NaN,0,4,6.5,6.5,7,Pierre-Emerick,6.0,3.980000,3.980000,3.980000,3.980000,5.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,2,NaN,0.0,0.0,1.0,0.0,1.0,36.7,39,13,False,86.8,125,13,357,NaN,2021-08-13T14:30:14.477664Z,99,0,0,1.0,0,NaN,54694.jpg,4.0,0,0,Aubameyang,2.1,False,NaN,a,1,3,Arsenal,215.0,17,9,20,187618,21726,249330,8252,NaN,NaN,NaN,NaN,0.6,NaN,2.0,Aubameyang,0.5,1.5,NaN,0.0,0.0,0.1,0.4,0.0,1.6,NaN,NaN,NaN,2.9,3.8,0.7,1.2,1.1,6.4,NaN,0.0,0.0,1.3,0.1,0.2,3.8,NaN,1.000000,1.000000,10.5,3.6,3.8,NaN,0
5,3.218557,1.072852,0,NaN,0.0,0.0,0.0,NaN,NaN,0,NaN,0.0,0.0,0.0,NaN,NaN,21,NaN,NaN,1.918557,0,NaN,0.0,0.0,0.0,0.0,0.0,58822,NaN,NaN,0,0,-2,2,36.1,171,42,5.0,NaN,0,2,0.8,0.8,0,Cédric,0.3,0.536525,0.536525,0.536525,0.536525,3.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,0,NaN,0.0,0.0,0.0,NaN,NaN,6.8,286,98,False,30.8,272,107,188,NaN,NaN,43,0,0,NaN,0,NaN,58822.jpg,0.3,0,0,Soares,0.2,False,NaN,a,1,3,Arsenal,1.0,328,112,1,9319,280,17194,762,NaN,NaN,NaN,NaN,0.1,NaN,0.2,Cédric,0.1,0.3,NaN,0.1,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,2.9,3.8,0.7,1.2,1.1,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,1.520093,-0.910517,1.0,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,245923,NaN,NaN,0,0,0,0,0.0,518,206,NaN,NaN,0,3,0.5,0.0,0,Luke,0.0,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,528,203,False,0.0,525,202,0,NaN,NaN,45,0,0,NaN,0,NaN,245923.jpg,0.0,0,0,Cundle,0.1,False,NaN,a,20,39,Wolves,0.0,491,194,0,8355,319,5315,572,NaN,NaN,NaN,NaN,0.0,NaN,0.0,Cundle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
548,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,461026,NaN,NaN,0,0,0,0,0.0,525,210,NaN,NaN,0,3,0.5,0.0,0,Chem,0.0,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,535,207,False,0.0,532,206,0,NaN,NaN,45,0,0,NaN,0,NaN,461026.jpg,0.0,0,0,Campbell,0.3,False,NaN,a,20,39,Wolves,0.0,500,199,0,32520,1049,19568,1853,NaN,NaN,NaN,NaN,0.0,NaN,0.0,Campbell,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
549,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,481626,NaN,NaN,0,0,0,0,0.0,429,164,NaN,NaN,0,2,0.0,0.0,0,Christian,0.0,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,448,164,False,0.0,441,162,0,Season-long loan to Belenenses,2021-09-07T09:00:15.908306Z,40,0,0,NaN,0,NaN,481626.jpg,0.0,0,0,Marques,0.3,False,NaN,u,20,39,Wolves,0.0,383,142,0,24271,0,21616,978,NaN,NaN,NaN,NaN,0.0,NaN,0.0,Marques,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
583,11.000000,3.666667,0,NaN,NaN,NaN,NaN,0.0,0.0,3,NaN,NaN,NaN,NaN,0.0,0.0,35,NaN,NaN,0.000000,1,NaN,NaN,NaN,NaN,0.0,1.0,184754,NaN,NaN,0,0,0,0,3.7,305,44,NaN,NaN,0,4,4.2,3.7,2,Hee-Chan,3.7,1.900000,1.900000,1.900000,1.900000,3.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,NaN,NaN,NaN,NaN,0.0,0.0,13.4,192,31,False,43.0,242,30,159,NaN,NaN,55,0,0,NaN,0,NaN,184754.jpg,3.7,0,0,Hwang,2.0,False,NaN,a,20,39,Wolves,87.0,84,28,11,260227,6846,110354,23392,NaN,NaN,NaN,NaN,0.7,NaN,2.0,Hwang,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,0.2,2.5,1.2,4.0,NaN,NaN,NaN,NaN,0.1,0.1,2.4,NaN,NaN,NaN,NaN,1.4,2.4,NaN,0
611,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,242510,NaN,NaN,0,0,0,0,0.0,412,24,NaN,NaN,0,1,1.5,1.0,0,Louie,0.0,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,431,43,False,0.0,424,43,0,NaN,NaN,40,0,0,NaN,0,NaN,242510.jpg,0.0,0,0,Moulden,0.0,False,NaN,a,20,39,Wolves,0.0,366,20,0,1429,1429,155,155,NaN,NaN,NaN,NaN,0.0,NaN,0.0,Moulden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [4]:
teams = ['Arsenal', 'Aston Villa', 'Brentford', 'Brighton', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton',
        'Leicester City', 'Leeds United', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle Utd', 
        'Norwich City', 'Southampton', 'Tottenham', 'Watford', 'West Ham', 'Wolves']

In [5]:
# get FPL fixtures data
fpl_fixtures_data = json.loads(requests.get('https://fantasy.premierleague.com/api/fixtures/').text)
fpl_fixtures = pd.DataFrame(fpl_fixtures_data)
fpl_fixtures['home team'] = [teams[i] for i in fpl_fixtures['team_h']-1]
fpl_fixtures['away team'] = [teams[i] for i in fpl_fixtures['team_a']-1]
filepath = Path('../data/fpl/fixtures.csv')
fpl_fixtures.to_csv(filepath)
fpl_fixtures

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,team_a_score,team_h,team_h_score,stats,team_h_difficulty,team_a_difficulty,pulse_id,home team,away team
0,2210271,1,True,True,1,2021-08-13T19:00:00Z,90,False,True,1,0.0,3,2.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",3,2,66342,Brentford,Arsenal
1,2210276,1,True,True,6,2021-08-14T11:30:00Z,90,False,True,10,1.0,13,5.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",2,4,66347,Manchester Utd,Leeds United
2,2210272,1,True,True,2,2021-08-14T14:00:00Z,90,False,True,4,2.0,5,1.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",3,2,66343,Burnley,Brighton
3,2210273,1,True,True,3,2021-08-14T14:00:00Z,90,False,True,7,0.0,6,3.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",2,5,66344,Chelsea,Crystal Palace
4,2210274,1,True,True,4,2021-08-14T14:00:00Z,90,False,True,16,1.0,8,3.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",2,4,66345,Everton,Southampton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2210646,38,False,False,376,2022-05-22T15:00:00Z,0,False,False,13,NaN,7,NaN,[],4,2,66717,Crystal Palace,Manchester Utd
376,2210647,38,False,False,377,2022-05-22T15:00:00Z,0,False,False,16,NaN,9,NaN,[],2,3,66718,Leicester City,Southampton
377,2210648,38,False,False,378,2022-05-22T15:00:00Z,0,False,False,20,NaN,11,NaN,[],2,5,66719,Liverpool,Wolves
378,2210649,38,False,False,379,2022-05-22T15:00:00Z,0,False,False,2,NaN,12,NaN,[],3,5,66720,Manchester City,Aston Villa
379,2210650,38,False,False,380,2022-05-22T15:00:00Z,0,False,False,17,NaN,15,NaN,[],3,2,66721,Norwich City,Tottenham

In [6]:
filepath = Path(f'../data/fbref/team_stats_week{latest_gameweek}.csv')
team_stats = pd.read_csv(filepath, index_col=0)
team_stats

,Rk,MP,W,D,L,GF,GA,GD,Pts,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper,Notes,xG per game,xGA per game,probability no goals allowed
Squad,,,,,,,,,,,,,,,,,,,,,
Liverpool,1,6,4,2,0,15,4,11,14,16.9,7.0,10.0,1.66,W D W W D,52864,Mohamed Salah - 5,Alisson,NaN,2.816667,1.166667,0.311403
Manchester City,2,6,4,1,1,12,1,11,13,13.9,3.0,10.9,1.81,W W W D W,52137,"Gabriel Jesus, Ferrán Torres - 2",Ederson,NaN,2.316667,0.500000,0.606531
Chelsea,3,6,4,1,1,12,2,10,13,7.9,7.2,0.7,0.12,W D W W L,39467,Romelu Lukaku - 3,Edouard Mendy,NaN,1.316667,1.200000,0.301194
Manchester Utd,4,6,4,1,1,13,5,8,13,9.9,6.7,3.2,0.53,D W W W L,72795,Bruno Fernandes - 4,David de Gea,NaN,1.650000,1.116667,0.327369
Everton,5,6,4,1,1,12,7,5,13,10.2,6.4,3.7,0.62,D W W L W,35769,"Demarai Gray, Dominic Calvert-Lewin - 3",Jordan Pickford,NaN,1.700000,1.066667,0.344154
Brighton,6,6,4,1,1,8,5,3,13,6.0,7.3,-1.3,-0.21,W L W W D,30370,Neal Maupay - 4,Robert Sánchez,NaN,1.000000,1.216667,0.296216
West Ham,7,6,3,2,1,13,8,5,11,10.1,6.7,3.4,0.56,W D D L W,59884,Michail Antonio - 5,Łukasz Fabiański,NaN,1.683333,1.116667,0.327369
Aston Villa,8,6,3,1,2,9,7,2,10,6.9,7.3,-0.4,-0.07,W D L W W,41966,Danny Ings - 2,Emiliano Martínez,NaN,1.150000,1.216667,0.296216
Brentford,9,6,2,3,1,8,5,3,9,8.4,6.0,2.3,0.39,D D L W D,16499,Ivan Toney - 2,David Raya,NaN,1.400000,1.000000,0.367879
Arsenal,10,6,3,0,3,5,10,-5,9,7.0,11.0,-4.0,-0.67,L L W W W,58883,Pierre-Emerick Aubameyang - 2,"Bernd Leno, Aaron Ramsdale",NaN,1.166667,1.833333,0.159880
Tottenham,11,6,3,0,3,4,9,-5,9,5.6,9.0,-3.5,-0.58,W W L L L,58664,Son Heung-min - 3,Hugo Lloris,NaN,0.933333,1.500000,0.223130
Watford,12,6,2,1,3,7,9,-2,7,6.0,9.0,-3.0,-0.50,L L L W D,20240,Ismaila Sarr - 4,Daniel Bachmann,NaN,1.000000,1.500000,0.223130
Leicester City,13,6,2,1,3,7,10,-3,7,8.0,10.1,-2.1,-0.36,L W L L D,31907,Jamie Vardy - 5,Kasper Schmeichel,NaN,1.333333,1.683333,0.185754
Wolves,14,6,2,0,4,3,5,-2,6,7.9,6.8,1.1,0.19,L L W L W,30330,"Hwang Hee-chan, Raúl Jiménez - 1",José Sá,NaN,1.316667,1.133333,0.321958
Crystal Palace,15,6,1,3,2,6,9,-3,6,6.2,6.4,-0.2,-0.04,D D W L D,24546,"Wilfried Zaha, Conor Gallagher... - 2",Vicente Guaita,NaN,1.033333,1.066667,0.344154
Southampton,16,6,0,4,2,4,7,-3,4,7.5,7.9,-0.4,-0.06,D D D D L,30001,"Mohamed Elyounoussi, Adam Armstrong... - 1",Alex McCarthy,NaN,1.250000,1.316667,0.268027
Newcastle Utd,17,6,0,3,3,7,14,-7,3,8.1,12.4,-4.3,-0.71,L D L D D,48366,"Allan Saint-Maximin, Callum Wilson - 2",Freddie Woodman,NaN,1.350000,2.066667,0.126607
Leeds United,18,6,0,3,3,6,14,-8,3,8.3,12.3,-3.9,-0.66,D D L D L,36406,Raphael Dias Belloli - 3,Illan Meslier,NaN,1.383333,2.050000,0.128735
Burnley,19,6,0,2,4,5,11,-6,2,6.4,10.8,-4.4,-0.74,L D L L D,18970,"Maxwel Cornet, Ben Mee... - 1",Nick Pope,NaN,1.066667,1.800000,0.165299
Norwich City,20,6,0,0,6,2,16,-14,0,5.3,13.0,-7.7,-1.29,L L L L L,26812,Teemu Pukki - 2,Tim Krul,NaN,0.883333,2.166667,0.114559

In [7]:
# upload model for making predictions
path = Path('../models/xgboost_predictor_v4_weightsAndBonus.pickle')
with open(path,'rb') as f:
    model = pickle.load(f)

In [8]:
# pre-allocate for model input
predictions = pd.DataFrame(index=players.index.copy())
input_columns = ['goalkeeper', 'defender', 'midfielder',
       'forward', 'xG90', 'xA90', 'xGA90', 'bonus', 'xPoints90',
       'games played', 'form 5', 'games_form5', 'form 10', 'games form10',
       'team xG per 90', 'team xGA per 90', 'home', 'opponent xG per 90',
       'opponent xGA per 90']
predictions[input_columns] = np.nan
predictions

,goalkeeper,defender,midfielder,forward,xG90,xA90,xGA90,bonus,xPoints90,games played,form 5,games_form5,form 10,games form10,team xG per 90,team xGA per 90,home,opponent xG per 90,opponent xGA per 90
id,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
611,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# run predictions for all players for a given time horizon
# assumes one match per gameweek at most currently?
horizon = 10
output_columns = [f'gameweek {i} prediction' for i in range(latest_gameweek+1,latest_gameweek+horizon+1)]
xGA_columns = [column for column in players.columns if 'xGA_week' in column]
xPoints_columns = [column for column in players.columns if 'xPoints week' in column]

for player_ix in players.index:
    
    # collect base info
    if players.loc[player_ix,'element_type'] == 1:
        predictions.loc[player_ix,'goalkeeper'] = 1
    elif players.loc[player_ix, 'element_type'] == 2:
        predictions.loc[player_ix,'defender'] = 1
    elif players.loc[player_ix, 'element_type'] == 3:
        predictions.loc[player_ix,'midfielder'] = 1
    elif players.loc[player_ix, 'element_type'] == 4:
        predictions.loc[player_ix,'forward'] = 1

    if players.loc[player_ix,'games played'] > 0:
        predictions.loc[player_ix, 'xG90'] = players.loc[player_ix,'xG'] / players.loc[player_ix,'games played']
        predictions.loc[player_ix, 'xA90'] = players.loc[player_ix,'xA'] / players.loc[player_ix,'games played']
        predictions.loc[player_ix, 'xGA90'] = players.loc[player_ix,xGA_columns].sum() / \
                                          players.loc[player_ix,'games played']                                        
        predictions.loc[player_ix, 'bonus'] = players.loc[player_ix, 'bps']
        predictions.loc[player_ix, 'xPoints90'] = players.loc[player_ix,'adjusted points per game']
        predictions.loc[player_ix, 'games played'] = players.loc[player_ix, 'games played']
        
        form5_points = players.loc[player_ix, xPoints_columns[-5:]].sum()
        form5_games = players.loc[player_ix, xPoints_columns[-5:]].notnull().sum()
        predictions.loc[player_ix, 'form 5'] = form5_points
        predictions.loc[player_ix, 'games_form5'] = form5_games
        
        form10_points = players.loc[player_ix, xPoints_columns[-10:]].sum()
        form10_games = players.loc[player_ix, xPoints_columns[-10:]].notnull().sum()
        predictions.loc[player_ix, 'form 10'] = form10_points
        predictions.loc[player_ix, 'games form10'] = form10_games
    else:
        predictions.loc[player_ix, 'xG90'] = 0
        predictions.loc[player_ix, 'xA90'] = 0
        predictions.loc[player_ix, 'xGA90'] = 0                       
        predictions.loc[player_ix, 'bonus'] = 0
        predictions.loc[player_ix, 'xPoints90'] = 0
        predictions.loc[player_ix, 'games played'] = 0
        predictions.loc[player_ix, 'form 5'] = 0
        predictions.loc[player_ix, 'games_form5'] = 0
        predictions.loc[player_ix, 'form 10'] = 0
        predictions.loc[player_ix, 'games form10'] = 0
        
    team = players.loc[player_ix, 'team_name']
    # team xG per 90 
    team_xG90 = team_stats.loc[team,'xG'] / team_stats.loc[team,'MP']
    predictions.loc[player_ix, 'team xG per 90'] = team_xG90
    # team xGA per 90 
    team_xGA90 = team_stats.loc[team,'xGA'] / team_stats.loc[team,'MP']
    predictions.loc[player_ix, 'team xGA per 90'] = team_xGA90
    
    for gameweek in range(latest_gameweek+1,latest_gameweek+horizon+1):

        # home games
        home_fixtures = fpl_fixtures[(fpl_fixtures['event']==gameweek) & (fpl_fixtures['home team']==team)]
        for fixture in home_fixtures.index:
            predictions.loc[player_ix, 'home'] = 1
            opponent = fpl_fixtures.loc[fixture, 'away team']
            # opponent xG per 90
            opponent_xG90 = team_stats.loc[opponent, 'xG'] / team_stats.loc[opponent,'MP']
            predictions.loc[player_ix, 'opponent xG per 90'] = opponent_xG90
            # opponent xGA per 90
            opponent_xGA90 = team_stats.loc[opponent, 'xGA'] / team_stats.loc[opponent,'MP']
            predictions.loc[player_ix, 'opponent xGA per 90'] = opponent_xGA90
            
            # predict player's points
            input_data = predictions.loc[player_ix:player_ix, input_columns]
            input_data = xgboost.DMatrix(input_data)
            prediction = model.predict(input_data)
            players.loc[player_ix, f'gameweek {gameweek} prediction'] = prediction
            
        # away game
        away_fixtures = fpl_fixtures[(fpl_fixtures['event']==gameweek) & (fpl_fixtures['away team']==team)]
        for fixture in away_fixtures.index:
            predictions.loc[player_ix, 'home'] = 0
            opponent = fpl_fixtures.loc[fixture, 'home team']
            # opponent xG per 90
            opponent_xG90 = team_stats.loc[opponent, 'xG'] / team_stats.loc[opponent,'MP']
            predictions.loc[player_ix, 'opponent xG per 90'] = opponent_xG90
            # opponent xGA per 90
            opponent_xGA90 = team_stats.loc[opponent, 'xGA'] / team_stats.loc[opponent,'MP']
            predictions.loc[player_ix, 'opponent xGA per 90'] = opponent_xGA90
            
            # predict player's points
            input_data = predictions.loc[player_ix:player_ix, input_columns]
            input_data = xgboost.DMatrix(input_data)
            prediction = model.predict(input_data)
            players.loc[player_ix, f'gameweek {gameweek} prediction'] = prediction

In [10]:
# all new predictions
players[output_columns]

,gameweek 7 prediction,gameweek 8 prediction,gameweek 9 prediction,gameweek 10 prediction,gameweek 11 prediction,gameweek 12 prediction,gameweek 13 prediction,gameweek 14 prediction,gameweek 15 prediction,gameweek 16 prediction
id,,,,,,,,,,
1,4.152637,4.162770,4.107661,3.916769,4.234356,3.578402,4.103364,3.639503,3.642461,4.013316
2,3.393607,3.083967,3.265695,3.253830,3.545321,2.763469,3.615238,2.602980,2.567395,3.171350
3,2.453064,2.337055,2.279263,2.415422,2.543098,1.980933,2.792080,2.042449,1.978490,2.104121
4,3.865051,3.865051,3.865051,4.204327,4.366367,3.507565,4.463622,3.507565,3.507565,3.846195
5,2.285419,2.229051,2.181255,1.981908,2.388438,1.526286,2.217425,1.537365,1.523844,1.856755
...,...,...,...,...,...,...,...,...,...,...
547,2.756961,2.457959,2.770300,2.283138,2.515752,2.283138,2.941258,2.771396,2.133414,2.249720
548,2.756961,2.457959,2.770300,2.283138,2.515752,2.283138,2.941258,2.771396,2.133414,2.249720
549,3.065368,2.904781,3.043218,2.256252,3.028062,2.256252,3.641613,3.471751,2.075216,2.191522
583,4.387609,3.817812,4.387609,3.347456,3.917798,3.347456,4.992019,4.583762,3.324655,3.327062
611,3.498936,3.444005,3.476785,2.852540,3.337764,2.786038,3.860973,3.706361,2.931813,2.929011

In [11]:
players['xPoints_next10'] = players[output_columns].sum(axis=1)

In [12]:
players.sort_values(f'gameweek {latest_gameweek+1} prediction', ascending=False)[['web_name','now_cost','adjusted points per game', f'gameweek {latest_gameweek+1} prediction']].head(20)

          web_name  now_cost  adjusted points per game  gameweek 7 prediction
id
579        Ronaldo       127                  6.600000               7.266773
413        Antonio        80                  7.480800               5.858992
177  Calvert-Lewin        80                  8.513333               5.002250
277      Fernandes       119                  5.214036               4.864809
189        Bamford        78                  5.268400               4.821449
529         Lukaku       117                  5.760000               4.819087
63          Maupay        65                  4.053333               4.777373
307  Saint-Maximin        68                  5.352167               4.693383
186          Klich        55                  4.796485               4.661447
435         Traoré        60                  3.738625               4.629018
196       Raphinha        65                  4.495402               4.529744
78           Toney        63                  5.110333               4.502553
205          Vardy       104                  5.745167               4.487015
240           Jota        77                  5.844737               4.439662
109           Wood        68                  3.816667               4.429325
461        Trincão        59                  3.821958               4.427263
233          Salah       126                  8.300237               4.415570
583          Hwang        55                  3.666667               4.387609
112           Pope        54                  2.711196               4.356630
419       Benrahma        66                  5.584369               4.354925

In [13]:
players.sort_values('xPoints_next10', ascending=False)[['web_name','now_cost','adjusted points per game', 'xPoints_next10']].head(20)

             web_name  now_cost  adjusted points per game  xPoints_next10
id
579           Ronaldo       127                  6.600000       79.839297
413           Antonio        80                  7.480800       60.431286
233             Salah       126                  8.300237       56.933177
277         Fernandes       119                  5.214036       55.935666
240              Jota        77                  5.844737       55.087295
78              Toney        63                  5.110333       53.001591
177     Calvert-Lewin        80                  8.513333       52.906919
529            Lukaku       117                  5.760000       52.247020
307     Saint-Maximin        68                  5.352167       51.749347
205             Vardy       104                  5.745167       49.736682
237  Alexander-Arnold        76                  6.994013       48.399914
230              Mané       119                  6.856570       47.501157
296            Wilson        74                  5.066667       45.441677
419          Benrahma        66                  5.584369       44.897441
272             Pogba        78                  5.043536       44.167313
189           Bamford        78                  5.268400       43.229059
63             Maupay        65                  4.053333       42.795158
289         Greenwood        77                  4.805869       42.636692
186             Klich        55                  4.796485       42.214880
270            de Gea        50                  4.976144       42.139909

In [14]:
# save data
filepath = Path('../data/fpl/data_week' + str(latest_gameweek) + str('.csv'))
players.to_csv(filepath)