In [1]:
# recent gameweek
latest_gameweek = 5

In [2]:
import pandas as pd
import numpy as np
import json
import requests
from scipy.stats import poisson

# allow more data columns to be shown than by default
pd.set_option('max_columns',100)

In [3]:
# fetch FPL fixtures online
fixtures_text = json.loads(requests.get('https://fantasy.premierleague.com/api/fixtures').text)
fixtures = pd.DataFrame(fixtures_text)
fixtures.head(20)

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,pulse_id,started,stats,team_a,team_a_difficulty,team_a_score,team_h,team_h_difficulty,team_h_score
0,2128286,NaN,False,False,379,None,0,False,58896,None,[],13,2,NaN,4,4,NaN
1,2128290,NaN,False,False,380,None,0,False,58900,None,[],2,5,NaN,12,3,NaN
2,2128288,1.0,True,True,2,2020-09-12T11:30:00Z,90,False,58898,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",1,2,3.0,8,4,0.0
3,2128287,1.0,True,True,1,2020-09-12T14:00:00Z,90,False,58897,True,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",16,3,0.0,6,2,1.0
4,2128289,1.0,True,True,3,2020-09-12T16:30:00Z,90,False,58899,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",10,5,3.0,11,2,4.0
5,2128293,1.0,True,True,6,2020-09-12T19:00:00Z,90,False,58903,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",14,3,2.0,19,2,0.0
6,2128292,1.0,True,True,5,2020-09-13T13:00:00Z,90,False,58902,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",9,2,3.0,18,3,0.0
7,2128291,1.0,True,True,4,2020-09-13T15:30:00Z,90,False,58901,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",7,4,1.0,17,3,0.0
8,2128295,1.0,True,True,8,2020-09-14T17:00:00Z,90,False,58905,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",20,3,2.0,15,3,0.0
9,2128294,1.0,True,True,7,2020-09-14T19:15:00Z,90,False,58904,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",5,3,3.0,3,4,1.0
10,2128299,2.0,True,True,12,2020-09-19T11:30:00Z,90,False,58909,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",18,3,2.0,7,2,5.0
11,2128300,2.0,True,True,13,2020-09-19T14:00:00Z,90,False,58910,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",8,3,3.0,10,2,4.0
12,2128302,2.0,True,True,15,2020-09-19T16:30:00Z,90,False,58912,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",6,4,3.0,13,2,1.0
13,2128296,2.0,True,True,9,2020-09-19T19:00:00Z,90,False,58906,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",19,4,1.0,1,3,2.0
14,2128304,2.0,True,True,17,2020-09-20T11:00:00Z,90,False,58914,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",17,3,5.0,16,4,2.0
15,2128303,2.0,True,True,16,2020-09-20T13:00:00Z,90,False,58913,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",3,3,3.0,14,2,0.0
16,2128298,2.0,True,True,11,2020-09-20T15:30:00Z,90,False,58908,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",11,4,2.0,5,4,0.0
17,2128301,2.0,True,True,14,2020-09-20T18:00:00Z,90,False,58911,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",4,4,2.0,9,2,4.0
18,2128297,2.0,True,True,10,2020-09-21T17:00:00Z,90,False,58907,True,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",15,3,0.0,2,3,1.0
19,2128305,2.0,True,True,18,2020-09-21T19:15:00Z,90,False,58915,True,"[{'identifier': 'goals_scored', 'a': [{'value'...",12,3,3.0,20,4,1.0

In [4]:
filepath = '../data/fbref/team_stats_week' + str(latest_gameweek) + '.csv'
teamStats = pd.read_csv(filepath, index_col='Squad')
display(teamStats)

,Rk,MP,W,D,L,GF,GA,GDiff,Pts,xG,xGA,xGDiff,xGDiff/90,Last 5,Attendance,Top Team Scorer,Goalkeeper,Notes,xG per game,xGA per game,probability no goals allowed
Squad,,,,,,,,,,,,,,,,,,,,,
Everton,1,5,4,1,0,14,7,7,13,9.9,5.1,4.8,0.95,W W W W D,NaN,Dominic Calvert-Lewin - 7,Jordan Pickford,NaN,1.980,1.020,0.360595
Aston Villa,2,4,4,0,0,12,2,10,12,7.2,3.9,3.3,0.83,W W W W,NaN,Jack Grealish Ollie Watkins - 3,Emiliano Martínez,NaN,1.800,0.975,0.377192
Liverpool,3,5,3,1,1,13,13,0,10,12.9,8.0,4.9,0.97,W W W L D,NaN,Mohamed Salah - 6,Alisson,NaN,2.580,1.600,0.201897
Leicester City,4,5,3,0,2,12,8,4,9,7.1,5.5,1.6,0.31,W W W L L,NaN,Jamie Vardy - 5,Kasper Schmeichel,NaN,1.420,1.100,0.332871
Arsenal,5,5,3,0,2,8,6,2,9,5.6,6.7,-1.1,-0.22,W W L W L,NaN,Alexandre Lacazette - 3,Bernd Leno,NaN,1.120,1.340,0.261846
Wolves,6,5,3,0,2,5,7,-2,9,4.4,6.4,-2.0,-0.41,W L L W W,NaN,Raúl Jiménez - 3,Rui Patrício,NaN,0.880,1.280,0.278037
Tottenham,7,5,2,2,1,15,8,7,8,10.8,7.0,3.8,0.76,L W D W D,NaN,Son Heung-min - 7,Hugo Lloris,NaN,2.160,1.400,0.246597
Chelsea,8,5,2,2,1,13,9,4,8,9.0,7.3,1.7,0.33,W L D W D,NaN,Jorginho - 3,Kepa Arrizabalaga,NaN,1.800,1.460,0.232236
West Ham,9,5,2,1,2,11,7,4,7,8.3,5.0,3.3,0.66,L L W W D,NaN,Jarrod Bowen - 3,Łukasz Fabiański,NaN,1.660,1.000,0.367879
Leeds United,10,5,2,1,2,9,9,0,7,7.1,8.7,-1.7,-0.33,L W W D L,NaN,Patrick Bamford - 3,Illan Meslier,NaN,1.420,1.740,0.175520
Manchester City,11,4,2,1,1,7,7,0,7,5.8,6.1,-0.3,-0.07,W L D W,NaN,Raheem Sterling - 2,Ederson,NaN,1.450,1.525,0.217621
Southampton,12,5,2,1,2,8,9,-1,7,6.4,5.8,0.6,0.11,L L W W D,NaN,Danny Ings - 4,Alex McCarthy,NaN,1.280,1.160,0.313486
Newcastle Utd,13,5,2,1,2,7,9,-2,7,5.5,8.3,-2.8,-0.55,W L D W L,NaN,Callum Wilson - 4,Karl Darlow,NaN,1.100,1.660,0.190139
Crystal Palace,14,5,2,1,2,6,8,-2,7,3.5,7.9,-4.4,-0.87,W W L L D,NaN,Wilfried Zaha - 4,Vicente Guaita,NaN,0.700,1.580,0.205975
Manchester Utd,15,4,2,0,2,9,12,-3,6,5.8,8.4,-2.6,-0.64,L W L W,NaN,Bruno Fernandes - 3,David de Gea,NaN,1.450,2.100,0.122456
Brighton,16,5,1,1,3,9,11,-2,4,8.1,5.3,2.8,0.56,L W L L D,NaN,Neal Maupay - 4,Mathew Ryan,NaN,1.620,1.060,0.346456
West Brom,17,5,0,2,3,5,13,-8,2,2.8,10.1,-7.3,-1.45,L L D L D,NaN,Callum Robinson - 2,Sam Johnstone,NaN,0.560,2.020,0.132655
Burnley,18,4,0,1,3,3,8,-5,1,4.1,5.0,-0.9,-0.22,L L L D,NaN,Jimmy Dunne Chris Wood... - 1,Nick Pope,NaN,1.025,1.250,0.286505
Sheffield Utd,19,5,0,1,4,2,7,-5,1,4.7,5.9,-1.2,-0.25,L L L L D,NaN,Billy Sharp David McGoldrick - 1,Aaron Ramsdale,NaN,0.940,1.180,0.307279
Fulham,20,5,0,1,4,4,12,-8,1,5.3,7.7,-2.5,-0.49,L L L L D,NaN,Aleksandar Mitrović - 2,Alphonse Areola,NaN,1.060,1.540,0.214381

In [5]:
# fetch FPL data
filepath = '../data/fpl/data_week' + str(latest_gameweek) + '.csv'
players = pd.read_csv(filepath, index_col=0)
players.head()

,assists,bonus,bps,chance_of_playing_next_round,chance_of_playing_this_round,clean_sheets,code,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,creativity,creativity_rank,creativity_rank_type,direct_freekicks_order,direct_freekicks_text,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,goals_conceded,goals_scored,ict_index,ict_index_rank,ict_index_rank_type,in_dreamteam,influence,influence_rank,influence_rank_type,minutes,news,news_added,now_cost,own_goals,penalties_missed,penalties_order,penalties_saved,penalties_text,photo,points_per_game,red_cards,saves,second_name,selected_by_percent,special,...,transfers_out,transfers_out_event,value_form,value_season,web_name,yellow_cards,team_name,games played,adjusted points,xG,xG_points,xG_week5,goals_week5,xPoints week 5,clean_sheet_points,xGA_week5,cleansheet_week5,xA,xA_points,xA_week5,assists_week5,adjusted points per game,xPoints week 1,xG_week1,goals_week1,xGA_week1,cleansheet_week1,xA_week1,assists_week1,xPoints week 2,xG_week2,goals_week2,xGA_week2,cleansheet_week2,xA_week2,assists_week2,xPoints week 3,xG_week3,goals_week3,xGA_week3,cleansheet_week3,xA_week3,assists_week3,xPoints week 4,xG_week4,goals_week4,xGA_week4,cleansheet_week4,xA_week4,assists_week4
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0.0,NaN,0,37605,NaN,NaN,0,0,-2,2,0.0,585,236,NaN,NaN,0,3,0.0,-0.5,0,Mesut,0.0,0,0,0.0,586,237,False,0.0,585,237,0,Not included in Arsenal's 25-man Premier Leagu...,2020-10-20T22:30:18.118477Z,68,0,0,NaN,0,NaN,37605.jpg,0.0,0,0,Özil,0.7,False,...,43052,2292,0.0,0.0,Özil,0,Arsenal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,0,0,0.0,100.0,0,39476,NaN,NaN,0,0,-1,1,0.0,508,197,NaN,NaN,0,2,0.0,-0.5,0,Sokratis,0.0,0,0,0.0,521,197,False,0.0,518,197,0,Not included in Arsenal's 25-man Premier Leagu...,2020-10-21T10:30:18.546407Z,49,0,0,NaN,0,NaN,39476.jpg,0.0,0,0,Papastathopoulos,0.1,False,...,16933,376,0.0,0.0,Sokratis,0,Arsenal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,0,39,100.0,100.0,0,41270,NaN,NaN,0,0,0,0,7.3,263,81,4.0,NaN,0,2,1.7,1.2,2,David,1.7,5,0,8.4,217,70,False,57.8,154,61,271,NaN,2020-09-10T14:30:11.632386Z,55,0,0,NaN,0,NaN,41270.jpg,1.5,0,0,Luiz Moreira Marinho,1.1,False,...,46311,3311,0.3,1.1,David Luiz,0,Arsenal,4.0,10.789531,0.1,0.6,0.1,0.0,3.586388,4.189531,1.4,0.0,0.0,0.0,0.0,0.0,2.697383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00000,0.0,0.0,1.9,0.0,0.0,0.0,1.199148,0.0,0.0,3.0,0.0,0.0,0.0,5.274923,0.0,0.0,0.2,0.0,0.0,0.0
4,1,0,61,100.0,75.0,1,54694,NaN,NaN,0,0,-2,2,87.1,45,34,6.0,NaN,0,3,2.0,1.1,2,Pierre-Emerick,2.0,6,1,27.9,43,23,False,86.8,87,30,450,NaN,2020-10-08T09:00:12.305506Z,118,0,0,1.0,0,NaN,54694.jpg,3.6,0,0,Aubameyang,17.3,False,...,2263736,183020,0.2,1.5,Aubameyang,1,Arsenal,5.0,17.100263,0.5,2.5,0.0,0.0,3.746597,1.309228,1.4,0.0,1.0,3.0,0.5,0.0,3.420053,3.818731,0.4,1.0,0.2,1.0,0.0,0.0,5.61799,0.1,0.0,1.9,0.0,0.5,1.0,2.049787,0.0,0.0,3.0,0.0,0.0,0.0,2.818731,0.0,0.0,0.2,0.0,0.0,0.0
5,0,0,0,100.0,100.0,0,58822,NaN,NaN,0,0,-2,2,0.0,492,193,NaN,NaN,0,2,0.0,-0.5,0,Cédric,0.0,0,0,0.0,508,193,False,0.0,505,193,0,NaN,2020-09-23T09:00:14.881983Z,48,0,0,NaN,0,NaN,58822.jpg,0.0,0,0,Soares,0.2,False,...,28343,892,0.0,0.0,Cédric,0,Arsenal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
coefficients = pd.DataFrame(np.nan, index=teamStats.index, columns=['xG','xGA','coefficient'])

for ix in coefficients.index:
    coefficients.loc[ix, 'xG'] = teamStats.loc[ix, 'xG per game']
    coefficients.loc[ix, 'xGA'] = teamStats.loc[ix, 'xGA per game']
    coefficients.loc[ix, 'coefficient'] = 0.755489209043063 * coefficients.loc[ix, 'xG']

display(coefficients)

                    xG    xGA  coefficient
Squad
Everton          1.980  1.020     1.495869
Aston Villa      1.800  0.975     1.359881
Liverpool        2.580  1.600     1.949162
Leicester City   1.420  1.100     1.072795
Arsenal          1.120  1.340     0.846148
Wolves           0.880  1.280     0.664831
Tottenham        2.160  1.400     1.631857
Chelsea          1.800  1.460     1.359881
West Ham         1.660  1.000     1.254112
Leeds United     1.420  1.740     1.072795
Manchester City  1.450  1.525     1.095459
Southampton      1.280  1.160     0.967026
Newcastle Utd    1.100  1.660     0.831038
Crystal Palace   0.700  1.580     0.528842
Manchester Utd   1.450  2.100     1.095459
Brighton         1.620  1.060     1.223893
West Brom        0.560  2.020     0.423074
Burnley          1.025  1.250     0.774376
Sheffield Utd    0.940  1.180     0.710160
Fulham           1.060  1.540     0.800819

In [7]:
def points_for_clean_sheet(position):
    if position < 3:
        return 4
    elif position==3:
        return 1
    elif position==4:
        return 0

In [8]:
goalkeepers = players['element_type'] == 1
defenders = players['element_type'] == 2
midfielders = players['element_type'] == 3
forwards = players['element_type'] == 4

In [9]:
home_coefficient = 1.0721855628874228
away_coefficient = 0.9280143971205758

In [10]:
team_names = np.sort(teamStats.index)
# for some reason the fpl team numbers are not alphabetical with leeds and leicester...
if (team_names[8]=='Leeds United') & (team_names[9]=='Leicester City'):
    team_names[8] = 'Leicester City'
    team_names[9] = 'Leeds United'
    
# how many gameweeks ahead do you want to look at
for number_gameweeks in [1,5,10]:
    expectations = pd.DataFrame(0, index=teamStats.index, \
                columns=['games','total_xG','total_xGA','xG per game', 'xGA per game'])
    gameweeks = np.arange(latest_gameweek+1, latest_gameweek+number_gameweeks+1)
    games = fixtures[fixtures['event'].isin(gameweeks)]
    for ix in games.index:
        home_team_number = games.loc[ix,'team_h']
        home_team = team_names[home_team_number-1]
        away_team_number = games.loc[ix,'team_a']
        away_team = team_names[away_team_number-1]

        home_xG = home_coefficient * coefficients.loc[home_team,'coefficient'] * \
                                    coefficients.loc[away_team,'xGA']
        away_xG = away_coefficient * coefficients.loc[away_team,'coefficient'] * \
                                    coefficients.loc[home_team,'xGA']
        expectations.loc[home_team,'total_xG'] += home_xG
        expectations.loc[home_team,'total_xGA'] += away_xG
        expectations.loc[home_team,'games'] += 1
        expectations.loc[away_team,'total_xG'] += away_xG
        expectations.loc[away_team,'total_xGA'] += home_xG
        expectations.loc[away_team,'games'] += 1

    expectations['xG per game'] = expectations['total_xG'] / expectations['games']
    expectations['xGA per game'] = expectations['total_xGA'] / expectations['games']
    print('expectations:')
    display(expectations)

    new_column = 'next' + str(number_gameweeks) + '_xG_xA_multiplier'
    coefficients[new_column] = expectations['xG per game'] / coefficients['xG']
    print('coefficients:')
    display(coefficients)
    
    new_column = 'next' + str(number_gameweeks) + '_xP'
    multiplier_xG_xA_column = 'next' + str(number_gameweeks) + '_xG_xA_multiplier'
    for ix in players.index:
        team = players.loc[ix,'team_name']
        position = players.loc[ix, 'element_type']

        # adjust xP based on xg and xa for the next game
        xg_points_per_game = players.loc[ix,'xG_points'] / players.loc[ix,'games played']
        xa_points_per_game = players.loc[ix,'xA_points'] / players.loc[ix,'games played']
        xpoints = xg_points_per_game + xa_points_per_game
        players.loc[ix, new_column] = players.loc[ix, 'adjusted points per game'] - \
                            xpoints + coefficients.loc[team, multiplier_xG_xA_column]*xpoints    

        # adjust xP based on probability to keep a clean sheet for the next game
        clean_sheet_points_per_game = players.loc[ix,'clean_sheet_points'] / \
                                        players.loc[ix,'games played']
        probability_clean_sheet_next = poisson.pmf(0, expectations.loc[team, 'xGA per game'])
        players.loc[ix, new_column] = players.loc[ix, new_column] - clean_sheet_points_per_game \
                + points_for_clean_sheet(position) * probability_clean_sheet_next

expectations:

                 games  total_xG  total_xGA  xG per game  xGA per game
Squad
Everton              1  1.610298   1.057568     1.610298      1.057568
Aston Villa          1  2.536997   0.970680     2.536997      0.970680
Liverpool            1  2.466039   1.054462     2.466039      1.054462
Leicester City       1  1.334062   0.997950     1.334062      0.997950
Arsenal              1  0.997950   1.334062     0.997950      1.334062
Wolves               1  1.183284   0.987156     1.183284      0.987156
Tottenham            1  1.892983   1.162385     1.892983      1.162385
Chelsea              1  2.650176   1.714822     2.650176      1.714822
West Ham             1  2.050577   1.016602     2.050577      1.016602
Leeds United         1  0.970680   2.536997     0.970680      2.536997
Manchester City      1  1.016602   2.050577     1.016602      2.050577
Southampton          1  1.057568   1.610298     1.057568      1.610298
Newcastle Utd        1  0.987156   1.183284     0.987156      1.183284
Crystal Palace       1  0.755791   1.356629     0.755791      1.356629
Manchester Utd       1  1.714822   2.650176     1.714822      2.650176
Brighton             1  2.650725   0.416176     2.650725      0.416176
West Brom            1  0.416176   2.650725     0.416176      2.650725
Burnley              1  1.162385   1.892983     1.162385      1.892983
Sheffield Utd        1  1.054462   2.466039     1.054462      2.466039
Fulham               1  1.356629   0.755791     1.356629      0.755791

coefficients:

                    xG    xGA  coefficient  next1_xG_xA_multiplier
Squad
Everton          1.980  1.020     1.495869                0.813282
Aston Villa      1.800  0.975     1.359881                1.409443
Liverpool        2.580  1.600     1.949162                0.955829
Leicester City   1.420  1.100     1.072795                0.939481
Arsenal          1.120  1.340     0.846148                0.891027
Wolves           0.880  1.280     0.664831                1.344641
Tottenham        2.160  1.400     1.631857                0.876381
Chelsea          1.800  1.460     1.359881                1.472320
West Ham         1.660  1.000     1.254112                1.235288
Leeds United     1.420  1.740     1.072795                0.683577
Manchester City  1.450  1.525     1.095459                0.701105
Southampton      1.280  1.160     0.967026                0.826225
Newcastle Utd    1.100  1.660     0.831038                0.897414
Crystal Palace   0.700  1.580     0.528842                1.079701
Manchester Utd   1.450  2.100     1.095459                1.182636
Brighton         1.620  1.060     1.223893                1.636250
West Brom        0.560  2.020     0.423074                0.743171
Burnley          1.025  1.250     0.774376                1.134034
Sheffield Utd    0.940  1.180     0.710160                1.121768
Fulham           1.060  1.540     0.800819                1.279839

expectations:

                 games   total_xG  total_xGA  xG per game  xGA per game
Squad
Everton              5  12.211277   4.894629     2.442255      0.978926
Aston Villa          5   8.726909   5.148625     1.745382      1.029725
Liverpool            5  11.530631   8.488347     2.306126      1.697669
Leicester City       5   7.902925   6.058216     1.580585      1.211643
Arsenal              5   6.059060   6.967063     1.211812      1.393413
Wolves               5   4.641828   5.397588     0.928366      1.079518
Tottenham            5  11.685902   6.852055     2.337180      1.370411
Chelsea              5  10.084318   7.401124     2.016864      1.480225
West Ham             5   8.667808   5.873049     1.733562      1.174610
Leeds United         5   6.365732   9.412907     1.273146      1.882581
Manchester City      5   6.986862   9.734380     1.397372      1.946876
Southampton          5   6.979724   6.202370     1.395945      1.240474
Newcastle Utd        5   5.310033   8.244966     1.062007      1.648993
Crystal Palace       5   3.925306   6.586241     0.785061      1.317248
Manchester Utd       5   7.877455  10.669103     1.575491      2.133821
Brighton             5   9.088109   6.495467     1.817622      1.299093
West Brom            5   3.015632  11.148030     0.603126      2.229606
Burnley              5   5.544087   7.192405     1.108817      1.438481
Sheffield Utd        5   5.270509   7.294710     1.054102      1.458942
Fulham               5   5.527512   7.340342     1.105502      1.468068

coefficients:

,xG,xGA,coefficient,next1_xG_xA_multiplier,next5_xG_xA_multiplier
Squad,,,,,
Everton,1.980,1.020,1.495869,0.813282,1.233462
Aston Villa,1.800,0.975,1.359881,1.409443,0.969657
Liverpool,2.580,1.600,1.949162,0.955829,0.893847
Leicester City,1.420,1.100,1.072795,0.939481,1.113088
Arsenal,1.120,1.340,0.846148,0.891027,1.081975
Wolves,0.880,1.280,0.664831,1.344641,1.054961
Tottenham,2.160,1.400,1.631857,0.876381,1.082028
Chelsea,1.800,1.460,1.359881,1.472320,1.120480
West Ham,1.660,1.000,1.254112,1.235288,1.044314
Leeds United,1.420,1.740,1.072795,0.683577,0.896582
Manchester City,1.450,1.525,1.095459,0.701105,0.963705
Southampton,1.280,1.160,0.967026,0.826225,1.090582
Newcastle Utd,1.100,1.660,0.831038,0.897414,0.965461
Crystal Palace,0.700,1.580,0.528842,1.079701,1.121516
Manchester Utd,1.450,2.100,1.095459,1.182636,1.086545
Brighton,1.620,1.060,1.223893,1.636250,1.121989
West Brom,0.560,2.020,0.423074,0.743171,1.077011
Burnley,1.025,1.250,0.774376,1.134034,1.081773
Sheffield Utd,0.940,1.180,0.710160,1.121768,1.121385
Fulham,1.060,1.540,0.800819,1.279839,1.042927

expectations:

                 games   total_xG  total_xGA  xG per game  xGA per game
Squad
Everton             10  21.602356   9.779572     2.160236      0.977957
Aston Villa         10  19.438091   8.217006     1.943809      0.821701
Liverpool           10  26.996603  14.807741     2.699660      1.480774
Leicester City      10  15.279475  12.715038     1.527948      1.271504
Arsenal             10  11.470306  15.317323     1.147031      1.531732
Wolves              10   9.133870  14.304471     0.913387      1.430447
Tottenham           10  22.709219  14.062768     2.270922      1.406277
Chelsea             10  18.672999  15.260744     1.867300      1.526074
West Ham            10  18.765675  11.124493     1.876567      1.112449
Leeds United        10  14.407376  18.611003     1.440738      1.861100
Manchester City     10  16.432061  16.014898     1.643206      1.601490
Southampton         10  13.320165  11.716702     1.332017      1.171670
Newcastle Utd       10  11.752042  16.409850     1.175204      1.640985
Crystal Palace      10   7.586998  16.981908     0.758700      1.698191
Manchester Utd      10  15.046768  21.732890     1.504677      2.173289
Brighton            10  16.293026  11.700019     1.629303      1.170002
West Brom           10   6.053295  23.082571     0.605330      2.308257
Burnley             10  10.367775  14.093239     1.036777      1.409324
Sheffield Utd       10   9.946781  14.079038     0.994678      1.407904
Fulham              10  11.174464  16.438072     1.117446      1.643807

coefficients:

,xG,xGA,coefficient,next1_xG_xA_multiplier,next5_xG_xA_multiplier,next10_xG_xA_multiplier
Squad,,,,,,
Everton,1.980,1.020,1.495869,0.813282,1.233462,1.091028
Aston Villa,1.800,0.975,1.359881,1.409443,0.969657,1.079894
Liverpool,2.580,1.600,1.949162,0.955829,0.893847,1.046380
Leicester City,1.420,1.100,1.072795,0.939481,1.113088,1.076019
Arsenal,1.120,1.340,0.846148,0.891027,1.081975,1.024134
Wolves,0.880,1.280,0.664831,1.344641,1.054961,1.037940
Tottenham,2.160,1.400,1.631857,0.876381,1.082028,1.051353
Chelsea,1.800,1.460,1.359881,1.472320,1.120480,1.037389
West Ham,1.660,1.000,1.254112,1.235288,1.044314,1.130462
Leeds United,1.420,1.740,1.072795,0.683577,0.896582,1.014604
Manchester City,1.450,1.525,1.095459,0.701105,0.963705,1.133246
Southampton,1.280,1.160,0.967026,0.826225,1.090582,1.040638
Newcastle Utd,1.100,1.660,0.831038,0.897414,0.965461,1.068367
Crystal Palace,0.700,1.580,0.528842,1.079701,1.121516,1.083857
Manchester Utd,1.450,2.100,1.095459,1.182636,1.086545,1.037708
Brighton,1.620,1.060,1.223893,1.636250,1.121989,1.005742
West Brom,0.560,2.020,0.423074,0.743171,1.077011,1.080946
Burnley,1.025,1.250,0.774376,1.134034,1.081773,1.011490
Sheffield Utd,0.940,1.180,0.710160,1.121768,1.121385,1.058168
Fulham,1.060,1.540,0.800819,1.279839,1.042927,1.054195

In [11]:
metric = 'next1_xP'
#minGames = players['games played'] >= 3

numberToShow = 50
display(players.sort_values(by=[metric], ascending=False)[['web_name','team_name',\
         'now_cost','games played','total_points','adjusted points','points_per_game',\
         'adjusted points per game','next1_xP','next5_xP','next10_xP']].head(numberToShow))

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,next1_xP,next5_xP,next10_xP
id,,,,,,,,,,,
388,Kane,Tottenham,108,5.000000,60,52.757241,12.0,10.551448,9.940276,10.956994,10.805336
105,Jorginho,Chelsea,52,4.000000,32,29.791014,8.0,7.447754,9.317856,7.933456,7.585077
68,Maupay,Brighton,66,5.000000,34,33.131034,6.8,6.626207,8.769096,7.037065,6.645547
37,Grealish,Aston Villa,72,4.000000,38,28.781873,9.5,7.195468,8.466374,7.081316,7.505630
251,Mané,Liverpool,119,3.974359,31,32.702409,7.8,8.228348,8.131435,7.624626,8.509482
470,Kilman,Wolves,41,2.000000,21,14.715333,10.5,7.357666,7.942842,7.637531,7.225089
302,Fernandes,Manchester Utd,105,3.974359,31,28.328755,7.8,7.127880,7.777314,7.456109,7.264011
33,Hourihane,Aston Villa,60,2.000000,17,13.445419,8.5,6.722710,7.625117,6.635867,6.960967
254,Salah,Liverpool,123,5.000000,48,37.440517,9.6,7.488103,7.447832,7.020503,7.709763
514,Watkins,Aston Villa,60,4.032258,25,24.191034,6.2,5.999377,7.309266,5.902302,6.254973
390,Son,Tottenham,94,5.000000,58,37.715054,11.6,7.543011,7.166597,7.844076,7.725311
69,Trossard,Brighton,60,5.000000,22,24.514348,4.4,4.902870,6.513928,5.078050,4.878494
232,Chilwell,Chelsea,57,2.000000,21,12.139959,10.5,6.069980,6.498650,6.214028,6.061059
224,Vardy,Leicester City,100,4.000000,34,26.380000,8.5,6.595000,6.407692,6.945007,6.830280
506,Wilson,Newcastle Utd,65,5.000000,36,33.531034,7.2,6.706207,6.393525,6.600931,6.914591
12,Martínez,Aston Villa,48,3.974359,31,24.996391,7.8,6.289415,6.295947,6.209066,6.539378
508,Rodríguez,Everton,80,5.000000,39,33.076078,7.8,6.615216,6.101515,7.256014,6.874655
389,Aurier,Tottenham,52,2.000000,13,12.063810,6.5,6.031905,5.999789,6.258394,6.148980
272,De Bruyne,Manchester City,115,2.982456,17,20.960080,5.7,7.027791,5.934649,6.830952,7.459425
164,Calvert-Lewin,Everton,77,5.000000,43,32.900000,8.6,6.580000,5.911548,7.415795,6.905881
450,Fornals,West Ham,64,5.000000,27,26.812501,5.4,5.362500,5.831724,5.393075,5.586907
325,Darlow,Newcastle Utd,50,5.000000,27,26.802780,5.4,5.360556,5.825085,5.368973,5.375156
252,Alisson,Liverpool,59,2.982456,17,15.408590,5.7,5.166410,5.752343,5.091263,5.268670
155,Digne,Everton,62,5.000000,27,28.685002,5.4,5.737000,5.549381,5.965572,5.864475
117,Werner,Chelsea,93,5.000000,27,23.682069,5.4,4.736414,5.501573,4.931591,4.796984
80,Mac Allister,Brighton,53,1.000000,9,4.846456,9.0,4.846456,5.477689,4.833773,4.813238
435,Cresswell,West Ham,50,5.000000,29,26.530692,5.8,5.306138,5.437200,5.099626,5.235737
572,Adarabioyo,Fulham,45,1.000000,2,4.057524,2.0,4.057524,5.414363,4.172992,4.038005
557,Lookman,Fulham,50,2.000000,11,9.328762,5.5,4.664381,5.325405,4.742614,4.721825
141,Zaha,Crystal Palace,72,5.000000,35,25.469875,7.0,5.093975,5.311944,5.409597,5.246107
77,Lamptey,Brighton,47,5.000000,13,18.102220,2.6,3.620444,5.292803,3.406249,3.479876
38,McGinn,Aston Villa,55,3.970588,27,18.761813,6.8,4.725197,5.252737,4.666136,4.890308
306,Rashford,Manchester Utd,95,4.000000,26,19.871895,6.5,4.967974,5.226637,5.111029,5.023424
437,Antonio,West Ham,63,5.000000,19,23.000000,3.8,4.600000,5.164690,4.706354,4.913110
255,Robertson,Liverpool,71,5.000000,25,22.819999,5.0,4.564000,5.086327,4.335993,4.733047
276,Sterling,Manchester City,116,3.970588,27,22.655118,6.8,5.705733,5.052193,5.562275,5.941394
41,Mings,Aston Villa,52,4.000000,30,19.026112,7.5,4.756528,5.039434,4.655697,5.060420
442,Masuaku,West Ham,45,3.958333,19,19.015792,4.8,4.803990,5.011581,4.611891,4.776023
184,Mitrović,Fulham,59,5.000000,17,21.240000,3.4,4.248000,4.933046,4.353085,4.380669
40,Trézéguet,Aston Villa,54,4.000000,14,17.099804,3.5,4.274951,4.921457,4.207073,4.463275
498,Castagne,Leicester City,58,5.000000,29,23.830525,5.8,4.766105,4.869215,4.700089,4.606432
65,March,Brighton,50,5.000000,21,19.723314,4.2,3.944663,4.855846,3.985655,3.913971
461,Saïss,Wolves,52,5.000000,31,21.260746,6.2,4.252149,4.816646,4.528716,4.117295
445,Bowen,West Ham,63,5.000000,29,22.139397,5.8,4.427879,4.812400,4.442501,4.605320
166,Richarlison,Everton,79,5.000000,22,26.493103,4.4,5.298621,4.790000,5.934572,5.546581
377,Adams,Southampton,58,5.000000,21,25.782069,4.2,5.156414,4.732403,5.377433,5.255570
277,Cancelo,Manchester City,54,1.000000,8,5.170484,8.0,5.170484,4.724974,4.859988,5.146357
366,Ings,Southampton,85,5.000000,31,25.420000,6.2,5.084000,4.721853,5.272773,5.168689
460,Jiménez,Wolves,85,5.000000,24,20.400000,4.8,4.080000,4.658997,4.172334,4.143739
202,Bamford,Leeds United,58,5.000000,32,26.282069,6.4,5.256414,4.642554,5.055783,5.284745

In [12]:
# save predictions
filepath = '../data/fpl/data_week' + str(latest_gameweek) + '.csv'
players.to_csv(filepath)