In [1]:
# recent gameweek
latest_gameweek = 8

In [2]:
import pandas as pd
import numpy as np

# allow more data columns to be shown than by default
pd.set_option('max_columns',100)

In [3]:
# fetch FPL data
filepath = '../data/fpl/data_week' + str(latest_gameweek) + '.csv'
players = pd.read_csv(filepath, index_col=0)

In [4]:
# how many gameweeks do we look form for
number_gameweeks = 5
# create a list of relevant column names
column_list = []
for i in range(0,number_gameweeks):
    column_list.append('xPoints week ' + str(latest_gameweek-i))
# calculate form
column_name = 'form ' + str(number_gameweeks)
players[column_name] = players[column_list].mean(axis=1)

In [5]:
# give a sorted list showing the players with best 'form 5'
players[['web_name', 'games played','total_points', 'points_per_game','adjusted points','adjusted points per game',\
                                'form 5']].sort_values(by='form 5', ascending=False)

,web_name,games played,total_points,points_per_game,adjusted points,adjusted points per game,form 5
id,,,,,,,
388,Kane,8.000000,80,10.0,70.695502,8.836938,8.572076
37,Grealish,6.976744,60,8.6,46.862071,6.716897,7.978918
282,Jesus,2.000000,15,7.5,11.800000,5.900000,7.700000
224,Vardy,7.023810,59,8.4,52.333876,7.450925,7.544385
390,Son,8.043478,74,9.2,53.191317,6.612975,7.228917
514,Watkins,7.014925,47,6.7,42.176938,6.012457,7.180165
254,Salah,7.976190,67,8.4,59.131449,7.413495,7.077624
506,Wilson,7.971014,55,6.9,50.673876,6.357268,6.893869
141,Zaha,7.941176,54,6.8,48.212548,6.071210,6.640317
277,Cancelo,4.000000,24,6.0,22.807690,5.701923,6.383358
302,Fernandes,6.973684,53,7.6,42.154990,6.044866,6.376661
232,Chilwell,5.000000,41,8.2,26.406925,5.281385,6.243458
431,Fabianski,8.039216,41,5.1,38.685461,4.812094,6.178293
389,Aurier,2.000000,13,6.5,12.619906,6.309953,6.081085
457,Doherty,6.000000,24,4.0,25.145844,4.190974,5.902166
450,Fornals,8.076923,42,5.2,40.503536,5.014723,5.884738
202,Bamford,8.055556,58,7.2,47.513876,5.898274,5.860000
508,Rodríguez,7.049180,43,6.1,38.715841,5.492247,5.838771
106,Barkley,7.045455,31,4.4,31.494325,4.470162,5.762914
492,Rodrigo,6.000000,18,3.0,21.656938,3.609490,5.722840
11,Bellerín,8.095238,34,4.2,31.848112,3.934178,5.716196
88,Mee,1.000000,8,8.0,5.893980,5.893980,5.690127
114,Ziyech,3.970588,27,6.8,22.559875,5.681746,5.630444
435,Cresswell,7.916667,38,4.8,36.008630,4.548459,5.556830
110,Zouma,6.956522,48,6.9,29.433808,4.231110,5.545086
461,Saïss,6.031746,38,6.3,26.339490,4.366810,5.527305
251,Mané,6.969697,46,6.6,47.726262,6.847681,5.490463
490,Thiago Silva,5.000000,28,5.6,18.893049,3.778610,5.470554
306,Rashford,7.000000,35,5.0,31.601119,4.514446,5.458916
455,Patrício,8.000000,40,5.0,34.132377,4.266547,5.415087
...,...,...,...,...,...,...,...
410,Grosicki,NaN,0,0.0,NaN,NaN,NaN
415,Austin,NaN,0,0.0,NaN,NaN,NaN
416,Zohore,NaN,0,0.0,NaN,NaN,NaN
420,Leko,NaN,0,0.0,NaN,NaN,NaN
426,Harper,1.000000,1,1.0,1.173774,1.173774,NaN
499,Kipre,NaN,0,0.0,NaN,NaN,NaN
600,Peltier,NaN,0,0.0,NaN,NaN,NaN
429,Martin,NaN,0,0.0,NaN,NaN,NaN
430,Randolph,NaN,0,0.0,NaN,NaN,NaN
433,Roberto,NaN,0,0.0,NaN,NaN,NaN
434,Wilshere,NaN,0,0.0,NaN,NaN,NaN
438,Fredericks,3.076923,4,1.3,9.163943,2.978282,NaN
440,Felipe Anderson,2.000000,2,1.0,2.602388,1.301194,NaN
444,Hugill,NaN,0,0.0,NaN,NaN,NaN
447,Ajeti,NaN,0,0.0,NaN,NaN,NaN
452,Johnson,1.000000,1,1.0,2.204777,2.204777,NaN
576,Dawson,NaN,0,0.0,NaN,NaN,NaN
453,Ruddy,NaN,0,0.0,NaN,NaN,NaN
456,Bennett,NaN,0,0.0,NaN,NaN,NaN
462,Jonny,NaN,0,0.0,NaN,NaN,NaN
463,Bonatini,NaN,0,0.0,NaN,NaN,NaN
467,Buur,1.000000,1,1.0,2.266547,2.266547,NaN
471,Vinagre,2.000000,1,0.5,3.533094,1.766547,NaN
472,Sarkic,NaN,0,0.0,NaN,NaN,NaN
473,Gibbs-White,NaN,0,0.0,NaN,NaN,NaN
475,Jordao,NaN,0,0.0,NaN,NaN,NaN
476,Campana,NaN,0,0.0,NaN,NaN,NaN
515,Vitinha,2.000000,2,1.0,2.633274,1.316637,NaN
553,Shabani,NaN,0,0.0,NaN,NaN,NaN
581,Otasowie,NaN,0,0.0,NaN,NaN,NaN

In [6]:
# save data
filepath = '../data/fpl/data_week' + str(latest_gameweek) + '.csv'
players.to_csv(filepath)