# Player evaluation

Here we compare players based on their adjusted points. Also, we calculate some useful metrics using the adjusted points to further evaluate player performance in FPL.

In [1]:
# recent gameweek
gameweek = 17

In [2]:
# import basic libraries
import pandas as pd
import numpy as np

pd.set_option('max_columns',100)

In [3]:
# fetch FPL data
df = pd.read_csv('../data/data_week' + str(gameweek) + '.csv', index_col=0, encoding='latin-1')
df.head()

,assists,bonus,bps,chance_of_playing_next_round,chance_of_playing_this_round,clean_sheets,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,creativity,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,goals_conceded,goals_scored,ict_index,in_dreamteam,influence,minutes,news,news_added,now_cost,own_goals,penalties_missed,penalties_saved,photo,points_per_game,red_cards,saves,second_name,selected_by_percent,special,squad_number,status,team,team_code,threat,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,yellow_cards,games played,adjusted points,adjusted points per game,form 5
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,1,0,24,100.0,100.0,0,69140,0,0,-3,3,0.8,0,2,1.3,0.3,0,Shkodran,0.8,2,0,7.5,False,19.8,90,NaN,2019-11-28T23:00:21.541666Z,52,0,0,0,69140.jpg,4.0,0,0,Mustafi,0.3,False,NaN,a,1,3,54.0,4,7831,116,32097,285,0.2,0.8,Mustafi,0,1.000000,4.281881,4.281881,NaN
2,0,0,26,0.0,75.0,0,98745,0,0,-1,1,22.7,0,2,0.0,-0.2,0,HÃÂ©ctor,0.2,6,0,6.9,False,30.8,262,Hamstring injury - Expected back 21 Dec,2019-12-09T20:00:21.228098Z,54,0,0,0,98745.jpg,0.3,0,0,BellerÃÂ­n,0.3,False,NaN,i,1,3,15.0,1,34609,34,33648,1577,0.0,0.2,BellerÃÂ­n,2,3.333333,4.088660,1.226598,NaN
3,2,1,196,75.0,100.0,1,111457,0,0,-3,3,149.6,0,2,1.6,1.1,0,Sead,1.6,17,0,37.8,False,174.4,928,Ankle injury - 75% chance of playing,2019-12-15T19:30:19.136195Z,52,0,0,0,111457.jpg,1.9,0,0,Kolasinac,0.6,False,NaN,d,1,3,55.0,27,46926,335,109248,1839,0.3,5.2,Kolasinac,2,14.210526,37.079065,2.609268,2.506510
4,2,3,124,100.0,100.0,1,154043,0,0,-4,4,127.9,1,2,1.1,0.1,1,Ainsley,0.6,14,0,32.9,False,173.0,670,NaN,2019-09-22T18:00:10.824841Z,46,0,0,0,154043.jpg,2.5,1,0,Maitland-Niles,2.6,False,NaN,a,1,3,33.0,20,546474,920,567069,2824,0.1,4.3,Maitland-Niles,0,8.000000,23.383351,2.922919,2.502208
5,0,2,224,0.0,NaN,2,39476,0,0,-1,1,30.7,0,2,0.0,-0.1,0,Sokratis,0.4,23,1,44.3,False,340.2,1350,Suspended until 26 Dec,2019-12-15T19:30:19.149412Z,49,0,0,0,39476.jpg,2.2,0,0,Papastathopoulos,1.4,False,NaN,s,1,3,71.0,33,107358,290,144034,6092,0.1,6.7,Sokratis,5,15.000000,33.948971,2.263265,1.515779

In [4]:
# fetch team data
filepath = '../data/fbref/team_stats_week' + str(gameweek) + '.csv'
teamStats = pd.read_csv(filepath, index_col=0, encoding='latin-1')

# fetch player stats data
filepath = '../data/fbref/player_stats_week' + str(gameweek) + '.csv'
playerStats = pd.read_csv(filepath, index_col=0, skiprows=1, encoding='latin-1')

## Value and value points

Here we calculate two interesting metrics: 'value' and 'value points'. 

Value is simply adjusted points per game divided by the cost of the player. Essentially, this measures how many 'points per pound(/euro/whatever)' has the player gained on an average game week. 

The value points is calculated as the geometric mean of a players adjusted points per game and value. Essentially, in FPL we want to gain the maximum possible amount of points. However, we are restrained by a limited budget, so that in practice we cannot just pick all the best players. Then, we would like to have a squad of players that give the most points given our budget. Thus, we would like to pick players that have high value ('bang for buck'). However, often the players with highest value are very cheap players who somewhat overperform relative to their price. Picking a squad full of these players might leave a part of our budget unused. Calculating the geometric mean of adjusted points and value allows us to weigh both aspects equally, i.e. we want players that both gain a lot of points but also have good value. For example, this metric values equally two players, where one has twice the points per game of the other who in turn has twice the value of the other.

In [5]:
# value = expected points / cost
df['value'] = df['adjusted points per game'] / (df['now_cost'] / 10.0)
# geometric mean of 'adjusted points per game' and 'value'
df['valuePoints metric'] = np.sqrt(df['adjusted points per game'] * df['value'])

In [6]:
# assign proper team names for each player
team_names = np.sort(teamStats['Squad'])
df['team_name'] = team_names[df['team']-1]

In [7]:
# save data
filepath = '../data/data_week' + str(gameweek) + str('.csv')
df.to_csv(filepath)

In [8]:
goalkeepers = df['element_type'] == 1
defenders = df['element_type'] == 2
midfielders = df['element_type'] == 3
forwards = df['element_type'] == 4

minGames = df['games played'] >= 3

## Player evaluation

Below we compile lists for each position sorting players based on a given metric.

In [9]:
metric = 'valuePoints metric'
#metric = 'adjusted points per game'
#metric = 'form 5'

numberToShow = 40

print('GOALKEEPERS')
display(df[goalkeepers & minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game','form 5',\
          'valuePoints metric']].head(numberToShow))
print('DEFENDERS')
display(df[defenders & minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game','form 5',\
          'valuePoints metric']].head(numberToShow))
print('MIDFIELDERS')
display(df[midfielders & minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game','form 5',\
          'valuePoints metric']].head(numberToShow))
print('FORWARDS')
display(df[forwards & minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game','form 5',\
          'valuePoints metric']].head(numberToShow))

GOALKEEPERS

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,form 5,valuePoints metric
id,,,,,,,,,,
411,PatrÃÂ­cio,Wolves,52,16.842105,64,72.493595,3.8,4.304307,3.709349,1.887564
341,Gazzaniga,Tottenham,46,10.967742,34,42.878194,3.1,3.909482,3.593710,1.822806
494,Ramsdale,Bournemouth,46,17.073171,70,65.678816,4.1,3.846902,4.224227,1.793627
131,Guaita,Crystal Palace,51,15.000000,69,59.537006,4.6,3.969134,6.570066,1.757562
47,Ryan,Brighton,48,17.000000,68,65.331051,4.0,3.843003,3.546943,1.754083
235,de Gea,Manchester Utd,55,17.096774,53,69.718133,3.1,4.077853,3.570257,1.738802
280,Krul,Norwich City,45,14.857143,52,54.541959,3.5,3.671093,2.254985,1.730570
471,Henderson,Sheffield Utd,48,16.000000,64,59.619621,4.0,3.726226,3.687495,1.700782
168,Schmeichel,Leicester City,54,17.073171,70,67.429636,4.1,3.949450,3.303809,1.699573
93,Pope,Burnley,47,17.222222,62,61.721136,3.6,3.583808,2.365890,1.653087
340,Lloris,Tottenham,53,6.969697,23,26.421170,3.3,3.790863,NaN,1.646646
14,Leno,Arsenal,50,16.969697,56,62.196816,3.3,3.665170,3.870040,1.639114
388,Fabianski,West Ham,49,6.956522,32,24.137499,4.6,3.469766,NaN,1.567480
262,Dubravka,Newcastle Utd,50,17.027027,63,59.515634,3.7,3.495363,4.322114,1.563174
526,AdriÃÂ¡n,Liverpool,42,10.000000,25,31.543072,2.5,3.154307,2.087452,1.539144
553,Martin,West Ham,41,4.000000,18,12.379062,4.5,3.094766,NaN,1.528396
366,Foster,Watford,48,16.857143,59,55.214395,3.5,3.275430,2.704539,1.495023
212,Ederson,Manchester City,60,16.111111,58,57.847655,3.6,3.590544,3.647628,1.465833
450,Roberto,West Ham,44,7.083333,17,21.212923,2.4,2.994766,2.691640,1.427698
319,Gunn,Southampton,44,10.000000,29,29.316914,2.9,2.931691,NaN,1.397629
148,Pickford,Everton,54,16.896552,49,54.469609,2.9,3.223712,3.293479,1.387265
318,McCarthy,Southampton,43,7.000000,14,19.821839,2.0,2.831691,3.268827,1.365563
111,Kepa,Chelsea,55,16.800000,42,52.500907,2.5,3.125054,3.272947,1.332527
189,Alisson,Liverpool,60,8.888889,24,28.927175,2.7,3.254307,3.041307,1.328565
94,Heaton,Aston Villa,45,15.925926,43,39.520525,2.7,2.481521,1.458234,1.169800

DEFENDERS

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,form 5,valuePoints metric
id,,,,,,,,,,
297,Lundstram,Sheffield Utd,52,17.115385,89,87.923184,5.2,5.137085,4.950149,2.252761
182,Alexander-Arnold,Liverpool,73,16.818182,74,89.175785,4.4,5.302344,4.104001,1.962486
208,Otamendi,Manchester City,50,11.000000,44,47.127475,4.0,4.284316,5.272050,1.916004
185,Matip,Liverpool,52,6.956522,32,29.916920,4.6,4.300557,NaN,1.885919
181,Robertson,Liverpool,71,16.976744,73,84.115817,4.3,4.954767,3.462681,1.859491
164,SÃÂ¶yÃÂ¼ncÃÂ¼,Leicester City,51,16.976744,73,71.234685,4.3,4.196016,5.073906,1.858027
162,Evans,Leicester City,52,17.111111,77,72.475379,4.5,4.235574,5.677803,1.857422
405,Boly,Wolves,48,8.095238,34,32.618246,4.2,4.029313,NaN,1.839121
161,Chilwell,Leicester City,58,13.877551,68,61.318072,4.9,4.418508,4.181216,1.834686
401,Doherty,Wolves,61,15.789474,60,69.553312,3.8,4.405043,3.749312,1.783550
159,Pereira,Leicester City,65,17.000000,85,76.368506,5.0,4.492265,4.454175,1.762011
440,AngeliÃÂ±o,Manchester City,47,6.111111,11,22.490945,1.8,3.680336,3.611762,1.697613
336,Aurier,Tottenham,51,11.951220,49,45.706510,4.1,3.824422,3.631772,1.693483
291,Stevens,Sheffield Utd,51,16.829268,69,63.927058,4.1,3.798564,4.317724,1.682033
294,Baldock,Sheffield Utd,49,17.111111,77,62.417944,4.5,3.647802,4.694002,1.647909
518,Cancelo,Manchester City,53,5.937500,19,22.488683,3.2,3.787568,3.326766,1.645214
293,O'Connell,Sheffield Utd,46,17.058824,58,59.463261,3.4,3.485777,3.503645,1.625252
183,van Dijk,Liverpool,64,16.976744,73,69.689402,4.3,4.104992,4.104622,1.622641
529,Tomori,Chelsea,48,11.142857,39,39.524071,3.5,3.547032,4.671498,1.618991
359,Janmaat,Watford,42,8.000000,36,26.457199,4.5,3.307150,NaN,1.613724
163,Fuchs,Leicester City,43,3.928571,11,13.013350,2.8,3.312489,3.459398,1.597424
103,Alonso,Chelsea,60,7.058824,36,27.544728,5.1,3.902170,NaN,1.593054
128,Kelly,Crystal Palace,44,12.093023,52,40.365039,4.3,3.337878,3.727006,1.591271
498,Willems,Newcastle Utd,47,13.953488,60,47.547011,4.3,3.407536,2.581237,1.571779
84,Tarkowski,Burnley,51,17.027027,63,59.866650,3.7,3.515978,2.687320,1.556901
160,Maguire,Manchester Utd,53,17.142857,36,60.884759,2.1,3.551611,3.286337,1.542721
122,Wan-Bissaka,Manchester Utd,53,15.217391,35,53.500963,2.3,3.515778,4.267177,1.527156
402,Jonny,Wolves,54,16.071429,45,56.718078,2.8,3.529125,3.944603,1.518694
105,Azpilicueta,Chelsea,58,15.000000,36,54.480661,2.4,3.632044,4.717433,1.508124
63,Adam Smith,Bournemouth,43,10.000000,32,31.264924,3.2,3.126492,3.078252,1.507729
295,Egan,Sheffield Utd,45,15.882353,54,50.675359,3.4,3.190671,2.945417,1.504097
203,Walker,Manchester City,58,14.062500,45,50.905868,3.2,3.619973,3.090102,1.503112
423,Basham,Sheffield Utd,45,17.096774,53,54.164514,3.1,3.168113,3.289194,1.493463
309,Targett,Aston Villa,44,11.111111,40,34.735119,3.6,3.126161,1.623326,1.490339
186,Lovren,Liverpool,53,8.000000,16,27.379741,2.0,3.422468,3.234845,1.486625
506,James,Chelsea,50,8.181818,18,27.103517,2.2,3.312652,4.674105,1.481463
6,Monreal,Arsenal,50,3.030303,10,10.035146,3.3,3.311598,NaN,1.480992
511,SidibÃÂ©,Everton,53,9.032258,28,30.774442,3.1,3.407170,3.571215,1.479980
447,Pieters,Burnley,45,15.000000,42,46.567161,2.8,3.104477,2.321267,1.463465
42,Dunk,Brighton,47,15.789474,60,49.872347,3.8,3.158582,3.778004,1.456945

MIDFIELDERS

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,form 5,valuePoints metric
id,,,,,,,,,,
215,De Bruyne,Manchester City,103,16.111111,116,104.660027,7.2,6.496140,6.763897,2.024122
191,Salah,Liverpool,122,14.054054,104,95.990860,7.4,6.830119,9.488022,1.955457
196,Keita,Liverpool,58,3.018868,16,14.042873,5.3,4.651702,11.362441,1.931514
171,Maddison,Leicester City,78,16.000000,88,85.543644,5.5,5.346478,6.696922,1.914346
431,Pulisic,Chelsea,74,14.042553,66,70.037786,4.7,4.987539,4.318254,1.833456
214,Sterling,Manchester City,118,15.964912,91,98.553096,5.7,6.173106,6.458342,1.797061
192,ManÃÂ©,Liverpool,122,15.972222,115,100.124111,7.2,6.268640,7.081143,1.794706
29,Grealish,Aston Villa,62,15.000000,66,66.787419,4.4,4.452495,4.440244,1.788165
219,David Silva,Manchester City,75,14.905660,79,71.878101,5.3,4.822202,4.824013,1.760819
287,Cantwell,Norwich City,47,16.944444,61,63.496319,3.6,3.747324,2.900166,1.728512
417,TraorÃÂ©,Wolves,53,15.853659,65,62.899872,4.1,3.967530,4.191626,1.723385
239,Martial,Manchester Utd,77,11.020408,54,52.019114,4.9,4.720253,3.551826,1.701061
463,Mount,Chelsea,65,16.904762,71,73.150871,4.2,4.327235,3.468637,1.697281
301,Fleck,Sheffield Utd,49,15.128205,59,55.482934,3.9,3.667516,4.871910,1.656815
269,Shelvey,Newcastle Utd,51,11.000000,55,40.821374,5.0,3.711034,5.295790,1.643273
114,Pedro,Chelsea,68,4.090909,9,17.369779,2.2,4.245946,4.670332,1.628246
321,Ward-Prowse,Southampton,59,16.944444,61,66.068420,3.6,3.899120,3.683787,1.605242
30,El Ghazi,Aston Villa,55,15.135135,56,55.905493,3.7,3.693756,3.720297,1.575023
344,Alli,Tottenham,87,10.000000,62,46.097790,6.2,4.609779,5.244896,1.562861
217,Mahrez,Manchester City,83,13.018868,69,58.289328,5.3,4.477296,3.479363,1.554092
243,James,Manchester Utd,61,16.842105,64,64.313900,3.8,3.818638,4.250249,1.546121
265,PÃÂ©rez,Leicester City,61,13.902439,57,51.845170,4.1,3.729214,4.721447,1.509915
31,McGinn,Aston Villa,57,17.142857,60,61.483465,3.5,3.586535,2.143101,1.502234
218,Bernardo Silva,Manchester City,79,15.000000,66,63.031879,4.4,4.202125,3.028193,1.495049
172,Barnes,Leicester City,59,16.060606,53,58.265679,3.3,3.627863,3.546419,1.493568
238,Pogba,Manchester Utd,84,5.000000,15,21.597788,3.0,4.319558,NaN,1.490389
448,Tielemans,Leicester City,66,16.829268,69,64.154581,4.1,3.812084,3.190245,1.483852
113,Willian,Chelsea,70,15.945946,59,62.575109,3.7,3.924202,3.173224,1.483209
415,Moutinho,Wolves,54,16.857143,59,58.009998,3.5,3.441271,3.720670,1.480887
371,Cleverley,Watford,48,8.888889,24,28.831088,2.7,3.243497,NaN,1.480447
421,Trossard,Brighton,58,11.081081,41,38.953521,3.7,3.515318,2.859018,1.459656
248,McTominay,Manchester Utd,51,15.142857,53,49.663867,3.5,3.279689,2.694976,1.452271
119,KantÃÂ©,Chelsea,50,10.000000,35,32.348349,3.5,3.234835,3.072763,1.446662
150,Richarlison,Everton,79,17.173913,79,67.374943,4.6,3.923098,2.874364,1.395776
117,Barkley,Chelsea,56,6.000000,9,19.609010,1.5,3.268168,NaN,1.381053
118,Jorginho,Chelsea,50,15.000000,45,46.158373,3.0,3.077225,2.506274,1.376177
283,BuendÃÂ­a,Norwich City,60,16.896552,49,56.723673,2.9,3.357115,3.471802,1.370537
17,Iwobi,Everton,56,14.782609,34,47.820993,2.3,3.234949,2.825555,1.367016
392,Yarmolenko,West Ham,55,14.848485,49,46.953125,3.3,3.162149,1.601034,1.348345
96,Gudmundsson,Burnley,59,4.047619,17,13.170366,4.2,3.253855,NaN,1.339591

FORWARDS

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,form 5,valuePoints metric
id,,,,,,,,,,
167,Iheanacho,Leicester City,57,3.013699,22,18.190566,7.3,6.035961,NaN,2.528186
278,Pukki,Norwich City,66,16.909091,93,88.735849,5.5,5.247819,6.665413,2.042711
233,Rashford,Manchester Utd,91,16.885246,103,103.626415,6.1,6.137098,6.930580,2.034428
460,Abraham,Chelsea,80,15.967742,99,90.535849,6.2,5.669922,4.783298,2.004620
166,Vardy,Leicester City,101,17.051282,133,107.526415,7.8,6.306060,8.106983,1.984255
502,Maupay,Brighton,58,17.073171,70,76.200000,4.1,4.463143,5.513333,1.853219
409,JimÃÂ©nez,Wolves,75,17.000000,85,85.826415,5.0,5.048613,4.991560,1.843493
313,Ings,Southampton,64,16.862745,86,76.845283,5.1,4.557104,4.879809,1.801354
68,King,Bournemouth,61,13.000000,52,54.535849,4.0,4.195065,3.073627,1.698532
91,Wood,Burnley,62,15.121951,62,63.600000,4.1,4.205806,4.246667,1.689093
210,AgÃÂ¼ero,Manchester City,117,12.000000,72,67.735849,6.0,5.644654,4.110925,1.650230
303,McGoldrick,Sheffield Utd,54,13.750000,33,52.490566,2.4,3.817496,4.601570,1.642789
11,Aubameyang,Arsenal,108,16.885246,103,89.835849,6.1,5.320376,6.143760,1.618939
468,Ayew,Crystal Palace,50,16.000000,56,56.300000,3.5,3.518750,2.420000,1.573633
187,Firmino,Liverpool,93,17.045455,75,79.926415,4.4,4.689016,3.434939,1.537589
410,Jota,Wolves,61,14.838710,46,55.145283,3.1,3.716313,4.625795,1.504691
90,Barnes,Burnley,62,15.135135,56,56.200000,3.7,3.713214,2.372727,1.491263
457,Haller,West Ham,70,16.153846,63,62.490566,3.9,3.868464,3.426285,1.462142
428,Wesley,Aston Villa,57,16.969697,56,58.845283,3.3,3.467668,2.173142,1.452446
67,Callum Wilson,Bournemouth,74,15.897436,62,60.235849,3.9,3.789029,2.252327,1.392875
70,Mousset,Sheffield Utd,51,14.146341,58,44.335849,4.1,3.134086,2.766094,1.387797
211,Jesus,Manchester City,96,13.846154,54,58.235849,3.9,4.205922,5.308046,1.357456
363,Deulofeu,Watford,61,17.142857,48,56.290566,2.8,3.283616,3.072951,1.329497
147,Calvert-Lewin,Everton,57,15.161290,47,47.900000,3.1,3.159362,4.120000,1.323311
338,Kane,Tottenham,109,16.153846,84,67.390566,5.2,4.171797,3.731298,1.263601
12,Lacazette,Arsenal,93,10.000000,47,37.990566,4.7,3.799057,4.573998,1.245760
534,Connolly,Brighton,46,11.000000,33,28.990566,3.0,2.635506,2.427341,1.228811
466,Joelinton,Newcastle Utd,56,17.272727,38,44.445283,2.2,2.573148,1.999809,1.087353
315,Long,Southampton,46,8.888889,16,20.045283,1.8,2.255094,3.222369,1.051443
362,Deeney,Watford,62,6.111111,11,15.700000,1.8,2.569091,2.369231,1.031772
188,Origi,Liverpool,52,13.000000,39,29.390566,3.0,2.260813,3.950405,0.991432
146,Tosun,Everton,57,4.000000,10,9.400000,2.5,2.350000,3.100000,0.984307
364,Gray,Watford,56,16.111111,29,37.200000,1.8,2.308966,1.253333,0.975716
69,Solanke,Bournemouth,52,14.666667,22,32.500000,1.5,2.215909,2.235714,0.971740
437,Adams,Southampton,54,11.666667,21,25.245283,1.8,2.163881,0.997502,0.931186
487,Cutrone,Wolves,56,11.000000,22,23.600000,2.0,2.145455,1.400000,0.906620
512,Welbeck,Watford,58,5.000000,7,10.500000,1.4,2.100000,NaN,0.871978
110,Giroud,Chelsea,66,5.000000,7,11.200000,1.4,2.240000,4.000000,0.871919
501,McBurnie,Sheffield Utd,57,14.736842,28,29.400000,1.9,1.995000,1.653333,0.835614
234,Greenwood,Manchester Utd,43,13.157895,25,22.500000,1.9,1.710000,3.063636,0.824635

Below we compile a list sorting players based on a given metric (irrespective of position).

In [10]:
#metric = 'adjusted points per game'
metric = 'form 5'

display(df[minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game','form 5',\
          'valuePoints metric']].head(numberToShow))

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,form 5,valuePoints metric
id,,,,,,,,,,
196,Keita,Liverpool,58,3.018868,16,14.042873,5.3,4.651702,11.362441,1.931514
191,Salah,Liverpool,122,14.054054,104,95.990860,7.4,6.830119,9.488022,1.955457
166,Vardy,Leicester City,101,17.051282,133,107.526415,7.8,6.306060,8.106983,1.984255
192,ManÃÂ©,Liverpool,122,15.972222,115,100.124111,7.2,6.268640,7.081143,1.794706
233,Rashford,Manchester Utd,91,16.885246,103,103.626415,6.1,6.137098,6.930580,2.034428
215,De Bruyne,Manchester City,103,16.111111,116,104.660027,7.2,6.496140,6.763897,2.024122
171,Maddison,Leicester City,78,16.000000,88,85.543644,5.5,5.346478,6.696922,1.914346
278,Pukki,Norwich City,66,16.909091,93,88.735849,5.5,5.247819,6.665413,2.042711
131,Guaita,Crystal Palace,51,15.000000,69,59.537006,4.6,3.969134,6.570066,1.757562
214,Sterling,Manchester City,118,15.964912,91,98.553096,5.7,6.173106,6.458342,1.797061
11,Aubameyang,Arsenal,108,16.885246,103,89.835849,6.1,5.320376,6.143760,1.618939
162,Evans,Leicester City,52,17.111111,77,72.475379,4.5,4.235574,5.677803,1.857422
107,Emerson,Chelsea,55,10.000000,16,33.493397,1.6,3.349340,5.538590,1.428163
502,Maupay,Brighton,58,17.073171,70,76.200000,4.1,4.463143,5.513333,1.853219
211,Jesus,Manchester City,96,13.846154,54,58.235849,3.9,4.205922,5.308046,1.357456
269,Shelvey,Newcastle Utd,51,11.000000,55,40.821374,5.0,3.711034,5.295790,1.643273
208,Otamendi,Manchester City,50,11.000000,44,47.127475,4.0,4.284316,5.272050,1.916004
344,Alli,Tottenham,87,10.000000,62,46.097790,6.2,4.609779,5.244896,1.562861
101,Westwood,Burnley,54,14.062500,45,43.194721,3.2,3.071625,5.200882,1.321817
164,SÃÂ¶yÃÂ¼ncÃÂ¼,Leicester City,51,16.976744,73,71.234685,4.3,4.196016,5.073906,1.858027
409,JimÃÂ©nez,Wolves,75,17.000000,85,85.826415,5.0,5.048613,4.991560,1.843493
330,Vertonghen,Tottenham,52,10.000000,35,31.393048,3.5,3.139305,4.974763,1.376676
297,Lundstram,Sheffield Utd,52,17.115385,89,87.923184,5.2,5.137085,4.950149,2.252761
38,Montoya,Brighton,45,15.185185,41,43.553193,2.7,2.868137,4.887465,1.352053
313,Ings,Southampton,64,16.862745,86,76.845283,5.1,4.557104,4.879809,1.801354
301,Fleck,Sheffield Utd,49,15.128205,59,55.482934,3.9,3.667516,4.871910,1.656815
219,David Silva,Manchester City,75,14.905660,79,71.878101,5.3,4.822202,4.824013,1.760819
460,Abraham,Chelsea,80,15.967742,99,90.535849,6.2,5.669922,4.783298,2.004620
265,PÃÂ©rez,Leicester City,61,13.902439,57,51.845170,4.1,3.729214,4.721447,1.509915
105,Azpilicueta,Chelsea,58,15.000000,36,54.480661,2.4,3.632044,4.717433,1.508124
294,Baldock,Sheffield Utd,49,17.111111,77,62.417944,4.5,3.647802,4.694002,1.647909
49,GroÃÂ,Brighton,64,16.250000,52,54.366861,3.2,3.345653,4.691134,1.322485
506,James,Chelsea,50,8.181818,18,27.103517,2.2,3.312652,4.674105,1.481463
529,Tomori,Chelsea,48,11.142857,39,39.524071,3.5,3.547032,4.671498,1.618991
114,Pedro,Chelsea,68,4.090909,9,17.369779,2.2,4.245946,4.670332,1.628246
410,Jota,Wolves,61,14.838710,46,55.145283,3.1,3.716313,4.625795,1.504691
303,McGoldrick,Sheffield Utd,54,13.750000,33,52.490566,2.4,3.817496,4.601570,1.642789
12,Lacazette,Arsenal,93,10.000000,47,37.990566,4.7,3.799057,4.573998,1.245760
305,Bertrand,Southampton,48,12.500000,15,28.441425,1.2,2.275314,4.542525,1.038534
503,Cahill,Crystal Palace,45,11.923077,31,33.555056,2.6,2.814295,4.522242,1.326671