In [1]:
# recent gameweek
latest_gameweek = 12

In [2]:
import pandas as pd
import numpy as np

# allow more data columns to be shown than by default
pd.set_option('max_columns',100)

In [3]:
# fetch FPL data
filepath = '../data/fpl/data_week' + str(latest_gameweek) + '.csv'
players = pd.read_csv(filepath, index_col=0)

In [4]:
# how many gameweeks do we look form for
for i in [5,10]:
    number_gameweeks = i
    # create a list of relevant column names
    column_list = []
    for i in range(0,number_gameweeks):
        column_list.append('xPoints week ' + str(latest_gameweek-i))
    # calculate form
    column_name = 'form ' + str(number_gameweeks)
    players[column_name] = players[column_list].mean(axis=1)

In [5]:
# give a sorted list showing the players with best 'form 5'
players[['web_name', 'games played','total_points', 'points_per_game','adjusted points','adjusted points per game',\
                                'form 5', 'form 10']].sort_values(by='form 5', ascending=False)

,web_name,games played,total_points,points_per_game,adjusted points,adjusted points per game,form 5,form 10
id,,,,,,,,
457,Doherty,6.000000,24,4.0,24.967383,4.161230,8.854254,5.558194
272,De Bruyne,10.000000,56,5.6,69.777154,6.977715,8.712051,6.470192
302,Fernandes,11.066667,83,7.5,73.907259,6.678367,8.287832,7.451353
254,Salah,11.046512,95,8.6,80.492210,7.286663,7.756663,7.078958
300,Shaw,7.931034,23,2.9,23.191704,2.924171,7.228481,3.569292
366,Ings,8.955224,60,6.7,48.875430,5.457756,6.989238,5.845073
275,Mahrez,8.965517,52,5.8,47.537223,5.302229,6.988379,5.482874
274,Mendy,5.000000,22,4.4,16.092587,3.218517,6.278102,3.665221
117,Werner,11.875000,57,4.8,61.013907,5.138013,6.248174,5.493191
96,Pope,10.000000,53,5.3,46.598499,4.659850,6.117111,5.260368
224,Vardy,11.012658,87,7.9,76.312384,6.929515,6.069414,7.369401
57,Groß,11.142857,39,3.5,41.263901,3.703171,6.060788,3.987539
141,Zaha,10.000000,74,7.4,60.933460,6.093346,5.986058,6.031976
202,Bamford,12.096774,75,6.2,71.935430,5.946662,5.955695,6.087848
367,Stephens,4.000000,8,2.0,9.446035,2.361509,5.726123,2.863061
431,Fabianski,12.083333,58,4.8,54.119165,4.478827,5.685122,5.257268
445,Bowen,12.040816,59,4.9,53.876084,4.474454,5.535000,4.801177
40,Trézéguet,8.928571,25,2.8,39.660953,4.442027,5.496803,4.595346
232,Chilwell,8.955224,60,6.7,44.202706,4.935969,5.496238,5.655915
388,Kane,12.022472,107,8.9,88.624768,7.371593,5.488174,7.089780
273,Stones,4.000000,22,5.5,16.894069,4.223517,5.442574,5.442574
560,Kelleher,1.000000,7,7.0,3.962034,3.962034,5.426123,5.426123
123,James,11.041667,53,4.8,50.172289,4.543905,5.360832,4.815922
229,Pérez,6.060606,20,3.3,19.450923,3.209402,5.275801,3.775577
306,Rashford,11.063830,52,4.7,50.348030,4.550687,5.263239,4.990528
383,Lloris,11.914894,56,4.7,51.864494,4.352913,5.232927,4.660450
329,Gayle,1.000000,8,8.0,5.200000,5.200000,5.200000,5.200000
106,Barkley,8.000000,32,4.0,32.802775,4.100347,5.069811,4.969095
164,Calvert-Lewin,12.028986,83,6.9,65.656954,5.458229,4.987083,4.733541
390,Son,11.931818,105,8.8,72.385665,6.066608,4.978521,5.788786
...,...,...,...,...,...,...,...,...
414,Hegazi,1.000000,6,6.0,2.639519,2.639519,NaN,3.331484
416,Zohore,NaN,0,0.0,NaN,NaN,NaN,NaN
420,Leko,NaN,0,0.0,NaN,NaN,NaN,NaN
423,Field,3.000000,3,1.0,3.479639,1.159880,NaN,1.000000
426,Harper,1.000000,1,1.0,1.159880,1.159880,NaN,NaN
499,Kipre,NaN,0,0.0,NaN,NaN,NaN,NaN
600,Peltier,NaN,0,0.0,NaN,NaN,NaN,NaN
429,Martin,NaN,0,0.0,NaN,NaN,NaN,NaN
430,Randolph,NaN,0,0.0,NaN,NaN,NaN,NaN
433,Roberto,NaN,0,0.0,NaN,NaN,NaN,NaN
434,Wilshere,NaN,0,0.0,NaN,NaN,NaN,NaN
436,Yarmolenko,5.000000,4,0.8,7.453707,1.490741,NaN,1.400000
438,Fredericks,3.076923,4,1.3,8.364524,2.718470,NaN,1.600000
440,Felipe Anderson,2.000000,2,1.0,2.501483,1.250741,NaN,NaN
444,Hugill,NaN,0,0.0,NaN,NaN,NaN,NaN
447,Ajeti,NaN,0,0.0,NaN,NaN,NaN,NaN
576,Dawson,NaN,0,0.0,NaN,NaN,NaN,NaN
453,Ruddy,NaN,0,0.0,NaN,NaN,NaN,NaN
456,Bennett,NaN,0,0.0,NaN,NaN,NaN,NaN
462,Jonny,NaN,0,0.0,NaN,NaN,NaN,NaN
463,Bonatini,NaN,0,0.0,NaN,NaN,NaN,NaN
467,Buur,1.000000,1,1.0,2.225025,2.225025,NaN,NaN
471,Vinagre,2.000000,1,0.5,3.450049,1.725025,NaN,0.661196
472,Sarkic,NaN,0,0.0,NaN,NaN,NaN,NaN
473,Gibbs-White,NaN,0,0.0,NaN,NaN,NaN,NaN
475,Jordao,NaN,0,0.0,NaN,NaN,NaN,NaN
476,Campana,NaN,0,0.0,NaN,NaN,NaN,NaN
545,Hoever,2.000000,2,1.0,4.450049,2.225025,NaN,1.000000
553,Shabani,NaN,0,0.0,NaN,NaN,NaN,NaN
581,Otasowie,NaN,0,0.0,NaN,NaN,NaN,NaN

In [6]:
# save data
filepath = '../data/fpl/data_week' + str(latest_gameweek) + '.csv'
players.to_csv(filepath)