# Player form

Here we are interested in evaluating how well the players have been doing recently, i.e. we evaluated each player's current form. Essentially, we calculate a weighted average of a player's adjusted points from a given number of previous games. We weight points so that more recent games are emphasized.

In [1]:
latest_gameweek = 16

# how many gameweeks do we use to evaluate form
number_games = 5

In [2]:
# import basic libraries

import pandas as pd
import numpy as np
pd.set_option('max_columns',100)

In [3]:
# fetch relevant data

data = []

for i in range(0, number_games+1):
    # create string for filename to be read
    data_string = '../data/data_week' + str(latest_gameweek-i) + '.csv'
    print(data_string)
    # read data
    new_data = pd.read_csv(data_string,index_col='id',encoding='latin1')
    data.append(new_data)

./data/data_week16.csv
./data/data_week15.csv
./data/data_week14.csv
./data/data_week13.csv
./data/data_week12.csv
./data/data_week11.csv

In [4]:
# calculate form

column_name = 'form ' + str(number_games)
for ix in data[0][data[0]['minutes']>0].index:
    points = 0
    total_weight = 0
    for i in range(0, number_games):
        if (ix in data[i].index) & (ix in data[i+1].index):
            if (data[i].loc[ix,'minutes'] > data[i+1].loc[ix,'minutes']):
                weight = (number_games-i) / number_games
                total_weight += weight
                points += weight * (data[i].loc[ix,'adjusted points'] - data[i+1].loc[ix,'adjusted points'])
    if total_weight > 0:
        data[0].loc[ix, column_name] = points / total_weight

In [5]:
# display a sorted list showing players with the best current form
data[0].sort_values(by=column_name, ascending=False)[['web_name',column_name]]

         web_name     form 5
id
196         Keita  11.362441
166         Vardy   9.726321
192          Mané   8.423082
233      Rashford   8.399026
191         Salah   8.060977
68           King   7.705919
171      Maddison   7.592412
11     Aubameyang   7.350845
162         Evans   6.694943
313          Ings   6.140489
460       Abraham   5.839820
215     De Bruyne   5.774794
409       Jiménez   5.630897
344          Alli   5.620795
159       Pereira   5.496658
164       Söyüncü   5.231467
131        Guaita   5.212198
269       Shelvey   5.110297
211         Jesus   5.040979
502        Maupay   5.026667
294       Baldock   5.008278
161      Chilwell   4.966420
529        Tomori   4.956755
410          Jota   4.952331
214      Sterling   4.887283
431       Pulisic   4.796177
208      Otamendi   4.787535
219   David Silva   4.770467
278         Pukki   4.746643
188         Origi   4.746555
..            ...        ...
367      Dahlberg        NaN
371     Cleverley        NaN
372          Sema        NaN
512       Welbeck        NaN
513         Gomes        NaN
542     Foulquier        NaN
563  Dele-Bashiru        NaN
379      Zabaleta        NaN
383          Reid        NaN
384       Johnson        NaN
385    Arnautovic        NaN
386    Chicharito        NaN
387   Xande Silva        NaN
388     Fabianski        NaN
394      Wilshere        NaN
398      Diangana        NaN
400        Obiang        NaN
553        Martin        NaN
405          Boly        NaN
408        Kilman        NaN
412         Ruddy        NaN
413        Norris        NaN
416   Gibbs-White        NaN
418         Costa        NaN
419     Cavaleiro        NaN
473       Vallejo        NaN
559   Ashley-Seal        NaN
560         Perry        NaN
566      Otasowie        NaN
567        Cundle        NaN

[569 rows x 2 columns]

In [6]:
# save data
filepath = '../data/data_week' + str(latest_gameweek) + str('.csv')
data[0].to_csv(filepath)