# Player form

Here we are interested in evaluating how well the players have been doing recently, i.e. we evaluated each player's current form. Essentially, we calculate a weighted average of a player's adjusted points from a given number of previous games. We weight points so that more recent games are emphasized.

In [8]:
latest_gameweek = 22

# how many gameweeks do we use to evaluate form
number_games = 5

In [9]:
# import basic libraries

import pandas as pd
import numpy as np
pd.set_option('max_columns',100)

In [10]:
# fetch relevant data

data = []

for i in range(0, number_games+1):
    # create string for filename to be read
    data_string = '../data/data_week' + str(latest_gameweek-i) + '.csv'    
    try:
        # read data
        new_data = pd.read_csv(data_string,index_col='id',encoding='latin1')
        print(data_string)
        data.append(new_data) 
    # throw an exception if the data file is not found
    except FileNotFoundError:
        print(data_string + ' not found.')

../data/data_week22.csv
../data/data_week21.csv
../data/data_week20.csv
../data/data_week19.csv not found.
../data/data_week18.csv
../data/data_week17.csv

In [11]:
# this is used in the following to calculate form as a weighted average of recent gameweek adjusted points
def weighted_points(games_played,points,total_weight):
    weight = (number_games-i) / number_games
    total_weight += weight
    points += weight * (data[i].loc[ix,'adjusted points'] - data[i+1].loc[ix,'adjusted points']) / games_played
    return points, total_weight

In [12]:
# calculate form

column_name = 'form ' + str(number_games)
for ix in data[0][data[0]['minutes']>0].index:
    points = 0
    total_weight = 0
    for i in range(0, len(data)-1):
        if (ix in data[i].index) & (ix in data[i+1].index):
            # sometimes players get to play two games in a gameweek
            # also, it is possible that data from a given gameweek is missing, in which case data[i] and data[i+1] 
            # cover two gameweeks
            if (data[i].loc[ix,'minutes'] - data[i+1].loc[ix,'minutes']) > 90:
                points, total_weight = weighted_points(2,points,total_weight)
            elif (data[i].loc[ix,'minutes'] - data[i+1].loc[ix,'minutes']) > 0:
                points, total_weight = weighted_points(1,points,total_weight)
    if total_weight > 0:
        data[0].loc[ix, column_name] = points / total_weight

In [13]:
# display a sorted list showing players with the best current form
data[0].sort_values(by=column_name, ascending=False)[['web_name',column_name]]

             web_name     form 5
id
342               Son  19.601332
105       Azpilicueta   8.203164
313              Ings   7.169739
191             Salah   6.948494
103            Alonso   6.851449
211             Jesus   6.651614
187           Firmino   6.650599
192              Mané   6.183230
217            Mahrez   6.139181
150       Richarlison   6.047085
141             Digne   5.928807
130           Wickham   5.836322
549          Williams   5.771857
210            Agüero   5.756895
233          Rashford   5.555840
368          Doucouré   5.505650
308          Stephens   5.440433
5            Sokratis   5.429350
182  Alexander-Arnold   5.351865
501          McBurnie   5.264286
506             James   5.260046
265             Pérez   5.236216
283           Buendía   5.208312
301             Fleck   5.059698
401           Doherty   5.057671
123       van Aanholt   4.916469
42               Dunk   4.823179
525              Sarr   4.795614
181         Robertson   4.784737
363          Deulofeu   4.706335
..                ...        ...
513             Gomes        NaN
542         Foulquier        NaN
563      Dele-Bashiru        NaN
592        João Pedro        NaN
383              Reid        NaN
384           Johnson        NaN
385        Arnautovic        NaN
386        Chicharito        NaN
387       Xande Silva        NaN
392        Yarmolenko        NaN
394          Wilshere        NaN
398          Diangana        NaN
400            Obiang        NaN
568           Holland        NaN
582             Anang        NaN
593            Ngakia        NaN
594           Cardoso        NaN
595              Rosa        NaN
405              Boly        NaN
412             Ruddy        NaN
413            Norris        NaN
416       Gibbs-White        NaN
418             Costa        NaN
419         Cavaleiro        NaN
473           Vallejo        NaN
559       Ashley-Seal        NaN
560             Perry        NaN
566          Otasowie        NaN
567            Cundle        NaN
587              Buur        NaN

[597 rows x 2 columns]

In [14]:
# save data
filepath = '../data/data_week' + str(latest_gameweek) + str('.csv')
data[0].to_csv(filepath)