# Player form

Here we are interested in evaluating how well the players have been doing recently, i.e. we evaluated each player's current form. Essentially, we calculate a weighted average of a player's adjusted points from a given number of previous games. We weight points so that more recent games are emphasized.

In [8]:
latest_gameweek = 28

# how many gameweeks do we use to evaluate form
number_games = 10

In [9]:
# import basic libraries

import pandas as pd
import numpy as np
pd.set_option('max_columns',100)

In [10]:
# fetch relevant data

data = []

for i in range(0, number_games+1):
    # create string for filename to be read
    data_string = '../data/data_week' + str(latest_gameweek-i) + '.csv'    
    try:
        # read data
        new_data = pd.read_csv(data_string,index_col='id')
        print(data_string)
        data.append(new_data) 
    # throw an exception if the data file is not found
    except FileNotFoundError:
        print(data_string + ' not found.')
    except UnicodeDecodeError:
        new_data = pd.read_csv(data_string, index_col='id', engine='python')
        print(data_string)
        data.append(new_data)

../data/data_week28.csv
../data/data_week27.csv
../data/data_week26.csv
../data/data_week25.csv
../data/data_week24.csv
../data/data_week23.csv
../data/data_week22.csv
../data/data_week21.csv
../data/data_week20.csv
../data/data_week19.csv not found.
../data/data_week18.csv

In [11]:
# this is used in the following to calculate form as a weighted average of recent gameweek adjusted points
def weighted_points(games_played,points,total_weight):
    weight = (number_games-i) / number_games
    total_weight += weight
    points += weight * (data[i].loc[ix,'adjusted points'] - data[i+1].loc[ix,'adjusted points']) / games_played
    return points, total_weight

In [12]:
# calculate form

column_name = 'form ' + str(number_games)
for ix in data[0][data[0]['minutes']>0].index:
    points = 0
    total_weight = 0
    for i in range(0, len(data)-1):
        if (ix in data[i].index) & (ix in data[i+1].index):
            # sometimes players get to play two games in a gameweek
            # also, it is possible that data from a given gameweek is missing, in which case data[i] and data[i+1] 
            # cover two gameweeks
            if (data[i].loc[ix,'minutes'] - data[i+1].loc[ix,'minutes']) > 90:
                points, total_weight = weighted_points(2,points,total_weight)
            elif (data[i].loc[ix,'minutes'] - data[i+1].loc[ix,'minutes']) > 0:
                points, total_weight = weighted_points(1,points,total_weight)
    if total_weight > 0:
        data[0].loc[ix, column_name] = points / total_weight

In [13]:
# display a sorted list showing players with the best current form
data[0].sort_values(by=column_name, ascending=False)[['web_name',column_name]]

             web_name   form 10
id
103            Alonso  8.581485
618         Fernandes  7.886019
150       Richarlison  6.647477
342               Son  6.492838
191             Salah  6.225873
233          Rashford  6.186154
410              Jota  6.122215
525              Sarr  6.056733
147     Calvert-Lewin  5.687180
215         De Bruyne  5.668131
93               Pope  5.462394
5            Sokratis  5.442480
401           Doherty  5.435851
187           Firmino  5.405589
446            Stacey  5.318765
182  Alexander-Arnold  5.310715
217            Mahrez  5.298195
210            Agüero  5.278193
409           Jiménez  5.246503
340            Lloris  5.155079
123       van Aanholt  5.139136
141             Digne  4.986978
105       Azpilicueta  4.932848
11         Aubameyang  4.913020
488              Pépé  4.906923
471         Henderson  4.886258
129           Benteke  4.821185
168        Schmeichel  4.803272
344              Alli  4.776725
411          Patrício  4.722631
..                ...       ...
592        João Pedro       NaN
383              Reid       NaN
384           Johnson       NaN
385        Arnautovic       NaN
386        Chicharito       NaN
387       Xande Silva       NaN
392        Yarmolenko       NaN
394          Wilshere       NaN
398          Diangana       NaN
400            Obiang       NaN
568           Holland       NaN
582             Anang       NaN
593            Ngakia       NaN
594           Cardoso       NaN
595              Rosa       NaN
616            Soucek       NaN
626             Bowen       NaN
412             Ruddy       NaN
413            Norris       NaN
418             Costa       NaN
419         Cavaleiro       NaN
473           Vallejo       NaN
487           Cutrone       NaN
559       Ashley-Seal       NaN
560             Perry       NaN
566          Otasowie       NaN
567            Cundle       NaN
587              Buur       NaN
607             Giles       NaN
609            Jordao       NaN

[626 rows x 2 columns]

In [14]:
# save form results to latest data file

filepath = '../data/data_week' + str(latest_gameweek) + str('.csv')
df = pd.read_csv(filepath, index_col=0)
df[column_name] = data[0][column_name].copy()
df.to_csv(filepath)