# Player form

Here we are interested in evaluating how well the players have been doing recently, i.e. we evaluated each player's current form. Essentially, we calculate a weighted average of a player's adjusted points from a given number of previous games. We weight points so that more recent games are emphasized.

In [1]:
latest_gameweek = 22

# how many gameweeks do we use to evaluate form
number_games = 10

In [2]:
# import basic libraries

import pandas as pd
import numpy as np
pd.set_option('max_columns',100)

In [3]:
# fetch relevant data

data = []

for i in range(0, number_games+1):
    # create string for filename to be read
    data_string = '../data/data_week' + str(latest_gameweek-i) + '.csv'    
    try:
        # read data
        new_data = pd.read_csv(data_string,index_col='id',encoding='latin1')
        print(data_string)
        data.append(new_data) 
    # throw an exception if the data file is not found
    except FileNotFoundError:
        print(data_string + ' not found.')

../data/data_week22.csv
../data/data_week21.csv
../data/data_week20.csv
../data/data_week19.csv not found.
../data/data_week18.csv
../data/data_week17.csv
../data/data_week16.csv
../data/data_week15.csv
../data/data_week14.csv
../data/data_week13.csv
../data/data_week12.csv

In [4]:
# this is used in the following to calculate form as a weighted average of recent gameweek adjusted points
def weighted_points(games_played,points,total_weight):
    weight = (number_games-i) / number_games
    total_weight += weight
    points += weight * (data[i].loc[ix,'adjusted points'] - data[i+1].loc[ix,'adjusted points']) / games_played
    return points, total_weight

In [5]:
# calculate form

column_name = 'form ' + str(number_games)
for ix in data[0][data[0]['minutes']>0].index:
    points = 0
    total_weight = 0
    for i in range(0, len(data)-1):
        if (ix in data[i].index) & (ix in data[i+1].index):
            # sometimes players get to play two games in a gameweek
            # also, it is possible that data from a given gameweek is missing, in which case data[i] and data[i+1] 
            # cover two gameweeks
            if (data[i].loc[ix,'minutes'] - data[i+1].loc[ix,'minutes']) > 90:
                points, total_weight = weighted_points(2,points,total_weight)
            elif (data[i].loc[ix,'minutes'] - data[i+1].loc[ix,'minutes']) > 0:
                points, total_weight = weighted_points(1,points,total_weight)
    if total_weight > 0:
        data[0].loc[ix, column_name] = points / total_weight

In [6]:
# display a sorted list showing players with the best current form
data[0].sort_values(by=column_name, ascending=False)[['web_name',column_name]]

             web_name   form 10
id
342               Son  8.538892
191             Salah  7.775896
103            Alonso  6.851449
192             ManÃ©  6.693703
105       Azpilicueta  6.631326
313              Ings  6.390705
166             Vardy  6.035419
211             Jesus  5.984383
233          Rashford  5.861906
196             Keita  5.832389
130           Wickham  5.762929
215         De Bruyne  5.427405
187           Firmino  5.248033
217            Mahrez  5.181592
265            PÃ©rez  5.109207
182  Alexander-Arnold  5.047349
301             Fleck  4.879007
131            Guaita  4.831698
210           AgÃ¼ero  4.799376
506             James  4.791603
549          Williams  4.736318
150       Richarlison  4.667169
308          Stephens  4.661043
401           Doherty  4.653654
283          BuendÃ­a  4.620905
409          JimÃ©nez  4.606512
42               Dunk  4.605256
214          Sterling  4.578472
525              Sarr  4.544642
181         Robertson  4.398792
..                ...       ...
513             Gomes       NaN
542         Foulquier       NaN
563      Dele-Bashiru       NaN
592       JoÃ£o Pedro       NaN
383              Reid       NaN
384           Johnson       NaN
385        Arnautovic       NaN
386        Chicharito       NaN
387       Xande Silva       NaN
394          Wilshere       NaN
398          Diangana       NaN
400            Obiang       NaN
553            Martin       NaN
582             Anang       NaN
593            Ngakia       NaN
594           Cardoso       NaN
595              Rosa       NaN
405              Boly       NaN
408            Kilman       NaN
412             Ruddy       NaN
413            Norris       NaN
416       Gibbs-White       NaN
418             Costa       NaN
419         Cavaleiro       NaN
473           Vallejo       NaN
559       Ashley-Seal       NaN
560             Perry       NaN
566          Otasowie       NaN
567            Cundle       NaN
587              Buur       NaN

[597 rows x 2 columns]

In [7]:
filepath = '../data/data_week' + str(latest_gameweek) + str('.csv')
df = pd.read_csv(filepath, index_col=0)
#df.head()

In [8]:
df[column_name] = data[0][column_name].copy()

In [9]:
df.to_csv(filepath)

In [ ]:
# save data
#filepath = '../data/data_week' + str(latest_gameweek) + str('.csv')
#data[0].to_csv(filepath)