# Player evaluation

Here we compare players based on their adjusted points. Also, we calculate some useful metrics using the adjusted points to further evaluate player performance in FPL.

In [1]:
# recent gameweek
gameweek = 18

In [2]:
# import basic libraries
import pandas as pd
import numpy as np

pd.set_option('max_columns',100)

In [3]:
# fetch FPL data
df = pd.read_csv('../data/data_week' + str(gameweek) + '.csv', index_col=0, encoding='latin-1')
df.head()

,assists,bonus,bps,chance_of_playing_next_round,chance_of_playing_this_round,clean_sheets,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,creativity,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,goals_conceded,goals_scored,ict_index,in_dreamteam,influence,minutes,news,news_added,now_cost,own_goals,penalties_missed,penalties_saved,photo,points_per_game,red_cards,saves,second_name,selected_by_percent,special,squad_number,status,team,team_code,threat,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,yellow_cards,games played,adjusted points,adjusted points per game,form 5
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,1,0,24,100.0,100.0,0,69140,0,0,-3,3,0.8,0,2,1.2,1.2,0,Shkodran,0.7,2,0,7.5,False,19.8,90,NaN,2019-11-28T23:00:21.541666Z,52,0,0,0,69140.jpg,4.0,0,0,Mustafi,0.3,False,NaN,a,1,3,54.0,4,7947,42,32342,135,0.1,0.8,Mustafi,0,1.000000,4.475512,4.475512,NaN
2,0,0,26,75.0,75.0,0,98745,0,0,-1,1,22.7,0,2,0.5,0.5,0,HÃÂ©ctor,0.2,6,0,6.9,False,30.8,262,Hamstring injury - 75% chance of playing,2019-12-09T20:00:21.228098Z,54,0,0,0,98745.jpg,0.3,0,0,BellerÃÂ­n,0.3,False,NaN,d,1,3,15.0,1,34674,24,34578,341,0.0,0.2,BellerÃÂ­n,2,3.333333,4.375909,1.312773,1.000168
3,2,1,196,0.0,0.0,1,111457,0,0,-3,3,149.6,0,2,0.0,0.0,0,Sead,1.3,17,0,37.8,False,174.4,928,Ankle injury - Expected back 11 Jan,2019-12-15T19:30:19.136195Z,52,0,0,0,111457.jpg,1.9,0,0,Kolasinac,0.6,False,NaN,i,1,3,55.0,27,46958,11,112204,1076,0.2,5.2,Kolasinac,2,14.210526,38.818566,2.731677,2.486991
4,2,3,150,100.0,100.0,2,154043,0,0,-4,4,143.5,1,2,2.0,2.0,6,Ainsley,1.5,14,0,35.4,False,182.8,760,NaN,2019-09-22T18:00:10.824841Z,46,0,0,0,154043.jpg,2.9,1,0,Maitland-Niles,2.6,False,NaN,a,1,3,33.0,26,548323,1040,569302,593,0.3,5.7,Maitland-Niles,0,8.965517,27.478614,3.064922,3.154755
5,0,2,224,100.0,0.0,2,39476,0,0,-1,1,30.7,0,2,0.8,0.0,0,Sokratis,0.3,23,1,44.3,False,340.2,1350,NaN,2019-12-15T19:30:19.149412Z,49,0,0,0,39476.jpg,2.2,0,0,Papastathopoulos,1.4,False,NaN,a,1,3,71.0,33,107545,179,148456,862,0.1,6.7,Sokratis,5,15.000000,35.841591,2.389439,1.569891

In [4]:
# fetch team data
filepath = '../data/fbref/team_stats_week' + str(gameweek) + '.csv'
teamStats = pd.read_csv(filepath, index_col=0, encoding='latin-1')

# fetch player stats data
filepath = '../data/fbref/player_stats_week' + str(gameweek) + '.csv'
playerStats = pd.read_csv(filepath, index_col=0, skiprows=1, encoding='latin-1')

## Value and value points

Here we calculate two interesting metrics: 'value' and 'value points'. 

Value is simply adjusted points per game divided by the cost of the player. Essentially, this measures how many 'points per pound(/euro/whatever)' has the player gained on an average game week. 

The value points is calculated as the geometric mean of a players adjusted points per game and value. Essentially, in FPL we want to gain the maximum possible amount of points. However, we are restrained by a limited budget, so that in practice we cannot just pick all the best players. Then, we would like to have a squad of players that give the most points given our budget. Thus, we would like to pick players that have high value ('bang for buck'). However, often the players with highest value are very cheap players who somewhat overperform relative to their price. Picking a squad full of these players might leave a part of our budget unused. Calculating the geometric mean of adjusted points and value allows us to weigh both aspects equally, i.e. we want players that both gain a lot of points but also have good value. For example, this metric values equally two players, where one has twice the points per game of the other who in turn has twice the value of the other.

In [5]:
# value = expected points / cost
df['value'] = df['adjusted points per game'] / (df['now_cost'] / 10.0)
# geometric mean of 'adjusted points per game' and 'value'
df['valuePoints metric'] = np.sqrt(df['adjusted points per game'] * df['value'])

In [6]:
# assign proper team names for each player
team_names = np.sort(teamStats['Squad'])
df['team_name'] = team_names[df['team']-1]

In [7]:
# save data
filepath = '../data/data_week' + str(gameweek) + str('.csv')
df.to_csv(filepath)

In [8]:
goalkeepers = df['element_type'] == 1
defenders = df['element_type'] == 2
midfielders = df['element_type'] == 3
forwards = df['element_type'] == 4

minGames = df['games played'] >= 3

## Player evaluation

Below we compile lists for each position sorting players based on a given metric.

In [9]:
metric = 'valuePoints metric'
#metric = 'adjusted points per game'
#metric = 'form 5'

numberToShow = 40

print('GOALKEEPERS')
display(df[goalkeepers & minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game','form 5',\
          'valuePoints metric']].head(numberToShow))
print('DEFENDERS')
display(df[defenders & minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game','form 5',\
          'valuePoints metric']].head(numberToShow))
print('MIDFIELDERS')
display(df[midfielders & minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game','form 5',\
          'valuePoints metric']].head(numberToShow))
print('FORWARDS')
display(df[forwards & minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game','form 5',\
          'valuePoints metric']].head(numberToShow))

GOALKEEPERS

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,form 5,valuePoints metric
id,,,,,,,,,,
411,PatrÃÂ­cio,Wolves,52,17.894737,68,78.186538,3.8,4.369248,4.284080,1.916042
471,Henderson,Sheffield Utd,48,16.888889,76,68.617960,4.5,4.062905,5.457301,1.854454
494,Ramsdale,Bournemouth,46,18.000000,72,70.362649,4.0,3.909036,4.597362,1.822597
47,Ryan,Brighton,48,17.948718,70,70.379577,3.9,3.921148,4.145499,1.789751
131,Guaita,Crystal Palace,51,16.136364,71,63.919737,4.4,3.961223,6.186102,1.754059
93,Pope,Burnley,47,18.157895,69,68.643690,3.8,3.780377,3.658800,1.743758
235,de Gea,Manchester Utd,55,18.000000,54,73.082516,3.0,4.060140,3.548081,1.731249
168,Schmeichel,Leicester City,54,17.857143,75,70.983515,4.2,3.975077,3.313907,1.710601
341,Gazzaniga,Tottenham,46,12.142857,34,44.511004,2.8,3.665612,2.994421,1.709100
280,Krul,Norwich City,45,16.060606,53,57.545104,3.3,3.582997,2.205677,1.689041
340,Lloris,Tottenham,53,6.969697,23,26.640184,3.3,3.822287,NaN,1.660295
14,Leno,Arsenal,50,18.235294,62,66.827032,3.4,3.664708,3.859674,1.638907
262,Dubravka,Newcastle Utd,50,18.205128,71,66.032581,3.9,3.627142,5.079441,1.622107
366,Foster,Watford,48,17.948718,70,63.715740,3.9,3.549877,4.711132,1.620290
388,Fabianski,West Ham,49,6.956522,32,24.599621,4.6,3.536196,NaN,1.597490
553,Martin,West Ham,41,4.000000,18,12.644782,4.5,3.161196,NaN,1.561203
526,AdriÃÂ¡n,Liverpool,42,10.000000,25,31.889320,2.5,3.188932,2.051264,1.556039
212,Ederson,Manchester City,60,17.142857,60,62.372463,3.5,3.638394,3.964974,1.485368
450,Roberto,West Ham,44,7.083333,17,21.683468,2.4,3.061196,NaN,1.459368
318,McCarthy,Southampton,43,8.095238,17,24.305894,2.1,3.002493,3.733966,1.447931
319,Gunn,Southampton,44,10.000000,29,30.024928,2.9,3.002493,NaN,1.431382
148,Pickford,Everton,53,17.741935,55,58.233814,3.1,3.282270,3.583000,1.425727
111,Kepa,Chelsea,55,17.777778,48,57.302679,2.7,3.223276,3.767651,1.374409
189,Alisson,Liverpool,60,8.888889,24,29.234951,2.7,3.288932,3.078428,1.342701
94,Heaton,Aston Villa,45,17.307692,45,42.474050,2.6,2.454056,1.797926,1.156853

DEFENDERS

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,form 5,valuePoints metric
id,,,,,,,,,,
297,Lundstram,Sheffield Utd,52,17.924528,95,93.225552,5.3,5.201004,5.278512,2.280791
182,Alexander-Arnold,Liverpool,72,16.818182,74,89.310307,4.4,5.310343,4.014168,1.979048
208,Otamendi,Manchester City,50,12.105263,46,51.575400,3.8,4.260577,5.010840,1.905388
181,Robertson,Liverpool,70,16.976744,73,84.640916,4.3,4.985698,3.185014,1.884417
185,Matip,Liverpool,52,6.956522,32,29.557788,4.6,4.248932,NaN,1.863280
405,Boly,Wolves,48,8.095238,34,32.499031,4.2,4.014586,NaN,1.832399
401,Doherty,Wolves,61,16.842105,64,75.904372,3.8,4.506822,4.411400,1.824759
164,SÃÂ¶yÃÂ¼ncÃÂ¼,Leicester City,51,17.804878,73,71.167815,4.1,3.997096,3.449786,1.769944
103,Alonso,Chelsea,60,7.966102,47,34.396178,5.9,4.317818,6.851449,1.762742
162,Evans,Leicester City,52,18.139535,78,72.258780,4.3,3.983497,3.776718,1.746879
440,AngeliÃÂ±o,Manchester City,47,6.111111,11,22.954034,1.8,3.756115,3.563086,1.732567
293,O'Connell,Sheffield Utd,46,18.055556,65,66.397465,3.6,3.677398,4.758586,1.714596
291,Stevens,Sheffield Utd,51,18.048780,74,69.841032,4.1,3.869571,5.028045,1.713475
161,Chilwell,Leicester City,58,15.000000,69,61.800372,4.6,4.120025,2.510711,1.710747
294,Baldock,Sheffield Utd,49,18.043478,83,68.186593,4.6,3.779016,5.217169,1.707185
518,Cancelo,Manchester City,53,5.937500,19,23.134212,3.2,3.896288,NaN,1.692440
529,Tomori,Chelsea,48,12.105263,46,44.229127,3.8,3.653710,4.844253,1.667683
159,Pereira,Leicester City,65,17.916667,86,75.914200,4.8,4.237072,2.639739,1.661916
183,van Dijk,Liverpool,64,16.976744,73,71.177217,4.3,4.192631,3.932108,1.657283
128,Kelly,Crystal Palace,44,12.857143,54,44.234059,4.2,3.440427,3.883456,1.640159
84,Tarkowski,Burnley,51,18.157895,69,66.849169,3.8,3.681548,3.834870,1.630217
359,Janmaat,Watford,42,8.000000,36,26.598612,4.5,3.324827,NaN,1.622349
498,Willems,Newcastle Utd,47,13.953488,60,49.027340,4.3,3.513626,2.703787,1.620715
336,Aurier,Tottenham,51,13.157895,50,47.334647,3.8,3.597433,2.884793,1.592970
160,Maguire,Manchester Utd,53,17.619048,37,64.209341,2.1,3.644314,3.381713,1.582989
295,Egan,Sheffield Utd,45,17.142857,60,57.009058,3.5,3.325528,4.089877,1.567669
186,Lovren,Liverpool,53,8.000000,16,28.664196,2.0,3.583024,3.156461,1.556366
87,Taylor,Burnley,42,5.945946,22,18.762720,3.7,3.155548,4.755863,1.539750
447,Pieters,Burnley,45,15.000000,42,48.807354,2.8,3.253824,2.457058,1.533867
163,Fuchs,Leicester City,43,3.928571,11,12.444373,2.8,3.167659,3.459398,1.527581
42,Dunk,Brighton,47,17.222222,62,56.922074,3.6,3.305153,4.783789,1.524553
203,Walker,Manchester City,58,15.161290,47,55.629513,3.1,3.669181,3.606104,1.523544
423,Basham,Sheffield Utd,45,18.125000,58,58.438743,3.2,3.224207,3.711989,1.519906
6,Monreal,Arsenal,50,3.030303,10,10.296281,3.3,3.397773,NaN,1.519530
63,Adam Smith,Bournemouth,43,10.000000,32,31.480467,3.2,3.148047,3.446930,1.518123
105,Azpilicueta,Chelsea,58,16.153846,42,58.096856,2.6,3.596472,4.483525,1.493354
511,SidibÃÂ©,Everton,53,10.000000,34,34.299096,3.4,3.429910,3.674396,1.489858
254,FernÃÂ¡ndez,Newcastle Utd,44,11.842105,45,36.883900,3.8,3.114640,4.025473,1.484847
402,Jonny,Wolves,54,17.037037,46,58.784149,2.7,3.450374,3.211940,1.484805
65,Rico,Bournemouth,44,15.000000,51,46.647070,3.4,3.109805,3.449028,1.482541

MIDFIELDERS

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,form 5,valuePoints metric
id,,,,,,,,,,
215,De Bruyne,Manchester City,104,16.901408,120,110.333132,7.1,6.528044,6.474742,2.024260
191,Salah,Liverpool,122,14.054054,104,93.542342,7.4,6.655897,9.896777,1.905578
192,ManÃÂ©,Liverpool,122,15.972222,115,101.014566,7.2,6.324390,6.922421,1.810668
196,Keita,Liverpool,58,3.018868,16,13.076462,5.3,4.331578,11.362441,1.798590
431,Pulisic,Chelsea,73,14.042553,66,67.754825,4.7,4.824965,4.323182,1.785800
171,Maddison,Leicester City,78,16.981132,90,84.622798,5.3,4.983343,4.260984,1.784323
287,Cantwell,Norwich City,48,18.205128,71,70.460533,3.9,3.870367,3.897995,1.766573
214,Sterling,Manchester City,118,17.142857,96,101.698595,5.6,5.932418,5.572534,1.726994
29,Grealish,Aston Villa,63,16.086957,74,69.512417,4.6,4.321042,3.790467,1.721544
219,David Silva,Manchester City,75,14.905660,79,70.054611,5.3,4.699866,4.948954,1.716149
239,Martial,Manchester Utd,77,11.914894,56,56.339959,4.7,4.728532,3.898916,1.704045
417,TraorÃÂ©,Wolves,53,17.179487,67,66.443186,3.9,3.867588,4.052009,1.679973
217,Mahrez,Manchester City,83,14.000000,77,66.200816,5.5,4.728630,4.800958,1.641331
301,Fleck,Sheffield Utd,49,15.128205,59,54.773114,3.9,3.620596,4.768474,1.635618
463,Mount,Chelsea,65,18.048780,74,74.227577,4.1,4.112609,2.759844,1.613098
269,Shelvey,Newcastle Utd,51,12.083333,58,43.794403,4.8,3.624364,4.332237,1.604896
114,Pedro,Chelsea,68,4.090909,9,16.955623,2.2,4.144708,4.670332,1.589423
321,Ward-Prowse,Southampton,59,18.055556,65,69.179232,3.6,3.831465,3.362850,1.577389
30,El Ghazi,Aston Villa,55,15.833333,57,58.477709,3.6,3.693329,3.243655,1.574841
113,Willian,Chelsea,70,17.045455,75,70.823314,4.4,4.154968,4.865907,1.570430
172,Barnes,Leicester City,59,17.058824,58,64.300972,3.4,3.769367,4.291946,1.551824
344,Alli,Tottenham,88,11.052632,63,49.487194,5.7,4.477413,4.485719,1.509336
119,KantÃÂ©,Chelsea,50,10.857143,38,35.663177,3.5,3.284766,2.993034,1.468992
415,Moutinho,Wolves,54,18.000000,63,61.248843,3.5,3.402713,3.332806,1.464295
248,McTominay,Manchester Utd,51,16.176471,55,53.390195,3.4,3.300485,3.094109,1.461479
371,Cleverley,Watford,48,8.888889,24,28.323854,2.7,3.186434,NaN,1.454401
218,Bernardo Silva,Manchester City,79,16.190476,68,65.637790,4.2,4.054099,2.789901,1.442384
243,James,Manchester Utd,62,18.055556,65,64.555225,3.6,3.575366,2.993725,1.435902
283,BuendÃÂ­a,Norwich City,60,18.275862,53,63.932564,2.9,3.498197,4.941341,1.428133
448,Tielemans,Leicester City,65,18.205128,71,66.118018,3.9,3.631835,2.800734,1.424523
31,McGinn,Aston Villa,57,17.941176,61,60.160683,3.4,3.353218,0.884644,1.404509
265,PÃÂ©rez,Leicester City,61,15.128205,59,52.457988,3.9,3.467562,1.901006,1.403975
421,Trossard,Brighton,58,12.000000,42,40.348688,3.5,3.362391,2.410006,1.396157
150,Richarlison,Everton,79,17.826087,82,69.889480,4.6,3.920629,2.714931,1.394897
238,Pogba,Manchester Utd,84,5.925926,16,23.434493,2.7,3.954571,1.836705,1.364457
266,AlmirÃÂ³n,Newcastle Utd,58,17.142857,48,55.791597,2.8,3.254510,4.876605,1.351362
346,Lamela,Tottenham,57,8.888889,32,28.441480,3.6,3.199667,NaN,1.340193
118,Jorginho,Chelsea,50,15.862069,46,47.502243,2.9,2.994707,2.133445,1.339274
392,Yarmolenko,West Ham,54,14.848485,49,46.207178,3.3,3.111912,1.766499,1.339154
96,Gudmundsson,Burnley,59,4.047619,17,13.140219,4.2,3.246407,NaN,1.336525

FORWARDS

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,form 5,valuePoints metric
id,,,,,,,,,,
167,Iheanacho,Leicester City,57,3.013699,22,17.605479,7.3,5.841818,NaN,2.446868
166,Vardy,Leicester City,101,17.974684,142,114.863699,7.9,6.390304,7.668943,2.010763
278,Pukki,Norwich City,66,17.924528,95,90.858219,5.3,5.068932,5.375786,1.973079
233,Rashford,Manchester Utd,91,18.103448,105,105.863699,5.8,5.847709,5.312540,1.938497
313,Ings,Southampton,65,18.000000,99,86.752740,5.5,4.819597,6.445262,1.890401
460,Abraham,Chelsea,79,17.118644,101,90.158219,5.9,5.266668,2.897281,1.873796
409,JimÃÂ©nez,Wolves,75,18.039216,92,90.663699,5.1,5.025922,4.854199,1.835207
502,Maupay,Brighton,58,18.000000,72,77.000000,4.0,4.277778,4.160000,1.776251
68,King,Bournemouth,61,13.846154,54,55.858219,3.9,4.034205,2.100706,1.633402
303,McGoldrick,Sheffield Utd,54,14.782609,34,55.105479,2.3,3.727724,4.146490,1.604157
91,Wood,Burnley,62,16.000000,64,61.600000,4.0,3.850000,2.186667,1.546197
187,Firmino,Liverpool,92,17.045455,75,79.163699,4.4,4.644270,3.085685,1.531171
11,Aubameyang,Arsenal,108,18.103448,105,90.658219,5.8,5.007787,4.321480,1.523821
468,Ayew,Crystal Palace,50,17.058824,58,58.000000,3.4,3.400000,2.140000,1.520526
210,AgÃÂ¼ero,Manchester City,117,13.035714,73,67.758219,5.6,5.197891,0.022370,1.519617
410,Jota,Wolves,61,16.000000,48,57.652740,3.0,3.603296,4.031929,1.458932
90,Barnes,Burnley,62,15.833333,57,55.700000,3.6,3.517895,0.958333,1.412821
457,Haller,West Ham,70,16.153846,63,60.005479,3.9,3.714625,3.688330,1.403996
211,Jesus,Manchester City,96,15.000000,60,65.058219,4.0,4.337215,5.918419,1.399830
428,Wesley,Aston Villa,57,18.125000,58,60.452740,3.2,3.335324,1.925262,1.397013
363,Deulofeu,Watford,61,17.857143,50,58.605479,2.8,3.281907,2.823858,1.328805
315,Long,Southampton,46,10.000000,21,28.105479,2.1,2.810548,4.906083,1.310425
70,Mousset,Sheffield Utd,51,15.128205,59,44.758219,3.9,2.958594,1.795786,1.310088
67,Callum Wilson,Bournemouth,74,17.027027,63,59.158219,3.7,3.474372,0.712935,1.277204
338,Kane,Tottenham,109,16.862745,86,70.605479,5.1,4.187069,3.562885,1.268227
147,Calvert-Lewin,Everton,57,15.806452,49,47.600000,3.1,3.011429,2.840000,1.261349
362,Deeney,Watford,62,7.083333,17,22.100000,2.4,3.120000,3.892857,1.253022
534,Connolly,Brighton,46,12.142857,34,30.205479,2.8,2.487510,1.665568,1.159808
12,Lacazette,Arsenal,93,10.909091,48,38.305479,4.4,3.511336,1.753068,1.151412
466,Joelinton,Newcastle Utd,56,18.181818,40,46.652740,2.2,2.565901,2.058595,1.084291
188,Origi,Liverpool,52,13.000000,39,30.405479,3.0,2.338883,4.224423,1.025668
146,Tosun,Everton,57,5.000000,12,11.500000,2.4,2.300000,2.100000,0.963364
364,Gray,Watford,56,16.111111,29,36.100000,1.8,2.240690,1.340000,0.946864
501,McBurnie,Sheffield Utd,57,16.363636,36,34.800000,2.2,2.126667,2.866667,0.890763
437,Adams,Southampton,53,12.941176,22,25.952740,1.7,2.005439,0.894085,0.871107
234,Greenwood,Manchester Utd,43,13.684211,26,24.300000,1.9,1.775769,2.666667,0.856352
110,Giroud,Chelsea,66,5.000000,7,10.900000,1.4,2.180000,4.000000,0.848564
487,Cutrone,Wolves,56,12.105263,23,24.200000,1.9,1.999130,1.000000,0.844787
69,Solanke,Bournemouth,52,16.428571,23,31.600000,1.4,1.923478,1.126667,0.843501
504,Martinelli,Arsenal,45,10.000000,20,17.552740,2.0,1.755274,2.825262,0.827444

Below we compile a list sorting players based on a given metric (irrespective of position).

In [11]:
metric = 'adjusted points per game'
#metric = 'form 5'

display(df[minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game','form 5',\
          'valuePoints metric']].head(numberToShow))

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,form 5,valuePoints metric
id,,,,,,,,,,
191,Salah,Liverpool,122,14.054054,104,93.542342,7.4,6.655897,9.896777,1.905578
215,De Bruyne,Manchester City,104,16.901408,120,110.333132,7.1,6.528044,6.474742,2.024260
166,Vardy,Leicester City,101,17.974684,142,114.863699,7.9,6.390304,7.668943,2.010763
192,ManÃÂ©,Liverpool,122,15.972222,115,101.014566,7.2,6.324390,6.922421,1.810668
214,Sterling,Manchester City,118,17.142857,96,101.698595,5.6,5.932418,5.572534,1.726994
233,Rashford,Manchester Utd,91,18.103448,105,105.863699,5.8,5.847709,5.312540,1.938497
167,Iheanacho,Leicester City,57,3.013699,22,17.605479,7.3,5.841818,NaN,2.446868
182,Alexander-Arnold,Liverpool,72,16.818182,74,89.310307,4.4,5.310343,4.014168,1.979048
460,Abraham,Chelsea,79,17.118644,101,90.158219,5.9,5.266668,2.897281,1.873796
297,Lundstram,Sheffield Utd,52,17.924528,95,93.225552,5.3,5.201004,5.278512,2.280791
210,AgÃÂ¼ero,Manchester City,117,13.035714,73,67.758219,5.6,5.197891,0.022370,1.519617
278,Pukki,Norwich City,66,17.924528,95,90.858219,5.3,5.068932,5.375786,1.973079
409,JimÃÂ©nez,Wolves,75,18.039216,92,90.663699,5.1,5.025922,4.854199,1.835207
11,Aubameyang,Arsenal,108,18.103448,105,90.658219,5.8,5.007787,4.321480,1.523821
181,Robertson,Liverpool,70,16.976744,73,84.640916,4.3,4.985698,3.185014,1.884417
171,Maddison,Leicester City,78,16.981132,90,84.622798,5.3,4.983343,4.260984,1.784323
431,Pulisic,Chelsea,73,14.042553,66,67.754825,4.7,4.824965,4.323182,1.785800
313,Ings,Southampton,65,18.000000,99,86.752740,5.5,4.819597,6.445262,1.890401
217,Mahrez,Manchester City,83,14.000000,77,66.200816,5.5,4.728630,4.800958,1.641331
239,Martial,Manchester Utd,77,11.914894,56,56.339959,4.7,4.728532,3.898916,1.704045
219,David Silva,Manchester City,75,14.905660,79,70.054611,5.3,4.699866,4.948954,1.716149
187,Firmino,Liverpool,92,17.045455,75,79.163699,4.4,4.644270,3.085685,1.531171
401,Doherty,Wolves,61,16.842105,64,75.904372,3.8,4.506822,4.411400,1.824759
344,Alli,Tottenham,88,11.052632,63,49.487194,5.7,4.477413,4.485719,1.509336
411,PatrÃÂ­cio,Wolves,52,17.894737,68,78.186538,3.8,4.369248,4.284080,1.916042
211,Jesus,Manchester City,96,15.000000,60,65.058219,4.0,4.337215,5.918419,1.399830
196,Keita,Liverpool,58,3.018868,16,13.076462,5.3,4.331578,11.362441,1.798590
29,Grealish,Aston Villa,63,16.086957,74,69.512417,4.6,4.321042,3.790467,1.721544
103,Alonso,Chelsea,60,7.966102,47,34.396178,5.9,4.317818,6.851449,1.762742
502,Maupay,Brighton,58,18.000000,72,77.000000,4.0,4.277778,4.160000,1.776251
208,Otamendi,Manchester City,50,12.105263,46,51.575400,3.8,4.260577,5.010840,1.905388
185,Matip,Liverpool,52,6.956522,32,29.557788,4.6,4.248932,NaN,1.863280
159,Pereira,Leicester City,65,17.916667,86,75.914200,4.8,4.237072,2.639739,1.661916
183,van Dijk,Liverpool,64,16.976744,73,71.177217,4.3,4.192631,3.932108,1.657283
338,Kane,Tottenham,109,16.862745,86,70.605479,5.1,4.187069,3.562885,1.268227
113,Willian,Chelsea,70,17.045455,75,70.823314,4.4,4.154968,4.865907,1.570430
114,Pedro,Chelsea,68,4.090909,9,16.955623,2.2,4.144708,4.670332,1.589423
161,Chilwell,Leicester City,58,15.000000,69,61.800372,4.6,4.120025,2.510711,1.710747
463,Mount,Chelsea,65,18.048780,74,74.227577,4.1,4.112609,2.759844,1.613098
471,Henderson,Sheffield Utd,48,16.888889,76,68.617960,4.5,4.062905,5.457301,1.854454