In [1]:
# recent gameweek
latest_gameweek = 17

In [2]:
import pandas as pd
import numpy as np

# allow more data columns to be shown than by default
pd.set_option('max_columns',100)

In [3]:
# fetch FPL data
filepath = '../data/fpl/data_week' + str(latest_gameweek) + '.csv'
players = pd.read_csv(filepath, index_col=0)

In [4]:
# how many gameweeks do we look form for
for i in [5,10]:
    number_gameweeks = i
    # create a list of relevant column names
    column_list = []
    for i in range(0,number_gameweeks):
        column_list.append('xPoints week ' + str(latest_gameweek-i))
    # calculate form
    column_name = 'form ' + str(number_gameweeks)
    players[column_name] = players[column_list].mean(axis=1)

In [5]:
# give a sorted list showing the players with best 'form 5'
players[['web_name', 'games played','total_points', 'points_per_game','adjusted points','adjusted points per game',\
                                'form 5', 'form 10']].sort_values(by='form 5', ascending=False)

,web_name,games played,total_points,points_per_game,adjusted points,adjusted points per game,form 5,form 10
id,,,,,,,,
302,Fernandes,16.049383,130,8.1,114.774728,7.151348,8.566375,8.427104
272,De Bruyne,13.965517,81,5.8,99.833152,7.148547,7.596205,8.216120
45,El Ghazi,9.038462,47,5.2,42.235904,4.672909,6.694115,4.752286
4,Aubameyang,15.142857,53,3.5,61.995316,4.094030,6.417507,4.357450
39,Hause,4.000000,28,7.0,21.549346,5.387336,6.371007,6.371007
271,Gündogan,10.000000,45,4.5,39.575574,3.957557,6.303573,4.907134
255,Robertson,17.021277,80,4.7,79.233667,4.654978,6.286418,5.279439
246,Matip,8.000000,40,5.0,34.403122,4.300390,6.223573,4.928497
572,Adarabioyo,10.857143,38,3.5,37.420871,3.446659,6.183487,4.044250
516,Areola,13.888889,50,3.6,50.988316,3.671159,6.082551,4.456399
37,Grealish,14.923077,97,6.5,86.525683,5.798113,6.008782,5.310273
390,Son,16.097561,132,8.2,96.763619,6.011073,5.977986,5.422727
277,Cancelo,11.000000,55,5.0,55.740243,5.067295,5.789293,5.084543
276,Sterling,14.074074,76,5.4,71.415326,5.074247,5.739462,5.051753
430,Randolph,1.000000,6,6.0,3.129289,3.129289,5.619350,5.619350
75,Bernardo,2.000000,3,1.5,8.142454,4.071227,5.604777,5.604777
306,Rashford,16.153846,84,5.2,76.911276,4.761174,5.500147,5.381693
12,Martínez,15.090909,83,5.5,69.672532,4.616855,5.496461,4.894301
367,Stephens,7.045455,31,4.4,25.293134,3.589993,5.446784,5.516619
259,Alexander-Arnold,15.000000,45,3.0,59.737347,3.982490,5.425133,4.395498
303,Martial,11.944444,43,3.6,42.038592,3.519510,5.422970,4.312761
202,Bamford,17.118644,101,5.9,98.058592,5.728175,5.323566,5.639631
258,Minamino,8.000000,16,2.0,15.466921,1.933365,5.318731,2.485297
449,Soucek,17.111111,77,4.5,73.298567,4.283682,5.316154,5.098717
24,Saka,15.135135,56,3.7,61.540735,4.066084,5.308196,4.366598
23,Smith Rowe,3.000000,18,6.0,15.296170,5.098723,5.211768,5.211768
165,Holgate,7.021277,33,4.7,27.446562,3.909056,5.188167,3.915232
283,Zinchenko,2.000000,3,1.5,7.540459,3.770229,5.186341,5.186341
540,Traoré,13.142857,46,3.5,41.000971,3.119639,5.181101,4.203225
6,Lacazette,14.146341,58,4.1,51.320000,3.627793,5.175000,3.750000
...,...,...,...,...,...,...,...,...
420,Leko,NaN,0,0.0,NaN,NaN,NaN,NaN
421,Edwards,5.000000,5,1.0,6.261157,1.252231,NaN,1.000000
423,Field,3.000000,3,1.0,3.456694,1.152231,NaN,NaN
499,Kipre,NaN,0,0.0,NaN,NaN,NaN,NaN
621,Diaby,NaN,0,0.0,NaN,NaN,NaN,NaN
429,Martin,NaN,0,0.0,NaN,NaN,NaN,NaN
433,Roberto,NaN,0,0.0,NaN,NaN,NaN,NaN
434,Wilshere,NaN,0,0.0,NaN,NaN,NaN,NaN
440,Felipe Anderson,2.000000,2,1.0,2.564645,1.282322,NaN,NaN
442,Masuaku,10.000000,37,3.7,36.860611,3.686061,NaN,3.141830
444,Hugill,NaN,0,0.0,NaN,NaN,NaN,NaN
447,Ajeti,NaN,0,0.0,NaN,NaN,NaN,NaN
453,Ruddy,NaN,0,0.0,NaN,NaN,NaN,NaN
456,Bennett,NaN,0,0.0,NaN,NaN,NaN,NaN
460,Jiménez,10.000000,43,4.3,36.967718,3.696772,NaN,2.372635
462,Jonny,NaN,0,0.0,NaN,NaN,NaN,NaN
463,Bonatini,NaN,0,0.0,NaN,NaN,NaN,NaN
467,Buur,1.000000,1,1.0,2.190686,2.190686,NaN,NaN
471,Vinagre,2.000000,1,0.5,3.381372,1.690686,NaN,NaN
472,Sarkic,NaN,0,0.0,NaN,NaN,NaN,NaN
473,Gibbs-White,NaN,0,0.0,NaN,NaN,NaN,NaN
475,Jordao,NaN,0,0.0,NaN,NaN,NaN,NaN
476,Campana,NaN,0,0.0,NaN,NaN,NaN,NaN
553,Shabani,NaN,0,0.0,NaN,NaN,NaN,NaN
610,Corbeanu,NaN,0,0.0,NaN,NaN,NaN,NaN
611,Perry,NaN,0,0.0,NaN,NaN,NaN,NaN
614,Cundle,NaN,0,0.0,NaN,NaN,NaN,NaN
615,Richards,NaN,0,0.0,NaN,NaN,NaN,NaN
616,Marques,NaN,0,0.0,NaN,NaN,NaN,NaN
617,Söndergaard,NaN,0,0.0,NaN,NaN,NaN,NaN

In [6]:
# save data
filepath = '../data/fpl/data_week' + str(latest_gameweek) + '.csv'
players.to_csv(filepath)