In [1]:
# recent gameweek
latest_gameweek = 15

In [2]:
import pandas as pd
import numpy as np

# allow more data columns to be shown than by default
pd.set_option('max_columns',100)

In [3]:
# fetch FPL data
filepath = '../data/fpl/data_week' + str(latest_gameweek) + '.csv'
players = pd.read_csv(filepath, index_col=0)

In [4]:
# how many gameweeks do we look form for
for i in [5,10]:
    number_gameweeks = i
    # create a list of relevant column names
    column_list = []
    for i in range(0,number_gameweeks):
        column_list.append('xPoints week ' + str(latest_gameweek-i))
    # calculate form
    column_name = 'form ' + str(number_gameweeks)
    players[column_name] = players[column_list].mean(axis=1)

In [5]:
# give a sorted list showing the players with best 'form 5'
players[['web_name', 'games played','total_points', 'points_per_game','adjusted points','adjusted points per game',\
                                'form 5', 'form 10']].sort_values(by='form 5', ascending=False)

,web_name,games played,total_points,points_per_game,adjusted points,adjusted points per game,form 5,form 10
id,,,,,,,,
272,De Bruyne,13.076923,68,5.2,88.639082,6.778283,8.346019,6.977607
45,El Ghazi,7.037037,38,5.4,35.282426,5.013818,8.143603,5.124916
302,Fernandes,14.074074,114,8.1,98.606464,7.006249,7.444981,7.377761
39,Hause,2.988506,26,8.7,17.979149,6.016100,7.299213,7.299213
12,Martínez,13.050847,77,5.9,62.376999,4.779536,7.025604,4.581985
224,Vardy,13.947368,106,7.6,93.725904,6.719970,6.725836,6.929684
254,Salah,13.953488,120,8.6,96.309324,6.902168,6.511569,6.751752
276,Sterling,12.909091,71,5.5,66.301620,5.136041,6.420625,4.895865
150,Sigurdsson,14.117647,48,3.4,49.236749,3.487603,6.244270,4.345996
306,Rashford,13.888889,75,5.4,70.651897,5.086937,6.205942,5.328242
273,Stones,6.000000,36,6.0,28.598068,4.766345,5.783998,5.743454
271,Gündogan,9.000000,36,4.0,34.111775,3.790197,5.759110,4.194986
202,Bamford,14.918033,91,6.1,88.428245,5.927608,5.675695,6.327848
246,Matip,8.000000,40,5.0,33.555447,4.194431,5.568317,4.928497
560,Kelleher,1.000000,7,7.0,4.127077,4.127077,5.426123,5.426123
102,Azpilicueta,6.000000,24,4.0,19.109069,3.184845,5.426123,4.706232
255,Robertson,14.893617,70,4.7,67.833330,4.554524,5.422484,4.919166
390,Son,15.063291,119,7.9,88.425382,5.870256,5.417111,5.168201
303,Martial,10.000000,36,3.6,38.147074,3.814707,5.382970,4.987836
37,Grealish,12.941176,88,6.8,76.263063,5.893055,5.370306,5.572173
103,Giroud,7.916667,19,2.4,21.800000,2.753684,5.333333,2.971429
96,Pope,13.018868,69,5.3,61.302903,4.708774,5.311654,5.330706
277,Cancelo,10.000000,53,5.3,50.366194,5.036619,5.283454,5.512307
449,Soucek,15.000000,63,4.2,60.893111,4.059541,5.274007,4.317397
165,Holgate,5.961538,31,5.2,23.919114,4.012238,5.218542,3.983641
251,Mané,13.928571,78,5.6,81.271718,5.834893,5.131569,4.921970
540,Traoré,10.882353,37,3.4,33.261250,3.056439,5.127633,3.491204
514,Watkins,13.000000,65,5.0,70.017660,5.385974,5.002061,5.234249
249,Firmino,15.000000,66,4.4,68.508245,4.567216,4.980562,4.840281
274,Mendy,6.000000,24,4.0,20.498068,3.416345,4.978102,5.745828
...,...,...,...,...,...,...,...,...
420,Leko,NaN,0,0.0,NaN,NaN,NaN,NaN
421,Edwards,5.000000,5,1.0,6.278363,1.255673,NaN,1.000000
423,Field,3.000000,3,1.0,3.467018,1.155673,NaN,NaN
426,Harper,1.000000,1,1.0,1.155673,1.155673,NaN,NaN
499,Kipre,NaN,0,0.0,NaN,NaN,NaN,NaN
429,Martin,NaN,0,0.0,NaN,NaN,NaN,NaN
430,Randolph,NaN,0,0.0,NaN,NaN,NaN,NaN
433,Roberto,NaN,0,0.0,NaN,NaN,NaN,NaN
434,Wilshere,NaN,0,0.0,NaN,NaN,NaN,NaN
437,Antonio,7.000000,28,4.0,28.400000,4.057143,NaN,2.700000
440,Felipe Anderson,2.000000,2,1.0,2.496493,1.248246,NaN,NaN
444,Hugill,NaN,0,0.0,NaN,NaN,NaN,NaN
447,Ajeti,NaN,0,0.0,NaN,NaN,NaN,NaN
576,Dawson,NaN,0,0.0,NaN,NaN,NaN,NaN
453,Ruddy,NaN,0,0.0,NaN,NaN,NaN,NaN
456,Bennett,NaN,0,0.0,NaN,NaN,NaN,NaN
460,Jiménez,10.000000,43,4.3,36.969415,3.696941,NaN,3.323581
462,Jonny,NaN,0,0.0,NaN,NaN,NaN,NaN
463,Bonatini,NaN,0,0.0,NaN,NaN,NaN,NaN
467,Buur,1.000000,1,1.0,2.262332,2.262332,NaN,NaN
471,Vinagre,2.000000,1,0.5,3.524665,1.762332,NaN,NaN
472,Sarkic,NaN,0,0.0,NaN,NaN,NaN,NaN
473,Gibbs-White,NaN,0,0.0,NaN,NaN,NaN,NaN
475,Jordao,NaN,0,0.0,NaN,NaN,NaN,NaN
476,Campana,NaN,0,0.0,NaN,NaN,NaN,NaN
545,Hoever,2.000000,2,1.0,4.524665,2.262332,NaN,NaN
553,Shabani,NaN,0,0.0,NaN,NaN,NaN,NaN
610,Corbeanu,NaN,0,0.0,NaN,NaN,NaN,NaN
611,Perry,NaN,0,0.0,NaN,NaN,NaN,NaN
614,Cundle,NaN,0,0.0,NaN,NaN,NaN,NaN

In [6]:
# save data
filepath = '../data/fpl/data_week' + str(latest_gameweek) + '.csv'
players.to_csv(filepath)