In [1]:
import pandas as pd
import numpy as np
from pulp import LpMaximize, LpProblem, LpStatus, lpSum, LpVariable
import json
import requests

In [2]:
# function to solve the optimization problem
def optimize(df, max_price, expected_column):
    
    # PRELIMINARIES

    # Create the model
    model = LpProblem(name="FPL", sense=LpMaximize)    
    variables = [LpVariable(name=f'{ix}', cat='Binary') for ix in df.index]
    captaincy_variables = [LpVariable(name=f'cap_{ix}', cat='Binary') for ix in df.index]
    prices = [df.loc[ix,'price'] for ix in df.index]
    # measure of player quality
    expected_points = [df.loc[ix,expected_column] for ix in df.index]
    goalkeepers = [1.0 if df.loc[ix,'position']=='GK' else 0.0 for ix in df.index]
    defenders = [1.0 if df.loc[ix,'position']=='DEF' else 0.0 for ix in df.index]
    midfielders = [1.0 if df.loc[ix,'position']=='MID' else 0.0 for ix in df.index]
    forwards = [1.0 if df.loc[ix,'position']=='FWD' else 0.0 for ix in df.index]
    teams = []
    for team in df['team'].unique():
        teams.append( [1.0 if df.loc[ix,'team']==team else 0.0 for ix in df.index] )

    # CONSTRAINTS

    # select 11 players
    model += lpSum(variables) == 11
    # select 1 captain
    model += lpSum(captaincy_variables) == 1
    # captain must be one of the 11 players in the team
    for i in range(0,len(variables)):
        model += captaincy_variables[i] <= variables[i]
    # set maximum price for starting 11
    model += np.dot(prices,variables) <= max_price
    # only 1 goalkeeper
    model += np.dot(goalkeepers,variables) == 1
    # at least 3 defenders
    model += np.dot(defenders,variables) >= 3
    # at most 5 defenders
    model += np.dot(defenders,variables) <= 5
    # at most 5 midfielders
    model += np.dot(midfielders,variables) <= 5
    # at least 1 forward
    model += np.dot(forwards,variables) >= 1
    # at most 3 forwards
    model += np.dot(forwards,variables) <= 3
    # max 3 players from any given team
    for team in teams:
        model += np.dot(team,variables) <= 3

    # OBJECTIVE
    # the second part doubles the captain's points
    model += np.dot(expected_points,variables) + np.dot(expected_points,captaincy_variables)

    # SOLVE OPTIMIZATION

    status = model.solve()
    print(f'Status: {LpStatus[model.status]}')
    #print(f'Mean total points per gameweek: {model.objective.value()}')

    players = [str(var) for var in model.variables() if var.value()==1]
    captain = [player for player in players if 'cap' in player]
    captain = int(captain[0].replace('cap_', ''))
    players = [int(player) for player in players if 'cap' not in player]
    dream_team = df.loc[players]
    cost = (dream_team['price']).sum()
    exp_points = dream_team[expected_column].sum() + df.loc[captain, expected_column]
    print(f'Cost: {cost}')
    if expected_column == 'xPpg_10':
        print(f'Expected points per week: {exp_points}')
    #elif expected_column == 'xPoints_next10':
    #    exp_points = exp_points / np.min((10, 38-gameweek))
    #    print(f'Expected points per week: {exp_points}')
    #else:
    #    print(f'Expected points: {exp_points}')
    display(dream_team[['position','name','price',expected_column]].sort_values('position'))

In [3]:
df = pd.read_csv('../../data/xPpg_10_full.csv', index_col=0)
df['position'] = pd.Categorical(df['position'], ['GK','DEF','MID','FWD'])
df

,name,xPpg_10,price,value,geometric_valuePoints,position,team
0,Aaron Cresswell,3.132260,5.0,0.626452,1.400789,DEF,West Ham
1,Aaron Ramsdale,3.353989,5.0,0.670798,1.499949,GK,Arsenal
2,Aaron Wan-Bissaka,2.802780,4.5,0.622840,1.321243,DEF,Manchester Utd
3,Abdoulaye Doucoure,2.483838,5.5,0.451607,1.059112,MID,Everton
4,Adam Armstrong,2.523005,5.5,0.458728,1.075813,FWD,Southampton
...,...,...,...,...,...,...,...
380,Yerry Mina,2.464379,4.5,0.547640,1.161719,DEF,Everton
381,Yoane Wissa,2.720535,5.5,0.494643,1.160040,MID,Brentford
382,Youri Tielemans,2.904057,6.5,0.446778,1.139065,MID,Leicester City
383,Yves Bissouma,2.412226,5.0,0.482445,1.078780,MID,Tottenham
384,Zack Steffen,3.748696,4.0,0.937174,1.874348,GK,Manchester City

In [ ]:
# only consider players that have played at least some minimum number of games
#df = df[df['games played']>=5]
#df

In [4]:
optimize(df, 82.5, 'xPpg_10')

Welcome to the CBC MILP Solver
Version: 2.9.0
Build Date: Feb 12 2015

command line - /Users/jaakkotoivonen/opt/anaconda3/lib/python3.8/site-packages/pulp/apis/../solverdir/cbc/osx/64/cbc /var/folders/ml/jr8p__z97xx1jjb90rwg7hfm0000gn/T/1a049e10be894eb6b1c9f7ddd7772d58-pulp.mps max branch printingOptions all solution /var/folders/ml/jr8p__z97xx1jjb90rwg7hfm0000gn/T/1a049e10be894eb6b1c9f7ddd7772d58-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 419 COLUMNS
At line 5610 RHS
At line 6025 BOUNDS
At line 6796 ENDATA
Problem MODEL has 414 rows, 770 columns and 2880 elements
Coin0008I MODEL read with 0 errors
Continuous objective value is 63.3725 - 0.01 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 1 strengthened rows, 0 substitutions
Cgl0004I processed model has 411 rows, 770 columns (770 integer (770 of which binary)) and 2695 elements
Cbc0038I Initial state - 4 integers unsatisfied sum - 1
Cbc0038I Solution found of -63.1695
Cbc0038I Before mini branch and bound, 766 integers at bound fixed and 0 continuous
Cbc0038I Full problem 411 rows 770 columns, reduced to 0 rows 0 columns
Cbc0038I Mini branch and bound did not improve solution (0.05 seconds)
Cbc0038I Round again with cutoff of -63.1898
Cbc0038I Reduced cost fixing fixed 752 variables on major pass 2
Cbc0038I Pass   1: suminf.    0.04137 (2) obj. -63.1898 iterations 5
Cbc0038I Pass   2: suminf.    0.91159 (3) obj. -63.1898 iterations 8
Cbc0038I Pass   3: suminf.    1.23069 (4) obj. -63.1898 iterations 4
Cbc0038I Pass   4: suminf.    0.90079 (3) obj. -63.1898 iterations 3
Cbc0038I Pass   5: suminf.    0.98226 (4) obj. -63.1898 iterations 8
Cbc0038I Pass   6: suminf.    0.98226 (4) obj. -63.1898 iterations 0
Cbc0038I Pass   7: suminf.    0.98226 (4) obj. -63.1898 iterations 0
Cbc0038I Pass   8: suminf.    0.98226 (4) obj. -63.1898 iterations 0
Cbc0038I Pass   9: suminf.    0.98226 (4) obj. -63.1898 iterations 2
Cbc0038I Pass  10: suminf.    0.98226 (4) obj. -63.1898 iterations 1
Cbc0038I Pass  11: suminf.    0.44444 (2) obj. -63.3356 iterations 7
Cbc0038I Pass  12: suminf.    0.72727 (2) obj. -63.2033 iterations 7
Cbc0038I Pass  13: suminf.    0.70269 (2) obj. -63.1898 iterations 7
Cbc0038I Pass  14: suminf.    0.72727 (2) obj. -63.2033 iterations 6
Cbc0038I Pass  15: suminf.    0.05532 (2) obj. -63.1898 iterations 5
Cbc0038I Pass  16: suminf.    0.04137 (2) obj. -63.1898 iterations 4
Cbc0038I Pass  17: suminf.    0.91159 (3) obj. -63.1898 iterations 8
Cbc0038I Pass  18: suminf.    0.81831 (3) obj. -63.1898 iterations 2
Cbc0038I Pass  19: suminf.    0.84455 (4) obj. -63.1898 iterations 3
Cbc0038I Pass  20: suminf.    0.71875 (3) obj. -63.1898 iterations 6
Cbc0038I Pass  21: suminf.    0.73326 (3) obj. -63.1898 iterations 2
Cbc0038I Pass  22: suminf.    0.72198 (3) obj. -63.1898 iterations 6
Cbc0038I Pass  23: suminf.    0.74752 (3) obj. -63.1898 iterations 4
Cbc0038I Pass  24: suminf.    1.88037 (5) obj. -63.1898 iterations 2
Cbc0038I Pass  25: suminf.    0.73995 (3) obj. -63.1898 iterations 5
Cbc0038I Pass  26: suminf.    0.74752 (3) obj. -63.1898 iterations 4
Cbc0038I Pass  27: suminf.    0.70269 (2) obj. -63.1898 iterations 4
Cbc0038I Pass  28: suminf.    0.72727 (2) obj. -63.2033 iterations 6
Cbc0038I Pass  29: suminf.    0.74080 (3) obj. -63.1898 iterations 3
Cbc0038I Pass  30: suminf.    0.80882 (3) obj. -63.1898 iterations 5
Cbc0038I No solution found this major pass
Cbc0038I Before mini branch and bound, 756 integers at bound fixed and 0 continuous
Cbc0038I Full problem 411 rows 770 columns, reduced to 8 rows 13 columns
Cbc0038I Mini branch and bound did not improve solution (0.07 seconds)
Cbc0038I After 0.07 seconds - Feasibility pump exiting with objective of -63.1695 - took 0.03 seconds
Cbc0012I Integer solution of -63.169489 found by feasibility pump after 0 iterations and 0 nodes (0.07 seconds)
Cbc0038I Full problem 411 rows 770 columns, reduced to 0 rows 0 columns
Cbc0031I 5 added rows had average density of 9.4
Cbc0013I At root node, 20 cuts changed objective from -63.372498 to -63.169489 in 3 passes
Cbc0014I Cut generator 0 (Probing) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.002 seconds - new frequency is -100
Cbc0014I Cut generator 1 (Gomory) - 12 row cuts average 14.2 elements, 0 column cuts (0 active)  in 0.003 seconds - new frequency is 1
Cbc0014I Cut generator 2 (Knapsack) - 5 row cuts average 5.2 elements, 0 column cuts (0 active)  in 0.003 seconds - new frequency is 1
Cbc0014I Cut generator 3 (Clique) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 4 (MixedIntegerRounding2) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 5 (FlowCover) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.001 seconds - new frequency is -100
Cbc0014I Cut generator 6 (TwoMirCuts) - 17 row cuts average 13.8 elements, 0 column cuts (0 active)  in 0.001 seconds - new frequency is -100
Cbc0001I Search completed - best objective -63.16948895, took 8 iterations and 0 nodes (0.10 seconds)
Cbc0035I Maximum depth 0, 756 variables fixed on reduced cost
Cuts at root node changed objective from -63.3725 to -63.1695
Probing was tried 3 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.002 seconds)
Gomory was tried 3 times and created 12 cuts of which 0 were active after adding rounds of cuts (0.003 seconds)
Knapsack was tried 3 times and created 5 cuts of which 0 were active after adding rounds of cuts (0.003 seconds)
Clique was tried 3 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 3 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 3 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.001 seconds)
TwoMirCuts was tried 3 times and created 17 cuts of which 0 were active after adding rounds of cuts (0.001 seconds)

Result - Optimal solution found

Objective value:                63.16948895
Enumerated nodes:               0
Total iterations:               8
Time (CPU seconds):             0.10
Time (Wallclock seconds):       0.10

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.11   (Wallclock seconds):       0.12

Status: Optimal
Cost: 81.5
Expected points per week: 63.16948895

    position                    name  price   xPpg_10
330       GK            Scott Carson    4.0  4.318765
142      DEF            Ivan Perisic    5.5  4.193641
176      DEF            Joao Cancelo    7.0  5.027473
239      DEF           Marcos Alonso    5.5  4.369889
35       DEF            Ben Chilwell    6.0  4.517095
360      DEF  Trent Alexander-Arnold    7.5  4.850756
225      MID               Luis Diaz    8.0  4.891454
261      MID           Mohamed Salah   13.0  7.657411
300      MID         Raheem Sterling   10.0  5.995931
310      MID            Riyad Mahrez    8.0  5.318112
143      FWD              Ivan Toney    7.0  4.371552

In [9]:
ban = []
# ban goalkeepers under 4.5 price
ban = ban + [ix for ix in df.index if (df.loc[ix,'position']=='GK') & (df.loc[ix,'price']<4.5)]
# ban given players
ban = ban + [233, 304, 46, 276, 239, 310]#294, 206]#, 31, 176, 196, 289, 270]
my_df = df.drop(ban).copy()

In [10]:
optimize(my_df, 82.5, 'xPpg_10')

Welcome to the CBC MILP Solver
Version: 2.9.0
Build Date: Feb 12 2015

command line - /Users/jaakkotoivonen/opt/anaconda3/lib/python3.8/site-packages/pulp/apis/../solverdir/cbc/osx/64/cbc /var/folders/ml/jr8p__z97xx1jjb90rwg7hfm0000gn/T/628b5a3bdc1349b5b20e1584a432c17a-pulp.mps max branch printingOptions all solution /var/folders/ml/jr8p__z97xx1jjb90rwg7hfm0000gn/T/628b5a3bdc1349b5b20e1584a432c17a-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 400 COLUMNS
At line 5341 RHS
At line 5737 BOUNDS
At line 6470 ENDATA
Problem MODEL has 395 rows, 732 columns and 2744 elements
Coin0008I MODEL read with 0 errors
Continuous objective value is 62.1397 - 0.01 seconds
Cgl0004I processed model has 391 rows, 732 columns (732 integer (732 of which binary)) and 2558 elements
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of -62.1397
Cbc0038I Before mini branch and bound, 732 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.03 seconds)
Cbc0038I After 0.03 seconds - Feasibility pump exiting with objective of -62.1397 - took 0.00 seconds
Cbc0012I Integer solution of -62.139654 found by feasibility pump after 0 iterations and 0 nodes (0.03 seconds)
Cbc0001I Search completed - best objective -62.13965434000001, took 0 iterations and 0 nodes (0.03 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from -62.1397 to -62.1397
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                62.13965434
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.04
Time (Wallclock seconds):       0.04

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.04   (Wallclock seconds):       0.05

Status: Optimal
Cost: 82.5
Expected points per week: 62.13965434

    position                       name  price   xPpg_10
101       GK  Ederson Santana de Moraes    5.5  4.010686
142      DEF               Ivan Perisic    5.5  4.193641
176      DEF               Joao Cancelo    7.0  5.027473
212      DEF                Kyle Walker    5.0  4.163124
35       DEF               Ben Chilwell    6.0  4.517095
360      DEF     Trent Alexander-Arnold    7.5  4.850756
225      MID                  Luis Diaz    8.0  4.891454
247      MID                Mason Mount    8.0  4.803122
261      MID              Mohamed Salah   13.0  7.657411
300      MID            Raheem Sterling   10.0  5.995931
143      FWD                 Ivan Toney    7.0  4.371552

## With decay

In [11]:
projections = pd.read_csv('../../data/pre_season_projections_full.csv', index_col=0)
projections

,name,team,opp_team,was_home,gameweek,xP
0,Cedric Alves Soares,Arsenal,Crystal Palace,0,1,2.978119
1,Cedric Alves Soares,Arsenal,Leicester City,1,2,2.828419
2,Cedric Alves Soares,Arsenal,Bournemouth,0,3,2.997868
3,Cedric Alves Soares,Arsenal,Fulham,1,4,3.286365
4,Cedric Alves Soares,Arsenal,Aston Villa,1,5,3.116242
...,...,...,...,...,...,...
5,Ivan Perisic,Tottenham,Fulham,1,6,4.786788
6,Ivan Perisic,Tottenham,Manchester City,0,7,2.795383
7,Ivan Perisic,Tottenham,Leicester City,1,8,4.518958
8,Ivan Perisic,Tottenham,Arsenal,0,9,3.986129
9,Ivan Perisic,Tottenham,Brighton,0,10,3.806766

In [12]:
fpl_data = json.loads(requests.get('https://fantasy.premierleague.com/api/bootstrap-static/').text)
fpl_df = pd.DataFrame(fpl_data['elements'])
fpl_df.set_index('id',inplace=True)
fpl_df['name'] = fpl_df['first_name'] + ' ' + fpl_df['second_name']
fpl_df['name'] = fpl_df['name'].str.normalize('NFD').str.encode('ascii','ignore').str.decode('ascii')
fpl_df['now_cost'] = fpl_df['now_cost'] / 10.0
fpl_df

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,...,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text,name
id,,,,,,,,,,,,,,,,,,,,,
1,NaN,None,58822,0,0,0,0,0,2,2.3,...,81,199,63,2.0,,3.0,,NaN,,Cedric Alves Soares
3,NaN,None,84450,0,0,0,0,0,3,2.0,...,85,102,63,NaN,,NaN,,NaN,,Granit Xhaka
4,NaN,None,153256,0,0,0,0,0,3,1.5,...,145,287,130,NaN,,NaN,,NaN,,Mohamed Elneny
5,NaN,None,156074,0,0,0,0,0,2,2.3,...,113,296,108,NaN,,NaN,,NaN,,Rob Holding
6,NaN,None,167199,0,0,0,0,0,3,2.0,...,60,132,76,NaN,,4.0,,NaN,,Thomas Partey
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,NaN,None,501837,0,0,0,0,0,2,1.5,...,166,426,166,NaN,,NaN,,NaN,,Yerson Mosquera Valdelamar
503,NaN,None,19624,0,0,0,0,0,3,2.0,...,111,74,47,1.0,,1.0,,NaN,,Joao Filipe Iria Santos Moutinho
516,NaN,None,432830,0,0,0,0,0,2,2.3,...,32,193,60,NaN,,NaN,,NaN,,Nathan Collins
557,NaN,None,246799,0,0,0,0,0,1,1.5,...,25,417,47,NaN,,NaN,,NaN,,Jackson Smith
558,NaN,None,530332,0,0,0,0,0,2,1.5,...,167,427,167,NaN,,NaN,,NaN,,Hugo Bueno Lopez

In [13]:
0.925**9

0.4957646934321482

In [14]:
first_gameweek = 1
projections['xP_decay'] = projections['xP']*0.925**(projections['gameweek']-first_gameweek)
projections

,name,team,opp_team,was_home,gameweek,xP,xP_decay
0,Cedric Alves Soares,Arsenal,Crystal Palace,0,1,2.978119,2.978119
1,Cedric Alves Soares,Arsenal,Leicester City,1,2,2.828419,2.616287
2,Cedric Alves Soares,Arsenal,Bournemouth,0,3,2.997868,2.565050
3,Cedric Alves Soares,Arsenal,Fulham,1,4,3.286365,2.601004
4,Cedric Alves Soares,Arsenal,Aston Villa,1,5,3.116242,2.281383
...,...,...,...,...,...,...,...
5,Ivan Perisic,Tottenham,Fulham,1,6,4.786788,3.241551
6,Ivan Perisic,Tottenham,Manchester City,0,7,2.795383,1.751022
7,Ivan Perisic,Tottenham,Leicester City,1,8,4.518958,2.618366
8,Ivan Perisic,Tottenham,Arsenal,0,9,3.986129,2.136413
9,Ivan Perisic,Tottenham,Brighton,0,10,3.806766,1.887260

In [15]:
# calculate ppg over 10 game horizon and geometric mean of ppg and cost
xPpg_10_decay = projections[projections['gameweek']<=11].groupby(by=['name']).sum()['xP_decay'] 
xPpg_10_decay = xPpg_10_decay.to_frame()
xPpg_10_decay = xPpg_10_decay.reset_index()
#xPpg_10_decay = xPpg_10_decay.rename(columns={'xP_decay':'xPpg_10_decay'})
xPpg_10_decay['price'] = [fpl_df.loc[fpl_df['name']==name, 'now_cost'].values[0] for name in xPpg_10_decay['name']]
xPpg_10_decay['value'] = xPpg_10_decay['xP_decay'] / xPpg_10_decay['price']
xPpg_10_decay['geometric_valuePoints'] = np.sqrt(xPpg_10_decay['xP_decay'] * xPpg_10_decay['value'])
xPpg_10_decay['position'] = [fpl_df.loc[fpl_df['name']==name, 'element_type'].values[0] for name in xPpg_10_decay['name']]
position_dict={1:'GK', 2:'DEF', 3:'MID', 4:'FWD'}
xPpg_10_decay['position'] = xPpg_10_decay['position'].map(position_dict)
xPpg_10_decay['position'] = pd.Categorical(xPpg_10_decay['position'], ['GK','DEF','MID','FWD'])
xPpg_10_decay['team'] = [projections.loc[projections['name']==name, 'team'].head(1).values[0] for name in xPpg_10_decay['name']]
xPpg_10_decay

,name,xP_decay,price,value,geometric_valuePoints,position,team
0,Aaron Cresswell,22.283248,5.0,4.456650,9.965372,DEF,West Ham
1,Aaron Ramsdale,24.384802,5.0,4.876960,10.905215,GK,Arsenal
2,Aaron Wan-Bissaka,20.269865,4.5,4.504414,9.555306,DEF,Manchester Utd
3,Abdoulaye Doucoure,17.872256,5.5,3.249501,7.620756,MID,Everton
4,Adam Armstrong,18.118704,5.5,3.294310,7.725841,FWD,Southampton
...,...,...,...,...,...,...,...
380,Yerry Mina,17.670502,4.5,3.926778,8.329954,DEF,Everton
381,Yoane Wissa,19.522677,5.5,3.549578,8.324498,MID,Brentford
382,Youri Tielemans,21.005273,6.5,3.231581,8.238946,MID,Leicester City
383,Yves Bissouma,17.445670,5.0,3.489134,7.801941,MID,Tottenham
384,Zack Steffen,26.856682,4.0,6.714171,13.428341,GK,Manchester City

In [16]:
optimize(xPpg_10_decay, 82.5, 'xP_decay')

Welcome to the CBC MILP Solver
Version: 2.9.0
Build Date: Feb 12 2015

command line - /Users/jaakkotoivonen/opt/anaconda3/lib/python3.8/site-packages/pulp/apis/../solverdir/cbc/osx/64/cbc /var/folders/ml/jr8p__z97xx1jjb90rwg7hfm0000gn/T/8675b46f74dd42e2b0d6312fddac551b-pulp.mps max branch printingOptions all solution /var/folders/ml/jr8p__z97xx1jjb90rwg7hfm0000gn/T/8675b46f74dd42e2b0d6312fddac551b-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 419 COLUMNS
At line 5610 RHS
At line 6025 BOUNDS
At line 6796 ENDATA
Problem MODEL has 414 rows, 770 columns and 2880 elements
Coin0008I MODEL read with 0 errors
Continuous objective value is 457.174 - 0.01 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 1 strengthened rows, 0 substitutions
Cgl0004I processed model has 411 rows, 770 columns (770 integer (770 of which binary)) and 2695 elements
Cbc0038I Initial state - 4 integers unsatisfied sum - 1
Cbc0038I Solution found of -455.732
Cbc0038I Before mini branch and bound, 766 integers at bound fixed and 0 continuous
Cbc0038I Full problem 411 rows 770 columns, reduced to 0 rows 0 columns
Cbc0038I Mini branch and bound did not improve solution (0.04 seconds)
Cbc0038I Round again with cutoff of -455.876
Cbc0038I Reduced cost fixing fixed 751 variables on major pass 2
Cbc0038I Pass   1: suminf.    0.04098 (2) obj. -455.876 iterations 7
Cbc0038I Pass   2: suminf.    0.33333 (2) obj. -456.905 iterations 3
Cbc0038I Pass   3: suminf.    0.74711 (3) obj. -455.876 iterations 6
Cbc0038I Pass   4: suminf.    1.00000 (3) obj. -455.876 iterations 2
Cbc0038I Pass   5: suminf.    1.00000 (3) obj. -455.876 iterations 0
Cbc0038I Pass   6: suminf.    1.25475 (4) obj. -455.876 iterations 3
Cbc0038I Pass   7: suminf.    0.04098 (2) obj. -455.876 iterations 2
Cbc0038I Pass   8: suminf.    0.70029 (3) obj. -455.876 iterations 4
Cbc0038I Pass   9: suminf.    0.64283 (2) obj. -455.876 iterations 3
Cbc0038I Pass  10: suminf.    0.72727 (2) obj. -456.245 iterations 4
Cbc0038I Pass  11: suminf.    1.04518 (4) obj. -455.876 iterations 8
Cbc0038I Pass  12: suminf.    0.04098 (2) obj. -455.876 iterations 5
Cbc0038I Pass  13: suminf.    0.33333 (2) obj. -456.905 iterations 2
Cbc0038I Pass  14: suminf.    1.80572 (5) obj. -455.876 iterations 7
Cbc0038I Pass  15: suminf.    1.80740 (5) obj. -455.876 iterations 2
Cbc0038I Pass  16: suminf.    1.25475 (4) obj. -455.876 iterations 6
Cbc0038I Pass  17: suminf.    0.80924 (3) obj. -455.876 iterations 4
Cbc0038I Pass  18: suminf.    1.89327 (5) obj. -455.876 iterations 1
Cbc0038I Pass  19: suminf.    0.80924 (3) obj. -455.876 iterations 2
Cbc0038I Pass  20: suminf.    0.04098 (2) obj. -455.876 iterations 6
Cbc0038I Pass  21: suminf.    0.33333 (2) obj. -456.905 iterations 2
Cbc0038I Pass  22: suminf.    0.44444 (2) obj. -457.08 iterations 2
Cbc0038I Pass  23: suminf.    0.40000 (2) obj. -457.037 iterations 12
Cbc0038I Pass  24: suminf.    1.97006 (5) obj. -455.876 iterations 10
Cbc0038I Pass  25: suminf.    1.94606 (5) obj. -455.876 iterations 2
Cbc0038I Pass  26: suminf.    0.04098 (2) obj. -455.876 iterations 9
Cbc0038I Pass  27: suminf.    1.00000 (3) obj. -455.876 iterations 4
Cbc0038I Pass  28: suminf.    1.00000 (3) obj. -455.876 iterations 0
Cbc0038I Pass  29: suminf.    0.44444 (2) obj. -457.08 iterations 3
Cbc0038I Pass  30: suminf.    0.04098 (2) obj. -455.876 iterations 3
Cbc0038I No solution found this major pass
Cbc0038I Before mini branch and bound, 756 integers at bound fixed and 0 continuous
Cbc0038I Full problem 411 rows 770 columns, reduced to 6 rows 11 columns
Cbc0038I Mini branch and bound did not improve solution (0.06 seconds)
Cbc0038I After 0.06 seconds - Feasibility pump exiting with objective of -455.732 - took 0.03 seconds
Cbc0012I Integer solution of -455.73186 found by feasibility pump after 0 iterations and 0 nodes (0.06 seconds)
Cbc0038I Full problem 411 rows 770 columns, reduced to 0 rows 0 columns
Cbc0031I 3 added rows had average density of 13
Cbc0013I At root node, 7 cuts changed objective from -457.17426 to -455.73186 in 2 passes
Cbc0014I Cut generator 0 (Probing) - 0 row cuts average 0.0 elements, 1 column cuts (1 active)  in 0.002 seconds - new frequency is 1
Cbc0014I Cut generator 1 (Gomory) - 5 row cuts average 14.6 elements, 0 column cuts (0 active)  in 0.003 seconds - new frequency is 1
Cbc0014I Cut generator 2 (Knapsack) - 1 row cuts average 44.0 elements, 0 column cuts (0 active)  in 0.002 seconds - new frequency is 1
Cbc0014I Cut generator 3 (Clique) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 4 (MixedIntegerRounding2) - 1 row cuts average 14.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is 1
Cbc0014I Cut generator 5 (FlowCover) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.001 seconds - new frequency is -100
Cbc0014I Cut generator 6 (TwoMirCuts) - 6 row cuts average 14.8 elements, 0 column cuts (0 active)  in 0.001 seconds - new frequency is -100
Cbc0001I Search completed - best objective -455.7318551576499, took 4 iterations and 0 nodes (0.08 seconds)
Cbc0035I Maximum depth 0, 754 variables fixed on reduced cost
Cuts at root node changed objective from -457.174 to -455.732
Probing was tried 2 times and created 1 cuts of which 0 were active after adding rounds of cuts (0.002 seconds)
Gomory was tried 2 times and created 5 cuts of which 0 were active after adding rounds of cuts (0.003 seconds)
Knapsack was tried 2 times and created 1 cuts of which 0 were active after adding rounds of cuts (0.002 seconds)
Clique was tried 2 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 2 times and created 1 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 2 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.001 seconds)
TwoMirCuts was tried 2 times and created 6 cuts of which 0 were active after adding rounds of cuts (0.001 seconds)

Result - Optimal solution found

Objective value:                455.73185516
Enumerated nodes:               0
Total iterations:               4
Time (CPU seconds):             0.09
Time (Wallclock seconds):       0.09

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.09   (Wallclock seconds):       0.10

Status: Optimal
Cost: 81.5

    position                    name  price   xP_decay
330       GK            Scott Carson    4.0  31.015530
142      DEF            Ivan Perisic    5.5  30.562659
176      DEF            Joao Cancelo    7.0  36.609714
239      DEF           Marcos Alonso    5.5  31.393253
35       DEF            Ben Chilwell    6.0  32.471946
360      DEF  Trent Alexander-Arnold    7.5  35.116319
225      MID               Luis Diaz    8.0  35.613351
261      MID           Mohamed Salah   13.0  55.127335
300      MID         Raheem Sterling   10.0  43.138329
310      MID            Riyad Mahrez    8.0  38.021791
143      FWD              Ivan Toney    7.0  31.534293

In [21]:
ban = []
# ban goalkeepers under 4.5 price
ban = ban + [ix for ix in df.index if (df.loc[ix,'position']=='GK') & (df.loc[ix,'price']<4.5)]
# ban given players
ban = ban + [239, 310, 300]
my_df = xPpg_10_decay.drop(ban).copy()

In [22]:
optimize(my_df, 82.5, 'xP_decay')

Welcome to the CBC MILP Solver
Version: 2.9.0
Build Date: Feb 12 2015

command line - /Users/jaakkotoivonen/opt/anaconda3/lib/python3.8/site-packages/pulp/apis/../solverdir/cbc/osx/64/cbc /var/folders/ml/jr8p__z97xx1jjb90rwg7hfm0000gn/T/48c00d07b1264d72b09a4ffc68ffe276-pulp.mps max branch printingOptions all solution /var/folders/ml/jr8p__z97xx1jjb90rwg7hfm0000gn/T/48c00d07b1264d72b09a4ffc68ffe276-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 403 COLUMNS
At line 5385 RHS
At line 5784 BOUNDS
At line 6523 ENDATA
Problem MODEL has 398 rows, 738 columns and 2767 elements
Coin0008I MODEL read with 0 errors
Continuous objective value is 443.826 - 0.01 seconds
Cgl0004I processed model has 394 rows, 738 columns (738 integer (738 of which binary)) and 2579 elements
Cbc0038I Initial state - 2 integers unsatisfied sum - 0.2
Cbc0038I Pass   1: suminf.    0.13333 (2) obj. -443.273 iterations 8
Cbc0038I Solution found of -421.142
Cbc0038I Before mini branch and bound, 735 integers at bound fixed and 0 continuous
Cbc0038I Full problem 394 rows 738 columns, reduced to 0 rows 0 columns
Cbc0038I Mini branch and bound improved solution from -421.142 to -434.572 (0.04 seconds)
Cbc0038I Round again with cutoff of -435.497
Cbc0038I Reduced cost fixing fixed 568 variables on major pass 2
Cbc0038I Pass   2: suminf.    0.13333 (2) obj. -443.273 iterations 0
Cbc0038I Pass   3: suminf.    0.78923 (2) obj. -435.497 iterations 5
Cbc0038I Pass   4: suminf.    0.96648 (4) obj. -435.497 iterations 14
Cbc0038I Pass   5: suminf.    0.36909 (2) obj. -435.497 iterations 8
Cbc0038I Pass   6: suminf.    0.78214 (3) obj. -435.497 iterations 8
Cbc0038I Pass   7: suminf.    0.59613 (2) obj. -435.497 iterations 3
Cbc0038I Pass   8: suminf.    0.42929 (3) obj. -435.497 iterations 13
Cbc0038I Pass   9: suminf.    0.28235 (3) obj. -435.497 iterations 4
Cbc0038I Pass  10: suminf.    0.62481 (2) obj. -435.497 iterations 4
Cbc0038I Pass  11: suminf.    0.26667 (2) obj. -439.369 iterations 8
Cbc0038I Pass  12: suminf.    0.59329 (2) obj. -435.497 iterations 7
Cbc0038I Pass  13: suminf.    1.86221 (4) obj. -435.497 iterations 23
Cbc0038I Pass  14: suminf.    0.34744 (2) obj. -435.497 iterations 8
Cbc0038I Pass  15: suminf.    1.00000 (3) obj. -435.497 iterations 7
Cbc0038I Pass  16: suminf.    0.07183 (2) obj. -435.497 iterations 4
Cbc0038I Pass  17: suminf.    0.07183 (2) obj. -435.497 iterations 2
Cbc0038I Pass  18: suminf.    1.10924 (4) obj. -435.497 iterations 15
Cbc0038I Pass  19: suminf.    0.84333 (5) obj. -435.497 iterations 7
Cbc0038I Pass  20: suminf.    0.19330 (2) obj. -435.497 iterations 6
Cbc0038I Pass  21: suminf.    0.19330 (2) obj. -435.497 iterations 0
Cbc0038I Pass  22: suminf.    0.71429 (2) obj. -439.26 iterations 8
Cbc0038I Pass  23: suminf.    0.95145 (2) obj. -435.497 iterations 5
Cbc0038I Pass  24: suminf.    1.28441 (4) obj. -435.497 iterations 16
Cbc0038I Pass  25: suminf.    1.28441 (4) obj. -435.497 iterations 3
Cbc0038I Pass  26: suminf.    0.87500 (3) obj. -435.497 iterations 7
Cbc0038I Pass  27: suminf.    0.94362 (2) obj. -435.497 iterations 2
Cbc0038I Pass  28: suminf.    1.51926 (4) obj. -435.497 iterations 7
Cbc0038I Pass  29: suminf.    1.00000 (3) obj. -435.497 iterations 5
Cbc0038I Pass  30: suminf.    0.76878 (2) obj. -435.497 iterations 8
Cbc0038I Pass  31: suminf.    0.43300 (3) obj. -435.497 iterations 6
Cbc0038I No solution found this major pass
Cbc0038I Before mini branch and bound, 706 integers at bound fixed and 0 continuous
Cbc0038I Full problem 394 rows 738 columns, reduced to 10 rows 32 columns
Cbc0038I Mini branch and bound improved solution from -434.572 to -443.658 (0.06 seconds)
Cbc0038I Round again with cutoff of -443.691
Cbc0038I Reduced cost fixing fixed 730 variables on major pass 3
Cbc0038I Pass  31: suminf.    0.20000 (2) obj. -443.826 iterations 1
Cbc0038I Pass  32: suminf.    0.52242 (3) obj. -443.691 iterations 9
Cbc0038I Pass  33: suminf.    0.52242 (3) obj. -443.691 iterations 1
Cbc0038I Pass  34: suminf.    0.20000 (2) obj. -443.826 iterations 4
Cbc0038I Pass  35: suminf.    0.52242 (3) obj. -443.691 iterations 2
Cbc0038I Pass  36: suminf.    0.52242 (3) obj. -443.691 iterations 2
Cbc0038I Pass  37: suminf.    0.22618 (2) obj. -443.691 iterations 4
Cbc0038I Pass  38: suminf.    0.20000 (2) obj. -443.826 iterations 1
Cbc0038I Pass  39: suminf.    0.22618 (2) obj. -443.691 iterations 2
Cbc0038I Pass  40: suminf.    0.20000 (2) obj. -443.826 iterations 2
Cbc0038I Pass  41: suminf.    0.22618 (2) obj. -443.691 iterations 2
Cbc0038I Pass  42: suminf.    0.22618 (2) obj. -443.691 iterations 0
Cbc0038I Pass  43: suminf.    0.22618 (2) obj. -443.691 iterations 0
Cbc0038I Pass  44: suminf.    0.52242 (3) obj. -443.691 iterations 3
Cbc0038I Pass  45: suminf.    0.20000 (2) obj. -443.826 iterations 3
Cbc0038I Pass  46: suminf.    0.20000 (2) obj. -443.826 iterations 1
Cbc0038I Pass  47: suminf.    0.20000 (2) obj. -443.826 iterations 0
Cbc0038I Pass  48: suminf.    0.52242 (3) obj. -443.691 iterations 3
Cbc0038I Pass  49: suminf.    0.52242 (3) obj. -443.691 iterations 0
Cbc0038I Pass  50: suminf.    0.20000 (2) obj. -443.826 iterations 3
Cbc0038I Pass  51: suminf.    0.20000 (2) obj. -443.826 iterations 0
Cbc0038I Pass  52: suminf.    0.20000 (2) obj. -443.826 iterations 0
Cbc0038I Pass  53: suminf.    0.20000 (2) obj. -443.826 iterations 1
Cbc0038I Pass  54: suminf.    0.20000 (2) obj. -443.826 iterations 1
Cbc0038I Pass  55: suminf.    0.20000 (2) obj. -443.826 iterations 1
Cbc0038I Pass  56: suminf.    0.52242 (3) obj. -443.691 iterations 3
Cbc0038I Pass  57: suminf.    0.20000 (2) obj. -443.826 iterations 4
Cbc0038I Pass  58: suminf.    0.20000 (2) obj. -443.826 iterations 1
Cbc0038I Pass  59: suminf.    0.20000 (2) obj. -443.826 iterations 2
Cbc0038I Pass  60: suminf.    0.52242 (3) obj. -443.691 iterations 3
Cbc0038I No solution found this major pass
Cbc0038I Before mini branch and bound, 735 integers at bound fixed and 0 continuous
Cbc0038I Full problem 394 rows 738 columns, reduced to 0 rows 0 columns
Cbc0038I Mini branch and bound did not improve solution (0.07 seconds)
Cbc0038I After 0.07 seconds - Feasibility pump exiting with objective of -443.658 - took 0.04 seconds
Cbc0012I Integer solution of -443.65754 found by feasibility pump after 0 iterations and 0 nodes (0.07 seconds)
Cbc0006I The LP relaxation is infeasible or too expensive
Cbc0013I At root node, 0 cuts changed objective from -443.82583 to -443.82583 in 1 passes
Cbc0014I Cut generator 0 (Probing) - 3 row cuts average 2.0 elements, 2 column cuts (2 active)  in 0.001 seconds - new frequency is 1
Cbc0014I Cut generator 1 (Gomory) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 2 (Knapsack) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 3 (Clique) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 4 (MixedIntegerRounding2) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 5 (FlowCover) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 6 (TwoMirCuts) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0001I Search completed - best objective -443.6575425307099, took 0 iterations and 0 nodes (0.07 seconds)
Cbc0035I Maximum depth 0, 728 variables fixed on reduced cost
Cuts at root node changed objective from -443.826 to -443.826
Probing was tried 1 times and created 5 cuts of which 0 were active after adding rounds of cuts (0.001 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                443.65754253
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.07
Time (Wallclock seconds):       0.08

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.08   (Wallclock seconds):       0.09

Status: Optimal
Cost: 82.5

    position                   name  price   xP_decay
16        GK  Alisson Ramses Becker    5.5  29.403032
142      DEF           Ivan Perisic    5.5  30.562659
176      DEF           Joao Cancelo    7.0  36.609714
212      DEF            Kyle Walker    5.0  29.909909
305      DEF            Reece James    6.0  30.807619
35       DEF           Ben Chilwell    6.0  32.471946
225      MID              Luis Diaz    8.0  35.613351
247      MID            Mason Mount    8.0  34.550492
261      MID          Mohamed Salah   13.0  55.127335
111      FWD          Erling Haland   11.5  41.939857
143      FWD             Ivan Toney    7.0  31.534293