# Player evaluation

Here we compare players based on their adjusted points. Also, we calculate some useful metrics using the adjusted points to further evaluate player performance in FPL.

In [1]:
# recent gameweek
gameweek = 3

In [2]:
# import basic libraries
import pandas as pd
import numpy as np

pd.set_option('max_columns',100)

In [3]:
# fetch FPL data
#filepath = '../../data/fpl/data_week' + str(gameweek) + '.csv'
filepath = 'data_week' + str(gameweek) + '.csv'
df = pd.read_csv(filepath, index_col=0)

# fetch team data
filepath = '../../data/fbref/team_stats_season19_20.csv'
teamStats = pd.read_csv(filepath, index_col='Squad')

# fetch player stats data
filepath = '../../data/fbref/player_stats_season19_20.csv'
playerStats = pd.read_csv(filepath, index_col=0, skiprows=1)

## Value and value points

Here we calculate two interesting metrics: 'value' and 'value points'. 

Value is simply adjusted points per game divided by the cost of the player. Essentially, this measures how many 'points per pound(/euro/whatever)' has the player gained on an average game week. 

The value points is calculated as the geometric mean of a players adjusted points per game and value. Essentially, in FPL we want to gain the maximum possible amount of points. However, we are restrained by a limited budget, so that in practice we cannot just pick all the best players. Then, we would like to have a squad of players that give the most points given our budget. Thus, we would like to pick players that have high value ('bang for buck'). However, often the players with highest value are very cheap players who somewhat overperform relative to their price. Picking a squad full of these players might leave a part of our budget unused. Calculating the geometric mean of adjusted points and value allows us to weigh both aspects equally, i.e. we want players that both gain a lot of points but also have good value. For example, this metric values equally two players, where one has twice the points per game of the other who in turn has twice the value of the other.

In [4]:
# value = expected points / cost
df['value'] = df['adjusted points per game'] / (df['now_cost'] / 10.0)
# geometric mean of 'adjusted points per game' and 'value'
df['valuePoints metric'] = np.sqrt(df['adjusted points per game'] * df['value'])

df['value_next1'] = df['next1_xP'] / (df['now_cost'] / 10.0)
df['valuePoints_next1 metric'] = np.sqrt(df['next1_xP'] * df['value_next1'])

df['value_next10'] = df['next10_xP'] / (df['now_cost'] / 10.0)
df['valuePoints_next10 metric'] = np.sqrt(df['next10_xP'] * df['value_next10'])

In [5]:
goalkeepers = df['element_type'] == 1
defenders = df['element_type'] == 2
midfielders = df['element_type'] == 3
forwards = df['element_type'] == 4

minGames = df['games played'] >= 5

## Player evaluation

Below we compile lists for each position sorting players based on a given metric.

In [6]:
metric = 'valuePoints metric'
#metric = 'valuePoints_next10 metric'
#metric = 'adjusted points per game'
#metric = 'form 10'
#metric = 'next1_xP'

numberToShow = 40

print('GOALKEEPERS')
display(df[goalkeepers & minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game',\
                      'next1_xP','next10_xP','valuePoints metric','valuePoints_next10 metric']].head(numberToShow))
print('DEFENDERS')
display(df[defenders & minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game',\
                    'next1_xP','next10_xP','valuePoints metric','valuePoints_next10 metric']].head(numberToShow))
print('MIDFIELDERS')
display(df[midfielders & minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game',\
                  'next1_xP','next10_xP','valuePoints metric','valuePoints_next10 metric']].head(numberToShow))
print('FORWARDS')
display(df[forwards & minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game',\
                  'next1_xP','next10_xP','valuePoints metric','valuePoints_next10 metric']].head(numberToShow))

GOALKEEPERS

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,next1_xP,next10_xP,valuePoints metric,valuePoints_next10 metric
id,,,,,,,,,,,,
383,Lloris,Tottenham,55,20.851064,98,95.283026,4.7,4.569696,4.250357,4.446519,1.948525,1.896002
305,Henderson,Manchester Utd,55,36.363636,160,160.072543,4.4,4.401995,4.657851,4.375105,1.877017,1.865551
455,Patr√≠cio,Wolves,55,38.250000,153,162.878622,4.0,4.258265,4.684434,4.310746,1.815730,1.838108
393,Gazzaniga,Tottenham,45,18.125000,58,69.400488,3.2,3.828992,3.494262,3.703699,1.805004,1.745941
483,Ramsdale,Sheffield Utd,50,37.058824,126,146.147362,3.4,3.943659,3.879160,3.746311,1.763658,1.675401
96,Pope,Burnley,55,37.777778,170,155.053609,4.5,4.104360,4.622856,4.118774,1.750105,1.756251
363,McCarthy,Southampton,45,28.108108,104,103.725496,3.7,3.690234,4.119967,3.790633,1.739593,1.786921
217,Schmeichel,Leicester City,55,38.048780,156,152.015579,4.1,3.995281,4.245613,4.129704,1.703594,1.760912
128,Guaita,Crystal Palace,50,35.128205,137,133.715297,3.9,3.806494,3.354694,3.957837,1.702316,1.769998
8,Leno,Arsenal,50,30.000000,114,113.417348,3.8,3.780578,4.158301,3.730283,1.690726,1.668233
70,Ryan,Brighton,45,37.500000,135,134.185543,3.6,3.578281,3.538883,3.637674,1.686818,1.714816
291,de Gea,Manchester Utd,55,37.631579,143,147.256827,3.8,3.913118,4.168974,3.886228,1.668559,1.657093
429,Martin,West Ham,40,5.000000,20,15.922718,4.0,3.184544,2.886065,3.129787,1.592272,1.564893
326,Dubravka,Newcastle Utd,50,37.631579,143,131.286986,3.8,3.488745,3.786880,3.577533,1.560214,1.599921
12,Mart√≠nez,Arsenal,45,8.918919,33,29.151103,3.7,3.268457,3.646180,3.218162,1.540765,1.517056
252,Alisson,Liverpool,60,29.047619,122,109.357209,4.2,3.764756,4.000533,3.759114,1.536955,1.534652
245,Adri√°n,Liverpool,45,10.800000,27,34.037955,2.5,3.151662,3.378597,3.145684,1.485708,1.482890
157,Pickford,Everton,50,37.741935,117,124.781230,3.1,3.306169,3.722704,3.296525,1.478564,1.474251
101,Caballero,Chelsea,50,5.000000,13,16.494379,2.6,3.298876,3.964862,3.468476,1.475302,1.551150
278,Ederson,Manchester City,60,35.000000,133,126.219752,3.8,3.606279,3.831612,3.686888,1.472257,1.505166
431,Fabianski,West Ham,50,25.151515,83,82.732463,3.3,3.289363,2.990884,3.234606,1.471048,1.446560
371,Gunn,Southampton,45,10.000000,29,30.863879,2.9,3.086388,3.516121,3.186787,1.454937,1.502266
112,Arrizabalaga,Chelsea,50,33.333333,90,107.962529,2.7,3.238876,3.904862,3.408476,1.448469,1.524317
433,Roberto,West Ham,45,8.181818,18,24.418994,2.2,2.984544,2.686065,2.929787,1.406927,1.381115
28,Heaton,Aston Villa,45,19.666667,59,56.924370,3.0,2.894460,2.604380,2.954299,1.364461,1.392670
35,Nyland,Aston Villa,40,7.142857,15,16.057277,2.1,2.248019,1.957939,2.307858,1.124009,1.153929

DEFENDERS

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,next1_xP,next10_xP,valuePoints metric,valuePoints_next10 metric
id,,,,,,,,,,,,
104,Alonso,Chelsea,60,17.857143,100,83.610480,5.6,4.682187,5.436008,4.842484,1.911495,1.976936
259,Alexander-Arnold,Liverpool,75,38.181818,210,195.332634,5.5,5.115855,5.603433,5.119780,1.868046,1.869479
102,Azpilicueta,Chelsea,60,36.111111,130,159.693332,3.6,4.422277,5.168618,4.583366,1.805387,1.871151
255,Robertson,Liverpool,70,36.200000,181,171.439514,5.0,4.735898,5.149064,4.736996,1.790001,1.790416
269,Otamendi,Manchester City,50,24.117647,82,93.933224,3.4,3.894792,4.251401,4.022043,1.741804,1.798712
232,Chilwell,Chelsea,55,27.142857,114,109.717403,4.2,4.042220,4.759251,4.206414,1.723608,1.793621
264,Williams,Liverpool,40,6.086957,14,20.575498,2.3,3.380260,3.681032,3.377088,1.690130,1.688544
457,Doherty,Tottenham,60,36.304348,167,149.446127,4.6,4.116480,3.492336,3.951399,1.680546,1.613152
246,Matip,Liverpool,55,9.069767,39,35.428774,4.3,3.906249,4.175659,3.901885,1.665630,1.663769
313,Wan-Bissaka,Manchester Utd,55,35.277778,127,136.982882,3.6,3.882979,4.182235,3.863701,1.655708,1.647488
226,Pereira,Leicester City,60,27.954545,123,112.817956,4.4,4.035764,4.481739,4.226014,1.647594,1.725263
458,Boly,Wolves,55,22.045455,97,85.075062,4.4,3.859075,4.334555,3.922384,1.645515,1.672510
250,van Dijk,Liverpool,65,37.872340,178,156.855989,4.7,4.141703,4.485615,4.140170,1.624510,1.623908
62,Dunk,Brighton,50,35.555556,128,128.994737,3.6,3.627977,3.486533,3.722333,1.622481,1.664678
123,James,Chelsea,50,24.400000,61,87.994991,2.5,3.606352,4.325907,3.770279,1.612810,1.686120
279,Ak√©,Manchester City,55,29.259259,79,110.506128,2.7,3.776792,4.120981,3.899630,1.610429,1.662808
139,van Aanholt,Crystal Palace,55,28.684211,109,107.622582,3.8,3.751980,3.047769,3.960424,1.599850,1.688730
461,Sa√Øss,Wolves,50,33.225806,103,117.873194,3.1,3.547640,4.188293,3.647215,1.586553,1.631084
83,Pieters,Burnley,45,24.062500,77,80.315287,3.2,3.337778,3.889449,3.360006,1.573444,1.583922
121,Tomori,Chelsea,50,15.000000,48,52.683138,3.2,3.512209,4.202594,3.679225,1.570708,1.645400
462,Jonny,Wolves,55,35.142857,123,127.485697,3.5,3.627642,4.174106,3.706536,1.546832,1.580472
270,Walker,Manchester City,60,29.230769,114,110.382215,3.9,3.776234,4.087593,3.887408,1.541641,1.587028
155,Digne,Everton,60,35.294118,120,132.450858,3.4,3.752774,4.296991,3.743690,1.532064,1.528355
354,O'Connell,Sheffield Utd,50,32.647059,111,111.331154,3.4,3.410143,3.359855,3.207200,1.525063,1.434304
459,Coady,Wolves,50,38.064516,118,129.678557,3.1,3.406810,3.855191,3.464168,1.523572,1.549223
135,Kelly,Crystal Palace,45,18.823529,64,60.685186,3.4,3.223900,2.717437,3.387609,1.519761,1.596934
353,Egan,Sheffield Utd,50,35.945946,133,121.682012,3.7,3.385139,3.334105,3.182489,1.513880,1.423252
274,Mendy,Manchester City,60,18.974359,74,70.280014,3.9,3.703947,3.995122,3.807949,1.512130,1.554589
277,Cancelo,Manchester City,55,17.307692,45,61.247130,2.6,3.538723,3.862383,3.654268,1.508917,1.558185
298,Maguire,Manchester Utd,55,38.437500,123,135.961628,3.2,3.537213,3.830412,3.516872,1.508273,1.499599
318,Williams,Manchester Utd,45,17.000000,51,54.125133,3.0,3.183831,3.477213,3.163523,1.500872,1.491299
308,Lindel√∂f,Manchester Utd,50,35.151515,116,117.849288,3.3,3.352609,3.618446,3.327470,1.499332,1.488090
238,S√∂y√ºnc√º,Leicester City,55,34.285714,120,119.996676,3.5,3.499903,3.871548,3.668943,1.492364,1.564442
288,Garcia,Manchester City,50,13.103448,38,43.509858,2.9,3.320489,3.612587,3.424820,1.484968,1.531626
347,Stevens,Sheffield Utd,55,38.378378,142,133.181335,3.7,3.470218,3.424341,3.265538,1.479706,1.392430
471,Vinagre,Wolves,45,16.000000,32,49.783868,2.0,3.111492,3.635800,3.185521,1.466771,1.501669
219,Evans,Leicester City,55,37.647059,128,129.143716,3.4,3.430380,3.818299,3.604063,1.462719,1.536778
486,Dann,Crystal Palace,45,15.937500,51,49.268766,3.2,3.091374,2.563272,3.259977,1.457287,1.536768
389,Aurier,Tottenham,55,32.631579,124,111.286061,3.8,3.410379,2.977053,3.271531,1.454191,1.394986
300,Shaw,Manchester Utd,50,23.928571,67,77.671699,2.8,3.245981,3.532496,3.224468,1.451647,1.442026

MIDFIELDERS

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,next1_xP,next10_xP,valuePoints metric,valuePoints_next10 metric
id,,,,,,,,,,,,
306,Rashford,Manchester Utd,95,31.052632,177,200.255107,5.7,6.448893,6.848269,6.500996,2.092297,2.109202
302,Fernandes,Manchester Utd,105,13.928571,117,90.275261,8.4,6.481301,6.815336,6.521944,2.000173,2.012716
254,Salah,Liverpool,120,33.768116,233,226.226806,6.9,6.699420,7.487292,6.725708,1.933956,1.941545
272,De Bruyne,Manchester City,115,34.861111,251,221.771295,7.2,6.361567,6.983719,6.582754,1.875924,1.941148
276,Sterling,Manchester City,115,32.903226,204,197.484712,6.2,6.001986,6.752800,6.268886,1.769889,1.848594
468,Jota,Wolves,65,33.870968,105,143.732249,3.1,4.243524,5.062093,4.412980,1.664447,1.730913
390,Son,Tottenham,90,30.178571,169,148.366669,5.6,4.916292,4.185068,4.795945,1.638764,1.598648
251,Man√©,Liverpool,120,35.079365,221,196.823253,6.3,5.610799,6.207469,5.629820,1.619698,1.625189
4,Aubameyang,Arsenal,120,35.964912,205,200.313236,5.7,5.569685,5.709656,5.498250,1.607830,1.587208
119,Pulisic,Chelsea,85,24.901961,127,116.720915,5.1,4.687218,5.027627,4.711197,1.607702,1.615927
275,Mahrez,Manchester City,85,33.018868,175,153.901407,5.3,4.661014,5.122125,4.824983,1.598715,1.654956
231,Maddison,Leicester City,70,31.250000,125,129.768623,4.0,4.152596,4.689080,4.321429,1.569534,1.633347
478,Willian,Arsenal,80,35.744681,168,155.347758,4.7,4.346038,4.469473,4.295976,1.536557,1.518857
37,Grealish,Aston Villa,70,36.341463,149,144.631078,4.1,3.979781,3.698604,4.062317,1.504216,1.535412
394,Alli,Tottenham,80,24.893617,117,105.639590,4.7,4.243642,3.665494,4.144340,1.500354,1.465245
321,Shelvey,Newcastle Utd,55,26.250000,105,91.152886,4.0,3.472491,3.563679,3.495337,1.480675,1.490417
120,Mount,Chelsea,70,37.027027,137,141.941988,3.7,3.833470,4.114811,3.863705,1.448915,1.460343
338,Saint-Maximin,Newcastle Utd,55,26.285714,92,88.994176,3.5,3.385648,3.478758,3.408569,1.443645,1.453419
445,Bowen,West Ham,65,12.941176,44,47.283069,3.4,3.653692,3.365984,3.644739,1.433096,1.429584
370,Ward-Prowse,Southampton,60,37.741935,117,132.311886,3.1,3.505700,4.137559,3.538954,1.431196,1.444772
235,Barnes,Leicester City,70,35.945946,133,135.669155,3.7,3.774255,4.309826,3.942828,1.426534,1.490249
465,Traor√©,Wolves,65,37.142857,130,134.422776,3.5,3.619075,4.126690,3.720257,1.419518,1.459205
69,Trossard,Brighton,60,30.588235,104,105.331140,3.4,3.443518,3.289663,3.507705,1.405810,1.432015
229,P√©rez,Leicester City,65,33.076923,129,118.150588,3.9,3.571995,4.012813,3.713530,1.401052,1.456566
449,Soucek,West Ham,50,12.812500,41,39.712992,3.2,3.099551,2.859788,3.089532,1.386161,1.381681
365,Redmond,Southampton,65,32.424242,107,113.140559,3.3,3.489382,4.022728,3.521104,1.368648,1.381091
105,Jorginho,Chelsea,50,30.666667,92,93.385011,3.0,3.045163,3.276332,3.080713,1.361838,1.377737
244,Henderson,Liverpool,55,29.743590,116,94.909817,3.9,3.190933,3.362794,3.193814,1.360619,1.361847
346,Fleck,Sheffield Utd,60,29.705882,101,98.566371,3.4,3.318076,3.333385,3.256363,1.354599,1.329405
304,Pereira,Manchester Utd,50,25.000000,60,75.476983,2.4,3.019079,3.185113,3.030258,1.350173,1.355173
454,Moutinho,Wolves,55,37.666667,113,119.112203,3.0,3.162271,3.513593,3.229136,1.348397,1.376908
355,Lundstram,Sheffield Utd,55,34.285714,144,108.290616,4.2,3.158476,3.176734,3.095603,1.346779,1.319970
38,McGinn,Aston Villa,55,28.000000,84,87.789761,3.0,3.135349,2.924360,3.195153,1.336917,1.362418
89,Westwood,Burnley,55,34.705882,118,108.143679,3.4,3.116004,3.293214,3.130816,1.328669,1.334984
281,Bernardo Silva,Manchester City,75,34.117647,116,123.949669,3.4,3.633008,3.996884,3.762430,1.326587,1.373845
427,Noble,West Ham,50,32.812500,105,96.840549,3.2,2.951331,2.762753,2.940175,1.319875,1.314886
469,Podence,Wolves,55,8.928571,25,27.522240,2.8,3.082491,3.603894,3.186700,1.314379,1.358814
339,Almir√≥n,Newcastle Utd,60,36.333333,109,116.415700,3.0,3.204102,3.297492,3.227034,1.308069,1.317431
100,McNeil,Burnley,60,38.437500,123,123.004398,3.2,3.200114,3.392824,3.218576,1.306441,1.313978
228,Tielemans,Leicester City,65,36.562500,117,120.313970,3.2,3.290638,3.637313,3.405310,1.290695,1.335672

FORWARDS

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,next1_xP,next10_xP,valuePoints metric,valuePoints_next10 metric
id,,,,,,,,,,,,
224,Vardy,Leicester City,100,35.000000,210,194.978468,6.0,5.570813,6.419737,5.813053,1.761646,1.838249
437,Antonio,West Ham,65,24.130435,111,103.164839,4.6,4.275300,3.884882,4.283978,1.676910,1.680314
460,Jim√©nez,Wolves,85,38.039216,194,182.558468,5.1,4.799217,5.567432,4.967891,1.646118,1.703972
366,Ings,Southampton,85,38.076923,198,180.562420,5.2,4.742043,5.536566,4.754398,1.626507,1.630745
91,Wood,Burnley,65,32.380952,136,131.531210,4.2,4.061993,4.193851,4.093049,1.593245,1.605426
118,Abraham,Chelsea,75,34.000000,153,145.467259,4.5,4.278449,4.448112,4.260478,1.562269,1.555707
282,Jesus,Manchester City,95,33.953488,146,156.709678,4.3,4.615422,5.151327,4.805828,1.497441,1.559217
268,Ag√ºero,Manchester City,105,24.000000,132,115.227259,5.5,4.801136,5.344743,4.994278,1.481663,1.541268
249,Firmino,Liverpool,95,37.804878,155,170.300888,4.1,4.504733,4.911769,4.520200,1.461528,1.466546
68,Maupay,Brighton,65,37.428571,131,135.473629,3.5,3.619524,3.444897,3.679355,1.419694,1.443162
303,Martial,Manchester Utd,90,32.258065,200,136.520888,6.2,4.232148,4.417120,4.264588,1.410716,1.421529
388,Kane,Tottenham,105,29.259259,158,130.362420,5.4,4.455424,3.936966,4.384147,1.374974,1.352977
164,Calvert-Lewin,Everton,70,36.000000,126,130.311210,3.5,3.619756,3.903861,3.621003,1.368139,1.368611
103,Giroud,Chelsea,70,17.894737,68,64.411210,3.8,3.599450,3.748943,3.583615,1.360464,1.354479
140,Ayew,Crystal Palace,60,36.666667,132,120.033629,3.6,3.273644,3.010873,3.333089,1.336460,1.360728
48,Wesley,Aston Villa,60,20.937500,67,67.431210,3.2,3.220595,3.063022,3.271627,1.314802,1.335636
344,McGoldrick,Sheffield Utd,55,28.260870,65,87.122420,2.3,3.082793,3.125832,3.065849,1.314507,1.307282
87,Barnes,Burnley,60,19.062500,61,60.420000,3.2,3.169574,3.267041,3.192530,1.293973,1.303345
166,Richarlison,Everton,80,35.869565,165,130.256049,4.6,3.631381,3.878079,3.632464,1.283887,1.284270
441,Haller,West Ham,65,31.875000,102,103.633629,3.2,3.251251,3.052652,3.255666,1.275246,1.276977
233,Iheanacho,Leicester City,60,20.000000,64,61.544839,3.2,3.077242,3.503758,3.198948,1.256279,1.305965
136,Wickham,Crystal Palace,45,6.000000,15,15.411210,2.5,2.568535,2.220347,2.647303,1.210819,1.247950
6,Lacazette,Arsenal,85,30.256410,118,105.278468,3.9,3.479543,3.506627,3.444535,1.193473,1.181466
329,Gayle,Newcastle Utd,60,20.000000,58,57.822420,2.9,2.891121,2.910425,2.891873,1.180295,1.180602
361,Long,Southampton,55,25.833333,62,70.133629,2.4,2.714850,3.073313,2.720424,1.157616,1.159993
93,Vydra,Burnley,50,18.571429,39,46.511210,2.1,2.504450,2.580487,2.522359,1.120024,1.128033
86,Rodriguez,Burnley,60,35.714286,100,97.942420,2.8,2.742388,2.819067,2.760448,1.119575,1.126948
357,McBurnie,Sheffield Utd,60,35.833333,86,95.011210,2.4,2.651476,2.686006,2.637881,1.082460,1.076910
359,Mousset,Sheffield Utd,60,30.000000,84,77.944839,2.8,2.598161,2.629825,2.585695,1.060695,1.055606
132,Benteke,Crystal Palace,55,23.333333,42,57.611210,1.8,2.469052,2.122942,2.547349,1.052807,1.086193
340,Joelinton,Newcastle Utd,60,37.142857,78,91.822420,2.1,2.472142,2.485594,2.472666,1.009248,1.009462
377,Adams,Southampton,60,30.000000,78,73.544839,2.6,2.451495,2.729304,2.455815,1.000818,1.002582
22,Nketiah,Arsenal,60,13.157895,25,31.900000,1.9,2.424400,2.445831,2.396699,0.989757,0.978448
343,Sharp,Sheffield Utd,60,24.782609,57,59.422420,2.3,2.397747,2.424620,2.387167,0.978876,0.974557
49,Samatta,Aston Villa,60,13.809524,29,32.800000,2.1,2.375172,2.293153,2.401735,0.969660,0.980504
78,Connolly,Brighton,55,24.400000,61,55.433629,2.5,2.271870,2.202476,2.295646,0.968729,0.978867
358,Callum Robinson,Sheffield Utd,55,15.714286,33,31.322420,2.1,1.993245,2.015328,1.984551,0.849922,0.846215
169,Kean,Everton,60,29.444444,53,60.222420,1.8,2.045290,2.162657,2.045805,0.834986,0.835196
381,Obafemi,Southampton,50,21.428571,45,39.622420,2.1,1.849046,2.059483,1.852319,0.826919,0.828382
50,Davis,Aston Villa,45,17.857143,25,29.911210,1.4,1.675028,1.608347,1.696623,0.789616,0.799796

Below we compile a list sorting players based on a given metric (irrespective of position).

In [7]:
metric = 'adjusted points per game'

display(df[minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game',\
                                                                'valuePoints metric']].head(numberToShow))

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,valuePoints metric
id,,,,,,,,,
254,Salah,Liverpool,120,33.768116,233,226.226806,6.9,6.699420,1.933956
302,Fernandes,Manchester Utd,105,13.928571,117,90.275261,8.4,6.481301,2.000173
306,Rashford,Manchester Utd,95,31.052632,177,200.255107,5.7,6.448893,2.092297
272,De Bruyne,Manchester City,115,34.861111,251,221.771295,7.2,6.361567,1.875924
276,Sterling,Manchester City,115,32.903226,204,197.484712,6.2,6.001986,1.769889
251,Man√©,Liverpool,120,35.079365,221,196.823253,6.3,5.610799,1.619698
224,Vardy,Leicester City,100,35.000000,210,194.978468,6.0,5.570813,1.761646
4,Aubameyang,Arsenal,120,35.964912,205,200.313236,5.7,5.569685,1.607830
259,Alexander-Arnold,Liverpool,75,38.181818,210,195.332634,5.5,5.115855,1.868046
390,Son,Tottenham,90,30.178571,169,148.366669,5.6,4.916292,1.638764
268,Ag√ºero,Manchester City,105,24.000000,132,115.227259,5.5,4.801136,1.481663
460,Jim√©nez,Wolves,85,38.039216,194,182.558468,5.1,4.799217,1.646118
366,Ings,Southampton,85,38.076923,198,180.562420,5.2,4.742043,1.626507
255,Robertson,Liverpool,70,36.200000,181,171.439514,5.0,4.735898,1.790001
119,Pulisic,Chelsea,85,24.901961,127,116.720915,5.1,4.687218,1.607702
104,Alonso,Chelsea,60,17.857143,100,83.610480,5.6,4.682187,1.911495
275,Mahrez,Manchester City,85,33.018868,175,153.901407,5.3,4.661014,1.598715
282,Jesus,Manchester City,95,33.953488,146,156.709678,4.3,4.615422,1.497441
383,Lloris,Tottenham,55,20.851064,98,95.283026,4.7,4.569696,1.948525
249,Firmino,Liverpool,95,37.804878,155,170.300888,4.1,4.504733,1.461528
388,Kane,Tottenham,105,29.259259,158,130.362420,5.4,4.455424,1.374974
102,Azpilicueta,Chelsea,60,36.111111,130,159.693332,3.6,4.422277,1.805387
305,Henderson,Manchester Utd,55,36.363636,160,160.072543,4.4,4.401995,1.877017
478,Willian,Arsenal,80,35.744681,168,155.347758,4.7,4.346038,1.536557
118,Abraham,Chelsea,75,34.000000,153,145.467259,4.5,4.278449,1.562269
437,Antonio,West Ham,65,24.130435,111,103.164839,4.6,4.275300,1.676910
455,Patr√≠cio,Wolves,55,38.250000,153,162.878622,4.0,4.258265,1.815730
394,Alli,Tottenham,80,24.893617,117,105.639590,4.7,4.243642,1.500354
468,Jota,Wolves,65,33.870968,105,143.732249,3.1,4.243524,1.664447
303,Martial,Manchester Utd,90,32.258065,200,136.520888,6.2,4.232148,1.410716
231,Maddison,Leicester City,70,31.250000,125,129.768623,4.0,4.152596,1.569534
250,van Dijk,Liverpool,65,37.872340,178,156.855989,4.7,4.141703,1.624510
457,Doherty,Tottenham,60,36.304348,167,149.446127,4.6,4.116480,1.680546
96,Pope,Burnley,55,37.777778,170,155.053609,4.5,4.104360,1.750105
91,Wood,Burnley,65,32.380952,136,131.531210,4.2,4.061993,1.593245
232,Chilwell,Chelsea,55,27.142857,114,109.717403,4.2,4.042220,1.723608
226,Pereira,Leicester City,60,27.954545,123,112.817956,4.4,4.035764,1.647594
217,Schmeichel,Leicester City,55,38.048780,156,152.015579,4.1,3.995281,1.703594
37,Grealish,Aston Villa,70,36.341463,149,144.631078,4.1,3.979781,1.504216
483,Ramsdale,Sheffield Utd,50,37.058824,126,146.147362,3.4,3.943659,1.763658

In [8]:
#metric = 'valuePoints metric'
metric = 'valuePoints_next10 metric'

display(df[minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game',\
                                'next1_xP','valuePoints metric']].head(numberToShow))

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,next1_xP,valuePoints metric
id,,,,,,,,,,
306,Rashford,Manchester Utd,95,31.052632,177,200.255107,5.7,6.448893,6.848269,2.092297
302,Fernandes,Manchester Utd,105,13.928571,117,90.275261,8.4,6.481301,6.815336,2.000173
104,Alonso,Chelsea,60,17.857143,100,83.610480,5.6,4.682187,5.436008,1.911495
254,Salah,Liverpool,120,33.768116,233,226.226806,6.9,6.699420,7.487292,1.933956
272,De Bruyne,Manchester City,115,34.861111,251,221.771295,7.2,6.361567,6.983719,1.875924
383,Lloris,Tottenham,55,20.851064,98,95.283026,4.7,4.569696,4.250357,1.948525
102,Azpilicueta,Chelsea,60,36.111111,130,159.693332,3.6,4.422277,5.168618,1.805387
259,Alexander-Arnold,Liverpool,75,38.181818,210,195.332634,5.5,5.115855,5.603433,1.868046
305,Henderson,Manchester Utd,55,36.363636,160,160.072543,4.4,4.401995,4.657851,1.877017
276,Sterling,Manchester City,115,32.903226,204,197.484712,6.2,6.001986,6.752800,1.769889
224,Vardy,Leicester City,100,35.000000,210,194.978468,6.0,5.570813,6.419737,1.761646
455,Patr√≠cio,Wolves,55,38.250000,153,162.878622,4.0,4.258265,4.684434,1.815730
269,Otamendi,Manchester City,50,24.117647,82,93.933224,3.4,3.894792,4.251401,1.741804
232,Chilwell,Chelsea,55,27.142857,114,109.717403,4.2,4.042220,4.759251,1.723608
255,Robertson,Liverpool,70,36.200000,181,171.439514,5.0,4.735898,5.149064,1.790001
363,McCarthy,Southampton,45,28.108108,104,103.725496,3.7,3.690234,4.119967,1.739593
128,Guaita,Crystal Palace,50,35.128205,137,133.715297,3.9,3.806494,3.354694,1.702316
217,Schmeichel,Leicester City,55,38.048780,156,152.015579,4.1,3.995281,4.245613,1.703594
96,Pope,Burnley,55,37.777778,170,155.053609,4.5,4.104360,4.622856,1.750105
393,Gazzaniga,Tottenham,45,18.125000,58,69.400488,3.2,3.828992,3.494262,1.805004
468,Jota,Wolves,65,33.870968,105,143.732249,3.1,4.243524,5.062093,1.664447
226,Pereira,Leicester City,60,27.954545,123,112.817956,4.4,4.035764,4.481739,1.647594
70,Ryan,Brighton,45,37.500000,135,134.185543,3.6,3.578281,3.538883,1.686818
460,Jim√©nez,Wolves,85,38.039216,194,182.558468,5.1,4.799217,5.567432,1.646118
139,van Aanholt,Crystal Palace,55,28.684211,109,107.622582,3.8,3.751980,3.047769,1.599850
264,Williams,Liverpool,40,6.086957,14,20.575498,2.3,3.380260,3.681032,1.690130
123,James,Chelsea,50,24.400000,61,87.994991,2.5,3.606352,4.325907,1.612810
437,Antonio,West Ham,65,24.130435,111,103.164839,4.6,4.275300,3.884882,1.676910
483,Ramsdale,Sheffield Utd,50,37.058824,126,146.147362,3.4,3.943659,3.879160,1.763658
458,Boly,Wolves,55,22.045455,97,85.075062,4.4,3.859075,4.334555,1.645515
8,Leno,Arsenal,50,30.000000,114,113.417348,3.8,3.780578,4.158301,1.690726
62,Dunk,Brighton,50,35.555556,128,128.994737,3.6,3.627977,3.486533,1.622481
246,Matip,Liverpool,55,9.069767,39,35.428774,4.3,3.906249,4.175659,1.665630
279,Ak√©,Manchester City,55,29.259259,79,110.506128,2.7,3.776792,4.120981,1.610429
291,de Gea,Manchester Utd,55,37.631579,143,147.256827,3.8,3.913118,4.168974,1.668559
275,Mahrez,Manchester City,85,33.018868,175,153.901407,5.3,4.661014,5.122125,1.598715
313,Wan-Bissaka,Manchester Utd,55,35.277778,127,136.982882,3.6,3.882979,4.182235,1.655708
121,Tomori,Chelsea,50,15.000000,48,52.683138,3.2,3.512209,4.202594,1.570708
231,Maddison,Leicester City,70,31.250000,125,129.768623,4.0,4.152596,4.689080,1.569534
461,Sa√Øss,Wolves,50,33.225806,103,117.873194,3.1,3.547640,4.188293,1.586553

In [9]:
metric = 'next1_xP'

display(df[minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game',\
                                                            'next1_xP','valuePoints metric']].head(numberToShow))

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,next1_xP,valuePoints metric
id,,,,,,,,,,
254,Salah,Liverpool,120,33.768116,233,226.226806,6.9,6.699420,7.487292,1.933956
272,De Bruyne,Manchester City,115,34.861111,251,221.771295,7.2,6.361567,6.983719,1.875924
306,Rashford,Manchester Utd,95,31.052632,177,200.255107,5.7,6.448893,6.848269,2.092297
302,Fernandes,Manchester Utd,105,13.928571,117,90.275261,8.4,6.481301,6.815336,2.000173
276,Sterling,Manchester City,115,32.903226,204,197.484712,6.2,6.001986,6.752800,1.769889
224,Vardy,Leicester City,100,35.000000,210,194.978468,6.0,5.570813,6.419737,1.761646
251,Man√©,Liverpool,120,35.079365,221,196.823253,6.3,5.610799,6.207469,1.619698
4,Aubameyang,Arsenal,120,35.964912,205,200.313236,5.7,5.569685,5.709656,1.607830
259,Alexander-Arnold,Liverpool,75,38.181818,210,195.332634,5.5,5.115855,5.603433,1.868046
460,Jim√©nez,Wolves,85,38.039216,194,182.558468,5.1,4.799217,5.567432,1.646118
366,Ings,Southampton,85,38.076923,198,180.562420,5.2,4.742043,5.536566,1.626507
104,Alonso,Chelsea,60,17.857143,100,83.610480,5.6,4.682187,5.436008,1.911495
268,Ag√ºero,Manchester City,105,24.000000,132,115.227259,5.5,4.801136,5.344743,1.481663
102,Azpilicueta,Chelsea,60,36.111111,130,159.693332,3.6,4.422277,5.168618,1.805387
282,Jesus,Manchester City,95,33.953488,146,156.709678,4.3,4.615422,5.151327,1.497441
255,Robertson,Liverpool,70,36.200000,181,171.439514,5.0,4.735898,5.149064,1.790001
275,Mahrez,Manchester City,85,33.018868,175,153.901407,5.3,4.661014,5.122125,1.598715
468,Jota,Wolves,65,33.870968,105,143.732249,3.1,4.243524,5.062093,1.664447
119,Pulisic,Chelsea,85,24.901961,127,116.720915,5.1,4.687218,5.027627,1.607702
249,Firmino,Liverpool,95,37.804878,155,170.300888,4.1,4.504733,4.911769,1.461528
232,Chilwell,Chelsea,55,27.142857,114,109.717403,4.2,4.042220,4.759251,1.723608
231,Maddison,Leicester City,70,31.250000,125,129.768623,4.0,4.152596,4.689080,1.569534
455,Patr√≠cio,Wolves,55,38.250000,153,162.878622,4.0,4.258265,4.684434,1.815730
305,Henderson,Manchester Utd,55,36.363636,160,160.072543,4.4,4.401995,4.657851,1.877017
96,Pope,Burnley,55,37.777778,170,155.053609,4.5,4.104360,4.622856,1.750105
250,van Dijk,Liverpool,65,37.872340,178,156.855989,4.7,4.141703,4.485615,1.624510
226,Pereira,Leicester City,60,27.954545,123,112.817956,4.4,4.035764,4.481739,1.647594
478,Willian,Arsenal,80,35.744681,168,155.347758,4.7,4.346038,4.469473,1.536557
118,Abraham,Chelsea,75,34.000000,153,145.467259,4.5,4.278449,4.448112,1.562269
303,Martial,Manchester Utd,90,32.258065,200,136.520888,6.2,4.232148,4.417120,1.410716
458,Boly,Wolves,55,22.045455,97,85.075062,4.4,3.859075,4.334555,1.645515
123,James,Chelsea,50,24.400000,61,87.994991,2.5,3.606352,4.325907,1.612810
235,Barnes,Leicester City,70,35.945946,133,135.669155,3.7,3.774255,4.309826,1.426534
155,Digne,Everton,60,35.294118,120,132.450858,3.4,3.752774,4.296991,1.532064
269,Otamendi,Manchester City,50,24.117647,82,93.933224,3.4,3.894792,4.251401,1.741804
383,Lloris,Tottenham,55,20.851064,98,95.283026,4.7,4.569696,4.250357,1.948525
217,Schmeichel,Leicester City,55,38.048780,156,152.015579,4.1,3.995281,4.245613,1.703594
121,Tomori,Chelsea,50,15.000000,48,52.683138,3.2,3.512209,4.202594,1.570708
91,Wood,Burnley,65,32.380952,136,131.531210,4.2,4.061993,4.193851,1.593245
461,Sa√Øss,Wolves,50,33.225806,103,117.873194,3.1,3.547640,4.188293,1.586553

In [10]:
#metric = 'form 10'

#display(df[minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
#          'games played','total_points','adjusted points','points_per_game','adjusted points per game','form 5',\
#          'form 10','valuePoints metric']].head(numberToShow))