# DATA PROCESSING AND CALCULATION OF xG-ADJUSTED FPL POINTS

## Setup and pre-processing

In [1]:
# give the number of the latest FPL round
latest_gameweek = 16

In [2]:
# import basic libraries
import pandas as pd
import numpy as np
import json
import requests
from scipy.stats import poisson

# allow more data columns to be shown than usually
pd.set_option('max_columns',100)

In [3]:
# import player data 
filepath = '../data/fbref/player_stats_week' + str(latest_gameweek) + '.csv'
playerStats = pd.read_csv(filepath, index_col=0, skiprows=1)#, encoding='latin-1')
playerStats.head()

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,Gls,Ast,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A,G-PK,G+A-PK,xG,npxG,xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA,Matches
Rk,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,Patrick van Aanholt\Patrick-van-Aanholt,nl NED,DF,Crystal Palace,28,1990,15,15,1289,2,0,1,1,0,0,0.14,0.00,0.14,0.07,0.07,1.3,0.6,0.4,0.09,0.03,0.12,0.04,0.07,Matches
2,Max Aarons\Max-Aarons,eng ENG,MF,Norwich City,19,2000,14,14,1260,0,0,0,0,4,0,0.00,0.00,0.00,0.00,0.00,0.3,0.3,1.7,0.02,0.12,0.14,0.02,0.14,Matches
3,Tammy Abraham\Tammy-Abraham,eng ENG,FW,Chelsea,21,1997,15,14,1143,11,3,0,0,2,0,0.87,0.24,1.10,0.87,1.10,8.7,8.7,2.2,0.69,0.17,0.86,0.69,0.86,Matches
4,Che Adams\Che-Adams,eng ENG,FW,Southampton,23,1996,11,6,485,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,1.5,1.5,0.2,0.27,0.04,0.31,0.27,0.31,Matches
5,Adrián\Adrian,es ESP,GK,Liverpool,32,1987,10,8,783,0,0,0,0,1,0,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,Matches

In [4]:
# import team data and pre-process
filepath = '../data/fbref/team_stats_week' + str(latest_gameweek) + '.csv'
teamStats = pd.read_csv(filepath, index_col=0, encoding='latin-1')

# change team names to match convention used in the FPL data
teamStats.loc[teamStats['Squad']=='Brighton & Hove Albion','Squad'] = 'Brighton'
teamStats.loc[teamStats['Squad']=='Manchester United','Squad'] = 'Manchester Utd'
teamStats.loc[teamStats['Squad']=='Newcastle United','Squad'] = 'Newcastle Utd'
teamStats.loc[teamStats['Squad']=='Sheffield United','Squad'] = 'Sheffield Utd'
teamStats.loc[teamStats['Squad']=='West Ham United','Squad'] = 'West Ham'
teamStats.loc[teamStats['Squad']=='Tottenham Hotspur','Squad'] = 'Tottenham'
teamStats.loc[teamStats['Squad']=='Wolverhampton Wanderers','Squad'] = 'Wolves'

teamStats.head()

,Squad,MP,W,D,L,GF,GA,GDiff,Pts,xG,xGA,xGDiff,xGDiff/90,Last 5,Attendance,Top Team Scorer,Goalkeeper,Notes,xGA per game,probability no goals allowed
Rk,,,,,,,,,,,,,,,,,,,,
1,Liverpool,16,15,1,0,40,14,26,46,30.6,16.0,14.6,0.91,W W W W W,53043,Sadio Mané - 9,Adrián,NaN,1.0000,0.367879
2,Leicester City,16,12,2,2,39,10,29,38,29.1,15.4,13.7,0.86,W W W W W,32018,Jamie Vardy - 16,Kasper Schmeichel,NaN,0.9625,0.381937
3,Manchester City,16,10,2,4,44,19,25,32,42.0,16.4,25.6,1.60,L W D W L,54364,Sergio Agüero - 9,Ederson,NaN,1.0250,0.358796
4,Chelsea,16,9,2,5,31,24,7,29,30.8,17.6,13.2,0.82,W L L W L,40596,Tammy Abraham - 11,Kepa Arrizabalaga,NaN,1.1000,0.332871
5,Manchester Utd,16,6,6,4,25,19,6,24,26.2,17.0,9.2,0.57,W D D W W,73486,Marcus Rashford - 10,David de Gea,NaN,1.0625,0.345591

In [5]:
# fetch FPL data online
data = json.loads(requests.get('https://fantasy.premierleague.com/api/bootstrap-static/').text)
df = pd.DataFrame(data['elements'])
df.set_index('id',inplace=True)

# fetch data locally
#df = pd.read_csv('./data/data_week' + str(latest_gameweek) + '.csv', index_col=0)#,encoding='latin-1')

df.head()

,assists,bonus,bps,chance_of_playing_next_round,chance_of_playing_this_round,clean_sheets,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,creativity,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,goals_conceded,goals_scored,ict_index,in_dreamteam,influence,minutes,news,news_added,now_cost,own_goals,penalties_missed,penalties_saved,photo,points_per_game,red_cards,saves,second_name,selected_by_percent,special,squad_number,status,team,team_code,threat,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,yellow_cards
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,1,0,24,100.0,100.0,0,69140,0,0,-3,3,0.8,0,2,0.5,1.5,0,Shkodran,1.0,2,0,7.5,False,19.8,90,,2019-11-28T23:00:21.541666Z,52,0,0,0,69140.jpg,4.0,0,0,Mustafi,0.3,False,None,a,1,3,54.0,4,7715,0,31812,0,0.2,0.8,Mustafi,0
2,0,0,26,75.0,75.0,0,98745,0,0,-1,1,22.7,0,2,-0.2,0.7,0,Héctor,0.2,6,0,6.9,False,30.8,262,Hamstring injury - 75% chance of playing,2019-12-09T20:00:21.228098Z,54,0,0,0,98745.jpg,0.3,0,0,Bellerín,0.3,False,None,d,1,3,15.0,1,34575,0,32071,0,0.0,0.2,Bellerín,2
3,2,1,191,100.0,100.0,1,111457,0,0,-3,3,148.9,0,2,1.5,2.5,0,Sead,2.0,14,0,37.3,False,172.6,889,,2019-11-21T14:30:19.207005Z,52,0,0,0,111457.jpg,2.1,0,0,Kolasinac,0.6,False,None,a,1,3,53.0,27,46591,0,107409,0,0.4,5.2,Kolasinac,2
4,2,3,106,100.0,100.0,1,154043,0,0,-4,4,110.0,1,2,0.0,1.0,0,Ainsley,0.5,11,0,29.3,False,155.0,580,,2019-09-22T18:00:10.824841Z,46,0,0,0,154043.jpg,2.7,1,0,Maitland-Niles,2.6,False,None,a,1,3,33.0,19,545554,0,564245,0,0.1,4.1,Maitland-Niles,0
5,0,2,217,NaN,NaN,2,39476,0,0,-1,1,30.4,0,2,0.0,1.0,0,Sokratis,0.5,20,1,43.1,False,328.8,1260,,None,49,0,0,0,39476.jpg,2.4,0,0,Papastathopoulos,1.5,False,None,a,1,3,71.0,33,107068,0,137942,0,0.1,6.7,Sokratis,4

## Probability to keep a clean sheet

Here, we estimate for each team the probability that the team keeps a clean sheet (against average opposition). We do this by first calculating the expected goals allowed per game for each team. Then, we assume that conceding goals follows a Poisson distribution, from which we then get the desired probability.

In [6]:
teamStats['xGA per game'] = teamStats['xGA'] / teamStats['MP']
teamStats['probability no goals allowed'] = poisson.pmf(0,teamStats['xGA per game'])
teamStats

,Squad,MP,W,D,L,GF,GA,GDiff,Pts,xG,xGA,xGDiff,xGDiff/90,Last 5,Attendance,Top Team Scorer,Goalkeeper,Notes,xGA per game,probability no goals allowed
Rk,,,,,,,,,,,,,,,,,,,,
1,Liverpool,16,15,1,0,40,14,26,46,30.6,16.0,14.6,0.91,W W W W W,53043,Sadio Mané - 9,Adrián,NaN,1.00000,0.367879
2,Leicester City,16,12,2,2,39,10,29,38,29.1,15.4,13.7,0.86,W W W W W,32018,Jamie Vardy - 16,Kasper Schmeichel,NaN,0.96250,0.381937
3,Manchester City,16,10,2,4,44,19,25,32,42.0,16.4,25.6,1.60,L W D W L,54364,Sergio Agüero - 9,Ederson,NaN,1.02500,0.358796
4,Chelsea,16,9,2,5,31,24,7,29,30.8,17.6,13.2,0.82,W L L W L,40596,Tammy Abraham - 11,Kepa Arrizabalaga,NaN,1.10000,0.332871
5,Manchester Utd,16,6,6,4,25,19,6,24,26.2,17.0,9.2,0.57,W D D W W,73486,Marcus Rashford - 10,David de Gea,NaN,1.06250,0.345591
6,Wolves,16,5,9,2,23,19,4,24,21.0,16.2,4.8,0.30,W W D W D,31183,Raúl Jiménez - 6,Rui Patrício,NaN,1.01250,0.363310
7,Tottenham,16,6,5,5,30,23,7,23,21.6,21.6,0.0,0.00,D W W L W,59459,Harry Kane - 9,Paulo Gazzaniga,NaN,1.35000,0.259240
8,Sheffield Utd,16,5,7,4,19,16,3,22,18.7,19.0,-0.3,-0.02,D D D L W,30922,Lys Mousset - 5,Dean Henderson,NaN,1.18750,0.304983
9,Arsenal,16,5,7,4,24,24,0,22,23.9,24.7,-0.8,-0.05,L D D L W,60299,Pierre-Emerick Aubameyang - 11,Bernd Leno,NaN,1.54375,0.213579
10,Crystal Palace,16,6,4,6,14,18,-4,22,14.5,21.8,-7.4,-0.46,L L W W D,25118,Jordan Ayew - 4,Vicente Guaita,NaN,1.36250,0.256020
11,Newcastle Utd,16,6,4,6,17,23,-6,22,13.3,27.6,-14.3,-0.89,W L D W W,46124,Jonjo Shelvey - 5,Martin Dúbravka,NaN,1.72500,0.178173
12,Brighton,16,5,4,7,20,24,-4,19,19.6,26.9,-7.3,-0.46,L L L W D,30298,Neal Maupay - 6,Mathew Ryan,NaN,1.68125,0.186141
13,Burnley,16,5,3,8,21,29,-8,18,19.9,19.0,0.9,0.06,W W L L L,20382,Chris Wood Ashley Barnes - 6,Nick Pope,NaN,1.18750,0.304983
14,Everton,16,5,2,9,19,28,-9,17,21.0,21.5,-0.5,-0.03,W L L L W,39204,Richarlison - 6,Jordan Pickford,NaN,1.34375,0.260866
15,Bournemouth,16,4,4,8,18,24,-6,16,19.3,25.3,-6.0,-0.37,L L L L L,10632,Harry Wilson - 6,Aaron Ramsdale,NaN,1.58125,0.205718
16,West Ham,16,4,4,8,18,28,-10,16,19.0,31.4,-12.4,-0.78,L L W L L,59915,Sébastien Haller - 4,Roberto,NaN,1.96250,0.140507
17,Aston Villa,16,4,3,9,23,28,-5,15,21.5,32.4,-10.9,-0.68,L W D L L,41738,Wesley Moraes Jack Grealish - 4,Tom Heaton,NaN,2.02500,0.131994
18,Southampton,16,4,3,9,18,35,-17,15,21.9,25.7,-3.8,-0.24,L D W W L,29540,Danny Ings - 9,Angus Gunn,NaN,1.60625,0.200639
19,Norwich City,16,3,2,11,17,34,-17,11,19.2,28.2,-9.0,-0.56,L W D L L,27038,Teemu Pukki - 8,Tim Krul,NaN,1.76250,0.171615
20,Watford,16,1,6,9,9,30,-21,9,18.9,28.2,-9.3,-0.58,W L L L D,20508,Andre Gray Gerard Deulofeu - 2,Ben Foster,NaN,1.76250,0.171615

## xG-adjusted points

Next, we determine for each player their 'adjusted points'. To do this, we first subtract for each player all the points they have accumulated through goals, assists and clean sheets. Then, we add points for each player based on their expected goals, assists and clean sheets. This gives a much improved estimate of each player's true point generating capability.

In [7]:
def incorporate_xG(indicator, ix):
    xG = playerStats.loc[indicator, 'xG'].values[0]
    if df.loc[ix, 'element_type']<=2:
        df.loc[ix, 'adjusted points'] =  df.loc[ix, 'total_points'] -  6 * (df.loc[ix, 'goals_scored'] - xG)
    elif df.loc[ix, 'element_type']==3:
        df.loc[ix, 'adjusted points'] =  df.loc[ix, 'total_points'] -  5 * (df.loc[ix, 'goals_scored'] - xG)
    elif df.loc[ix, 'element_type']==4:
        df.loc[ix, 'adjusted points'] =  df.loc[ix, 'total_points'] -  4 * (df.loc[ix, 'goals_scored'] - xG)

In [8]:
# always run 'team_xGA' AFTER 'incorporate_xG'
def team_xGA(indicator, ix):
    team = team_names[df.loc[ix, 'team']-1]
    clean_sheets = df.loc[ix, 'clean_sheets']
    probability_cleanSheet = teamStats.loc[teamStats['Squad']==team, 'probability no goals allowed'].values[0]
    if df.loc[ix, 'element_type']<=2:
        df.loc[ix, 'adjusted points'] =  df.loc[ix, 'adjusted points'] -  \
                    4 * (df.loc[ix, 'clean_sheets'] - df.loc[ix, 'games played']*probability_cleanSheet)
    elif df.loc[ix, 'element_type']==3:
        df.loc[ix, 'adjusted points'] =  df.loc[ix, 'adjusted points'] -  \
                    (df.loc[ix, 'clean_sheets'] - df.loc[ix, 'games played']*probability_cleanSheet)

A player who gives an assist that directly leads to a shot, is assigned the xG-value of the shot in xA (expected assists), i.e. xA is a measure of 'goal assists'. In FPL, however, the definition of an assist is somewhat more relaxed, e.g. goals resulting from a rebound of parried shot will award an assist to the player making the initial shot. For this reason, we calculate the total number of assists awarded in FPL and the total sum of xA of all players and get an estimate of the proportion of assists that xA covers in FPL. Then, we modify that proportion of players assists based on their xA.

In [9]:
# always run 'xA' AFTER 'incorporate_xG'
def xA(indicator, ix):
    xA = playerStats.loc[indicator, 'xA'].values[0]
    df.loc[ix, 'adjusted points'] =  df.loc[ix, 'adjusted points'] -  3 * (xA_proportion*df.loc[ix, 'assists'] - xA)

In [10]:
team_names = np.sort(playerStats['Squad'].unique())
xA_proportion = playerStats['xA'].sum()/df['assists'].sum()
df['points_per_game'] = df['points_per_game'].astype(float)
df['games played'] = df['total_points']/df['points_per_game']
#df['games played'] = df['minutes']/90.0
xA_proportion

0.7819753086419754

## Main loop for assigning adjusted points

Below is the main loop where we calculate adjusted points for each player. Calculation of the adjusted points itself is straightforward, but there is some work required to match players in two different data sets. Comparing player names in both data sets gives unique matches in many cases, but some special cases need to be covered through individual solutions.

In [12]:
for ix in df[df['minutes']>0].index:    
    name = df.loc[ix, 'web_name'].lower().replace(' ', '').replace('-', '').replace('ü', 'u').replace('ö', 'o').\
                        replace('ä', 'a')
    indicator = playerStats['Player'].str.lower().str.replace(' ', '').str.replace('-', '').str.contains(name)
    if playerStats.loc[indicator].shape[0]==1:
        incorporate_xG(indicator, ix)
        team_xGA(indicator, ix)
        xA(indicator, ix)
    elif playerStats.loc[indicator].shape[0]==0:
        first_name = df.loc[ix, 'first_name'].lower().replace(' ', '').replace('-', '').replace('ü', 'u')\
                                                                    .replace('ö', 'o').replace('ä', 'a')
        first_name_indicator = playerStats['Player'].str.lower().str.replace(' ', '').str.replace('-', '')\
                                                                            .str.contains(first_name)
        if playerStats.loc[first_name_indicator].shape[0]==1:
            incorporate_xG(first_name_indicator, ix)
            team_xGA(first_name_indicator, ix)
            xA(first_name_indicator, ix)
        else:
            names = ['rodrigo','garcia','chicharito']
            names_playerStats_index = [76, 380, 335]
            if name in names:
                name_ix = names.index(name)
                exceptional_case_indicator = playerStats.index == names_playerStats_index[name_ix]
                incorporate_xG(exceptional_case_indicator, ix)
                team_xGA(exceptional_case_indicator, ix)
                xA(exceptional_case_indicator, ix)
            else:
                print(str(ix) + ': no player found.')
    elif playerStats.loc[indicator].shape[0]>1:
        full_name = df.loc[ix, 'first_name'].lower().replace(' ', '').replace('-', '') \
            + df.loc[ix, 'second_name'].lower().replace(' ', '').replace('-', '')
        full_name_indicator = playerStats['Player'].str.lower().str.replace(' ', '').str.replace('-', '')\
                                                                            .str.contains(full_name)
        if playerStats.loc[full_name_indicator].shape[0]==1:
            incorporate_xG(full_name_indicator, ix)
            team_xGA(full_name_indicator, ix)
            xA(full_name_indicator, ix)
        else:
            team = team_names[df.loc[ix, 'team']-1]
            team_indicator = playerStats['Squad']==team
            if playerStats.loc[indicator & team_indicator].shape[0]==1:
                incorporate_xG(indicator & team_indicator, ix)
                team_xGA(indicator & team_indicator, ix)
                xA(indicator & team_indicator, ix)
            else:
                if name=='son':
                    exceptional_case_indicator = playerStats.index == 176
                    incorporate_xG(exceptional_case_indicator, ix)
                    team_xGA(exceptional_case_indicator, ix)
                    xA(exceptional_case_indicator, ix)
                else:
                    print(str(ix) + ': non-unique name.')
    else:
        print(str(ix) + 'Player not found')

In [13]:
df['adjusted points per game'] = df['adjusted points'] / df['games played']

In [14]:
# give a sorted list showing the players with highest 'adjusted points per game'
df[['web_name', 'games played','total_points', 'points_per_game','adjusted points','adjusted points per game']]\
                                .sort_values(by='adjusted points per game', ascending=False)

,web_name,games played,total_points,points_per_game,adjusted points,adjusted points per game
id,,,,,,
167,Iheanacho,2.000000,21,10.5,16.808148,8.404074
191,Salah,12.941176,88,6.8,85.677089,6.620502
215,De Bruyne,14.923077,97,6.5,96.095088,6.439362
166,Vardy,16.000000,128,8.0,102.916296,6.432269
192,Mané,14.931507,109,7.3,95.617439,6.403737
233,Rashford,16.031746,101,6.3,100.170370,6.248251
281,McGovern,2.000000,11,5.5,12.372922,6.186461
214,Sterling,15.000000,81,5.4,89.136021,5.942401
460,Abraham,14.923077,97,6.5,87.362222,5.854170
210,Agüero,12.000000,72,6.0,67.762222,5.646852
11,Aubameyang,16.031746,101,6.3,87.062222,5.430614
171,Maddison,15.087719,86,5.7,81.532926,5.403927
182,Alexander-Arnold,16.190476,68,4.2,86.603092,5.349014
409,Jiménez,16.000000,80,5.0,81.716296,5.107269
181,Robertson,16.000000,72,4.5,81.414655,5.088416
297,Lundstram,15.918367,78,4.9,80.827459,5.077622
431,Pulisic,13.125000,63,4.8,66.231155,5.046183
239,Martial,10.000000,52,5.2,49.518130,4.951813
187,Firmino,15.869565,73,4.6,76.870370,4.843886
278,Pukki,16.153846,84,5.2,78.162222,4.838614
219,David Silva,14.905660,79,5.3,71.780691,4.815667
217,Mahrez,11.929825,68,5.7,55.804823,4.677757
344,Alli,8.955224,60,6.7,41.783777,4.665855
196,Keita,3.018868,16,5.3,14.064654,4.658916
159,Pereira,15.961538,83,5.2,74.039273,4.638605
313,Ings,16.153846,84,5.2,74.554074,4.615252
161,Chilwell,12.941176,66,5.1,58.033071,4.484374
401,Doherty,15.128205,59,3.9,67.293035,4.448184
502,Maupay,16.000000,64,4.0,70.600000,4.412500
162,Evans,15.957447,75,4.7,69.987096,4.385858
...,...,...,...,...,...,...
326,Johnson,NaN,0,0.0,NaN,NaN
327,Slattery,NaN,0,0.0,NaN,NaN
485,Hoedt,NaN,0,0.0,NaN,NaN
535,N'Lundulu,NaN,0,0.0,NaN,NaN
548,Lewis,NaN,0,0.0,NaN,NaN
334,Trippier,NaN,0,0.0,NaN,NaN
339,Janssen,NaN,0,0.0,NaN,NaN
351,Amos,NaN,0,0.0,NaN,NaN
543,Whiteman,NaN,0,0.0,NaN,NaN
555,Vorm,NaN,0,0.0,NaN,NaN
558,Austin,NaN,0,0.0,NaN,NaN
360,Navarro,NaN,0,0.0,NaN,NaN
367,Dahlberg,NaN,0,0.0,NaN,NaN
372,Sema,NaN,0,0.0,NaN,NaN
513,Gomes,NaN,0,0.0,NaN,NaN
563,Dele-Bashiru,NaN,0,0.0,NaN,NaN
383,Reid,NaN,0,0.0,NaN,NaN
384,Johnson,NaN,0,0.0,NaN,NaN
385,Arnautovic,NaN,0,0.0,NaN,NaN
387,Xande Silva,NaN,0,0.0,NaN,NaN
398,Diangana,NaN,0,0.0,NaN,NaN
400,Obiang,NaN,0,0.0,NaN,NaN
412,Ruddy,NaN,0,0.0,NaN,NaN
413,Norris,NaN,0,0.0,NaN,NaN
418,Costa,NaN,0,0.0,NaN,NaN
419,Cavaleiro,NaN,0,0.0,NaN,NaN
559,Ashley-Seal,NaN,0,0.0,NaN,NaN
560,Perry,NaN,0,0.0,NaN,NaN
566,Otasowie,NaN,0,0.0,NaN,NaN
567,Cundle,NaN,0,0.0,NaN,NaN

In [15]:
# save data
filepath = '../data/data_week' + str(latest_gameweek) + str('.csv')
df.to_csv(filepath)

filepath = '../data/fbref/team_stats_week' + str(latest_gameweek) + '.csv'
teamStats.to_csv(filepath)

Below we check how well the total xG matches the total scored goals.

In [16]:
playerStats['xG'].sum()

458.00000000000017

In [17]:
df['goals_scored'].sum()

454

In [18]:
playerStats['xG'].sum()/df['goals_scored'].sum()

1.008810572687225