# Tableau and player form

Here we create a csv file that is used for making further Tableau visualizations.

In [1]:
# recent gameweek
gameweek = 17

In [2]:
# import basic libraries
import pandas as pd
import numpy as np

pd.set_option('max_columns',100)

In [3]:
# fetch player stats data
all_df = pd.read_csv('../data/fpl/data_week1.csv', index_col=0)
all_df['gameweek'] = 1
all_df['xPoints'] = all_df['adjusted points']

for week in range(2,gameweek+1):
    filepath = '../data/fpl/data_week' + str(week) + '.csv'
    df = pd.read_csv(filepath, index_col=0)
    df['gameweek'] = week
    column_name = 'xPoints week ' + str(week)
    df['xPoints'] = df[column_name]
    all_df = all_df.append(df,sort='False')

all_df.shape

(10453, 250)

In [4]:
# calculate player form
for i in [5,10,15,20]:
    gameweeks = np.arange(gameweek-i+1,gameweek+1)
    column_name = 'form ' + str(i)
    all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].count()
    
    #    all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / all_df.loc[(all_df['gameweek']==gameweek),'games played']
    #else:    
    #    all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / (all_df.loc[(all_df['gameweek']==gameweek),'games played'] - all_df.loc[(all_df['gameweek']==gameweek-i),'games played'] )
    
    # dirty fix in case there are inf results
    #all_df.loc[(all_df['gameweek']==gameweek) & np.isinf(all_df[column_name]), column_name] = np.nan

In [5]:
# top form players
all_df[all_df['gameweek']==gameweek][['web_name', 'games played','total_points', 'points_per_game','adjusted points','adjusted points per game',\
                                'form 5', 'form 10', 'form 15', 'form 20']].sort_values(by=['form 5'], ascending=False).head(20)

,web_name,games played,total_points,points_per_game,adjusted points,adjusted points per game,form 5,form 10,form 15,form 20
id,,,,,,,,,,
210,Tielemans,12.0,67,5.6,60.715233,5.059603,11.048812,6.666060,5.455780,5.189396
364,Davies,6.0,29,4.8,27.374669,4.562445,8.406429,5.708873,4.757394,4.757394
252,Stones,5.0,31,6.2,24.584234,4.916847,8.274923,4.761541,4.761541,4.761541
233,Salah,17.0,168,9.9,140.284738,8.252043,8.044810,8.287928,8.422143,8.353961
359,Son,13.0,81,6.2,69.784862,5.368066,7.806857,5.405635,5.596548,5.404476
240,Jota,16.0,87,5.4,96.691930,6.043246,7.708246,6.571562,6.157543,5.984299
237,Alexander-Arnold,15.0,119,7.9,108.125486,7.208366,7.699840,7.636812,7.386526,7.437904
265,Foden,11.0,61,5.5,67.015328,6.092303,7.452439,6.722282,5.907905,5.907905
255,Sterling,14.0,53,3.8,63.139964,4.509997,7.302904,5.942604,4.497379,4.338648
212,Maddison,16.0,69,4.3,63.054977,3.940936,7.261272,5.191709,4.076348,3.898990
16,Tierney,11.0,55,5.0,41.572425,3.779311,7.257346,6.292338,4.551981,4.243459
588,Emerson Royal,10.0,23,2.3,29.021115,2.902111,6.963273,3.827698,3.243994,3.243994
250,GÃ¼ndogan,12.0,62,5.2,68.754540,5.729545,6.674829,6.280176,6.308572,5.696924
63,Maupay,14.0,55,3.9,52.120000,3.722857,6.600000,3.614286,3.800000,3.757143
259,Laporte,13.0,56,4.3,59.239007,4.556847,6.527778,4.180492,4.399616,4.785750
123,Jorginho,15.0,61,4.1,57.904652,3.860310,6.483099,5.748406,4.233364,4.054357
370,ReguilÃ³n,13.0,62,4.8,59.000449,4.538496,6.317136,6.017235,4.941782,4.711097
261,Bernardo,16.0,91,5.7,77.740387,4.858774,6.182323,5.548029,4.945309,4.817780
234,Robertson,13.0,60,4.6,57.602021,4.430925,6.088240,4.984761,4.596234,4.596234
579,Ronaldo,13.0,67,5.2,66.882000,5.144769,6.075000,5.115778,5.218615,5.218615

In [6]:
# save data
filepath = '../data/fpl/all_data.csv'
all_df.to_csv(filepath)

filepath = '../data/fpl/data_week' + str(gameweek) + '.csv'
all_df[all_df['gameweek']==gameweek].to_csv(filepath)