# Tableau and player form

Here we create a csv file that is used for making further Tableau visualizations.

In [1]:
# recent gameweek
gameweek = 19

In [2]:
# import basic libraries
import pandas as pd
import numpy as np

pd.set_option('max_columns',100)

In [3]:
# fetch player stats data
all_df = pd.read_csv('../data/fpl/data_week1.csv', index_col=0)
all_df['gameweek'] = 1
all_df['xPoints'] = all_df['adjusted points']

for week in range(2,gameweek+1):
    filepath = '../data/fpl/data_week' + str(week) + '.csv'
    df = pd.read_csv(filepath, index_col=0)
    df['gameweek'] = week
    column_name = 'xPoints week ' + str(week)
    df['xPoints'] = df[column_name]
    all_df = all_df.append(df,sort='False')

all_df.shape

(11779, 268)

In [4]:
# calculate player form
for i in [5,10,15,20]:
    gameweeks = np.arange(gameweek-i+1,gameweek+1)
    column_name = 'form ' + str(i)
    all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].count()
    
    #    all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / all_df.loc[(all_df['gameweek']==gameweek),'games played']
    #else:    
    #    all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / (all_df.loc[(all_df['gameweek']==gameweek),'games played'] - all_df.loc[(all_df['gameweek']==gameweek-i),'games played'] )
    
    # dirty fix in case there are inf results
    #all_df.loc[(all_df['gameweek']==gameweek) & np.isinf(all_df[column_name]), column_name] = np.nan

In [5]:
# top form players
all_df[all_df['gameweek']==gameweek][['web_name', 'games played','total_points', 'points_per_game','adjusted points','adjusted points per game',\
                                'form 5', 'form 10', 'form 15', 'form 20']].sort_values(by=['form 5'], ascending=False).head(20)

,web_name,games played,total_points,points_per_game,adjusted points,adjusted points per game,form 5,form 10,form 15,form 20
id,,,,,,,,,,
255,Sterling,16.0,75,4.7,81.098293,5.068643,9.994089,7.123923,5.485799,4.937632
237,Alexander-Arnold,16.0,126,7.9,114.394848,7.149678,9.084502,7.890557,7.208578,7.469069
123,Jorginho,16.0,76,4.8,71.562594,4.472662,8.346156,7.057528,5.534611,4.704011
359,Son,15.0,96,6.4,82.192329,5.479489,7.171586,5.319779,5.696256,5.526670
362,Lucas Moura,15.0,54,3.6,54.992329,3.666155,6.820876,4.736590,4.225562,3.671204
591,Rond√≥n,11.0,21,1.9,25.000000,2.272727,6.800000,2.480000,2.400000,2.400000
254,Mahrez,15.0,68,4.5,65.563087,4.370872,6.744719,4.896897,4.095255,4.139106
363,Dele,9.0,23,2.6,27.287598,3.031955,6.623130,2.874377,2.454540,2.923155
213,Iheanacho,13.0,43,3.3,40.784000,3.137231,6.571000,3.785500,3.853778,3.137231
212,Maddison,17.0,79,4.6,70.878942,4.169350,6.548251,5.519504,4.502289,4.140483
210,Tielemans,13.0,69,5.3,62.650897,4.819300,6.541092,5.347487,5.783076,4.946625
16,Tierney,13.0,70,5.4,50.965042,3.920388,6.491498,6.491498,5.041939,4.412577
233,Salah,18.0,170,9.4,142.226301,7.901461,6.409438,6.852667,7.762620,8.026873
256,Cancelo,18.0,113,6.3,108.039818,6.002212,6.336854,6.521600,5.967098,6.207584
588,Emerson Royal,12.0,34,2.8,40.464853,3.372071,6.269222,4.955537,3.794035,3.794035
269,Cavani,6.0,17,2.8,19.800000,3.300000,6.200000,6.300000,3.760000,3.300000
357,Kane,15.0,45,3.0,63.771000,4.251400,6.166667,4.928571,4.830917,4.251400
259,Laporte,15.0,72,4.8,67.923348,4.528223,6.159153,4.693201,4.319859,4.824955
22,Saka,19.0,87,4.6,77.840342,4.096860,6.134174,4.792289,4.591245,4.178569
364,Davies,7.0,29,4.1,28.963414,4.137631,6.071053,4.906148,4.906148,4.205270

In [6]:
# save data
filepath = '../data/fpl/all_data.csv'
all_df.to_csv(filepath)

filepath = '../data/fpl/data_week' + str(gameweek) + '.csv'
all_df[all_df['gameweek']==gameweek].to_csv(filepath)