# Tableau and player form

Here we create a csv file that is used for making further Tableau visualizations.

In [1]:
# recent gameweek
gameweek = 5

In [2]:
# import basic libraries
import pandas as pd
import numpy as np

pd.set_option('max_columns',100)

In [3]:
# fetch player stats data
all_df = pd.read_csv('../data/fpl/data_week1.csv', index_col=0)
all_df['gameweek'] = 1
all_df['xPoints'] = all_df['adjusted points']

for week in range(2,gameweek+1):
    filepath = '../data/fpl/data_week' + str(week) + '.csv'
    df = pd.read_csv(filepath, index_col=0)
    df['gameweek'] = week
    column_name = 'xPoints week ' + str(week)
    df['xPoints'] = df[column_name]
    all_df = all_df.append(df,sort='False')

all_df.shape

(2903, 142)

In [6]:
# calculate player form
for i in [5,10,15,20]:
    gameweeks = np.arange(gameweek-i+1,gameweek+1)
    column_name = 'form ' + str(i)
    if gameweek-i <= 0:
        all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / all_df.loc[(all_df['gameweek']==gameweek),'games played']
    else:    
        all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / (all_df.loc[(all_df['gameweek']==gameweek),'games played'] - all_df.loc[(all_df['gameweek']==gameweek-i),'games played'] )
    
    # dirty fix in case there are inf results
    #all_df.loc[(all_df['gameweek']==gameweek) & np.isinf(all_df[column_name]), column_name] = np.nan

In [8]:
# top form players
all_df[all_df['gameweek']==gameweek][['web_name', 'games played','total_points', 'points_per_game','adjusted points','adjusted points per game',\
                                'form 5', 'form 10', 'form 15', 'form 20']].sort_values(by=['form 5'], ascending=False).head(20)

,web_name,games played,total_points,points_per_game,adjusted points,adjusted points per game,form 5,form 10,form 15,form 20
id,,,,,,,,,,
177,Calvert-Lewin,3.0,23,7.7,25.540000,8.513333,8.833333,8.833333,8.833333,8.833333
233,Salah,5.0,50,10.0,41.935975,8.387195,8.496923,8.496923,8.496923,8.496923
294,Darlow,1.0,8,8.0,8.417402,8.417402,8.443213,8.443213,8.443213,8.443213
237,Alexander-Arnold,4.0,34,8.5,32.911519,8.227880,8.250543,8.250543,8.250543,8.250543
230,Man√©,5.0,32,6.4,36.573975,7.314795,7.328523,7.328523,7.328523,7.328523
413,Antonio,4.0,39,9.8,28.004000,7.001000,7.001000,7.001000,7.001000,7.001000
259,Laporte,3.0,25,8.3,18.492979,6.164326,6.845338,6.845338,6.845338,6.845338
256,Cancelo,5.0,32,6.4,31.725965,6.345193,6.575685,6.575685,6.575685,6.575685
529,Lukaku,4.0,25,6.2,26.200000,6.550000,6.550000,6.550000,6.550000,6.550000
262,Dias,5.0,34,6.8,31.325965,6.265193,6.495685,6.495685,6.495685,6.495685
268,Torres,4.0,26,6.5,25.101993,6.275498,6.325634,6.325634,6.325634,6.325634
142,James,3.0,20,6.7,15.836453,5.278818,5.922849,5.922849,5.922849,5.922849
122,Alonso,5.0,38,7.6,27.028422,5.405684,5.889046,5.889046,5.889046,5.889046
229,van Dijk,5.0,33,6.6,27.982899,5.596580,5.651490,5.651490,5.651490,5.651490
419,Benrahma,5.0,39,7.8,28.006355,5.601271,5.629828,5.629828,5.629828,5.629828
144,Gallagher,4.0,28,7.0,21.695945,5.423986,5.556168,5.556168,5.556168,5.556168
270,de Gea,5.0,24,4.8,26.657422,5.331484,5.489537,5.489537,5.489537,5.489537
240,Jota,5.0,23,4.6,27.602975,5.520595,5.444457,5.444457,5.444457,5.444457
23,Gabriel,2.0,15,7.5,8.704554,4.352277,5.395559,5.395559,5.395559,5.395559
17,P√©p√©,4.0,13,3.2,20.923277,5.230819,5.374084,5.374084,5.374084,5.374084

In [9]:
# save data
filepath = '../data/fpl/all_data.csv'
all_df.to_csv(filepath)

filepath = '../data/fpl/data_week' + str(gameweek) + '.csv'
all_df[all_df['gameweek']==gameweek].to_csv(filepath)