# Tableau and player form

Here we create a csv file that is used for making further Tableau visualizations.

In [1]:
# recent gameweek
gameweek = 4

In [2]:
# import basic libraries
import pandas as pd
import numpy as np

pd.set_option('max_columns',100)

In [3]:
# fetch player stats data
all_df = pd.read_csv('../data/fpl/data_week1.csv', index_col=0)
all_df['gameweek'] = 1
all_df['xPoints'] = all_df['adjusted points']

for week in range(2,gameweek+1):
    filepath = '../data/fpl/data_week' + str(week) + '.csv'
    df = pd.read_csv(filepath, index_col=0)
    df['gameweek'] = week
    column_name = 'xPoints week ' + str(week)
    df['xPoints'] = df[column_name]
    all_df = all_df.append(df,sort='False')

all_df.shape

(2297, 133)

In [4]:
# calculate player form
for i in [5,10,15,20]:
    gameweeks = np.arange(gameweek-i+1,gameweek+1)
    column_name = 'form ' + str(i)
    all_df.loc[all_df['gameweek']==gameweek, column_name] = (all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / (all_df.loc[(all_df['gameweek']==gameweek),'games played'].round() - all_df.loc[(all_df['gameweek']==gameweek-i),'games played'].round()) )
    # dirty fix in case there are inf results
    all_df.loc[(all_df['gameweek']==gameweek) & np.isinf(all_df[column_name]), column_name] = np.nan

In [5]:
all_df.head()

,adjusted points,adjusted points per game,assists,assists_week1,assists_week2,assists_week3,assists_week4,bonus,bonus_week1,bonus_week2,bonus_week3,bonus_week4,bps,chance_of_playing_next_round,chance_of_playing_this_round,clean_sheet_points,clean_sheets,cleansheet_week1,cleansheet_week2,cleansheet_week3,cleansheet_week4,code,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,creativity,creativity_rank,creativity_rank_type,direct_freekicks_order,direct_freekicks_text,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,form 10,form 15,form 20,form 5,games played,gameweek,gameweek 10 prediction,gameweek 11 prediction,gameweek 12 prediction,gameweek 13 prediction,...,saves,second_name,selected_by_percent,special,squad_number,status,team,team_code,team_name,threat,threat_rank,threat_rank_type,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value,value form 10,value form 5,valuePoints metric,value_form,value_next10,value_season,web_name,xA,xA_points,xA_week1,xA_week2,xA_week3,xA_week4,xG,xG+xA,xG+xA per game,xGA_week1,xGA_week2,xGA_week3,xGA_week4,xG_points,xG_week1,xG_week2,xG_week3,xG_week4,xPoints,xPoints week 1,xPoints week 2,xPoints week 3,xPoints week 4,xPoints_next10,yellow_cards
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,2.090127,2.090127,0,0.0,NaN,NaN,NaN,0,0.0,NaN,NaN,NaN,11,NaN,NaN,1.090127,0,0.0,NaN,NaN,NaN,80201,NaN,NaN,0,0,0,0,0.0,427,45,NaN,NaN,0,1,2.6,3.6,1,Bernd,1.0,NaN,NaN,NaN,NaN,1.0,1,3.082758,2.972527,NaN,NaN,...,1,Leno,2.1,False,NaN,a,1,3,Arsenal,0.0,391,45,1,1996,1996,19699,19699,0.418025,NaN,NaN,0.934733,0.2,6.095886,0.2,Leno,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,1.3,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,2.090127,2.090127,NaN,NaN,NaN,30.479428,0
2,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,115918,NaN,NaN,0,0,0,0,0.0,268,11,NaN,NaN,0,1,1.0,2.0,0,Rúnar Alex,0.0,NaN,NaN,NaN,NaN,NaN,1,3.343534,3.292944,NaN,NaN,...,0,Rúnarsson,1.5,False,NaN,a,1,3,Arsenal,0.0,201,10,0,4578,4578,2251,2251,NaN,NaN,NaN,NaN,0.0,8.343311,0.0,Rúnarsson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.373245,0
3,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,47431,4.0,NaN,-1,1,-1,1,0.0,537,225,2.0,NaN,0,3,2.2,3.2,0,Willian,0.0,NaN,NaN,NaN,NaN,NaN,1,2.353971,2.503876,NaN,NaN,...,0,Borges Da Silva,0.3,False,NaN,a,1,3,Arsenal,0.0,531,222,0,614,614,5283,5283,NaN,NaN,NaN,NaN,0.0,3.867183,0.0,Willian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.749969,0
4,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,25.0,25.0,NaN,0,NaN,NaN,NaN,NaN,54694,NaN,NaN,-1,1,-1,1,0.0,553,73,NaN,NaN,0,4,0.8,1.0,0,Pierre-Emerick,0.0,NaN,NaN,NaN,NaN,NaN,1,2.530502,2.740044,NaN,NaN,...,0,Aubameyang,1.8,False,NaN,d,1,3,Arsenal,0.0,553,73,0,817,817,74611,74611,NaN,NaN,NaN,NaN,0.0,2.653677,0.0,Aubameyang,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.271403,0
5,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,58822,NaN,NaN,0,0,0,0,0.0,309,116,5.0,NaN,0,2,1.7,2.7,0,Cédric,0.0,NaN,NaN,NaN,NaN,NaN,1,2.840203,3.049745,NaN,NaN,...,0,Soares,0.2,False,NaN,a,1,3,Arsenal,0.0,247,90,0,453,453,2645,2645,NaN,NaN,NaN,NaN,0.0,6.374511,0.0,Cédric,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.685298,0

In [6]:
# top form players
all_df[all_df['gameweek']==gameweek][['web_name', 'games played','total_points', 'points_per_game','adjusted points','adjusted points per game',\
                                'form 5', 'form 10', 'form 15', 'form 20']].sort_values(by=['form 5'], ascending=False).head(20)

,web_name,games played,total_points,points_per_game,adjusted points,adjusted points per game,form 5,form 10,form 15,form 20
id,,,,,,,,,,
1,Leno,3.0,4,1.3,5.363298,1.787766,NaN,NaN,NaN,NaN
2,Rúnarsson,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Willian,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,Aubameyang,3.0,11,3.7,12.500000,4.166667,NaN,NaN,NaN,NaN
5,Cédric,3.0,1,0.3,2.663298,0.887766,NaN,NaN,NaN,NaN
6,Lacazette,1.0,1,1.0,1.000000,1.000000,NaN,NaN,NaN,NaN
7,Xhaka,3.0,2,0.7,3.140824,1.046941,NaN,NaN,NaN,NaN
8,Marí,2.0,1,0.5,4.008865,2.004433,NaN,NaN,NaN,NaN
9,Bellerín,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
10,Chambers,2.0,1,0.5,2.808865,1.404433,NaN,NaN,NaN,NaN
11,Kolasinac,1.0,-1,-1.0,-0.545567,-0.545567,NaN,NaN,NaN,NaN
12,Elneny,1.0,1,1.0,1.113608,1.113608,NaN,NaN,NaN,NaN
13,Maitland-Niles,2.0,4,2.0,3.827216,1.913608,NaN,NaN,NaN,NaN
14,Holding,2.0,0,0.0,1.508865,0.754433,NaN,NaN,NaN,NaN
15,Partey,1.0,0,0.0,0.613608,0.613608,NaN,NaN,NaN,NaN
16,Tierney,4.0,9,2.2,10.417730,2.604433,NaN,NaN,NaN,NaN
17,Pépé,3.0,10,3.3,16.111824,5.370608,NaN,NaN,NaN,NaN
18,Torreira,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
20,Nketiah,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
21,Smith Rowe,4.0,7,1.8,10.954433,2.738608,NaN,NaN,NaN,NaN

In [7]:
# save data
filepath = '../data/fpl/all_data.csv'
all_df.to_csv(filepath)

filepath = '../data/fpl/data_week' + str(gameweek) + '.csv'
all_df[all_df['gameweek']==gameweek].to_csv(filepath)