# Tableau and player form

Here we create a csv file that is used for making further Tableau visualizations.

In [1]:
# recent gameweek
gameweek = 9

In [2]:
# import basic libraries
import pandas as pd
import numpy as np

pd.set_option('max_columns',100)

In [3]:
# fetch player stats data
all_df = pd.read_csv('../data/fpl/data_week1.csv', index_col=0)
all_df['gameweek'] = 1
all_df['xPoints'] = all_df['adjusted points']

for week in range(2,gameweek+1):
    filepath = '../data/fpl/data_week' + str(week) + '.csv'
    df = pd.read_csv(filepath, index_col=0)
    df['gameweek'] = week
    column_name = 'xPoints week ' + str(week)
    df['xPoints'] = df[column_name]
    all_df = all_df.append(df,sort='False')

all_df.shape

(5362, 178)

In [4]:
# calculate player form
for i in [5,10,15,20]:
    gameweeks = np.arange(gameweek-i+1,gameweek+1)
    column_name = 'form ' + str(i)
    all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].count()
    
    #    all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / all_df.loc[(all_df['gameweek']==gameweek),'games played']
    #else:    
    #    all_df.loc[all_df['gameweek']==gameweek, column_name] = all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / (all_df.loc[(all_df['gameweek']==gameweek),'games played'] - all_df.loc[(all_df['gameweek']==gameweek-i),'games played'] )
    
    # dirty fix in case there are inf results
    #all_df.loc[(all_df['gameweek']==gameweek) & np.isinf(all_df[column_name]), column_name] = np.nan

In [5]:
# top form players
all_df[all_df['gameweek']==gameweek][['web_name', 'games played','total_points', 'points_per_game','adjusted points','adjusted points per game',\
                                'form 5', 'form 10', 'form 15', 'form 20']].sort_values(by=['form 5'], ascending=False).head(20)

,web_name,games played,total_points,points_per_game,adjusted points,adjusted points per game,form 5,form 10,form 15,form 20
id,,,,,,,,,,
233,Salah,9.0,107,11.9,82.076000,9.119556,9.400534,9.201079,9.201079,9.201079
250,GÃ¼ndogan,6.0,29,4.8,33.546589,5.591098,6.808459,5.674742,5.674742,5.674742
189,Bamford,5.0,21,4.2,26.342000,5.268400,6.671000,5.268400,5.268400,5.268400
468,King,7.0,36,5.1,32.113000,4.587571,6.628250,4.587571,4.587571,4.587571
135,Chilwell,3.0,35,11.7,17.963499,5.987833,6.532753,6.532753,6.532753,6.532753
265,Foden,5.0,35,7.0,32.797491,6.559498,6.413035,6.413035,6.413035,6.413035
240,Jota,8.0,43,5.4,45.275444,5.659431,6.245785,5.599857,5.599857,5.599857
205,Vardy,9.0,57,6.3,48.071000,5.341222,6.240000,5.341222,5.341222,5.341222
359,Son,8.0,53,6.6,44.998163,5.624770,6.223324,5.707700,5.707700,5.707700
210,Tielemans,9.0,47,5.2,42.541649,4.726850,6.131546,4.768465,4.768465,4.768465
84,Janelt,6.0,23,3.8,22.982887,3.830481,6.093652,3.921131,3.921131,3.921131
122,Alonso,6.0,39,6.5,29.697999,4.949666,5.844038,5.295994,5.295994,5.295994
527,Chalobah,6.0,44,7.3,26.726999,4.454500,5.832753,4.725675,4.725675,4.725675
413,Antonio,8.0,57,7.1,51.004000,6.375500,5.750000,6.375500,6.375500,6.375500
138,Mount,7.0,41,5.9,37.886708,5.412387,5.693959,5.509526,5.509526,5.509526
30,MartÃ­nez,8.0,41,5.1,36.061269,4.507659,5.583677,4.664285,4.664285,4.664285
228,Firmino,7.0,33,4.7,30.771000,4.395857,5.567750,4.395857,4.395857,4.395857
336,Redmond,8.0,26,3.2,33.736818,4.217102,5.559159,4.304415,4.304415,4.304415
127,RÃ¼diger,8.0,45,5.6,31.573665,3.946708,5.398453,4.460213,4.460213,4.460213
119,Azpilicueta,8.0,42,5.2,34.715665,4.339458,5.309496,4.400544,4.400544,4.400544

In [6]:
# save data
filepath = '../data/fpl/all_data.csv'
all_df.to_csv(filepath)

filepath = '../data/fpl/data_week' + str(gameweek) + '.csv'
all_df[all_df['gameweek']==gameweek].to_csv(filepath)