# Tableau and player form

Here we create a csv file that is used for making further Tableau visualizations.

In [1]:
# recent gameweek
gameweek = 1

In [2]:
# import basic libraries
import pandas as pd
import numpy as np

pd.set_option('max_columns',100)

In [3]:
# fetch player stats data
all_df = pd.read_csv('../data/fpl/data_week1.csv', index_col=0)
all_df['gameweek'] = 1
all_df['xPoints'] = all_df['adjusted points']

for week in range(2,gameweek+1):
    filepath = '../data/fpl/data_week' + str(week) + '.csv'
    df = pd.read_csv(filepath, index_col=0)
    df['gameweek'] = week
    column_name = 'xPoints week ' + str(week)
    df['xPoints'] = df[column_name]
    all_df = all_df.append(df,sort='False')

all_df.shape

(555, 85)

In [4]:
# calculate player form
for i in [5,10,15,20]:
    gameweeks = np.arange(gameweek-i+1,gameweek+1)
    column_name = 'form ' + str(i)
    all_df.loc[all_df['gameweek']==gameweek, column_name] = (all_df[all_df['gameweek'].isin(gameweeks)].groupby(['id'])['xPoints'].sum() / (all_df.loc[(all_df['gameweek']==gameweek),'games played'].round() - all_df.loc[(all_df['gameweek']==gameweek-i),'games played'].round()) )
    # dirty fix in case there are inf results
    all_df.loc[(all_df['gameweek']==gameweek) & np.isinf(all_df[column_name]), column_name] = np.nan

In [6]:
all_df.head()

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,in_dreamteam,news,news_added,now_cost,photo,points_per_game,second_name,selected_by_percent,special,squad_number,status,team,team_code,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text,team_name,games played,adjusted points,xG,xG_points,xG_week1,goals_week1,xPoints week 1,bonus_week1,clean_sheet_points,xGA_week1,cleansheet_week1,xA,xA_points,xA_week1,assists_week1,adjusted points per game,gameweek,xPoints,form 5,form 10,form 15,form 20
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,80201,0,0,0,0,0,1,2.6,3.6,1,Bernd,1.0,False,NaN,NaN,50,80201.jpg,1.0,Leno,2.1,False,NaN,a,1,3,1,1996,1996,19699,19699,0.2,0.2,Leno,90,0,0,0,2,0,0,0,0,0,1,0,11,11.8,0.0,0.0,1.2,150,17,427,45,391,45,217,17,NaN,NaN,NaN,NaN,NaN,NaN,Arsenal,1.0,2.090127,0.0,0.0,0.0,0.0,2.090127,0.0,1.090127,1.3,0.0,0.0,0.0,0.0,0.0,2.090127,1,2.090127,NaN,NaN,NaN,NaN
2,NaN,NaN,115918,0,0,0,0,0,1,1.0,2.0,0,Rúnar Alex,0.0,False,NaN,NaN,40,115918.jpg,0.0,Rúnarsson,1.5,False,NaN,a,1,3,0,4578,4578,2251,2251,0.0,0.0,Rúnarsson,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,277,30,268,11,201,10,290,30,NaN,NaN,NaN,NaN,NaN,NaN,Arsenal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,47431,-1,1,-1,1,0,3,2.2,3.2,0,Willian,0.0,False,NaN,NaN,64,47431.jpg,0.0,Borges Da Silva,0.3,False,NaN,a,1,3,0,614,614,5283,5283,0.0,0.0,Willian,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,534,224,537,225,531,222,537,225,4.0,NaN,2.0,NaN,NaN,NaN,Arsenal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
4,25.0,25.0,54694,-1,1,-1,1,0,4,0.8,1.0,0,Pierre-Emerick,0.0,False,Illness - 25% chance of playing,2021-08-13T14:30:14.477664Z,99,54694.jpg,0.0,Aubameyang,1.8,False,NaN,d,1,3,0,817,817,74611,74611,0.0,0.0,Aubameyang,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,553,73,553,73,553,73,553,73,NaN,NaN,NaN,NaN,1.0,NaN,Arsenal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,58822,0,0,0,0,0,2,1.7,2.7,0,Cédric,0.0,False,NaN,NaN,45,58822.jpg,0.0,Soares,0.2,False,NaN,a,1,3,0,453,453,2645,2645,0.0,0.0,Cédric,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,315,119,309,116,247,90,328,120,NaN,NaN,5.0,NaN,NaN,NaN,Arsenal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN

In [5]:
# top form players
all_df[all_df['gameweek']==gameweek][['web_name', 'games played','total_points', 'points_per_game','adjusted points','adjusted points per game',\
                                'form 5', 'form 10', 'form 15', 'form 20']].sort_values(by=['form 5'], ascending=False).head(20)

,web_name,games played,total_points,points_per_game,adjusted points,adjusted points per game,form 5,form 10,form 15,form 20
id,,,,,,,,,,
1,Leno,1.0,1,1.0,2.090127,2.090127,NaN,NaN,NaN,NaN
2,Rúnarsson,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Willian,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,Aubameyang,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
5,Cédric,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
6,Lacazette,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7,Xhaka,1.0,2,2.0,3.072532,3.072532,NaN,NaN,NaN,NaN
8,Marí,1.0,1,1.0,3.890127,3.890127,NaN,NaN,NaN,NaN
9,Bellerín,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
10,Chambers,1.0,1,1.0,2.990127,2.990127,NaN,NaN,NaN,NaN
11,Kolasinac,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
12,Elneny,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
13,Maitland-Niles,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
14,Holding,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
15,Partey,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
16,Tierney,1.0,1,1.0,4.490127,4.490127,NaN,NaN,NaN,NaN
17,Pépé,1.0,2,2.0,4.372532,4.372532,NaN,NaN,NaN,NaN
18,Torreira,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
20,Nketiah,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
21,Smith Rowe,1.0,2,2.0,3.972532,3.972532,NaN,NaN,NaN,NaN

In [7]:
# save data
filepath = '../data/fpl/all_data.csv'
all_df.to_csv(filepath)

filepath = '../data/fpl/data_week' + str(gameweek) + '.csv'
all_df[all_df['gameweek']==gameweek].to_csv(filepath)