In [1]:
# give the number of the latest FPL round
latest_gameweek = 1

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
import json
import requests
import xgboost
import pickle

# allow more data columns to be shown than by default
pd.set_option('max_columns',500)

In [3]:
filepath = Path('../data/fpl/data_week' + str(latest_gameweek) + str('.csv'))
players = pd.read_csv(filepath, index_col=0)
players

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,in_dreamteam,news,news_added,now_cost,photo,points_per_game,second_name,selected_by_percent,special,squad_number,status,team,team_code,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text,team_name,games played,adjusted points,xG,xG_points,xG_week1,goals_week1,xPoints week 1,bonus_week1,clean_sheet_points,xGA_week1,cleansheet_week1,xA,xA_points,xA_week1,assists_week1,adjusted points per game,gameweek,xPoints,form 5,form 10,form 15,form 20
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,80201,0,0,0,0,0,1,2.6,3.6,1,Bernd,1.0,False,NaN,NaN,50,80201.jpg,1.0,Leno,2.1,False,NaN,a,1,3,1,1996,1996,19699,19699,0.2,0.2,Leno,90,0,0,0,2,0,0,0,0,0,1,0,11,11.8,0.0,0.0,1.2,150,17,427,45,391,45,217,17,NaN,NaN,NaN,NaN,NaN,NaN,Arsenal,1.0,2.090127,0.0,0.0,0.0,0.0,2.090127,0.0,1.090127,1.3,0.0,0.0,0.0,0.0,0.0,2.090127,1,2.090127,NaN,NaN,NaN,NaN
2,NaN,NaN,115918,0,0,0,0,0,1,1.0,2.0,0,Rúnar Alex,0.0,False,NaN,NaN,40,115918.jpg,0.0,Rúnarsson,1.5,False,NaN,a,1,3,0,4578,4578,2251,2251,0.0,0.0,Rúnarsson,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,277,30,268,11,201,10,290,30,NaN,NaN,NaN,NaN,NaN,NaN,Arsenal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,47431,-1,1,-1,1,0,3,2.2,3.2,0,Willian,0.0,False,NaN,NaN,64,47431.jpg,0.0,Borges Da Silva,0.3,False,NaN,a,1,3,0,614,614,5283,5283,0.0,0.0,Willian,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,534,224,537,225,531,222,537,225,4.0,NaN,2.0,NaN,NaN,NaN,Arsenal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
4,25.0,25.0,54694,-1,1,-1,1,0,4,0.8,1.0,0,Pierre-Emerick,0.0,False,Illness - 25% chance of playing,2021-08-13T14:30:14.477664Z,99,54694.jpg,0.0,Aubameyang,1.8,False,NaN,d,1,3,0,817,817,74611,74611,0.0,0.0,Aubameyang,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,553,73,553,73,553,73,553,73,NaN,NaN,NaN,NaN,1.0,NaN,Arsenal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,58822,0,0,0,0,0,2,1.7,2.7,0,Cédric,0.0,False,NaN,NaN,45,58822.jpg,0.0,Soares,0.2,False,NaN,a,1,3,0,453,453,2645,2645,0.0,0.0,Cédric,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,315,119,309,116,247,90,328,120,NaN,NaN,5.0,NaN,NaN,NaN,Arsenal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,NaN,NaN,149065,0,0,0,0,0,1,2.1,2.1,3,José,3.0,False,NaN,NaN,50,149065.jpg,3.0,Malheiro de Sá,0.4,False,NaN,a,20,39,3,1274,1274,1666,1666,0.6,0.6,Sá,90,0,0,0,1,0,0,0,0,0,4,0,17,26.2,0.0,0.0,2.6,60,8,444,49,412,49,152,10,NaN,NaN,NaN,NaN,NaN,NaN,Wolves,1.0,4.797316,0.0,0.0,0.0,0.0,4.797316,0.0,1.797316,0.8,0.0,0.0,0.0,0.0,0.0,4.797316,1,4.797316,NaN,NaN,NaN,NaN
523,0.0,NaN,209353,0,0,0,0,0,4,0.0,0.8,0,Patrick,0.0,False,Season long loan to Empoli,2021-08-15T12:06:51.809579Z,50,209353.jpg,0.0,Cutrone,0.2,False,NaN,u,20,39,0,1047,1047,5271,5271,0.0,0.0,Cutrone,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,459,45,463,51,437,43,468,51,NaN,NaN,NaN,NaN,NaN,NaN,Wolves,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
547,NaN,NaN,245923,0,0,0,0,0,3,0.5,0.5,0,Luke,0.0,False,NaN,NaN,45,245923.jpg,0.0,Cundle,0.0,False,NaN,a,20,39,0,448,448,137,137,0.0,0.0,Cundle,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,400,152,398,157,356,139,410,156,NaN,NaN,NaN,NaN,NaN,NaN,Wolves,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
548,NaN,NaN,461026,0,0,0,0,0,3,0.5,0.5,0,Chem,0.0,False,NaN,NaN,45,461026.jpg,0.0,Campbell,0.1,False,NaN,a,20,39,0,2741,2741,665,665,0.0,0.0,Campbell,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,411,157,408,162,367,145,420,161,NaN,NaN,NaN,NaN,NaN,NaN,Wolves,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
549,NaN,NaN,481626,0,0,0,0,0,2,0.5,0.5,0,Christian,0.0,False,NaN,NaN,40,481626.jpg,0.0,Marques,0.1,False,NaN,a,20,39,0,4109,4109,655,655,0.0,0.0,Marques,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,298,112,289,109,224,80,311,113,NaN,NaN,NaN,NaN,NaN,NaN,Wolves,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN

In [4]:
teams = ['Arsenal', 'Aston Villa', 'Brentford', 'Brighton', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton',
        'Leicester City', 'Leeds United', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle Utd', 
        'Norwich City', 'Southampton', 'Tottenham', 'Watford', 'West Ham', 'Wolves']

In [5]:
# get FPL fixtures data
fpl_fixtures_data = json.loads(requests.get('https://fantasy.premierleague.com/api/fixtures/').text)
fpl_fixtures = pd.DataFrame(fpl_fixtures_data)
fpl_fixtures['home team'] = [teams[i] for i in fpl_fixtures['team_h']-1]
fpl_fixtures['away team'] = [teams[i] for i in fpl_fixtures['team_a']-1]
filepath = Path('../data/fpl/fixtures.csv')
fpl_fixtures.to_csv(filepath)
fpl_fixtures

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,team_a_score,team_h,team_h_score,stats,team_h_difficulty,team_a_difficulty,pulse_id,home team,away team
0,2210271,1,True,True,1,2021-08-13T19:00:00Z,90,False,True,1,0.0,3,2.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",3,2,66342,Brentford,Arsenal
1,2210276,1,True,True,6,2021-08-14T11:30:00Z,90,False,True,10,1.0,13,5.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",3,4,66347,Manchester Utd,Leeds United
2,2210272,1,True,True,2,2021-08-14T14:00:00Z,90,False,True,4,2.0,5,1.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",2,2,66343,Burnley,Brighton
3,2210273,1,True,True,3,2021-08-14T14:00:00Z,90,False,True,7,0.0,6,3.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",2,4,66344,Chelsea,Crystal Palace
4,2210274,1,True,True,4,2021-08-14T14:00:00Z,90,False,True,16,1.0,8,3.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",2,3,66345,Everton,Southampton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2210646,38,False,False,376,2022-05-22T15:00:00Z,0,False,False,13,NaN,7,NaN,[],4,2,66717,Crystal Palace,Manchester Utd
376,2210647,38,False,False,377,2022-05-22T15:00:00Z,0,False,False,16,NaN,9,NaN,[],2,3,66718,Leicester City,Southampton
377,2210648,38,False,False,378,2022-05-22T15:00:00Z,0,False,False,20,NaN,11,NaN,[],2,4,66719,Liverpool,Wolves
378,2210649,38,False,False,379,2022-05-22T15:00:00Z,0,False,False,2,NaN,12,NaN,[],2,5,66720,Manchester City,Aston Villa
379,2210650,38,False,False,380,2022-05-22T15:00:00Z,0,False,False,17,NaN,15,NaN,[],3,2,66721,Norwich City,Tottenham

In [6]:
filepath = Path(f'../data/fbref/team_stats_week{latest_gameweek}.csv')
team_stats = pd.read_csv(filepath, index_col=0)
team_stats

,Rk,MP,W,D,L,GF,GA,GD,Pts,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper,Notes,xG per game,xGA per game,probability no goals allowed
Squad,,,,,,,,,,,,,,,,,,,,,
Manchester Utd,1,1,1,0,0,5,1,4,3,1.5,0.6,0.8,0.84,W,72732.0,Bruno Fernandes - 3,David de Gea,NaN,1.5,0.6,0.548812
Chelsea,2,1,1,0,0,3,0,3,3,0.9,0.3,0.6,0.57,W,38965.0,"Trevoh Chalobah, Marcos Alonso... - 1",Edouard Mendy,NaN,0.9,0.3,0.740818
Liverpool,3,1,1,0,0,3,0,3,3,2.0,1.4,0.6,0.61,W,NaN,"Diogo Jota, Roberto Firmino... - 1",Alisson,NaN,2.0,1.4,0.246597
West Ham,4,1,1,0,0,4,2,2,3,2.2,1.4,0.8,0.79,W,NaN,"Aaron Cresswell, Tomáš Souček... - 1",Łukasz Fabiański,NaN,2.2,1.4,0.246597
Everton,5,1,1,0,0,3,1,2,3,2.4,0.7,1.7,1.69,W,NaN,"Abdoulaye Doucouré, Richarlison... - 1",Jordan Pickford,NaN,2.4,0.7,0.496585
Brentford,6,1,1,0,0,2,0,2,3,1.3,1.5,-0.2,-0.21,W,16479.0,"Sergi Canós, Christian Nørgaard - 1",David Raya,NaN,1.3,1.5,0.223130
Watford,7,1,1,0,0,3,2,1,3,1.2,1.1,0.1,0.13,W,20051.0,"Ismaila Sarr, Cucho... - 1",Daniel Bachmann,NaN,1.2,1.1,0.332871
Brighton,8,1,1,0,0,2,1,1,3,1.2,1.1,0.1,0.08,W,NaN,"Alexis Mac Allister, Neal Maupay - 1",Robert Sánchez,NaN,1.2,1.1,0.332871
Leicester City,9,1,1,0,0,1,0,1,3,0.8,1.1,-0.3,-0.33,W,31983.0,Jamie Vardy - 1,Kasper Schmeichel,NaN,0.8,1.1,0.332871
Tottenham,10,1,1,0,0,1,0,1,3,1.3,1.9,-0.6,-0.61,W,58262.0,Son Heung-min - 1,Hugo Lloris,NaN,1.3,1.9,0.149569
Aston Villa,11,1,0,0,1,2,3,-1,0,1.1,1.2,-0.1,-0.13,L,NaN,"John McGinn, Danny Ings - 1",Emiliano Martínez,NaN,1.1,1.2,0.301194
Burnley,12,1,0,0,1,1,2,-1,0,1.1,1.2,-0.1,-0.08,L,NaN,James Tarkowski - 1,Nick Pope,NaN,1.1,1.2,0.301194
Manchester City,13,1,0,0,1,0,1,-1,0,1.9,1.3,0.6,0.61,L,NaN,NaN,Ederson,NaN,1.9,1.3,0.272532
Wolves,14,1,0,0,1,0,1,-1,0,1.1,0.8,0.3,0.33,L,NaN,NaN,José Sá,NaN,1.1,0.8,0.449329
Newcastle Utd,15,1,0,0,1,2,4,-2,0,1.4,2.2,-0.8,-0.79,L,50673.0,"Jacob Murphy, Callum Wilson - 1",Freddie Woodman,NaN,1.4,2.2,0.110803
Southampton,16,1,0,0,1,1,3,-2,0,0.7,2.4,-1.7,-1.69,L,NaN,Adam Armstrong - 1,Alex McCarthy,NaN,0.7,2.4,0.090718
Arsenal,17,1,0,0,1,0,2,-2,0,1.5,1.3,0.2,0.21,L,NaN,NaN,Bernd Leno,NaN,1.5,1.3,0.272532
Crystal Palace,18,1,0,0,1,0,3,-3,0,0.3,0.9,-0.6,-0.57,L,NaN,NaN,Vicente Guaita,NaN,0.3,0.9,0.406570
Norwich City,19,1,0,0,1,0,3,-3,0,1.4,2.0,-0.6,-0.61,L,27023.0,NaN,Tim Krul,NaN,1.4,2.0,0.135335
Leeds United,20,1,0,0,1,1,5,-4,0,0.6,1.5,-0.8,-0.84,L,NaN,Luke Ayling - 1,Illan Meslier,NaN,0.6,1.5,0.223130

In [7]:
# upload model for making predictions
path = Path('../models/xgboost_predictor_v4_weightsAndBonus.pickle')
with open(path,'rb') as f:
    model = pickle.load(f)

In [8]:
# pre-allocate for model input
predictions = pd.DataFrame(index=players.index.copy())
input_columns = ['goalkeeper', 'defender', 'midfielder',
       'forward', 'xG90', 'xA90', 'xGA90', 'bonus', 'xPoints90',
       'games played', 'form 5', 'games_form5', 'form 10', 'games form10',
       'team xG per 90', 'team xGA per 90', 'home', 'opponent xG per 90',
       'opponent xGA per 90']
predictions[input_columns] = np.nan
predictions

,goalkeeper,defender,midfielder,forward,xG90,xA90,xGA90,bonus,xPoints90,games played,form 5,games_form5,form 10,games form10,team xG per 90,team xGA per 90,home,opponent xG per 90,opponent xGA per 90
id,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# run predictions for all players for a given time horizon
# assumes one match per gameweek at most currently
horizon = 10
output_columns = [f'gameweek {i} prediction' for i in range(latest_gameweek+1,latest_gameweek+horizon+1)]
xGA_columns = [column for column in players.columns if 'xGA_week' in column]
xPoints_columns = [column for column in players.columns if 'xPoints week' in column]

for player_ix in players.index:
    
    # collect base info
    if players.loc[player_ix,'element_type'] == 1:
        predictions.loc[player_ix,'goalkeeper'] = 1
    elif players.loc[player_ix, 'element_type'] == 2:
        predictions.loc[player_ix,'defender'] = 1
    elif players.loc[player_ix, 'element_type'] == 3:
        predictions.loc[player_ix,'midfielder'] = 1
    elif players.loc[player_ix, 'element_type'] == 4:
        predictions.loc[player_ix,'forward'] = 1

    if players.loc[player_ix,'games played'] > 0:
        predictions.loc[player_ix, 'xG90'] = players.loc[player_ix,'xG'] / players.loc[player_ix,'games played']
        predictions.loc[player_ix, 'xA90'] = players.loc[player_ix,'xA'] / players.loc[player_ix,'games played']
        predictions.loc[player_ix, 'xGA90'] = players.loc[player_ix,xGA_columns].sum() / \
                                          players.loc[player_ix,'games played']                                        
        predictions.loc[player_ix, 'bonus'] = players.loc[player_ix, 'bps']
        predictions.loc[player_ix, 'xPoints90'] = players.loc[player_ix,'adjusted points per game']
        predictions.loc[player_ix, 'games played'] = players.loc[player_ix, 'games played']
        
        form5_points = players.loc[player_ix, xPoints_columns[-5:]].sum()
        form5_games = players.loc[player_ix, xPoints_columns[-5:]].notnull().sum()
        predictions.loc[player_ix, 'form 5'] = form5_points
        predictions.loc[player_ix, 'games_form5'] = form5_games
        
        form10_points = players.loc[player_ix, xPoints_columns[-10:]].sum()
        form10_games = players.loc[player_ix, xPoints_columns[-10:]].notnull().sum()
        predictions.loc[player_ix, 'form 10'] = form10_points
        predictions.loc[player_ix, 'games form10'] = form10_games
    else:
        predictions.loc[player_ix, 'xG90'] = 0
        predictions.loc[player_ix, 'xA90'] = 0
        predictions.loc[player_ix, 'xGA90'] = 0                       
        predictions.loc[player_ix, 'bonus'] = 0
        predictions.loc[player_ix, 'xPoints90'] = 0
        predictions.loc[player_ix, 'games played'] = 0
        predictions.loc[player_ix, 'form 5'] = 0
        predictions.loc[player_ix, 'games_form5'] = 0
        predictions.loc[player_ix, 'form 10'] = 0
        predictions.loc[player_ix, 'games form10'] = 0
        
    team = players.loc[player_ix, 'team_name']
    # team xG per 90 
    team_xG90 = team_stats.loc[team,'xG'] / team_stats.loc[team,'MP']
    predictions.loc[player_ix, 'team xG per 90'] = team_xG90
    # team xGA per 90 
    team_xGA90 = team_stats.loc[team,'xGA'] / team_stats.loc[team,'MP']
    predictions.loc[player_ix, 'team xGA per 90'] = team_xGA90
    
    for gameweek in range(1,horizon+1):

        # home game
        if fpl_fixtures[(fpl_fixtures['event']==gameweek) & (fpl_fixtures['home team']==team)].shape[0]==1:
            predictions.loc[player_ix, 'home'] = 1
            opponent = fpl_fixtures.loc[(fpl_fixtures['event']==gameweek) & (fpl_fixtures['home team']==team),\
                                        'away team'].values[0]
            # opponent xG per 90
            opponent_xG90 = team_stats.loc[opponent, 'xG'] / team_stats.loc[opponent,'MP']
            predictions.loc[player_ix, 'opponent xG per 90'] = opponent_xG90
            # opponent xGA per 90
            opponent_xGA90 = team_stats.loc[opponent, 'xGA'] / team_stats.loc[opponent,'MP']
            predictions.loc[player_ix, 'opponent xGA per 90'] = opponent_xGA90
            
            # predict player's points
            input_data = predictions.loc[player_ix:player_ix, input_columns]
            input_data = xgboost.DMatrix(input_data)
            prediction = model.predict(input_data)
            players.loc[player_ix, output_columns[gameweek-1]] = prediction
            
        # away game
        elif fpl_fixtures[(fpl_fixtures['event']==gameweek) & (fpl_fixtures['away team']==team)].shape[0]==1:
            predictions.loc[player_ix, 'home'] = 0
            opponent = fpl_fixtures.loc[(fpl_fixtures['event']==gameweek) & (fpl_fixtures['away team']==team),\
                                        'home team'].values[0]
            # opponent xG per 90
            opponent_xG90 = team_stats.loc[opponent, 'xG'] / team_stats.loc[opponent,'MP']
            predictions.loc[player_ix, 'opponent xG per 90'] = opponent_xG90
            # opponent xGA per 90
            opponent_xGA90 = team_stats.loc[opponent, 'xGA'] / team_stats.loc[opponent,'MP']
            predictions.loc[player_ix, 'opponent xGA per 90'] = opponent_xGA90
            
            # predict player's points
            input_data = predictions.loc[player_ix:player_ix, input_columns]
            input_data = xgboost.DMatrix(input_data)
            prediction = model.predict(input_data)
            players.loc[player_ix, output_columns[gameweek-1]] = prediction

In [17]:
players['xPoints_next10'] = players[output_columns].sum(axis=1)

In [18]:
players

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,in_dreamteam,news,news_added,now_cost,photo,points_per_game,second_name,selected_by_percent,special,squad_number,status,team,team_code,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text,team_name,games played,adjusted points,xG,xG_points,xG_week1,goals_week1,xPoints week 1,bonus_week1,clean_sheet_points,xGA_week1,cleansheet_week1,xA,xA_points,xA_week1,assists_week1,adjusted points per game,gameweek,xPoints,form 5,form 10,form 15,form 20,gameweek 2 prediction,gameweek 3 prediction,gameweek 4 prediction,gameweek 5 prediction,gameweek 6 prediction,gameweek 7 prediction,gameweek 8 prediction,gameweek 9 prediction,gameweek 10 prediction,gameweek 11 prediction,xPoints_next10
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,80201,0,0,0,0,0,1,2.6,3.6,1,Bernd,1.0,False,NaN,NaN,50,80201.jpg,1.0,Leno,2.1,False,NaN,a,1,3,1,1996,1996,19699,19699,0.2,0.2,Leno,90,0,0,0,2,0,0,0,0,0,1,0,11,11.8,0.0,0.0,1.2,150,17,427,45,391,45,217,17,NaN,NaN,NaN,NaN,NaN,NaN,Arsenal,1.0,2.090127,0.0,0.0,0.0,0.0,2.090127,0.0,1.090127,1.3,0.0,0.0,0.0,0.0,0.0,2.090127,1,2.090127,NaN,NaN,NaN,NaN,3.143764,3.105668,2.457404,3.307485,3.082758,3.479783,2.775793,3.071486,3.082758,2.972527,30.479428
2,NaN,NaN,115918,0,0,0,0,0,1,1.0,2.0,0,Rúnar Alex,0.0,False,NaN,NaN,40,115918.jpg,0.0,Rúnarsson,1.5,False,NaN,a,1,3,0,4578,4578,2251,2251,0.0,0.0,Rúnarsson,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,277,30,268,11,201,10,290,30,NaN,NaN,NaN,NaN,NaN,NaN,Arsenal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,3.423262,3.366444,2.794477,3.599014,3.403175,3.721921,3.096210,3.332263,3.343534,3.292944,33.373245
3,NaN,NaN,47431,-1,1,-1,1,0,3,2.2,3.2,0,Willian,0.0,False,NaN,NaN,64,47431.jpg,0.0,Borges Da Silva,0.3,False,NaN,a,1,3,0,614,614,5283,5283,0.0,0.0,Willian,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,534,224,537,225,531,222,537,225,4.0,NaN,2.0,NaN,NaN,NaN,Arsenal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,2.463295,2.436352,2.019078,2.918608,2.413611,2.842632,2.396376,2.402170,2.353971,2.503876,24.749969
4,25.0,25.0,54694,-1,1,-1,1,0,4,0.8,1.0,0,Pierre-Emerick,0.0,False,Illness - 25% chance of playing,2021-08-13T14:30:14.477664Z,99,54694.jpg,0.0,Aubameyang,1.8,False,NaN,d,1,3,0,817,817,74611,74611,0.0,0.0,Aubameyang,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,553,73,553,73,553,73,553,73,NaN,NaN,NaN,NaN,1.0,NaN,Arsenal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,2.574336,2.672519,2.019078,3.045354,2.590142,2.953674,2.507417,2.638337,2.530502,2.740044,26.271403
5,NaN,NaN,58822,0,0,0,0,0,2,1.7,2.7,0,Cédric,0.0,False,NaN,NaN,45,58822.jpg,0.0,Soares,0.2,False,NaN,a,1,3,0,453,453,2645,2645,0.0,0.0,Cédric,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,315,119,309,116,247,90,328,120,NaN,NaN,5.0,NaN,NaN,NaN,Arsenal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,2.786228,2.982220,1.966114,3.165447,2.899843,3.230340,2.817119,2.948039,2.840203,3.049745,28.685298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,NaN,NaN,149065,0,0,0,0,0,1,2.1,2.1,3,José,3.0,False,NaN,NaN,50,149065.jpg,3.0,Malheiro de Sá,0.4,False,NaN,a,20,39,3,1274,1274,1666,1666,0.6,0.6,Sá,90,0,0,0,1,0,0,0,0,0,4,0,17,26.2,0.0,0.0,2.6,60,8,444,49,412,49,152,10,NaN,NaN,NaN,NaN,NaN,NaN,Wolves,1.0,4.797316,0.0,0.0,0.0,0.0,4.797316,0.0,1.797316,0.8,0.0,0.0,0.0,0.0,0.0,4.797316,1,4.797316,NaN,NaN,NaN,NaN,3.885622,3.610196,3.387592,3.684489,3.580491,3.938425,3.664079,3.704735,3.945212,3.355482,36.756323
523,0.0,NaN,209353,0,0,0,0,0,4,0.0,0.8,0,Patrick,0.0,False,Season long loan to Empoli,2021-08-15T12:06:51.809579Z,50,209353.jpg,0.0,Cutrone,0.2,False,NaN,u,20,39,0,1047,1047,5271,5271,0.0,0.0,Cutrone,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,459,45,463,51,437,43,468,51,NaN,NaN,NaN,NaN,NaN,NaN,Wolves,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,2.887639,3.124092,2.576775,2.693739,2.888571,3.453220,3.240436,2.817020,3.126415,2.325153,29.133060
547,NaN,NaN,245923,0,0,0,0,0,3,0.5,0.5,0,Luke,0.0,False,NaN,NaN,45,245923.jpg,0.0,Cundle,0.0,False,NaN,a,20,39,0,448,448,137,137,0.0,0.0,Cundle,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,400,152,398,157,356,139,410,156,NaN,NaN,NaN,NaN,NaN,NaN,Wolves,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,2.766254,2.986971,2.485452,2.556618,2.751451,3.331835,3.087611,2.695635,3.005029,2.330387,27.997243
548,NaN,NaN,461026,0,0,0,0,0,3,0.5,0.5,0,Chem,0.0,False,NaN,NaN,45,461026.jpg,0.0,Campbell,0.1,False,NaN,a,20,39,0,2741,2741,665,665,0.0,0.0,Campbell,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,411,157,408,162,367,145,420,161,NaN,NaN,NaN,NaN,NaN,NaN,Wolves,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,2.766254,2.986971,2.485452,2.556618,2.751451,3.331835,3.087611,2.695635,3.005029,2.330387,27.997243
549,NaN,NaN,481626,0,0,0,0,0,2,0.5,0.5,0,Christian,0.0,False,NaN,NaN,40,481626.jpg,0.0,Marques,0.1,False,NaN,a,20,39,0,4109,4109,655,655,0.0,0.0,Marques,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,298,112,289,109,224,80,311,113,NaN,NaN,NaN,NaN,NaN,NaN,Wolves,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,3.197340,3.400759,2.645320,3.003440,3.100463,3.950966,3.360528,3.126721,3.487664,2.272189,31.545390

In [22]:
players.sort_values(f'gameweek {latest_gameweek+1} prediction', ascending=False)[['web_name','now_cost','adjusted points per game', f'gameweek {latest_gameweek+1} prediction']].head(20)

          web_name  now_cost  adjusted points per game  gameweek 2 prediction
id
272          Pogba        76                 10.732812               8.203049
180    Richarlison        76                  8.771000               8.149935
233          Salah       125                 11.388597               8.058703
228        Firmino        90                  5.700000               6.901327
240           Jota        75                  5.746597               6.051579
277      Fernandes       121                  8.848812               6.021688
422         Soucek        60                  6.246597               5.829545
413        Antonio        76                  8.762000               5.605855
177  Calvert-Lewin        80                  9.400000               5.522447
453    Fernandinho        50                  4.172532               5.506608
133    Christensen        50                  5.963273               5.454056
527       Chalobah        50                  6.963273               5.432165
230           Mané       120                  3.846597               5.121901
258            Aké        50                  4.290127               5.079722
119    Azpilicueta        60                  4.963273               4.969656
419       Benrahma        60                  6.617597               4.946887
122         Alonso        55                  9.163273               4.855158
482       Townsend        55                  5.367585               4.851320
274           Fred        50                  3.548812               4.782224
284       Lindelöf        50                  5.566247               4.745463

In [20]:
players.sort_values('xPoints_next10', ascending=False)[['web_name','now_cost','adjusted points per game', 'xPoints_next10']].head(20)

          web_name  now_cost  adjusted points per game  xPoints_next10
id
233          Salah       125                 11.388597       82.097636
272          Pogba        76                 10.732812       77.993418
180    Richarlison        76                  8.771000       73.876881
228        Firmino        90                  5.700000       58.367266
422         Soucek        60                  6.246597       50.348725
240           Jota        75                  5.746597       50.308769
277      Fernandes       121                  8.848812       50.277627
413        Antonio        76                  8.762000       48.853138
450         Dennis        50                  9.271000       46.616719
482       Townsend        55                  5.367585       46.073121
337           Ings        80                  5.720000       45.852616
435         Traoré        60                  5.749329       44.933051
307  Saint-Maximin        65                  4.971000       44.895975
419       Benrahma        60                  6.617597       44.006187
453    Fernandinho        50                  4.172532       43.818769
107       Westwood        55                  5.972194       43.668270
296         Wilson        75                  4.400000       43.574921
274           Fred        50                  3.548812       43.560022
133    Christensen        50                  5.963273       43.509816
527       Chalobah        50                  6.963273       43.368445

In [23]:
# save data
filepath = Path('../data/fpl/data_week' + str(latest_gameweek) + str('.csv'))
players.to_csv(filepath)