In [1]:
# give the number of the latest FPL round
latest_gameweek = 7

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
import json
import requests
import xgboost
import pickle

# allow more data columns to be shown than by default
pd.set_option('max_columns',500)

In [3]:
filepath = Path('../data/fpl/data_week' + str(latest_gameweek) + str('.csv'))
players = pd.read_csv(filepath, index_col=0)
players

,adjusted points,adjusted points per game,assists,assists_week1,assists_week2,assists_week3,assists_week4,assists_week5,assists_week6,assists_week7,bonus,bonus_week1,bonus_week2,bonus_week3,bonus_week4,bonus_week5,bonus_week6,bonus_week7,bps,chance_of_playing_next_round,chance_of_playing_this_round,clean_sheet_points,clean_sheets,cleansheet_week1,cleansheet_week2,cleansheet_week3,cleansheet_week4,cleansheet_week5,cleansheet_week6,cleansheet_week7,code,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,creativity,creativity_rank,creativity_rank_type,direct_freekicks_order,direct_freekicks_text,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,form 10,form 15,form 20,form 5,games played,gameweek,gameweek 10 prediction,gameweek 11 prediction,gameweek 12 prediction,gameweek 13 prediction,gameweek 14 prediction,gameweek 15 prediction,gameweek 16 prediction,gameweek 2 prediction,gameweek 3 prediction,gameweek 4 prediction,gameweek 5 prediction,gameweek 6 prediction,gameweek 7 prediction,gameweek 8 prediction,gameweek 9 prediction,goals_conceded,goals_scored,goals_week1,goals_week2,goals_week3,goals_week4,goals_week5,goals_week6,goals_week7,ict_index,ict_index_rank,ict_index_rank_type,in_dreamteam,influence,influence_rank,influence_rank_type,minutes,news,news_added,now_cost,own_goals,penalties_missed,penalties_order,penalties_saved,penalties_text,photo,points_per_game,red_cards,saves,second_name,selected_by_percent,special,squad_number,status,team,team_code,team_name,threat,threat_rank,threat_rank_type,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value,value form 10,value form 5,valuePoints metric,value_form,value_next10,value_season,web_name,xA,xA_points,xA_week1,xA_week2,xA_week3,xA_week4,xA_week5,xA_week6,xA_week7,xG,xG+xA,xG+xA per game,xGA_week1,xGA_week2,xGA_week3,xGA_week4,xGA_week5,xGA_week6,xGA_week7,xG_points,xG_week1,xG_week2,xG_week3,xG_week4,xG_week5,xG_week6,xG_week7,xPoints,xPoints week 1,xPoints week 2,xPoints week 3,xPoints week 4,xPoints week 5,xPoints week 6,xPoints week 7,xPoints_next10,yellow_cards
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,6.041078,2.013693,0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,48,NaN,NaN,2.041078,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80201,NaN,NaN,0,0,-2,2,0.0,546,55,NaN,NaN,0,1,0.5,0.5,0,Bernd,0.0,1.799901,1.799901,1.799901,1.089483,3.0,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,7.9,287,20,False,79.0,172,20,270,NaN,NaN,48,0,0,NaN,0,NaN,80201.jpg,1.3,0,9,Leno,1.2,False,NaN,a,1,3,Arsenal,0.0,531,52,4,53508,1027,144304,5651,NaN,NaN,NaN,NaN,0.0,NaN,0.8,Leno,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,1.3,2.9,3.8,0.7,1.2,1.1,1.4,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,2.090127,2.220093,1.089483,NaN,NaN,NaN,NaN,NaN,0
2,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115918,NaN,NaN,0,0,0,0,0.0,405,18,NaN,NaN,0,1,0.0,0.0,0,Rúnar Alex,0.0,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,425,37,False,0.0,419,37,0,Joined OH Leuven on a season-long loan - Expec...,2021-08-31T22:00:09.069158Z,40,0,0,NaN,0,NaN,115918.jpg,0.0,0,0,Rúnarsson,0.9,False,NaN,u,1,3,Arsenal,0.0,363,14,0,19017,0,52713,2149,NaN,NaN,NaN,NaN,0.0,NaN,0.0,Rúnarsson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47431,NaN,NaN,0,0,-2,2,0.0,606,248,NaN,NaN,0,3,0.0,0.0,0,Willian,0.0,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,607,248,False,0.0,607,248,0,Transferred to Corinthians,2021-08-20T09:30:14.065783Z,63,0,0,NaN,0,NaN,47431.jpg,0.0,0,0,Borges Da Silva,0.1,False,NaN,u,1,3,Arsenal,0.0,605,248,0,914,0,19670,193,NaN,NaN,NaN,NaN,0.0,NaN,0.0,Willian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,22.300000,3.716667,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,4,NaN,0.0,0.0,3.0,0.0,1.0,0.0,74,100.0,100.0,0.000000,3,NaN,0.0,0.0,1.0,1.0,0.0,1.0,54694,NaN,NaN,0,0,-1,1,68.7,116,19,NaN,NaN,0,4,4.2,4.2,2,Pierre-Emerick,3.7,3.716667,3.716667,3.716667,4.260000,6.0,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,2,NaN,0.0,0.0,1.0,0.0,1.0,0.0,40.7,40,11,False,86.8,148,15,428,NaN,2021-08-13T14:30:14.477664Z,99,0,0,1.0,0,NaN,54694.jpg,3.7,0,0,Aubameyang,2.3,False,NaN,a,1,3,Arsenal,253.0,12,6,22,224268,18733,269119,12743,NaN,NaN,NaN,NaN,0.4,NaN,2.2,Aubameyang,0.5,1.5,NaN,0.0,0.0,0.1,0.4,0.0,0.0,1.7,NaN,NaN,NaN,2.9,3.8,0.7,1.2,1.1,1.4,6.8,NaN,0.0,0.0,1.3,0.1,0.2,0.1,2.4,NaN,1.000000,1.000000,10.5,3.6,3.8,2.4,NaN,0
5,3.341078,1.113693,0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,21,NaN,NaN,2.041078,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,58822,NaN,NaN,0,0,-2,2,36.1,181,46,NaN,NaN,0,2,0.5,0.5,0,Cédric,0.0,0.536525,0.536525,0.536525,0.044742,3.0,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,6.8,304,105,False,30.8,292,113,188,NaN,NaN,43,0,0,NaN,0,NaN,58822.jpg,0.3,0,0,Soares,0.2,False,NaN,a,1,3,Arsenal,1.0,339,118,1,9675,205,18458,690,NaN,NaN,NaN,NaN,0.0,NaN,0.2,Cédric,0.1,0.3,NaN,0.1,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,2.9,3.8,0.7,1.2,1.1,1.4,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,1.520093,-0.910517,1.0,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,245923,NaN,NaN,0,0,0,0,0.0,521,208,NaN,NaN,0,3,0.0,0.5,0,Luke,0.0,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,533,206,False,0.0,530,205,0,NaN,NaN,45,0,0,NaN,0,NaN,245923.jpg,0.0,0,0,Cundle,0.1,False,NaN,a,20,39,Wolves,0.0,498,199,0,9036,553,6247,659,NaN,NaN,NaN,NaN,0.0,NaN,0.0,Cundle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
548,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,461026,NaN,NaN,0,0,0,0,0.0,529,213,NaN,NaN,0,3,0.0,0.5,0,Chem,0.0,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,541,211,False,0.0,538,210,0,NaN,NaN,45,0,0,NaN,0,NaN,461026.jpg,0.0,0,0,Campbell,0.3,False,NaN,a,20,39,Wolves,0.0,508,205,0,34016,1040,22198,1740,NaN,NaN,NaN,NaN,0.0,NaN,0.0,Campbell,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
549,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,481626,NaN,NaN,0,0,0,0,0.0,434,167,NaN,NaN,0,2,0.0,0.0,0,Christian,0.0,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,454,167,False,0.0,448,165,0,Season-long loan to Belenenses,2021-09-07T09:00:15.908306Z,40,0,0,NaN,0,NaN,481626.jpg,0.0,0,0,Marques,0.2,False,NaN,u,20,39,Wolves,0.0,394,148,0,24271,0,22936,852,NaN,NaN,NaN,NaN,0.0,NaN,0.0,Marques,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
583,18.800000,4.700000,0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,6,NaN,NaN,NaN,NaN,0.0,0.0,3.0,96,NaN,NaN,0.000000,1,NaN,NaN,NaN,NaN,0.0,1.0,0.0,184754,NaN,NaN,1,-1,1,-1,25.0,229,34,NaN,NaN,1,4,5.3,5.8,13,Hee-Chan,5.3,3.866667,3.866667,3.866667,3.866667,4.0,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3,NaN,NaN,NaN,NaN,0.0,0.0,2.0,26.7,98,25,False,114.4,96,13,249,NaN,NaN,56,0,0,NaN,0,NaN,184754.jpg,6.0,0,0,Hwang,4.6,False,NaN,a,20,39,Wolves,127.0,61,23,24,496809,232301,145268,19918,NaN,NaN,NaN,NaN,0.9,NaN,4.3,Hwang,0.4,1.2,NaN,NaN,NaN,NaN,0.0,0.0,0.4,1.4,NaN,NaN,NaN,NaN,NaN,0.2,2.5,1.2,0.6,5.6,NaN,NaN,NaN,NaN,0.1,0.1,0.4,7.8,NaN,NaN,NaN,NaN,1.4,2.4,7.8,NaN,0
611,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,242510,NaN,NaN,0,0,0,0,0.0,417,24,NaN,NaN,0,1,0.0,0.5,0,Louie,0.0,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,437,43,False,0.0,431,43,0,NaN,NaN,40,0,0,NaN,0,NaN,242510.jpg,0.0,0,0,Moulden,0.1,False,NaN,a,20,39,Wolves,0.0,377,20,0,5621,2985,935,633,NaN,NaN,NaN,NaN,0.0,NaN,0.0,Moulden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [4]:
teams = ['Arsenal', 'Aston Villa', 'Brentford', 'Brighton', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton',
        'Leicester City', 'Leeds United', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle Utd', 
        'Norwich City', 'Southampton', 'Tottenham', 'Watford', 'West Ham', 'Wolves']

In [5]:
# get FPL fixtures data
fpl_fixtures_data = json.loads(requests.get('https://fantasy.premierleague.com/api/fixtures/').text)
fpl_fixtures = pd.DataFrame(fpl_fixtures_data)
fpl_fixtures['home team'] = [teams[i] for i in fpl_fixtures['team_h']-1]
fpl_fixtures['away team'] = [teams[i] for i in fpl_fixtures['team_a']-1]
filepath = Path('../data/fpl/fixtures.csv')
fpl_fixtures.to_csv(filepath)
fpl_fixtures

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,team_a_score,team_h,team_h_score,stats,team_h_difficulty,team_a_difficulty,pulse_id,home team,away team
0,2210271,1,True,True,1,2021-08-13T19:00:00Z,90,False,True,1,0.0,3,2.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",3,2,66342,Brentford,Arsenal
1,2210276,1,True,True,6,2021-08-14T11:30:00Z,90,False,True,10,1.0,13,5.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",2,4,66347,Manchester Utd,Leeds United
2,2210272,1,True,True,2,2021-08-14T14:00:00Z,90,False,True,4,2.0,5,1.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",3,2,66343,Burnley,Brighton
3,2210273,1,True,True,3,2021-08-14T14:00:00Z,90,False,True,7,0.0,6,3.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",2,5,66344,Chelsea,Crystal Palace
4,2210274,1,True,True,4,2021-08-14T14:00:00Z,90,False,True,16,1.0,8,3.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",2,4,66345,Everton,Southampton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2210646,38,False,False,376,2022-05-22T15:00:00Z,0,False,False,13,NaN,7,NaN,[],4,2,66717,Crystal Palace,Manchester Utd
376,2210647,38,False,False,377,2022-05-22T15:00:00Z,0,False,False,16,NaN,9,NaN,[],2,3,66718,Leicester City,Southampton
377,2210648,38,False,False,378,2022-05-22T15:00:00Z,0,False,False,20,NaN,11,NaN,[],2,5,66719,Liverpool,Wolves
378,2210649,38,False,False,379,2022-05-22T15:00:00Z,0,False,False,2,NaN,12,NaN,[],3,5,66720,Manchester City,Aston Villa
379,2210650,38,False,False,380,2022-05-22T15:00:00Z,0,False,False,17,NaN,15,NaN,[],3,2,66721,Norwich City,Tottenham

In [6]:
filepath = Path(f'../data/fbref/team_stats_week{latest_gameweek}.csv')
team_stats = pd.read_csv(filepath, index_col=0)
team_stats

,Rk,MP,W,D,L,GF,GA,GD,Pts,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper,Notes,xG per game,xGA per game,probability no goals allowed
Squad,,,,,,,,,,,,,,,,,,,,,
Chelsea,1,7,5,1,1,15,3,12,16,11.6,8.6,3.0,0.43,D W W L W,39770,Romelu Lukaku - 3,Edouard Mendy,NaN,1.657143,1.228571,0.292710
Liverpool,2,7,4,3,0,17,6,11,15,17.9,8.1,9.9,1.41,D W W D D,52923,Mohamed Salah - 6,Alisson,NaN,2.557143,1.157143,0.314383
Manchester City,3,7,4,2,1,14,3,11,14,15.0,4.0,11.0,1.57,W W D W D,52137,"Gabriel Jesus, Ferrán Torres - 2",Ederson,NaN,2.142857,0.571429,0.564718
Manchester Utd,4,7,4,2,1,14,6,8,14,10.8,7.9,2.9,0.42,W W W L D,72879,Bruno Fernandes - 4,David de Gea,NaN,1.542857,1.128571,0.323495
Everton,5,7,4,2,1,13,8,5,14,11.3,7.3,4.0,0.57,W W L W D,35769,"Demarai Gray, Dominic Calvert-Lewin... - 3",Jordan Pickford,NaN,1.614286,1.042857,0.352446
Brighton,6,7,4,2,1,8,5,3,14,7.4,7.7,-0.3,-0.05,L W W D D,30594,Neal Maupay - 4,Robert Sánchez,NaN,1.057143,1.100000,0.332871
Brentford,7,7,3,3,1,10,6,4,12,9.6,7.5,2.2,0.31,D L W D W,16624,"Yoane Wissa, Ivan Toney... - 2",David Raya,NaN,1.371429,1.071429,0.342519
Tottenham,8,7,4,0,3,6,10,-4,12,7.3,10.1,-2.8,-0.40,W L L L W,57267,Son Heung-min - 3,Hugo Lloris,NaN,1.042857,1.442857,0.236252
West Ham,9,7,3,2,2,14,10,4,11,11.5,8.0,3.5,0.50,D D L W L,57398,Michail Antonio - 5,Łukasz Fabiański,NaN,1.642857,1.142857,0.318907
Aston Villa,10,7,3,1,3,10,9,1,10,7.9,9.0,-1.1,-0.15,D L W W L,41966,Danny Ings - 2,Emiliano Martínez,NaN,1.128571,1.285714,0.276453
Arsenal,11,7,3,1,3,5,10,-5,10,7.4,12.4,-5.0,-0.71,L W W W D,58883,Pierre-Emerick Aubameyang - 2,Aaron Ramsdale,NaN,1.057143,1.771429,0.170090
Wolves,12,7,3,0,4,5,6,-1,9,8.8,7.4,1.4,0.20,L W L W W,30368,Hwang Hee-chan - 3,José Sá,NaN,1.257143,1.057143,0.347447
Leicester City,13,7,2,2,3,9,12,-3,8,9.7,11.5,-1.8,-0.26,W L L D D,31907,Jamie Vardy - 6,Kasper Schmeichel,NaN,1.385714,1.642857,0.193427
Crystal Palace,14,7,1,4,2,8,11,-3,7,7.6,8.1,-0.6,-0.08,D W L D D,24267,"Wilfried Zaha, Conor Gallagher... - 2",Vicente Guaita,NaN,1.085714,1.157143,0.314383
Watford,15,7,2,1,4,7,10,-3,7,6.2,10.8,-4.6,-0.66,L L W D L,20240,Ismaila Sarr - 4,Daniel Bachmann,NaN,0.885714,1.542857,0.213769
Leeds United,16,7,1,3,3,7,14,-7,6,10.2,12.5,-2.3,-0.33,D L D L W,36370,Raphael Dias Belloli - 3,Illan Meslier,NaN,1.457143,1.785714,0.167677
Southampton,17,7,0,4,3,5,10,-5,4,8.9,11.6,-2.7,-0.38,D D D L L,30001,James Ward-Prowse - 2,Alex McCarthy,NaN,1.271429,1.657143,0.190683
Burnley,18,7,0,3,4,5,11,-6,3,7.4,11.3,-3.9,-0.56,D L L D D,18584,"Maxwel Cornet, Ben Mee... - 1",Nick Pope,NaN,1.057143,1.614286,0.199033
Newcastle Utd,19,7,0,3,4,8,16,-8,3,8.8,13.3,-4.5,-0.65,D L D D L,48366,"Allan Saint-Maximin, Callum Wilson - 2",Freddie Woodman,NaN,1.257143,1.900000,0.149569
Norwich City,20,7,0,1,6,2,16,-14,1,5.8,14.0,-8.2,-1.18,L L L L D,26812,Teemu Pukki - 2,Tim Krul,NaN,0.828571,2.000000,0.135335

In [7]:
# upload model for making predictions
path = Path('../models/xgboost_predictor_v4_weightsAndBonus.pickle')
with open(path,'rb') as f:
    model = pickle.load(f)

In [8]:
# pre-allocate for model input
predictions = pd.DataFrame(index=players.index.copy())
input_columns = ['goalkeeper', 'defender', 'midfielder',
       'forward', 'xG90', 'xA90', 'xGA90', 'bonus', 'xPoints90',
       'games played', 'form 5', 'games_form5', 'form 10', 'games form10',
       'team xG per 90', 'team xGA per 90', 'home', 'opponent xG per 90',
       'opponent xGA per 90']
predictions[input_columns] = np.nan
predictions

,goalkeeper,defender,midfielder,forward,xG90,xA90,xGA90,bonus,xPoints90,games played,form 5,games_form5,form 10,games form10,team xG per 90,team xGA per 90,home,opponent xG per 90,opponent xGA per 90
id,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
611,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# run predictions for all players for a given time horizon
# assumes one match per gameweek at most currently?
horizon = 10
output_columns = [f'gameweek {i} prediction' for i in range(latest_gameweek+1,latest_gameweek+horizon+1)]
xGA_columns = [column for column in players.columns if 'xGA_week' in column]
xPoints_columns = [column for column in players.columns if 'xPoints week' in column]

for player_ix in players.index:
    
    # collect base info
    if players.loc[player_ix,'element_type'] == 1:
        predictions.loc[player_ix,'goalkeeper'] = 1
    elif players.loc[player_ix, 'element_type'] == 2:
        predictions.loc[player_ix,'defender'] = 1
    elif players.loc[player_ix, 'element_type'] == 3:
        predictions.loc[player_ix,'midfielder'] = 1
    elif players.loc[player_ix, 'element_type'] == 4:
        predictions.loc[player_ix,'forward'] = 1

    if players.loc[player_ix,'games played'] > 0:
        predictions.loc[player_ix, 'xG90'] = players.loc[player_ix,'xG'] / players.loc[player_ix,'games played']
        predictions.loc[player_ix, 'xA90'] = players.loc[player_ix,'xA'] / players.loc[player_ix,'games played']
        predictions.loc[player_ix, 'xGA90'] = players.loc[player_ix,xGA_columns].sum() / \
                                          players.loc[player_ix,'games played']                                        
        predictions.loc[player_ix, 'bonus'] = players.loc[player_ix, 'bps']
        predictions.loc[player_ix, 'xPoints90'] = players.loc[player_ix,'adjusted points per game']
        predictions.loc[player_ix, 'games played'] = players.loc[player_ix, 'games played']
        
        form5_points = players.loc[player_ix, xPoints_columns[-5:]].sum()
        form5_games = players.loc[player_ix, xPoints_columns[-5:]].notnull().sum()
        predictions.loc[player_ix, 'form 5'] = form5_points
        predictions.loc[player_ix, 'games_form5'] = form5_games
        
        form10_points = players.loc[player_ix, xPoints_columns[-10:]].sum()
        form10_games = players.loc[player_ix, xPoints_columns[-10:]].notnull().sum()
        predictions.loc[player_ix, 'form 10'] = form10_points
        predictions.loc[player_ix, 'games form10'] = form10_games
    else:
        predictions.loc[player_ix, 'xG90'] = 0
        predictions.loc[player_ix, 'xA90'] = 0
        predictions.loc[player_ix, 'xGA90'] = 0                       
        predictions.loc[player_ix, 'bonus'] = 0
        predictions.loc[player_ix, 'xPoints90'] = 0
        predictions.loc[player_ix, 'games played'] = 0
        predictions.loc[player_ix, 'form 5'] = 0
        predictions.loc[player_ix, 'games_form5'] = 0
        predictions.loc[player_ix, 'form 10'] = 0
        predictions.loc[player_ix, 'games form10'] = 0
        
    team = players.loc[player_ix, 'team_name']
    # team xG per 90 
    team_xG90 = team_stats.loc[team,'xG'] / team_stats.loc[team,'MP']
    predictions.loc[player_ix, 'team xG per 90'] = team_xG90
    # team xGA per 90 
    team_xGA90 = team_stats.loc[team,'xGA'] / team_stats.loc[team,'MP']
    predictions.loc[player_ix, 'team xGA per 90'] = team_xGA90
    
    for gameweek in range(latest_gameweek+1,latest_gameweek+horizon+1):

        # home games
        home_fixtures = fpl_fixtures[(fpl_fixtures['event']==gameweek) & (fpl_fixtures['home team']==team)]
        for fixture in home_fixtures.index:
            predictions.loc[player_ix, 'home'] = 1
            opponent = fpl_fixtures.loc[fixture, 'away team']
            # opponent xG per 90
            opponent_xG90 = team_stats.loc[opponent, 'xG'] / team_stats.loc[opponent,'MP']
            predictions.loc[player_ix, 'opponent xG per 90'] = opponent_xG90
            # opponent xGA per 90
            opponent_xGA90 = team_stats.loc[opponent, 'xGA'] / team_stats.loc[opponent,'MP']
            predictions.loc[player_ix, 'opponent xGA per 90'] = opponent_xGA90
            
            # predict player's points
            input_data = predictions.loc[player_ix:player_ix, input_columns]
            input_data = xgboost.DMatrix(input_data)
            prediction = model.predict(input_data)
            players.loc[player_ix, f'gameweek {gameweek} prediction'] = prediction
            
        # away game
        away_fixtures = fpl_fixtures[(fpl_fixtures['event']==gameweek) & (fpl_fixtures['away team']==team)]
        for fixture in away_fixtures.index:
            predictions.loc[player_ix, 'home'] = 0
            opponent = fpl_fixtures.loc[fixture, 'home team']
            # opponent xG per 90
            opponent_xG90 = team_stats.loc[opponent, 'xG'] / team_stats.loc[opponent,'MP']
            predictions.loc[player_ix, 'opponent xG per 90'] = opponent_xG90
            # opponent xGA per 90
            opponent_xGA90 = team_stats.loc[opponent, 'xGA'] / team_stats.loc[opponent,'MP']
            predictions.loc[player_ix, 'opponent xGA per 90'] = opponent_xGA90
            
            # predict player's points
            input_data = predictions.loc[player_ix:player_ix, input_columns]
            input_data = xgboost.DMatrix(input_data)
            prediction = model.predict(input_data)
            players.loc[player_ix, f'gameweek {gameweek} prediction'] = prediction

In [10]:
# all new predictions
players[output_columns]

,gameweek 8 prediction,gameweek 9 prediction,gameweek 10 prediction,gameweek 11 prediction,gameweek 12 prediction,gameweek 13 prediction,gameweek 14 prediction,gameweek 15 prediction,gameweek 16 prediction,gameweek 17 prediction
id,,,,,,,,,,
1,3.977383,3.965480,3.758779,4.198713,3.512175,4.151344,3.567563,3.639779,4.017078,3.573277
2,3.277598,3.265695,3.197049,3.628563,2.763469,3.681364,2.896853,2.669482,3.405957,2.803473
3,2.337055,2.217583,2.394131,2.647381,1.980933,2.694813,2.136439,2.042449,2.419406,1.982808
4,3.666691,3.685681,4.005966,4.177683,3.280962,4.398808,3.543188,3.280962,4.131710,3.280962
5,2.229051,2.119575,1.925128,2.502861,1.526286,2.274930,1.681431,1.537365,2.140664,1.537365
...,...,...,...,...,...,...,...,...,...,...
547,2.428080,2.843718,2.260516,2.485872,2.260516,3.008731,2.828578,2.103535,2.219841,2.485872
548,2.428080,2.843718,2.260516,2.485872,2.260516,3.008731,2.828578,2.103535,2.219841,2.485872
549,2.874902,3.055134,2.271759,2.998183,2.271759,3.709087,3.528933,2.045337,2.161643,2.998183
583,3.749084,4.073353,3.391598,3.813177,3.391598,4.679199,4.301036,3.391598,3.188145,3.813177
611,3.414126,3.503952,2.868047,3.501515,3.061678,3.928446,3.763543,2.901933,2.899131,3.241382

In [11]:
players['xPoints_next10'] = players[output_columns].sum(axis=1)

In [12]:
players.sort_values(f'gameweek {latest_gameweek+1} prediction', ascending=False)[['web_name','now_cost','adjusted points per game', f'gameweek {latest_gameweek+1} prediction']].head(20)

,web_name,now_cost,adjusted points per game,gameweek 8 prediction
id,,,,
233,Salah,127,8.357812,7.000152
413,Antonio,80,6.850667,6.697718
237,Alexander-Arnold,75,7.005933,6.022261
230,Mané,119,6.424526,5.985117
529,Lukaku,117,5.850000,5.626909
240,Jota,76,5.271526,5.490295
135,Chilwell,56,7.370842,5.399131
177,Calvert-Lewin,80,8.513333,5.361868
277,Fernandes,118,4.993638,5.231637
579,Ronaldo,126,5.450000,5.158253
63,Maupay,65,3.831429,5.129704
189,Bamford,78,5.268400,4.967443
256,Cancelo,62,6.122015,4.948884
359,Son,101,5.326585,4.851413
186,Klich,55,4.641877,4.784630
224,Matip,50,4.074199,4.774378
268,Torres,69,6.257468,4.672123
229,van Dijk,66,4.510533,4.662850
369,Bergwijn,59,4.483585,4.616672
307,Saint-Maximin,68,5.101857,4.601574

In [13]:
players.sort_values('xPoints_next10', ascending=False)[['web_name','now_cost','adjusted points per game', 'xPoints_next10']].head(20)

             web_name  now_cost  adjusted points per game  xPoints_next10
id
413           Antonio        80                  6.850667       70.894950
135          Chilwell        56                  7.370842       62.754489
529            Lukaku       117                  5.850000       61.808534
233             Salah       127                  8.357812       61.296235
177     Calvert-Lewin        80                  8.513333       52.705400
237  Alexander-Arnold        75                  7.005933       50.984297
205             Vardy       105                  5.895857       50.385484
230              Mané       119                  6.424526       49.441953
277         Fernandes       118                  4.993638       49.072983
579           Ronaldo       126                  5.450000       48.179348
240              Jota        76                  5.271526       48.146505
78              Toney        64                  4.851714       47.087679
419          Benrahma        66                  5.367764       45.658441
138             Mount        74                  4.261110       44.944363
256           Cancelo        62                  6.122015       44.827553
307     Saint-Maximin        68                  5.101857       44.662884
189           Bamford        78                  5.268400       44.349471
296            Wilson        73                  5.066667       43.222291
482          Townsend        56                  5.204161       43.045551
334          McCarthy        45                  2.905589       42.876951

In [14]:
# save data
filepath = Path('../data/fpl/data_week' + str(latest_gameweek) + str('.csv'))
players.to_csv(filepath)