In [1]:
# give the number of the latest FPL round
latest_gameweek = 5

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
import json
import requests
import xgboost
import pickle

# allow more data columns to be shown than by default
pd.set_option('max_columns',500)

In [3]:
filepath = Path('../data/fpl/data_week' + str(latest_gameweek) + str('.csv'))
players = pd.read_csv(filepath, index_col=0)
players

,adjusted points,adjusted points per game,assists,assists_week1,assists_week2,assists_week3,assists_week4,assists_week5,bonus,bonus_week1,bonus_week2,bonus_week3,bonus_week4,bonus_week5,bps,chance_of_playing_next_round,chance_of_playing_this_round,clean_sheet_points,clean_sheets,cleansheet_week1,cleansheet_week2,cleansheet_week3,cleansheet_week4,cleansheet_week5,code,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,creativity,creativity_rank,creativity_rank_type,direct_freekicks_order,direct_freekicks_text,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,form 10,form 15,form 20,form 5,games played,gameweek,gameweek 10 prediction,gameweek 11 prediction,gameweek 12 prediction,gameweek 13 prediction,gameweek 14 prediction,gameweek 2 prediction,gameweek 3 prediction,gameweek 4 prediction,gameweek 5 prediction,gameweek 6 prediction,gameweek 7 prediction,gameweek 8 prediction,gameweek 9 prediction,goals_conceded,goals_scored,goals_week1,goals_week2,goals_week3,goals_week4,goals_week5,ict_index,ict_index_rank,ict_index_rank_type,in_dreamteam,influence,influence_rank,influence_rank_type,minutes,news,news_added,now_cost,own_goals,penalties_missed,penalties_order,penalties_saved,penalties_text,photo,points_per_game,red_cards,saves,second_name,selected_by_percent,special,squad_number,status,team,team_code,team_name,threat,threat_rank,threat_rank_type,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value,value form 10,value form 5,valuePoints metric,value_form,value_next10,value_season,web_name,xA,xA_points,xA_week1,xA_week2,xA_week3,xA_week4,xA_week5,xG,xG+xA,xG+xA per game,xGA_week1,xGA_week2,xGA_week3,xGA_week4,xGA_week5,xG_points,xG_week1,xG_week2,xG_week3,xG_week4,xG_week5,xPoints,xPoints week 1,xPoints week 2,xPoints week 3,xPoints week 4,xPoints week 5,xPoints_next10,yellow_cards
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,5.656831,1.88561,0,0.0,0.0,0.0,NaN,NaN,0,0.0,0.0,0.0,NaN,NaN,48,NaN,NaN,1.656831,0,0.0,0.0,0.0,0.0,0.0,80201,NaN,NaN,0,0,-1,1,0.0,533,54,NaN,NaN,0,1,0.8,1.8,0,Bernd,0.8,1.799901,1.799901,1.799901,1.799901,3.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,0,0.0,0.0,0.0,NaN,NaN,7.9,242,18,False,79.0,115,16,270,NaN,NaN,49,0,0,NaN,0,NaN,80201.jpg,1.3,0,9,Leno,1.5,False,NaN,a,1,3,Arsenal,0.0,512,52,4,49210,1237,114869,9238,NaN,NaN,NaN,NaN,0.2,NaN,0.8,Leno,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,1.3,2.9,3.8,0.7,1.2,0.0,0.0,0.0,0.0,NaN,NaN,NaN,2.090127,2.220093,1.089483,NaN,NaN,NaN,0
2,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,115918,NaN,NaN,0,0,0,0,0.0,388,17,NaN,NaN,0,1,0.0,0.0,0,Rúnar Alex,0.0,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0.0,410,37,False,0.0,401,37,0,Joined OH Leuven on a season-long loan - Expec...,2021-08-31T22:00:09.069158Z,40,0,0,NaN,0,NaN,115918.jpg,0.0,0,0,Rúnarsson,1.0,False,NaN,u,1,3,Arsenal,0.0,337,14,0,19017,0,43384,2356,NaN,NaN,NaN,NaN,0.0,NaN,0.0,Rúnarsson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,47431,NaN,NaN,0,0,-2,2,0.0,599,245,NaN,NaN,0,3,0.0,0.0,0,Willian,0.0,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0.0,600,245,False,0.0,600,245,0,Transferred to Corinthians,2021-08-20T09:30:14.065783Z,63,0,0,NaN,0,NaN,47431.jpg,0.0,0,0,Borges Da Silva,0.1,False,NaN,u,1,3,Arsenal,0.0,597,245,0,914,0,18829,301,NaN,NaN,NaN,NaN,0.0,NaN,0.0,Willian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,16.100000,4.02500,0,NaN,0.0,0.0,0.0,0.0,3,NaN,0.0,0.0,3.0,0.0,41,100.0,100.0,0.000000,2,NaN,0.0,0.0,1.0,1.0,54694,NaN,NaN,0,0,-1,1,62.6,89,14,NaN,NaN,0,4,3.2,4.2,2,Pierre-Emerick,3.2,4.025000,4.025000,4.025000,4.025000,4.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,1,NaN,0.0,0.0,1.0,0.0,25.0,64,18,False,48.0,200,20,267,NaN,2021-08-13T14:30:14.477664Z,99,0,0,1.0,0,NaN,54694.jpg,3.2,0,0,Aubameyang,2.2,False,NaN,a,1,3,Arsenal,140.0,38,16,13,159241,3774,211519,16518,NaN,NaN,NaN,NaN,0.3,NaN,1.3,Aubameyang,0.5,1.5,NaN,0.0,0.0,0.1,0.4,1.4,NaN,NaN,NaN,2.9,3.8,0.7,1.2,5.6,NaN,0.0,0.0,1.3,0.1,3.6,NaN,1.000000,1.000000,10.5,3.6,NaN,0
5,2.956831,0.98561,0,NaN,0.0,0.0,0.0,NaN,0,NaN,0.0,0.0,0.0,NaN,21,NaN,NaN,1.656831,0,NaN,0.0,0.0,0.0,0.0,58822,NaN,NaN,0,0,-1,1,36.1,151,32,5.0,NaN,0,2,0.2,1.2,0,Cédric,0.2,0.536525,0.536525,0.536525,0.536525,3.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,0,NaN,0.0,0.0,0.0,NaN,6.8,258,88,False,30.8,255,100,188,NaN,NaN,44,0,0,NaN,0,NaN,58822.jpg,0.3,0,0,Soares,0.2,False,NaN,a,1,3,Arsenal,1.0,314,105,1,8761,225,15305,917,NaN,NaN,NaN,NaN,0.0,NaN,0.2,Cédric,0.1,0.3,NaN,0.1,0.0,0.0,NaN,0.0,NaN,NaN,NaN,2.9,3.8,0.7,1.2,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,1.520093,-0.910517,1.0,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,209353,NaN,NaN,0,0,0,0,0.0,564,71,NaN,NaN,0,4,0.0,0.0,0,Patrick,0.0,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0.0,568,71,False,0.0,563,68,0,Season long loan to Empoli,2021-08-15T12:06:51.809579Z,50,0,0,NaN,0,NaN,209353.jpg,0.0,0,0,Cutrone,0.1,False,NaN,u,20,39,Wolves,0.0,549,66,0,1047,0,14797,281,NaN,NaN,NaN,NaN,0.0,NaN,0.0,Cutrone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
547,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,245923,NaN,NaN,0,0,0,0,0.0,507,203,NaN,NaN,0,3,0.0,0.5,0,Luke,0.0,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0.0,518,200,False,0.0,513,198,0,NaN,NaN,45,0,0,NaN,0,NaN,245923.jpg,0.0,0,0,Cundle,0.1,False,NaN,a,20,39,Wolves,0.0,478,190,0,7320,558,4092,568,NaN,NaN,NaN,NaN,0.0,NaN,0.0,Cundle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
548,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,461026,NaN,NaN,0,0,0,0,0.0,514,207,NaN,NaN,0,3,0.0,0.5,0,Chem,0.0,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0.0,525,204,False,0.0,520,202,0,NaN,NaN,45,0,0,NaN,0,NaN,461026.jpg,0.0,0,0,Campbell,0.3,False,NaN,a,20,39,Wolves,0.0,487,195,0,29068,2002,15549,1974,NaN,NaN,NaN,NaN,0.0,NaN,0.0,Campbell,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
549,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,481626,NaN,NaN,0,0,0,0,0.0,416,159,NaN,NaN,0,2,0.0,0.0,0,Christian,0.0,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0.0,438,161,False,0.0,429,159,0,Season-long loan to Belenenses,2021-09-07T09:00:15.908306Z,40,0,0,NaN,0,NaN,481626.jpg,0.0,0,0,Marques,0.3,False,NaN,u,20,39,Wolves,0.0,367,133,0,24271,0,19334,1494,NaN,NaN,NaN,NaN,0.0,NaN,0.0,Marques,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
583,8.600000,4.30000,0,NaN,NaN,NaN,NaN,0.0,3,NaN,NaN,NaN,NaN,0.0,30,NaN,NaN,0.000000,0,NaN,NaN,NaN,NaN,0.0,184754,NaN,NaN,0,0,0,0,0.9,323,46,NaN,NaN,0,4,4.5,5.0,1,Hee-Chan,4.5,0.700000,0.700000,0.700000,0.700000,2.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,NaN,NaN,NaN,NaN,0.0,10.8,195,30,False,41.6,224,26,72,NaN,NaN,55,0,0,NaN,0,NaN,184754.jpg,4.5,0,0,Hwang,2.4,False,NaN,a,20,39,Wolves,65.0,86,24,9,239838,13083,59617,23216,NaN,NaN,NaN,NaN,0.8,NaN,1.6,Hwang,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.9,NaN,NaN,NaN,NaN,NaN,0.2,2.5,3.6,NaN,NaN,NaN,NaN,0.1,1.4,NaN,NaN,NaN,NaN,1.4,NaN,0

In [4]:
teams = ['Arsenal', 'Aston Villa', 'Brentford', 'Brighton', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton',
        'Leicester City', 'Leeds United', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle Utd', 
        'Norwich City', 'Southampton', 'Tottenham', 'Watford', 'West Ham', 'Wolves']

In [5]:
# get FPL fixtures data
fpl_fixtures_data = json.loads(requests.get('https://fantasy.premierleague.com/api/fixtures/').text)
fpl_fixtures = pd.DataFrame(fpl_fixtures_data)
fpl_fixtures['home team'] = [teams[i] for i in fpl_fixtures['team_h']-1]
fpl_fixtures['away team'] = [teams[i] for i in fpl_fixtures['team_a']-1]
filepath = Path('../data/fpl/fixtures.csv')
fpl_fixtures.to_csv(filepath)
fpl_fixtures

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,team_a_score,team_h,team_h_score,stats,team_h_difficulty,team_a_difficulty,pulse_id,home team,away team
0,2210271,1,True,True,1,2021-08-13T19:00:00Z,90,False,True,1,0.0,3,2.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",3,2,66342,Brentford,Arsenal
1,2210276,1,True,True,6,2021-08-14T11:30:00Z,90,False,True,10,1.0,13,5.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",3,4,66347,Manchester Utd,Leeds United
2,2210272,1,True,True,2,2021-08-14T14:00:00Z,90,False,True,4,2.0,5,1.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",2,2,66343,Burnley,Brighton
3,2210273,1,True,True,3,2021-08-14T14:00:00Z,90,False,True,7,0.0,6,3.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",2,4,66344,Chelsea,Crystal Palace
4,2210274,1,True,True,4,2021-08-14T14:00:00Z,90,False,True,16,1.0,8,3.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",2,3,66345,Everton,Southampton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2210646,38,False,False,376,2022-05-22T15:00:00Z,0,False,False,13,NaN,7,NaN,[],4,2,66717,Crystal Palace,Manchester Utd
376,2210647,38,False,False,377,2022-05-22T15:00:00Z,0,False,False,16,NaN,9,NaN,[],2,3,66718,Leicester City,Southampton
377,2210648,38,False,False,378,2022-05-22T15:00:00Z,0,False,False,20,NaN,11,NaN,[],2,4,66719,Liverpool,Wolves
378,2210649,38,False,False,379,2022-05-22T15:00:00Z,0,False,False,2,NaN,12,NaN,[],2,5,66720,Manchester City,Aston Villa
379,2210650,38,False,False,380,2022-05-22T15:00:00Z,0,False,False,17,NaN,15,NaN,[],3,2,66721,Norwich City,Tottenham

In [6]:
filepath = Path(f'../data/fbref/team_stats_week{latest_gameweek}.csv')
team_stats = pd.read_csv(filepath, index_col=0)
team_stats

,Rk,MP,W,D,L,GF,GA,GD,Pts,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper,Notes,xG per game,xGA per game,probability no goals allowed
Squad,,,,,,,,,,,,,,,,,,,,,
Chelsea,1,5,4,1,0,12,1,11,13,7.6,5.5,2.1,0.42,W W D W W,39467,Romelu Lukaku - 3,Edouard Mendy,NaN,1.52,1.10,0.332871
Liverpool,2,5,4,1,0,12,1,11,13,14.5,5.1,9.4,1.88,W W D W W,53296,Mohamed Salah - 4,Alisson,NaN,2.90,1.02,0.360595
Manchester Utd,3,5,4,1,0,13,4,9,13,7.6,5.5,2.1,0.41,W D W W W,72732,Bruno Fernandes - 4,David de Gea,NaN,1.52,1.10,0.332871
Brighton,4,5,4,0,1,7,4,3,12,5.3,6.0,-0.6,-0.13,W W L W W,30370,Neal Maupay - 3,Robert Sánchez,NaN,1.06,1.20,0.301194
Manchester City,5,5,3,1,1,11,1,10,10,12.2,2.7,9.5,1.90,L W W W D,52137,Ferrán Torres - 2,Ederson,NaN,2.44,0.54,0.582748
Everton,6,5,3,1,1,10,7,3,10,8.1,5.8,2.3,0.46,W D W W L,34244,"Demarai Gray, Dominic Calvert-Lewin - 3",Jordan Pickford,NaN,1.62,1.16,0.313486
Tottenham,7,5,3,0,2,3,6,-3,9,4.6,8.2,-3.6,-0.73,W W W L L,58664,Son Heung-min - 2,Hugo Lloris,NaN,0.92,1.64,0.193980
West Ham,8,5,2,2,1,11,7,4,8,8.2,5.5,2.7,0.54,W W D D L,59826,Michail Antonio - 4,Łukasz Fabiański,NaN,1.64,1.10,0.332871
Brentford,9,5,2,2,1,5,2,3,8,6.5,3.6,2.9,0.58,W D D L W,16499,Ivan Toney - 2,David Raya,NaN,1.30,0.72,0.486752
Aston Villa,10,5,2,1,2,8,7,1,7,5.6,4.9,0.7,0.14,L W D L W,41966,Danny Ings - 2,Emiliano Martínez,NaN,1.12,0.98,0.375311
Watford,11,5,2,0,3,6,8,-2,6,4.7,6.5,-1.7,-0.34,W L L L W,20035,Ismaila Sarr - 3,Daniel Bachmann,NaN,0.94,1.30,0.272532
Leicester City,12,5,2,0,3,5,8,-3,6,5.5,9.5,-4.0,-0.80,W L W L L,32035,Jamie Vardy - 3,Kasper Schmeichel,NaN,1.10,1.90,0.149569
Arsenal,13,5,2,0,3,2,9,-7,6,6.1,9.9,-3.8,-0.76,L L L W W,58365,"Pierre-Emerick Aubameyang, Martin Ødegaard - 1",Bernd Leno,NaN,1.22,1.98,0.138069
Crystal Palace,14,5,1,2,2,5,8,-3,5,4.8,5.8,-1.0,-0.20,L D D W L,24546,"Conor Gallagher, Odsonne Édouard - 2",Vicente Guaita,NaN,0.96,1.16,0.313486
Southampton,15,5,0,4,1,4,6,-2,4,6.3,7.0,-0.7,-0.13,L D D D D,31000,"Mohamed Elyounoussi, Adam Armstrong... - 1",Alex McCarthy,NaN,1.26,1.40,0.246597
Wolves,16,5,1,0,4,2,5,-3,3,7.0,5.6,1.4,0.28,L L L W L,30495,Hwang Hee-chan - 1,José Sá,NaN,1.40,1.12,0.326280
Leeds United,17,5,0,3,2,5,12,-7,3,7.0,10.3,-3.3,-0.65,L D D L D,36400,Raphael Dias Belloli - 2,Illan Meslier,NaN,1.40,2.06,0.127454
Newcastle Utd,18,5,0,2,3,6,13,-7,2,5.6,11.3,-5.7,-1.14,L L D L D,48366,"Allan Saint-Maximin, Callum Wilson - 2",Freddie Woodman,NaN,1.12,2.26,0.104350
Burnley,19,5,0,1,4,3,9,-6,1,5.8,8.2,-2.3,-0.47,L L D L L,18455,"Ben Mee, Chris Wood... - 1",Nick Pope,NaN,1.16,1.64,0.193980
Norwich City,20,5,0,0,5,2,14,-12,0,4.7,10.9,-6.3,-1.25,L L L L L,26894,Teemu Pukki - 2,Tim Krul,NaN,0.94,2.18,0.113042

In [7]:
# upload model for making predictions
path = Path('../models/xgboost_predictor_v4_weightsAndBonus.pickle')
with open(path,'rb') as f:
    model = pickle.load(f)

In [8]:
# pre-allocate for model input
predictions = pd.DataFrame(index=players.index.copy())
input_columns = ['goalkeeper', 'defender', 'midfielder',
       'forward', 'xG90', 'xA90', 'xGA90', 'bonus', 'xPoints90',
       'games played', 'form 5', 'games_form5', 'form 10', 'games form10',
       'team xG per 90', 'team xGA per 90', 'home', 'opponent xG per 90',
       'opponent xGA per 90']
predictions[input_columns] = np.nan
predictions

,goalkeeper,defender,midfielder,forward,xG90,xA90,xGA90,bonus,xPoints90,games played,form 5,games_form5,form 10,games form10,team xG per 90,team xGA per 90,home,opponent xG per 90,opponent xGA per 90
id,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# run predictions for all players for a given time horizon
# assumes one match per gameweek at most currently
horizon = 10
output_columns = [f'gameweek {i} prediction' for i in range(latest_gameweek+1,latest_gameweek+horizon+1)]
xGA_columns = [column for column in players.columns if 'xGA_week' in column]
xPoints_columns = [column for column in players.columns if 'xPoints week' in column]

for player_ix in players.index:
    
    # collect base info
    if players.loc[player_ix,'element_type'] == 1:
        predictions.loc[player_ix,'goalkeeper'] = 1
    elif players.loc[player_ix, 'element_type'] == 2:
        predictions.loc[player_ix,'defender'] = 1
    elif players.loc[player_ix, 'element_type'] == 3:
        predictions.loc[player_ix,'midfielder'] = 1
    elif players.loc[player_ix, 'element_type'] == 4:
        predictions.loc[player_ix,'forward'] = 1

    if players.loc[player_ix,'games played'] > 0:
        predictions.loc[player_ix, 'xG90'] = players.loc[player_ix,'xG'] / players.loc[player_ix,'games played']
        predictions.loc[player_ix, 'xA90'] = players.loc[player_ix,'xA'] / players.loc[player_ix,'games played']
        predictions.loc[player_ix, 'xGA90'] = players.loc[player_ix,xGA_columns].sum() / \
                                          players.loc[player_ix,'games played']                                        
        predictions.loc[player_ix, 'bonus'] = players.loc[player_ix, 'bps']
        predictions.loc[player_ix, 'xPoints90'] = players.loc[player_ix,'adjusted points per game']
        predictions.loc[player_ix, 'games played'] = players.loc[player_ix, 'games played']
        
        form5_points = players.loc[player_ix, xPoints_columns[-5:]].sum()
        form5_games = players.loc[player_ix, xPoints_columns[-5:]].notnull().sum()
        predictions.loc[player_ix, 'form 5'] = form5_points
        predictions.loc[player_ix, 'games_form5'] = form5_games
        
        form10_points = players.loc[player_ix, xPoints_columns[-10:]].sum()
        form10_games = players.loc[player_ix, xPoints_columns[-10:]].notnull().sum()
        predictions.loc[player_ix, 'form 10'] = form10_points
        predictions.loc[player_ix, 'games form10'] = form10_games
    else:
        predictions.loc[player_ix, 'xG90'] = 0
        predictions.loc[player_ix, 'xA90'] = 0
        predictions.loc[player_ix, 'xGA90'] = 0                       
        predictions.loc[player_ix, 'bonus'] = 0
        predictions.loc[player_ix, 'xPoints90'] = 0
        predictions.loc[player_ix, 'games played'] = 0
        predictions.loc[player_ix, 'form 5'] = 0
        predictions.loc[player_ix, 'games_form5'] = 0
        predictions.loc[player_ix, 'form 10'] = 0
        predictions.loc[player_ix, 'games form10'] = 0
        
    team = players.loc[player_ix, 'team_name']
    # team xG per 90 
    team_xG90 = team_stats.loc[team,'xG'] / team_stats.loc[team,'MP']
    predictions.loc[player_ix, 'team xG per 90'] = team_xG90
    # team xGA per 90 
    team_xGA90 = team_stats.loc[team,'xGA'] / team_stats.loc[team,'MP']
    predictions.loc[player_ix, 'team xGA per 90'] = team_xGA90
    
    for gameweek in range(latest_gameweek+1,latest_gameweek+horizon+1):

        # home games
        home_fixtures = fpl_fixtures[(fpl_fixtures['event']==gameweek) & (fpl_fixtures['home team']==team)]
        for fixture in home_fixtures.index:
            predictions.loc[player_ix, 'home'] = 1
            opponent = fpl_fixtures.loc[fixture, 'away team']
            # opponent xG per 90
            opponent_xG90 = team_stats.loc[opponent, 'xG'] / team_stats.loc[opponent,'MP']
            predictions.loc[player_ix, 'opponent xG per 90'] = opponent_xG90
            # opponent xGA per 90
            opponent_xGA90 = team_stats.loc[opponent, 'xGA'] / team_stats.loc[opponent,'MP']
            predictions.loc[player_ix, 'opponent xGA per 90'] = opponent_xGA90
            
            # predict player's points
            input_data = predictions.loc[player_ix:player_ix, input_columns]
            input_data = xgboost.DMatrix(input_data)
            prediction = model.predict(input_data)
            players.loc[player_ix, f'gameweek {gameweek} prediction'] = prediction
            
        # away game
        away_fixtures = fpl_fixtures[(fpl_fixtures['event']==gameweek) & (fpl_fixtures['away team']==team)]
        for fixture in away_fixtures.index:
            predictions.loc[player_ix, 'home'] = 0
            opponent = fpl_fixtures.loc[fixture, 'home team']
            # opponent xG per 90
            opponent_xG90 = team_stats.loc[opponent, 'xG'] / team_stats.loc[opponent,'MP']
            predictions.loc[player_ix, 'opponent xG per 90'] = opponent_xG90
            # opponent xGA per 90
            opponent_xGA90 = team_stats.loc[opponent, 'xGA'] / team_stats.loc[opponent,'MP']
            predictions.loc[player_ix, 'opponent xGA per 90'] = opponent_xGA90
            
            # predict player's points
            input_data = predictions.loc[player_ix:player_ix, input_columns]
            input_data = xgboost.DMatrix(input_data)
            prediction = model.predict(input_data)
            players.loc[player_ix, f'gameweek {gameweek} prediction'] = prediction

In [10]:
# all new predictions
players[output_columns]

,gameweek 6 prediction,gameweek 7 prediction,gameweek 8 prediction,gameweek 9 prediction,gameweek 10 prediction,gameweek 11 prediction,gameweek 12 prediction,gameweek 13 prediction,gameweek 14 prediction,gameweek 15 prediction
id,,,,,,,,,,
1,4.340850,4.096268,4.235878,4.248686,4.301834,4.235878,3.795575,4.399228,3.712381,3.718094
2,3.651815,3.337238,3.417208,3.146587,3.787612,3.417208,2.641918,3.861710,2.636720,2.863113
3,2.670633,2.396696,2.417029,2.279263,2.866067,2.355349,1.978490,2.909526,2.136439,2.042449
4,4.292720,3.638972,3.731075,3.638972,4.299881,3.808844,3.342511,4.401132,3.541665,3.342511
5,2.662610,2.229051,2.368660,2.181255,2.657266,2.306980,1.523844,2.710721,1.681431,1.537365
...,...,...,...,...,...,...,...,...,...,...
523,2.521257,2.912129,2.565201,2.893246,2.324723,2.767059,2.324723,3.113988,2.820845,2.152560
547,2.384137,2.775009,2.428080,2.740421,2.260516,2.564450,2.260516,2.911378,2.683725,2.157793
548,2.384137,2.775009,2.428080,2.740421,2.260516,2.564450,2.260516,2.911378,2.683725,2.157793
549,2.681601,3.409875,2.874902,3.013338,2.271759,3.076761,2.271759,3.611734,3.318591,2.099595
583,3.702343,4.530964,3.538067,4.329434,3.242756,3.798155,3.104692,4.655256,4.491465,3.081892

In [11]:
players['xPoints_next10'] = players[output_columns].sum(axis=1)

In [12]:
players.sort_values(f'gameweek {latest_gameweek+1} prediction', ascending=False)[['web_name','now_cost','adjusted points per game', f'gameweek {latest_gameweek+1} prediction']].head(20)

,web_name,now_cost,adjusted points per game,gameweek 6 prediction
id,,,,
177,Calvert-Lewin,81,8.513333,6.853114
413,Antonio,79,7.001000,6.420408
419,Benrahma,64,5.601271,5.254013
579,Ronaldo,127,8.500000,5.098462
484,Gray,57,4.293486,5.046570
423,Fornals,60,4.167071,4.860206
529,Lukaku,116,6.550000,4.845487
237,Alexander-Arnold,76,8.227880,4.826486
180,Richarlison,75,3.992750,4.814730
578,Cornet,60,2.993980,4.790352
422,Soucek,59,3.532871,4.784264
420,Bowen,63,4.147071,4.772722
359,Son,100,4.468980,4.705836
17,Pépé,72,5.230819,4.661509
170,Pickford,50,3.253945,4.625066
399,Sarr,61,5.232532,4.581307
205,Vardy,104,4.734200,4.571732
109,Wood,69,4.100000,4.526552
169,Keane,50,3.713945,4.517921
112,Pope,55,2.975920,4.450612

In [13]:
players.sort_values('xPoints_next10', ascending=False)[['web_name','now_cost','adjusted points per game', 'xPoints_next10']].head(20)

             web_name  now_cost  adjusted points per game  xPoints_next10
id
529            Lukaku       116                  6.550000       59.560102
177     Calvert-Lewin        81                  8.513333       57.773018
413           Antonio        79                  7.001000       56.761342
579           Ronaldo       127                  8.500000       54.749139
237  Alexander-Arnold        76                  8.227880       50.481091
240              Jota        77                  5.520595       48.410384
233             Salah       126                  8.387195       47.678480
142             James        56                  5.278818       47.649794
78              Toney        63                  4.998200       46.731518
259           Laporte        56                  6.164326       45.518750
121      Thiago Silva        54                  4.298151       45.317638
270            de Gea        50                  5.331484       45.034061
122            Alonso        57                  5.405684       44.314309
296            Wilson        74                  5.066667       44.117237
230              Mané       119                  7.314795       43.290407
277         Fernandes       119                  4.832871       43.044153
419          Benrahma        64                  5.601271       43.044064
189           Bamford        80                  5.268400       42.928177
129      Arrizabalaga        49                  3.331484       42.596176
256           Cancelo        60                  6.345193       42.584457

In [14]:
# save data
filepath = Path('../data/fpl/data_week' + str(latest_gameweek) + str('.csv'))
players.to_csv(filepath)