In [12]:
import pandas 
pandas.set_option('max_columns',100)

In [2]:
data = pandas.read_html('https://fbref.com/en/comps/9/Premier-League-Stats')
data

[    Rk            Squad  MP   W   D   L  GF  GA  GD  Pts    xG   xGA   xGD  \
 0    1  Manchester City  38  27   5   6  83  32  51   86  73.3  31.4  42.0
 1    2   Manchester Utd  38  21  11   6  73  44  29   74  60.2  42.2  18.0
 2    3        Liverpool  38  20   9   9  68  42  26   69  72.6  45.3  27.3
 3    4          Chelsea  38  19  10   9  58  36  22   67  64.0  32.8  31.2
 4    5   Leicester City  38  20   6  12  68  50  18   66  56.0  47.7   8.3
 5    6         West Ham  38  19   8  11  62  47  15   65  53.9  48.3   5.6
 6    7        Tottenham  38  18   8  12  68  45  23   62  54.5  49.5   5.0
 7    8          Arsenal  38  18   7  13  55  39  16   61  53.5  44.3   9.2
 8    9     Leeds United  38  18   5  15  62  54   8   59  57.5  62.9  -5.4
 9   10          Everton  38  17   8  13  47  48  -1   59  47.2  52.0  -4.8
 10  11      Aston Villa  38  16   7  15  55  46   9   55  52.9  52.9   0.1
 11  12    Newcastle Utd  38  12   9  17  46  62 -16   45  41.0  54.0 -13.0
 12  13           Wolves  38  12   9  17  36  52 -16   45  39.9  45.9  -6.0
 13  14   Crystal Palace  38  12   8  18  41  66 -25   44  32.4  57.5 -25.0
 14  15      Southampton  38  12   7  19  47  68 -21   43  42.4  54.2 -11.8
 15  16         Brighton  38   9  14  15  40  46  -6   41  51.6  37.7  13.9
 16  17          Burnley  38  10   9  19  33  55 -22   39  39.9  57.6 -17.7
 17  18           Fulham  38   5  13  20  27  53 -26   28  41.3  53.0 -11.7
 18  19        West Brom  38   5  11  22  35  76 -41   26  33.8  67.7 -34.0
 19  20    Sheffield Utd  38   7   2  29  20  63 -43   23  31.4  62.4 -31.0

     xGD/90  Attendance                     Top Team Scorer         Goalkeeper  \
 0     1.10         526                 İlkay Gündoğan - 13            Ederson
 1     0.47         526                Bruno Fernandes - 18       David de Gea
 2     0.72         837                  Mohamed Salah - 22            Alisson
 3     0.82         526                        Jorginho - 7      Edouard Mendy
 4     0.22         421                    Jamie Vardy - 15  Kasper Schmeichel
 5     0.15         632  Tomáš Souček, Michail Antonio - 10   Łukasz Fabiański
 6     0.13         632                     Harry Kane - 23        Hugo Lloris
 7     0.24         632            Alexandre Lacazette - 13         Bernd Leno
 8    -0.14         421                Patrick Bamford - 17      Illan Meslier
 9    -0.13         368          Dominic Calvert-Lewin - 16    Jordan Pickford
 10    0.00         526                  Ollie Watkins - 14  Emiliano Martínez
 11   -0.34         526                  Callum Wilson - 12        Karl Darlow
 12   -0.16         237         Rúben Neves, Pedro Neto - 5       Rui Patrício
 13   -0.66         447                  Wilfried Zaha - 11     Vicente Guaita
 14   -0.31         526                     Danny Ings - 12      Alex McCarthy
 15    0.37         523                     Neal Maupay - 8     Robert Sánchez
 16   -0.47         178                     Chris Wood - 12          Nick Pope
 17   -0.31         211                      Bobby Reid - 5    Alphonse Areola
 18   -0.89         283                Matheus Pereira - 11      Sam Johnstone
 19   -0.82         263                David McGoldrick - 8     Aaron Ramsdale

                                                 Notes
 0           → UEFA Champions League via league finish
 1           → UEFA Champions League via league finish
 2           → UEFA Champions League via league finish
 3           → UEFA Champions League via league finish
 4                    → UEFA Europa League via cup win
 5              → UEFA Europa League via league finish
 6   → UEFA Europa Conference League via league fin...
 7                                                 NaN
 8                                                 NaN
 9                                                 NaN
 10                                                NaN
 11                                                NaN
 12                                                NaN
 13                                                NaN
 14                                                NaN
 15                                                NaN
 16                                                NaN
 17                                          Relegated
 18                                          Relegated
 19                                          Relegated  ,
    Unnamed: 0_level_0 Unnamed: 1_level_0 Home                             ...  \
                    Rk              Squad   MP   W  D   L  GF  GA  GD Pts  ...
 0                   1    Manchester City   19  13  2   4  43  17  26  41  ...
 1                   2     Manchester Utd   19   9  4   6  38  28  10  31  ...
 2                   3          Liverpool   19  10  3   6  29  20   9  33  ...
 3                   4            Chelsea   19   9  6   4  31  18  13  33  ...
 4                   5     Leicester City   19   9  1   9  34  30   4  28  ...
 5                   6           West Ham   19  10  4   5  32  22  10  34  ...
 6                   7          Tottenham   19  10  3   6  35  20  15  33  ...
 7                   8            Arsenal   19   8  4   7  24  21   3  28  ...
 8                   9       Leeds United   19   8  5   6  28  21   7  29  ...
 9                  10            Everton   19   6  4   9  24  28  -4  22  ...
 10                 11        Aston Villa   19   7  4   8  29  27   2  25  ...
 11                 12      Newcastle Utd   19   6  5   8  26  33  -7  23  ...
 12                 13             Wolves   19   7  4   8  21  25  -4  25  ...
 13                 14     Crystal Palace   19   6  5   8  20  32 -12  23  ...
 14                 15        Southampton   19   8  3   8  28  25   3  27  ...
 15                 16           Brighton   19   4  9   6  22  22   0  21  ...
 16                 17            Burnley   19   4  6   9  14  27 -13  18  ...
 17                 18             Fulham   19   2  4  13   9  28 -19  10  ...
 18                 19          West Brom   19   3  6  10  15  39 -24  15  ...
 19                 20      Sheffield Utd   19   5  1  13  12  27 -15  16  ...

    Away
       L  GF  GA  GD Pts Pts/G    xG   xGA   xGD xGD/90
 0     2  40  15  25  45  2.37  33.6  15.8  17.8   0.93
 1     0  35  16  19  43  2.26  28.6  20.9   7.7   0.41
 2     3  39  22  17  36  1.89  36.9  23.6  13.3   0.70
 3     5  27  18   9  34  1.79  28.4  15.6  12.8   0.67
 4     3  34  20  14  38  2.00  27.1  21.4   5.7   0.30
 5     6  30  25   5  31  1.63  29.7  22.6   7.1   0.37
 6     6  33  25   8  29  1.53  25.3  27.3  -1.9  -0.10
 7     6  31  18  13  33  1.74  28.9  22.1   6.9   0.36
 8     9  34  33   1  30  1.58  26.9  36.9 -10.0  -0.53
 9     4  23  20   3  37  1.95  21.8  24.8  -3.0  -0.16
 10    7  26  19   7  30  1.58  25.2  25.1   0.1   0.01
 11    9  20  29  -9  22  1.16  16.9  30.9 -14.0  -0.74
 12    9  15  27 -12  20  1.05  16.5  25.5  -9.0  -0.48
 13   10  21  34 -13  21  1.11  18.6  31.3 -12.7  -0.67
 14   11  19  43 -24  16  0.84  21.6  31.8 -10.2  -0.54
 15    9  18  24  -6  20  1.05  20.1  23.0  -2.9  -0.15
 16   10  19  28  -9  21  1.11  19.3  30.0 -10.7  -0.57
 17    7  18  25  -7  18  0.95  22.5  28.1  -5.6  -0.29
 18   12  20  37 -17  11  0.58  16.6  31.7 -15.1  -0.79
 19   16   8  36 -28   7  0.37  14.5  31.9 -17.4  -0.92

 [20 rows x 28 columns],
    Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                 Squad               # Pl                Age
 0             Arsenal                 29               25.9
 1         Aston Villa                 24               25.2
 2            Brighton                 27               25.8
 3             Burnley                 25               28.3
 4             Chelsea                 27               26.0
 5      Crystal Palace                 24               29.1
 6             Everton                 29               26.3
 7              Fulham                 28               25.2
 8        Leeds United                 23               26.1
 9      Leicester City                 27               26.5
 10          Liverpool                 28               26.8
 11    Manchester City                 24               26.1
 12     Manchester Utd                 29               25.6
 13      Newcastle Utd                 27               27.1
 14      Sheffield Utd                 27               26.7
 15        Southampton                 29               26.6
 16          Tottenham                 24               27.2
 17          West Brom                 30               26.4
 18           West Ham                 24               27.8
 19             Wolves                 27               26.3

    Unnamed: 3_level_0 Playing Time                    Performance      ...  \
                  Poss           MP Starts   Min   90s         Gls Ast  ...
 0                53.8           38    418  3420  38.0          53  38  ...
 1                48.1           38    418  3420  38.0          52  38  ...
 2                51.3           38    418  3420  38.0          39  24  ...
 3                41.7           38    418  3420  38.0          32  20  ...
 4                61.4           38    418  3420  38.0          56  38  ...
 5                40.1           38    418  3420  38.0          39  29  ...
 6                46.5           38    418  3420  38.0          45  32  ...
 7                49.9           38    418  3420  38.0          26  18  ...
 8                57.6           38    418  3420  38.0          60  45  ...
 9                54.6           38    418  3420  38.0          64  45  ...
 10               62.4           38    418  3420  38.0          65  43  ...
 11               63.9           38    418  3420  38.0          82  55  ...
 12               55.8           38    418  3420  38.0          70  51  ...
 13               38.2           38    418  3420  38.0          44  26  ...
 14               41.5           38    418  3420  38.0          19  13  ...
 15               52.2           38    418  3420  38.0          47  33  ...
 16               51.7           38    418  3420  38.0          66  50  ...
 17               37.6           38    418  3420  38.0          33  20  ...
 18               42.9           38    418  3420  38.0          60  46  ...
 19               49.3           38    418  3420  38.0          34  21  ...

    Per 90 Minutes Expected                     Per 90 Minutes              \
            G+A-PK       xG  npxG    xA npxG+xA             xG    xA xG+xA
 0            2.24     53.5  49.0  36.6    85.5           1.41  0.96  2.37
 1            2.24     52.9  48.5  37.1    85.6           1.39  0.98  2.37
 2            1.50     51.6  44.8  33.0    77.8           1.36  0.87  2.23
 3            1.29     39.9  37.6  27.1    64.8           1.05  0.71  1.76
 4            2.26     64.0  56.4  42.4    98.8           1.68  1.12  2.80
 5            1.71     32.4  29.5  20.9    50.4           0.85  0.55  1.40
 6            1.92     47.2  43.5  32.9    76.4           1.24  0.87  2.11
 7            1.08     41.3  36.8  27.8    64.6           1.09  0.73  1.82
 8            2.66     57.5  54.5  42.5    97.0           1.51  1.12  2.63
 9            2.61     56.0  46.9  33.1    80.0           1.47  0.87  2.35
 10           2.68     72.6  68.1  50.0   118.1           1.91  1.32  3.23
 11           3.47     73.3  66.6  51.0   117.5           1.93  1.34  3.27
 12           2.92     60.2  51.9  40.5    92.4           1.58  1.07  2.65
 13           1.68     41.0  35.5  26.1    61.6           1.08  0.69  1.77
 14           0.76     31.4  28.4  22.6    51.0           0.83  0.60  1.42
 15           1.97     42.4  37.9  27.4    65.4           1.12  0.72  1.84
 16           2.92     54.5  50.7  35.5    86.2           1.43  0.93  2.37
 17           1.29     33.8  30.7  21.2    52.0           0.89  0.56  1.45
 18           2.74     53.9  50.7  36.8    87.5           1.42  0.97  2.39
 19           1.34     39.9  36.8  26.4    63.3           1.05  0.70  1.74


     npxG npxG+xA
 0   1.29    2.25
 1   1.28    2.25
 2   1.18    2.05
 3   0.99    1.70
 4   1.48    2.60
 5   0.78    1.33
 6   1.14    2.01
 7   0.97    1.70
 8   1.43    2.55
 9   1.23    2.11
 10  1.79    3.11
 11  1.75    3.09
 12  1.37    2.43
 13  0.93    1.62
 14  0.75    1.34
 15  1.00    1.72
 16  1.33    2.27
 17  0.81    1.37
 18  1.33    2.30
 19  0.97    1.66

 [20 rows x 29 columns],
     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                  Squad               # Pl                Age
 0           vs Arsenal                 29                NaN
 1       vs Aston Villa                 24                NaN
 2          vs Brighton                 27                NaN
 3           vs Burnley                 25                NaN
 4           vs Chelsea                 27                NaN
 5    vs Crystal Palace                 24                NaN
 6           vs Everton                 29                NaN
 7            vs Fulham                 28                NaN
 8      vs Leeds United                 23                NaN
 9    vs Leicester City                 27                NaN
 10        vs Liverpool                 28                NaN
 11  vs Manchester City                 24                NaN
 12   vs Manchester Utd                 29                NaN
 13    vs Newcastle Utd                 27                NaN
 14    vs Sheffield Utd                 27                NaN
 15      vs Southampton                 29                NaN
 16        vs Tottenham                 24                NaN
 17        vs West Brom                 30                NaN
 18         vs West Ham                 24                NaN
 19           vs Wolves                 27                NaN

    Unnamed: 3_level_0 Playing Time                    Performance      ...  \
                  Poss           MP Starts   Min   90s         Gls Ast  ...
 0                46.2           38    418  3420  38.0          35  25  ...
 1                51.9           38    418  3420  38.0          45  30  ...
 2                48.7           38    418  3420  38.0          44  30  ...
 3                58.3           38    418  3420  38.0          54  47  ...
 4                38.6           38    418  3420  38.0          35  26  ...
 5                59.9           38    418  3420  38.0          66  47  ...
 6                53.5           38    418  3420  38.0          47  33  ...
 7                50.1           38    418  3420  38.0          52  34  ...
 8                42.4           38    418  3420  38.0          52  36  ...
 9                45.4           38    418  3420  38.0          48  29  ...
 10               37.6           38    418  3420  38.0          42  29  ...
 11               36.1           38    418  3420  38.0          31  17  ...
 12               44.2           38    418  3420  38.0          42  28  ...
 13               61.8           38    418  3420  38.0          59  41  ...
 14               58.5           38    418  3420  38.0          60  45  ...
 15               47.8           38    418  3420  38.0          67  44  ...
 16               48.3           38    418  3420  38.0          42  24  ...
 17               62.4           38    418  3420  38.0          73  52  ...
 18               57.1           38    418  3420  38.0          43  34  ...
 19               50.7           38    418  3420  38.0          49  34  ...

    Per 90 Minutes Expected                     Per 90 Minutes              \
            G+A-PK       xG  npxG    xA npxG+xA             xG    xA xG+xA
 0            1.53     44.3  42.1  29.9    71.9           1.17  0.79  1.95
 1            1.84     52.9  48.4  32.7    81.1           1.39  0.86  2.25
 2            1.79     37.7  32.4  23.9    56.3           0.99  0.63  1.62
 3            2.58     57.6  55.4  43.6    99.0           1.52  1.15  2.66
 4            1.53     32.8  29.8  22.0    51.8           0.86  0.58  1.44
 5            2.89     57.5  54.4  39.8    94.2           1.51  1.05  2.56
 6            2.03     52.0  48.9  33.5    82.5           1.37  0.88  2.25
 7            2.08     53.0  47.8  36.2    84.0           1.39  0.95  2.35
 8            2.11     62.9  56.0  41.6    97.6           1.66  1.10  2.75
 9            1.92     47.7  44.7  34.2    78.9           1.25  0.90  2.16
 10           1.76     45.3  39.3  29.7    69.1           1.19  0.78  1.97
 11           1.05     31.4  23.7  15.6    39.2           0.83  0.41  1.24
 12           1.74     42.2  39.3  28.2    67.5           1.11  0.74  1.85
 13           2.53     54.0  50.2  37.9    88.1           1.42  1.00  2.42
 14           2.68     62.4  59.5  43.4   102.8           1.64  1.14  2.78
 15           2.71     54.2  47.4  36.3    83.7           1.43  0.95  2.38
 16           1.47     49.5  41.9  33.0    75.0           1.30  0.87  2.17
 17           3.11     67.7  59.4  44.1   103.5           1.78  1.16  2.94
 18           1.95     48.3  44.5  35.3    79.8           1.27  0.93  2.20
 19           2.00     45.9  39.8  30.2    70.0           1.21  0.80  2.00


     npxG npxG+xA
 0   1.11    1.89
 1   1.27    2.13
 2   0.85    1.48
 3   1.46    2.60
 4   0.78    1.36
 5   1.43    2.48
 6   1.29    2.17
 7   1.26    2.21
 8   1.47    2.57
 9   1.18    2.08
 10  1.04    1.82
 11  0.62    1.03
 12  1.03    1.78
 13  1.32    2.32
 14  1.56    2.71
 15  1.25    2.20
 16  1.10    1.97
 17  1.56    2.72
 18  1.17    2.10
 19  1.05    1.84

 [20 rows x 29 columns],
    Unnamed: 0_level_0 Unnamed: 1_level_0 Playing Time                     \
                 Squad               # Pl           MP Starts   Min   90s
 0             Arsenal                  3           38     38  3417  38.0
 1         Aston Villa                  1           38     38  3420  38.0
 2            Brighton                  2           38     38  3420  38.0
 3             Burnley                  3           38     38  3420  38.0
 4             Chelsea                  3           38     38  3420  38.0
 5      Crystal Palace                  2           38     38  3420  38.0
 6             Everton                  3           38     38  3420  38.0
 7              Fulham                  2           38     38  3420  38.0
 8        Leeds United                  2           38     38  3420  38.0
 9      Leicester City                  1           38     38  3420  38.0
 10          Liverpool                  3           38     38  3420  38.0
 11    Manchester City                  3           38     38  3420  38.0
 12     Manchester Utd                  2           38     38  3420  38.0
 13      Newcastle Utd                  2           38     38  3420  38.0
 14      Sheffield Utd                  1           38     38  3420  38.0
 15        Southampton                  2           38     38  3420  38.0
 16          Tottenham                  1           38     38  3420  38.0
 17          West Brom                  2           38     38  3420  38.0
 18           West Ham                  2           38     38  3420  38.0
 19             Wolves                  2           38     38  3420  38.0

    Performance                   ...                       Penalty Kicks      \
             GA  GA90 SoTA Saves  ...   W   D   L  CS   CS%         PKatt PKA
 0           39  1.03  128    94  ...  18   7  13  12  31.6             3   2
 1           46  1.21  177   135  ...  16   7  15  15  39.5             6   5
 2           46  1.21  117    79  ...   9  14  15  12  31.6             7   6
 3           55  1.45  179   127  ...  10   9  19  11  28.9             3   3
 4           36  0.95  103    70  ...  19  10   9  18  47.4             4   3
 5           66  1.74  173   108  ...  12   8  18   8  21.1             4   3
 6           48  1.26  158   111  ...  17   8  13  12  31.6             4   3
 7           53  1.39  164   118  ...   5  13  20   9  23.7             7   7

In [3]:
len(data)

24

In [4]:
team_stats_for = data[0]
team_stats_for

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,xG,xGA,xGD,xGD/90,Attendance,Top Team Scorer,Goalkeeper,Notes
0,1,Manchester City,38,27,5,6,83,32,51,86,73.3,31.4,42.0,1.10,526,İlkay Gündoğan - 13,Ederson,→ UEFA Champions League via league finish
1,2,Manchester Utd,38,21,11,6,73,44,29,74,60.2,42.2,18.0,0.47,526,Bruno Fernandes - 18,David de Gea,→ UEFA Champions League via league finish
2,3,Liverpool,38,20,9,9,68,42,26,69,72.6,45.3,27.3,0.72,837,Mohamed Salah - 22,Alisson,→ UEFA Champions League via league finish
3,4,Chelsea,38,19,10,9,58,36,22,67,64.0,32.8,31.2,0.82,526,Jorginho - 7,Edouard Mendy,→ UEFA Champions League via league finish
4,5,Leicester City,38,20,6,12,68,50,18,66,56.0,47.7,8.3,0.22,421,Jamie Vardy - 15,Kasper Schmeichel,→ UEFA Europa League via cup win
5,6,West Ham,38,19,8,11,62,47,15,65,53.9,48.3,5.6,0.15,632,"Tomáš Souček, Michail Antonio - 10",Łukasz Fabiański,→ UEFA Europa League via league finish
6,7,Tottenham,38,18,8,12,68,45,23,62,54.5,49.5,5.0,0.13,632,Harry Kane - 23,Hugo Lloris,→ UEFA Europa Conference League via league fin...
7,8,Arsenal,38,18,7,13,55,39,16,61,53.5,44.3,9.2,0.24,632,Alexandre Lacazette - 13,Bernd Leno,NaN
8,9,Leeds United,38,18,5,15,62,54,8,59,57.5,62.9,-5.4,-0.14,421,Patrick Bamford - 17,Illan Meslier,NaN
9,10,Everton,38,17,8,13,47,48,-1,59,47.2,52.0,-4.8,-0.13,368,Dominic Calvert-Lewin - 16,Jordan Pickford,NaN
10,11,Aston Villa,38,16,7,15,55,46,9,55,52.9,52.9,0.1,0.00,526,Ollie Watkins - 14,Emiliano Martínez,NaN
11,12,Newcastle Utd,38,12,9,17,46,62,-16,45,41.0,54.0,-13.0,-0.34,526,Callum Wilson - 12,Karl Darlow,NaN
12,13,Wolves,38,12,9,17,36,52,-16,45,39.9,45.9,-6.0,-0.16,237,"Rúben Neves, Pedro Neto - 5",Rui Patrício,NaN
13,14,Crystal Palace,38,12,8,18,41,66,-25,44,32.4,57.5,-25.0,-0.66,447,Wilfried Zaha - 11,Vicente Guaita,NaN
14,15,Southampton,38,12,7,19,47,68,-21,43,42.4,54.2,-11.8,-0.31,526,Danny Ings - 12,Alex McCarthy,NaN
15,16,Brighton,38,9,14,15,40,46,-6,41,51.6,37.7,13.9,0.37,523,Neal Maupay - 8,Robert Sánchez,NaN
16,17,Burnley,38,10,9,19,33,55,-22,39,39.9,57.6,-17.7,-0.47,178,Chris Wood - 12,Nick Pope,NaN
17,18,Fulham,38,5,13,20,27,53,-26,28,41.3,53.0,-11.7,-0.31,211,Bobby Reid - 5,Alphonse Areola,Relegated
18,19,West Brom,38,5,11,22,35,76,-41,26,33.8,67.7,-34.0,-0.89,283,Matheus Pereira - 11,Sam Johnstone,Relegated
19,20,Sheffield Utd,38,7,2,29,20,63,-43,23,31.4,62.4,-31.0,-0.82,263,David McGoldrick - 8,Aaron Ramsdale,Relegated

In [7]:
data[1]

   Unnamed: 0_level_0 Unnamed: 1_level_0 Home                             \
                   Rk              Squad   MP   W  D   L  GF  GA  GD Pts
0                   1    Manchester City   19  13  2   4  43  17  26  41
1                   2     Manchester Utd   19   9  4   6  38  28  10  31
2                   3          Liverpool   19  10  3   6  29  20   9  33
3                   4            Chelsea   19   9  6   4  31  18  13  33
4                   5     Leicester City   19   9  1   9  34  30   4  28
5                   6           West Ham   19  10  4   5  32  22  10  34
6                   7          Tottenham   19  10  3   6  35  20  15  33
7                   8            Arsenal   19   8  4   7  24  21   3  28
8                   9       Leeds United   19   8  5   6  28  21   7  29
9                  10            Everton   19   6  4   9  24  28  -4  22
10                 11        Aston Villa   19   7  4   8  29  27   2  25
11                 12      Newcastle Utd   19   6  5   8  26  33  -7  23
12                 13             Wolves   19   7  4   8  21  25  -4  25
13                 14     Crystal Palace   19   6  5   8  20  32 -12  23
14                 15        Southampton   19   8  3   8  28  25   3  27
15                 16           Brighton   19   4  9   6  22  22   0  21
16                 17            Burnley   19   4  6   9  14  27 -13  18
17                 18             Fulham   19   2  4  13   9  28 -19  10
18                 19          West Brom   19   3  6  10  15  39 -24  15
19                 20      Sheffield Utd   19   5  1  13  12  27 -15  16

                                  Away                                         \
   Pts/G    xG   xGA   xGD xGD/90   MP   W  D   L  GF  GA  GD Pts Pts/G    xG
0   2.16  39.7  15.5  24.2   1.27   19  14  3   2  40  15  25  45  2.37  33.6
1   1.63  31.7  21.4  10.3   0.54   19  12  7   0  35  16  19  43  2.26  28.6
2   1.74  35.7  21.7  14.0   0.74   19  10  6   3  39  22  17  36  1.89  36.9
3   1.74  35.6  17.2  18.4   0.97   19  10  4   5  27  18   9  34  1.79  28.4
4   1.47  28.9  26.2   2.7   0.14   19  11  5   3  34  20  14  38  2.00  27.1
5   1.79  24.2  25.7  -1.5  -0.08   19   9  4   6  30  25   5  31  1.63  29.7
6   1.74  29.2  22.3   6.9   0.36   19   8  5   6  33  25   8  29  1.53  25.3
7   1.47  24.6  22.3   2.3   0.12   19  10  3   6  31  18  13  33  1.74  28.9
8   1.53  30.6  26.0   4.6   0.24   19  10  0   9  34  33   1  30  1.58  26.9
9   1.16  25.3  27.2  -1.9  -0.10   19  11  4   4  23  20   3  37  1.95  21.8
10  1.32  27.7  27.8   0.0   0.00   19   9  3   7  26  19   7  30  1.58  25.2
11  1.21  24.1  23.1   1.0   0.05   19   6  4   9  20  29  -9  22  1.16  16.9
12  1.32  23.3  20.3   3.0   0.16   19   5  5   9  15  27 -12  20  1.05  16.5
13  1.21  13.8  26.2 -12.4  -0.65   19   6  3  10  21  34 -13  21  1.11  18.6
14  1.42  20.8  22.4  -1.6  -0.08   19   4  4  11  19  43 -24  16  0.84  21.6
15  1.11  31.5  14.6  16.9   0.89   19   5  5   9  18  24  -6  20  1.05  20.1
16  0.95  20.6  27.6  -7.0  -0.37   19   6  3  10  19  28  -9  21  1.11  19.3
17  0.53  18.8  24.9  -6.1  -0.32   19   3  9   7  18  25  -7  18  0.95  22.5
18  0.79  17.2  36.1 -18.9  -0.99   19   2  5  12  20  37 -17  11  0.58  16.6
19  0.84  16.9  30.5 -13.6  -0.72   19   2  1  16   8  36 -28   7  0.37  14.5


     xGA   xGD xGD/90
0   15.8  17.8   0.93
1   20.9   7.7   0.41
2   23.6  13.3   0.70
3   15.6  12.8   0.67
4   21.4   5.7   0.30
5   22.6   7.1   0.37
6   27.3  -1.9  -0.10
7   22.1   6.9   0.36
8   36.9 -10.0  -0.53
9   24.8  -3.0  -0.16
10  25.1   0.1   0.01
11  30.9 -14.0  -0.74
12  25.5  -9.0  -0.48
13  31.3 -12.7  -0.67
14  31.8 -10.2  -0.54
15  23.0  -2.9  -0.15
16  30.0 -10.7  -0.57
17  28.1  -5.6  -0.29
18  31.7 -15.1  -0.79
19  31.9 -17.4  -0.92

In [8]:
data[2]

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                Squad               # Pl                Age
0             Arsenal                 29               25.9
1         Aston Villa                 24               25.2
2            Brighton                 27               25.8
3             Burnley                 25               28.3
4             Chelsea                 27               26.0
5      Crystal Palace                 24               29.1
6             Everton                 29               26.3
7              Fulham                 28               25.2
8        Leeds United                 23               26.1
9      Leicester City                 27               26.5
10          Liverpool                 28               26.8
11    Manchester City                 24               26.1
12     Manchester Utd                 29               25.6
13      Newcastle Utd                 27               27.1
14      Sheffield Utd                 27               26.7
15        Southampton                 29               26.6
16          Tottenham                 24               27.2
17          West Brom                 30               26.4
18           West Ham                 24               27.8
19             Wolves                 27               26.3

   Unnamed: 3_level_0 Playing Time                    Performance           \
                 Poss           MP Starts   Min   90s         Gls Ast G-PK
0                53.8           38    418  3420  38.0          53  38   47
1                48.1           38    418  3420  38.0          52  38   47
2                51.3           38    418  3420  38.0          39  24   33
3                41.7           38    418  3420  38.0          32  20   29
4                61.4           38    418  3420  38.0          56  38   48
5                40.1           38    418  3420  38.0          39  29   36
6                46.5           38    418  3420  38.0          45  32   41
7                49.9           38    418  3420  38.0          26  18   23
8                57.6           38    418  3420  38.0          60  45   56
9                54.6           38    418  3420  38.0          64  45   54
10               62.4           38    418  3420  38.0          65  43   59
11               63.9           38    418  3420  38.0          82  55   77
12               55.8           38    418  3420  38.0          70  51   60
13               38.2           38    418  3420  38.0          44  26   38
14               41.5           38    418  3420  38.0          19  13   16
15               52.2           38    418  3420  38.0          47  33   42
16               51.7           38    418  3420  38.0          66  50   61
17               37.6           38    418  3420  38.0          33  20   29
18               42.9           38    418  3420  38.0          60  46   58
19               49.3           38    418  3420  38.0          34  21   30

                       Per 90 Minutes                          Expected        \
    PK PKatt CrdY CrdR            Gls   Ast   G+A  G-PK G+A-PK       xG  npxG
0    6     6   49    5           1.39  1.00  2.39  1.24   2.24     53.5  49.0
1    5     6   71    4           1.37  1.00  2.37  1.24   2.24     52.9  48.5
2    6     9   49    6           1.03  0.63  1.66  0.87   1.50     51.6  44.8
3    3     3   48    0           0.84  0.53  1.37  0.76   1.29     39.9  37.6
4    8    10   51    3           1.47  1.00  2.47  1.26   2.26     64.0  56.4
5    3     4   56    2           1.03  0.76  1.79  0.95   1.71     32.4  29.5
6    4     5   59    2           1.18  0.84  2.03  1.08   1.92     47.2  43.5
7    3     6   67    3           0.68  0.47  1.16  0.61   1.08     41.3  36.8
8    4     4   61    1           1.58  1.18  2.76  1.47   2.66     57.5  54.5
9   10    12   61    0           1.68  1.18  2.87  1.42   2.61     56.0  46.9
10   6     6   40    0           1.71  1.13  2.84  1.55   2.68     72.6  68.1
11   5     9   46    2           2.16  1.45  3.61  2.03   3.47     73.3  66.6
12  10    11   64    1           1.84  1.34  3.18  1.58   2.92     60.2  51.9
13   6     7   65    3           1.16  0.68  1.84  1.00   1.68     41.0  35.5
14   3     4   73    3           0.50  0.34  0.84  0.42   0.76     31.4  28.4
15   5     6   52    3           1.24  0.87  2.11  1.11   1.97     42.4  37.9
16   5     5   57    2           1.74  1.32  3.05  1.61   2.92     54.5  50.7
17   4     4   51    4           0.87  0.53  1.39  0.76   1.29     33.8  30.7
18   2     4   50    3           1.58  1.21  2.79  1.53   2.74     53.9  50.7
19   4     4   55    1           0.89  0.55  1.45  0.79   1.34     39.9  36.8

                 Per 90 Minutes
      xA npxG+xA             xG    xA xG+xA  npxG npxG+xA
0   36.6    85.5           1.41  0.96  2.37  1.29    2.25
1   37.1    85.6           1.39  0.98  2.37  1.28    2.25
2   33.0    77.8           1.36  0.87  2.23  1.18    2.05
3   27.1    64.8           1.05  0.71  1.76  0.99    1.70
4   42.4    98.8           1.68  1.12  2.80  1.48    2.60
5   20.9    50.4           0.85  0.55  1.40  0.78    1.33
6   32.9    76.4           1.24  0.87  2.11  1.14    2.01
7   27.8    64.6           1.09  0.73  1.82  0.97    1.70
8   42.5    97.0           1.51  1.12  2.63  1.43    2.55
9   33.1    80.0           1.47  0.87  2.35  1.23    2.11
10  50.0   118.1           1.91  1.32  3.23  1.79    3.11
11  51.0   117.5           1.93  1.34  3.27  1.75    3.09
12  40.5    92.4           1.58  1.07  2.65  1.37    2.43
13  26.1    61.6           1.08  0.69  1.77  0.93    1.62
14  22.6    51.0           0.83  0.60  1.42  0.75    1.34
15  27.4    65.4           1.12  0.72  1.84  1.00    1.72
16  35.5    86.2           1.43  0.93  2.37  1.33    2.27
17  21.2    52.0           0.89  0.56  1.45  0.81    1.37
18  36.8    87.5           1.42  0.97  2.39  1.33    2.30
19  26.4    63.3           1.05  0.70  1.74  0.97    1.66

In [9]:
data[2].to_csv('../../data/fbref/team_stats_for20_21.csv')

In [10]:
data[3]

    Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                 Squad               # Pl                Age
0           vs Arsenal                 29                NaN
1       vs Aston Villa                 24                NaN
2          vs Brighton                 27                NaN
3           vs Burnley                 25                NaN
4           vs Chelsea                 27                NaN
5    vs Crystal Palace                 24                NaN
6           vs Everton                 29                NaN
7            vs Fulham                 28                NaN
8      vs Leeds United                 23                NaN
9    vs Leicester City                 27                NaN
10        vs Liverpool                 28                NaN
11  vs Manchester City                 24                NaN
12   vs Manchester Utd                 29                NaN
13    vs Newcastle Utd                 27                NaN
14    vs Sheffield Utd                 27                NaN
15      vs Southampton                 29                NaN
16        vs Tottenham                 24                NaN
17        vs West Brom                 30                NaN
18         vs West Ham                 24                NaN
19           vs Wolves                 27                NaN

   Unnamed: 3_level_0 Playing Time                    Performance           \
                 Poss           MP Starts   Min   90s         Gls Ast G-PK
0                46.2           38    418  3420  38.0          35  25   33
1                51.9           38    418  3420  38.0          45  30   40
2                48.7           38    418  3420  38.0          44  30   38
3                58.3           38    418  3420  38.0          54  47   51
4                38.6           38    418  3420  38.0          35  26   32
5                59.9           38    418  3420  38.0          66  47   63
6                53.5           38    418  3420  38.0          47  33   44
7                50.1           38    418  3420  38.0          52  34   45
8                42.4           38    418  3420  38.0          52  36   44
9                45.4           38    418  3420  38.0          48  29   44
10               37.6           38    418  3420  38.0          42  29   38
11               36.1           38    418  3420  38.0          31  17   23
12               44.2           38    418  3420  38.0          42  28   38
13               61.8           38    418  3420  38.0          59  41   55
14               58.5           38    418  3420  38.0          60  45   57
15               47.8           38    418  3420  38.0          67  44   59
16               48.3           38    418  3420  38.0          42  24   32
17               62.4           38    418  3420  38.0          73  52   66
18               57.1           38    418  3420  38.0          43  34   40
19               50.7           38    418  3420  38.0          49  34   42

                       Per 90 Minutes                          Expected        \
    PK PKatt CrdY CrdR            Gls   Ast   G+A  G-PK G+A-PK       xG  npxG
0    2     3   74    2           0.92  0.66  1.58  0.87   1.53     44.3  42.1
1    5     6   73    7           1.18  0.79  1.97  1.05   1.84     52.9  48.4
2    6     7   51    2           1.16  0.79  1.95  1.00   1.79     37.7  32.4
3    3     3   32    2           1.42  1.24  2.66  1.34   2.58     57.6  55.4
4    3     4   56    3           0.92  0.68  1.61  0.84   1.53     32.8  29.8
5    3     4   44    4           1.74  1.24  2.97  1.66   2.89     57.5  54.4
6    3     4   66    1           1.24  0.87  2.11  1.16   2.03     52.0  48.9
7    7     7   40    1           1.37  0.89  2.26  1.18   2.08     53.0  47.8
8    8     9   49    2           1.37  0.95  2.32  1.16   2.11     62.9  56.0
9    4     4   61    1           1.26  0.76  2.03  1.16   1.92     47.7  44.7
10   4     8   56    2           1.11  0.76  1.87  1.00   1.76     45.3  39.3
11   8    10   61    2           0.82  0.45  1.26  0.61   1.05     31.4  23.7
12   4     4   64    3           1.11  0.74  1.84  1.00   1.74     42.2  39.3
13   4     5   60    3           1.55  1.08  2.63  1.45   2.53     54.0  50.2
14   3     4   39    1           1.58  1.18  2.76  1.50   2.68     62.4  59.5
15   8     9   58    3           1.76  1.16  2.92  1.55   2.71     54.2  47.4
16  10    10   77    1           1.11  0.63  1.74  0.84   1.47     49.5  41.9
17   7    11   50    1           1.92  1.37  3.29  1.74   3.11     67.7  59.4
18   3     5   52    1           1.13  0.89  2.03  1.05   1.95     48.3  44.5
19   7     8   62    6           1.29  0.89  2.18  1.11   2.00     45.9  39.8

                 Per 90 Minutes
      xA npxG+xA             xG    xA xG+xA  npxG npxG+xA
0   29.9    71.9           1.17  0.79  1.95  1.11    1.89
1   32.7    81.1           1.39  0.86  2.25  1.27    2.13
2   23.9    56.3           0.99  0.63  1.62  0.85    1.48
3   43.6    99.0           1.52  1.15  2.66  1.46    2.60
4   22.0    51.8           0.86  0.58  1.44  0.78    1.36
5   39.8    94.2           1.51  1.05  2.56  1.43    2.48
6   33.5    82.5           1.37  0.88  2.25  1.29    2.17
7   36.2    84.0           1.39  0.95  2.35  1.26    2.21
8   41.6    97.6           1.66  1.10  2.75  1.47    2.57
9   34.2    78.9           1.25  0.90  2.16  1.18    2.08
10  29.7    69.1           1.19  0.78  1.97  1.04    1.82
11  15.6    39.2           0.83  0.41  1.24  0.62    1.03
12  28.2    67.5           1.11  0.74  1.85  1.03    1.78
13  37.9    88.1           1.42  1.00  2.42  1.32    2.32
14  43.4   102.8           1.64  1.14  2.78  1.56    2.71
15  36.3    83.7           1.43  0.95  2.38  1.25    2.20
16  33.0    75.0           1.30  0.87  2.17  1.10    1.97
17  44.1   103.5           1.78  1.16  2.94  1.56    2.72
18  35.3    79.8           1.27  0.93  2.20  1.17    2.10
19  30.2    70.0           1.21  0.80  2.00  1.05    1.84

In [11]:
data[3].to_csv('../../data/fbref/team_stats_against20_21.csv')

In [14]:
fixtures = pandas.read_html('https://fbref.com/en/comps/9/schedule/Premier-League-Scores-and-Fixtures')
fixtures

[       Wk  Day        Date   Time            Home   xG Score  xG.1  \
 0     1.0  Sat  2020-09-12  12:30          Fulham  0.2   0–3   1.8
 1     1.0  Sat  2020-09-12  15:00  Crystal Palace  0.7   1–0   0.8
 2     1.0  Sat  2020-09-12  17:30       Liverpool  3.3   4–3   0.6
 3     1.0  Sat  2020-09-12  20:00        West Ham  1.1   0–2   1.5
 4     1.0  Sun  2020-09-13  14:00       West Brom  0.5   0–3   2.2
 ..    ...  ...         ...    ...             ...  ...   ...   ...
 435  38.0  Sun  2021-05-23  16:00        West Ham  1.6   3–0   1.5
 436  38.0  Sun  2021-05-23  16:00         Arsenal  1.1   2–0   0.4
 437  38.0  Sun  2021-05-23  16:00          Fulham  0.9   0–2   1.2
 438  38.0  Sun  2021-05-23  16:00   Sheffield Utd  0.6   1–0   1.0
 439  38.0  Sun  2021-05-23  16:00       Liverpool  1.8   2–0   0.7

                Away  Attendance             Venue          Referee  \
 0           Arsenal         NaN    Craven Cottage   Chris Kavanagh
 1       Southampton         NaN     Selhurst Park    Jonathan Moss
 2      Leeds United         NaN           Anfield   Michael Oliver
 3     Newcastle Utd         NaN    London Stadium   Stuart Attwell
 4    Leicester City         NaN     The Hawthorns   Anthony Taylor
 ..              ...         ...               ...              ...
 435     Southampton     10000.0    London Stadium  Martin Atkinson
 436        Brighton     10000.0  Emirates Stadium    Jonathan Moss
 437   Newcastle Utd      2000.0    Craven Cottage   Chris Kavanagh
 438         Burnley      5000.0      Bramall Lane     Kevin Friend
 439  Crystal Palace      9901.0           Anfield     Craig Pawson

      Match Report  Notes
 0    Match Report    NaN
 1    Match Report    NaN
 2    Match Report    NaN
 3    Match Report    NaN
 4    Match Report    NaN
 ..            ...    ...
 435  Match Report    NaN
 436  Match Report    NaN
 437  Match Report    NaN
 438  Match Report    NaN
 439  Match Report    NaN

 [440 rows x 14 columns]]

In [17]:
fixture_data = fixtures[0]
fixture_data.rename(columns={'xG':'xG home','xG.1':'xG away'}, inplace=True)
fixture_data

,Wk,Day,Date,Time,Home,xG home,Score,xG away,Away,Attendance,Venue,Referee,Match Report,Notes
0,1.0,Sat,2020-09-12,12:30,Fulham,0.2,0–3,1.8,Arsenal,NaN,Craven Cottage,Chris Kavanagh,Match Report,NaN
1,1.0,Sat,2020-09-12,15:00,Crystal Palace,0.7,1–0,0.8,Southampton,NaN,Selhurst Park,Jonathan Moss,Match Report,NaN
2,1.0,Sat,2020-09-12,17:30,Liverpool,3.3,4–3,0.6,Leeds United,NaN,Anfield,Michael Oliver,Match Report,NaN
3,1.0,Sat,2020-09-12,20:00,West Ham,1.1,0–2,1.5,Newcastle Utd,NaN,London Stadium,Stuart Attwell,Match Report,NaN
4,1.0,Sun,2020-09-13,14:00,West Brom,0.5,0–3,2.2,Leicester City,NaN,The Hawthorns,Anthony Taylor,Match Report,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,38.0,Sun,2021-05-23,16:00,West Ham,1.6,3–0,1.5,Southampton,10000.0,London Stadium,Martin Atkinson,Match Report,NaN
436,38.0,Sun,2021-05-23,16:00,Arsenal,1.1,2–0,0.4,Brighton,10000.0,Emirates Stadium,Jonathan Moss,Match Report,NaN
437,38.0,Sun,2021-05-23,16:00,Fulham,0.9,0–2,1.2,Newcastle Utd,2000.0,Craven Cottage,Chris Kavanagh,Match Report,NaN
438,38.0,Sun,2021-05-23,16:00,Sheffield Utd,0.6,1–0,1.0,Burnley,5000.0,Bramall Lane,Kevin Friend,Match Report,NaN
439,38.0,Sun,2021-05-23,16:00,Liverpool,1.8,2–0,0.7,Crystal Palace,9901.0,Anfield,Craig Pawson,Match Report,NaN

In [18]:
fixture_data.to_csv('../../data/fbref/fixtures20_21.csv')