# Player evaluation

Here we compare players based on their adjusted points. Also, we calculate some useful metrics using the adjusted points to further evaluate player performance in FPL.

In [1]:
# recent gameweek
gameweek = 4

In [2]:
# import basic libraries
import pandas as pd
import numpy as np

pd.set_option('max_columns',100)

In [3]:
# fetch FPL data
#filepath = '../../data/fpl/data_week' + str(gameweek) + '.csv'
filepath = 'data_week' + str(gameweek) + '.csv'
df = pd.read_csv(filepath, index_col=0)

# fetch team data
filepath = '../../data/fbref/team_stats_season19_20.csv'
teamStats = pd.read_csv(filepath, index_col='Squad')

# fetch player stats data
filepath = '../../data/fbref/player_stats_season19_20.csv'
playerStats = pd.read_csv(filepath, index_col=0, skiprows=1)

## Value and value points

Here we calculate two interesting metrics: 'value' and 'value points'. 

Value is simply adjusted points per game divided by the cost of the player. Essentially, this measures how many 'points per pound(/euro/whatever)' has the player gained on an average game week. 

The value points is calculated as the geometric mean of a players adjusted points per game and value. Essentially, in FPL we want to gain the maximum possible amount of points. However, we are restrained by a limited budget, so that in practice we cannot just pick all the best players. Then, we would like to have a squad of players that give the most points given our budget. Thus, we would like to pick players that have high value ('bang for buck'). However, often the players with highest value are very cheap players who somewhat overperform relative to their price. Picking a squad full of these players might leave a part of our budget unused. Calculating the geometric mean of adjusted points and value allows us to weigh both aspects equally, i.e. we want players that both gain a lot of points but also have good value. For example, this metric values equally two players, where one has twice the points per game of the other who in turn has twice the value of the other.

In [4]:
# value = expected points / cost
df['value'] = df['adjusted points per game'] / (df['now_cost'] / 10.0)
# geometric mean of 'adjusted points per game' and 'value'
df['valuePoints metric'] = np.sqrt(df['adjusted points per game'] * df['value'])

df['value_next1'] = df['next1_xP'] / (df['now_cost'] / 10.0)
df['valuePoints_next1 metric'] = np.sqrt(df['next1_xP'] * df['value_next1'])

df['value_next10'] = df['next10_xP'] / (df['now_cost'] / 10.0)
df['valuePoints_next10 metric'] = np.sqrt(df['next10_xP'] * df['value_next10'])

In [5]:
goalkeepers = df['element_type'] == 1
defenders = df['element_type'] == 2
midfielders = df['element_type'] == 3
forwards = df['element_type'] == 4

minGames = df['games played'] >= 5

## Player evaluation

Below we compile lists for each position sorting players based on a given metric.

In [6]:
metric = 'valuePoints metric'
#metric = 'valuePoints_next10 metric'
#metric = 'adjusted points per game'
#metric = 'form 10'
#metric = 'next1_xP'

numberToShow = 40

print('GOALKEEPERS')
display(df[goalkeepers & minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game',\
                      'next1_xP','next10_xP','valuePoints metric','valuePoints_next10 metric']].head(numberToShow))
print('DEFENDERS')
display(df[defenders & minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game',\
                    'next1_xP','next10_xP','valuePoints metric','valuePoints_next10 metric']].head(numberToShow))
print('MIDFIELDERS')
display(df[midfielders & minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game',\
                  'next1_xP','next10_xP','valuePoints metric','valuePoints_next10 metric']].head(numberToShow))
print('FORWARDS')
display(df[forwards & minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game',\
                  'next1_xP','next10_xP','valuePoints metric','valuePoints_next10 metric']].head(numberToShow))

GOALKEEPERS

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,next1_xP,next10_xP,valuePoints metric,valuePoints_next10 metric
id,,,,,,,,,,,,
383,Lloris,Tottenham,55,20.851064,98,95.283026,4.7,4.569696,4.803986,4.465697,1.948525,1.904180
305,Henderson,Manchester Utd,55,36.363636,160,160.072543,4.4,4.401995,4.908682,4.389302,1.877017,1.871605
455,Patr√≠cio,Wolves,55,38.250000,153,162.878622,4.0,4.258265,4.481977,4.282289,1.815730,1.825974
393,Gazzaniga,Tottenham,45,18.125000,58,69.400488,3.2,3.828992,4.079147,3.724193,1.805004,1.755601
483,Ramsdale,Sheffield Utd,50,37.058824,126,146.147362,3.4,3.943659,4.383439,3.767445,1.763658,1.684853
96,Pope,Burnley,55,37.777778,170,155.053609,4.5,4.104360,4.340466,4.093402,1.750105,1.745433
363,McCarthy,Southampton,45,28.108108,104,103.725496,3.7,3.690234,3.250339,3.651587,1.739593,1.721374
217,Schmeichel,Leicester City,55,38.048780,156,152.015579,4.1,3.995281,4.445986,4.109241,1.703594,1.752186
128,Guaita,Crystal Palace,50,35.128205,137,133.715297,3.9,3.806494,4.217767,3.976836,1.702316,1.778495
8,Leno,Arsenal,50,30.000000,114,113.417348,3.8,3.780578,3.079618,3.697283,1.690726,1.653475
70,Ryan,Brighton,45,37.500000,135,134.185543,3.6,3.578281,4.042821,3.676591,1.686818,1.733162
291,de Gea,Manchester Utd,55,37.631579,143,147.256827,3.8,3.913118,4.419806,3.900425,1.668559,1.663147
429,Martin,West Ham,40,5.000000,20,15.922718,4.0,3.184544,3.223972,3.114740,1.592272,1.557370
326,Dubravka,Newcastle Utd,50,37.631579,143,131.286986,3.8,3.488745,3.362579,3.586991,1.560214,1.604151
12,Mart√≠nez,Arsenal,45,8.918919,33,29.151103,3.7,3.268457,2.567497,3.185162,1.540765,1.501500
252,Alisson,Liverpool,60,29.047619,122,109.357209,4.2,3.764756,3.716699,3.777774,1.536955,1.542270
245,Adri√°n,Liverpool,45,10.800000,27,34.037955,2.5,3.151662,3.108865,3.165472,1.485708,1.492218
157,Pickford,Everton,50,37.741935,117,124.781230,3.1,3.306169,2.941647,3.274972,1.478564,1.464612
101,Caballero,Chelsea,50,5.000000,13,16.494379,2.6,3.298876,3.307046,3.432312,1.475302,1.534977
278,Ederson,Manchester City,60,35.000000,133,126.219752,3.8,3.606279,3.751685,3.642428,1.472257,1.487015
431,Fabianski,West Ham,50,25.151515,83,82.732463,3.3,3.289363,3.328792,3.219559,1.471048,1.439831
371,Gunn,Southampton,45,10.000000,29,30.863879,2.9,3.086388,2.646493,3.047740,1.454937,1.436719
112,Arrizabalaga,Chelsea,50,33.333333,90,107.962529,2.7,3.238876,3.247046,3.372312,1.448469,1.508144
433,Roberto,West Ham,45,8.181818,18,24.418994,2.2,2.984544,3.023972,2.914740,1.406927,1.374022
28,Heaton,Aston Villa,45,19.666667,59,56.924370,3.0,2.894460,2.612060,3.016165,1.364461,1.421834
35,Nyland,Aston Villa,40,7.142857,15,16.057277,2.1,2.248019,1.965620,2.369724,1.124009,1.184862

DEFENDERS

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,next1_xP,next10_xP,valuePoints metric,valuePoints_next10 metric
id,,,,,,,,,,,,
104,Alonso,Chelsea,60,17.857143,100,83.610480,5.6,4.682187,4.825464,4.829740,1.911495,1.971733
259,Alexander-Arnold,Liverpool,75,38.181818,210,195.332634,5.5,5.115855,4.918013,5.106313,1.868046,1.864562
102,Azpilicueta,Chelsea,60,36.111111,130,159.693332,3.6,4.422277,4.554047,4.568628,1.805387,1.865135
255,Robertson,Liverpool,70,36.200000,181,171.439514,5.0,4.735898,4.582321,4.733023,1.790001,1.788915
269,Otamendi,Manchester City,50,24.117647,82,93.933224,3.4,3.894792,4.160331,3.963324,1.741804,1.772452
232,Chilwell,Chelsea,55,27.142857,114,109.717403,4.2,4.042220,4.128906,4.183860,1.723608,1.784004
264,Williams,Liverpool,40,6.086957,14,20.575498,2.3,3.380260,3.293541,3.387455,1.690130,1.693727
457,Doherty,Tottenham,60,36.304348,167,149.446127,4.6,4.116480,4.664939,3.996630,1.680546,1.631617
246,Matip,Liverpool,55,9.069767,39,35.428774,4.3,3.906249,3.838186,3.916253,1.665630,1.669896
313,Wan-Bissaka,Manchester Utd,55,35.277778,127,136.982882,3.6,3.882979,4.422049,3.889992,1.655708,1.658698
226,Pereira,Leicester City,60,27.954545,123,112.817956,4.4,4.035764,4.733020,4.183388,1.647594,1.707861
458,Boly,Wolves,55,22.045455,97,85.075062,4.4,3.859075,4.108999,3.887549,1.645515,1.657656
250,van Dijk,Liverpool,65,37.872340,178,156.855989,4.7,4.141703,4.029322,4.145032,1.624510,1.625815
62,Dunk,Brighton,50,35.555556,128,128.994737,3.6,3.627977,4.045189,3.772971,1.622481,1.687324
123,James,Chelsea,50,24.400000,61,87.994991,2.5,3.606352,3.696921,3.748398,1.612810,1.676335
279,Ak√©,Manchester City,55,29.259259,79,110.506128,2.7,3.776792,4.030965,3.842260,1.610429,1.638345
139,van Aanholt,Crystal Palace,55,28.684211,109,107.622582,3.8,3.751980,4.304541,3.992909,1.599850,1.702582
461,Sa√Øss,Wolves,50,33.225806,103,117.873194,3.1,3.547640,3.885364,3.591018,1.586553,1.605952
83,Pieters,Burnley,45,24.062500,77,80.315287,3.2,3.337778,3.663381,3.320163,1.573444,1.565140
121,Tomori,Chelsea,50,15.000000,48,52.683138,3.2,3.512209,3.557909,3.649567,1.570708,1.632136
462,Jonny,Wolves,55,35.142857,123,127.485697,3.5,3.627642,3.915299,3.662521,1.546832,1.561704
270,Walker,Manchester City,60,29.230769,114,110.382215,3.9,3.776234,4.000364,3.833603,1.541641,1.565062
155,Digne,Everton,60,35.294118,120,132.450858,3.4,3.752774,3.282023,3.723697,1.532064,1.520193
354,O'Connell,Sheffield Utd,50,32.647059,111,111.331154,3.4,3.410143,4.013153,3.227587,1.525063,1.443421
459,Coady,Wolves,50,38.064516,118,129.678557,3.1,3.406810,3.642329,3.432838,1.523572,1.535212
135,Kelly,Crystal Palace,45,18.823529,64,60.685186,3.4,3.223900,3.665772,3.409529,1.519761,1.607268
353,Egan,Sheffield Utd,50,35.945946,133,121.682012,3.7,3.385139,3.979590,3.202915,1.513880,1.432387
274,Mendy,Manchester City,60,18.974359,74,70.280014,3.9,3.703947,3.909606,3.756337,1.512130,1.533518
277,Cancelo,Manchester City,55,17.307692,45,61.247130,2.6,3.538723,3.774110,3.599127,1.508917,1.534673
298,Maguire,Manchester Utd,55,38.437500,123,135.961628,3.2,3.537213,4.071764,3.541476,1.508273,1.510090
318,Williams,Manchester Utd,45,17.000000,51,54.125133,3.0,3.183831,3.718519,3.188177,1.500872,1.502921
308,Lindel√∂f,Manchester Utd,50,35.151515,116,117.849288,3.3,3.352609,3.866744,3.344448,1.499332,1.495683
238,S√∂y√ºnc√º,Leicester City,55,34.285714,120,119.996676,3.5,3.499903,4.103488,3.634737,1.492364,1.549857
288,Garcia,Manchester City,50,13.103448,38,43.509858,2.9,3.320489,3.526993,3.373107,1.484968,1.508499
347,Stevens,Sheffield Utd,55,38.378378,142,133.181335,3.7,3.470218,4.123899,3.285692,1.479706,1.401024
471,Vinagre,Wolves,45,16.000000,32,49.783868,2.0,3.111492,3.387371,3.144372,1.466771,1.482271
219,Evans,Leicester City,55,37.647059,128,129.143716,3.4,3.430380,4.054473,3.568014,1.462719,1.521406
486,Dann,Crystal Palace,45,15.937500,51,49.268766,3.2,3.091374,3.545357,3.283053,1.457287,1.547646
389,Aurier,Tottenham,55,32.631579,124,111.286061,3.8,3.410379,3.762158,3.300453,1.454191,1.407318
300,Shaw,Manchester Utd,50,23.928571,67,77.671699,2.8,3.245981,3.775545,3.247209,1.451647,1.452196

MIDFIELDERS

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,next1_xP,next10_xP,valuePoints metric,valuePoints_next10 metric
id,,,,,,,,,,,,
306,Rashford,Manchester Utd,95,31.052632,177,200.255107,5.7,6.448893,6.825831,6.598017,2.092297,2.140679
302,Fernandes,Manchester Utd,105,13.928571,117,90.275261,8.4,6.481301,6.809485,6.600756,2.000173,2.037038
254,Salah,Liverpool,120,33.768116,233,226.226806,6.9,6.699420,6.253803,6.637370,1.933956,1.916044
272,De Bruyne,Manchester City,115,34.861111,251,221.771295,7.2,6.361567,6.915710,6.510178,1.875924,1.919747
276,Sterling,Manchester City,115,32.903226,204,197.484712,6.2,6.001986,6.673869,6.182335,1.769889,1.823071
468,Jota,Wolves,65,33.870968,105,143.732249,3.1,4.243524,4.677938,4.313780,1.664447,1.692004
390,Son,Tottenham,90,30.178571,169,148.366669,5.6,4.916292,5.646265,4.856417,1.638764,1.618806
251,Man√©,Liverpool,120,35.079365,221,196.823253,6.3,5.610799,5.278918,5.565878,1.619698,1.606731
4,Aubameyang,Arsenal,120,35.964912,205,200.313236,5.7,5.569685,4.506531,5.454812,1.607830,1.574669
119,Pulisic,Chelsea,85,24.901961,127,116.720915,5.1,4.687218,4.956770,4.748529,1.607702,1.628732
275,Mahrez,Manchester City,85,33.018868,175,153.901407,5.3,4.661014,5.067785,4.769900,1.598715,1.636062
231,Maddison,Leicester City,70,31.250000,125,129.768623,4.0,4.152596,4.862487,4.262628,1.569534,1.611122
478,Willian,Arsenal,80,35.744681,168,155.347758,4.7,4.346038,3.605284,4.265315,1.536557,1.508016
37,Grealish,Aston Villa,70,36.341463,149,144.631078,4.1,3.979781,3.659969,4.129403,1.504216,1.560767
394,Alli,Tottenham,80,24.893617,117,105.639590,4.7,4.243642,4.815835,4.191728,1.500354,1.481999
321,Shelvey,Newcastle Utd,55,26.250000,105,91.152886,4.0,3.472491,3.262516,3.531467,1.480675,1.505823
120,Mount,Chelsea,70,37.027027,137,141.941988,3.7,3.833470,4.012164,3.885287,1.448915,1.468500
338,Saint-Maximin,Newcastle Utd,55,26.285714,92,88.994176,3.5,3.385648,3.155088,3.448594,1.443645,1.470486
445,Bowen,West Ham,65,12.941176,44,47.283069,3.4,3.653692,3.611408,3.623976,1.433096,1.421440
370,Ward-Prowse,Southampton,60,37.741935,117,132.311886,3.1,3.505700,2.989584,3.416454,1.431196,1.394762
235,Barnes,Leicester City,70,35.945946,133,135.669155,3.7,3.774255,4.482997,3.884130,1.426534,1.468063
465,Traor√©,Wolves,65,37.142857,130,134.422776,3.5,3.619075,3.888198,3.661272,1.419518,1.436069
69,Trossard,Brighton,60,30.588235,104,105.331140,3.4,3.443518,3.492866,3.533976,1.405810,1.442740
229,P√©rez,Leicester City,65,33.076923,129,118.150588,3.9,3.571995,4.161328,3.665566,1.401052,1.437753
449,Soucek,West Ham,50,12.812500,41,39.712992,3.2,3.099551,3.068998,3.072594,1.386161,1.374106
365,Redmond,Southampton,65,32.424242,107,113.140559,3.3,3.489382,3.049559,3.415086,1.368648,1.339507
105,Jorginho,Chelsea,50,30.666667,92,93.385011,3.0,3.045163,3.146683,3.088917,1.361838,1.381406
244,Henderson,Liverpool,55,29.743590,116,94.909817,3.9,3.190933,3.111751,3.184072,1.360619,1.357693
346,Fleck,Sheffield Utd,60,29.705882,101,98.566371,3.4,3.318076,3.789087,3.259992,1.354599,1.330886
304,Pereira,Manchester Utd,50,25.000000,60,75.476983,2.4,3.019079,3.221910,3.062252,1.350173,1.369481
454,Moutinho,Wolves,55,37.666667,113,119.112203,3.0,3.162271,3.348315,3.190365,1.348397,1.360376
355,Lundstram,Sheffield Utd,55,34.285714,144,108.290616,4.2,3.158476,3.663350,3.099077,1.346779,1.321451
38,McGinn,Aston Villa,55,28.000000,84,87.789761,3.0,3.135349,2.899367,3.244875,1.336917,1.383619
89,Westwood,Burnley,55,34.705882,118,108.143679,3.4,3.116004,3.303406,3.103716,1.328669,1.323429
281,Bernardo Silva,Manchester City,75,34.117647,116,123.949669,3.4,3.633008,3.950798,3.717908,1.326587,1.357588
427,Noble,West Ham,50,32.812500,105,96.840549,3.2,2.951331,2.933303,2.927321,1.319875,1.309138
469,Podence,Wolves,55,8.928571,25,27.522240,2.8,3.082491,3.358944,3.125933,1.314379,1.332902
339,Almir√≥n,Newcastle Utd,60,36.333333,109,116.415700,3.0,3.204102,2.970539,3.267627,1.308069,1.334003
100,McNeil,Burnley,60,38.437500,123,123.004398,3.2,3.200114,3.429330,3.184715,1.306441,1.300155
228,Tielemans,Leicester City,65,36.562500,117,120.313970,3.2,3.290638,3.761330,3.368011,1.290695,1.321043

FORWARDS

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,next1_xP,next10_xP,valuePoints metric,valuePoints_next10 metric
id,,,,,,,,,,,,
224,Vardy,Leicester City,100,35.000000,210,194.978468,6.0,5.570813,6.640636,5.716885,1.761646,1.807838
437,Antonio,West Ham,65,24.130435,111,103.164839,4.6,4.275300,4.179767,4.252828,1.676910,1.668096
460,Jim√©nez,Wolves,85,38.039216,194,182.558468,5.1,4.799217,5.207571,4.868538,1.646118,1.669895
366,Ings,Southampton,85,38.076923,198,180.562420,5.2,4.742043,4.126725,4.621472,1.626507,1.585152
91,Wood,Burnley,65,32.380952,136,131.531210,4.2,4.061993,4.417711,4.035533,1.593245,1.582866
118,Abraham,Chelsea,75,34.000000,153,145.467259,4.5,4.278449,4.539422,4.305718,1.562269,1.572226
282,Jesus,Manchester City,95,33.953488,146,156.709678,4.3,4.615422,5.105838,4.747617,1.497441,1.540330
268,Ag√ºero,Manchester City,105,24.000000,132,115.227259,5.5,4.801136,5.298600,4.935231,1.481663,1.523045
249,Firmino,Liverpool,95,37.804878,155,170.300888,4.1,4.504733,4.262608,4.468267,1.461528,1.449697
68,Maupay,Brighton,65,37.428571,131,135.473629,3.5,3.619524,3.538536,3.699413,1.419694,1.451029
303,Martial,Manchester Utd,90,32.258065,200,136.520888,6.2,4.232148,4.370164,4.316136,1.410716,1.438712
388,Kane,Tottenham,105,29.259259,158,130.362420,5.4,4.455424,4.989810,4.428462,1.374974,1.366653
164,Calvert-Lewin,Everton,70,36.000000,126,130.311210,3.5,3.619756,3.383385,3.624473,1.368139,1.369922
103,Giroud,Chelsea,70,17.894737,68,64.411210,3.8,3.599450,3.829398,3.623477,1.360464,1.369546
140,Ayew,Crystal Palace,60,36.666667,132,120.033629,3.6,3.273644,3.420730,3.347129,1.336460,1.366460
48,Wesley,Aston Villa,60,20.937500,67,67.431210,3.2,3.220595,3.032396,3.310608,1.314802,1.351550
344,McGoldrick,Sheffield Utd,55,28.260870,65,87.122420,2.3,3.082793,3.577151,3.063584,1.314507,1.306316
87,Barnes,Burnley,60,19.062500,61,60.420000,3.2,3.169574,3.432515,3.150015,1.293973,1.285988
166,Richarlison,Everton,80,35.869565,165,130.256049,4.6,3.631381,3.426132,3.635477,1.283887,1.285335
441,Haller,West Ham,65,31.875000,102,103.633629,3.2,3.251251,3.202655,3.239820,1.275246,1.270762
233,Iheanacho,Leicester City,60,20.000000,64,61.544839,3.2,3.077242,3.614742,3.150631,1.256279,1.286240
136,Wickham,Crystal Palace,45,6.000000,15,15.411210,2.5,2.568535,2.763433,2.665906,1.210819,1.256720
6,Lacazette,Arsenal,85,30.256410,118,105.278468,3.9,3.479543,2.951458,3.423607,1.193473,1.174288
329,Gayle,Newcastle Utd,60,20.000000,58,57.822420,2.9,2.891121,2.684300,2.931010,1.180295,1.196580
361,Long,Southampton,55,25.833333,62,70.133629,2.4,2.714850,2.437238,2.660452,1.157616,1.134421
93,Vydra,Burnley,50,18.571429,39,46.511210,2.1,2.504450,2.709578,2.489191,1.120024,1.113200
86,Rodriguez,Burnley,60,35.714286,100,97.942420,2.8,2.742388,2.949249,2.727000,1.119575,1.113293
357,McBurnie,Sheffield Utd,60,35.833333,86,95.011210,2.4,2.651476,3.048105,2.636063,1.082460,1.076168
359,Mousset,Sheffield Utd,60,30.000000,84,77.944839,2.8,2.598161,2.961863,2.584029,1.060695,1.054925
132,Benteke,Crystal Palace,55,23.333333,42,57.611210,1.8,2.469052,2.662786,2.565842,1.052807,1.094079
340,Joelinton,Newcastle Utd,60,37.142857,78,91.822420,2.1,2.472142,2.328023,2.499938,1.009248,1.020596
377,Adams,Southampton,60,30.000000,78,73.544839,2.6,2.451495,2.236346,2.409336,1.000818,0.983607
22,Nketiah,Arsenal,60,13.157895,25,31.900000,1.9,2.424400,2.006538,2.380139,0.989757,0.971688
343,Sharp,Sheffield Utd,60,24.782609,57,59.422420,2.3,2.397747,2.706423,2.385752,0.978876,0.973979
49,Samatta,Aston Villa,60,13.809524,29,32.800000,2.1,2.375172,2.277212,2.422026,0.969660,0.988788
78,Connolly,Brighton,55,24.400000,61,55.433629,2.5,2.271870,2.239687,2.303617,0.968729,0.982265
358,Callum Robinson,Sheffield Utd,55,15.714286,33,31.322420,2.1,1.993245,2.246896,1.983389,0.849922,0.845720
169,Kean,Everton,60,29.444444,53,60.222420,1.8,2.045290,1.947642,2.047239,0.834986,0.835782
381,Obafemi,Southampton,50,21.428571,45,39.622420,2.1,1.849046,1.686073,1.817112,0.826919,0.812637
50,Davis,Aston Villa,45,17.857143,25,29.911210,1.4,1.675028,1.595387,1.713119,0.789616,0.807572

Below we compile a list sorting players based on a given metric (irrespective of position).

In [7]:
metric = 'adjusted points per game'

display(df[minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game',\
                                                                'valuePoints metric']].head(numberToShow))

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,valuePoints metric
id,,,,,,,,,
254,Salah,Liverpool,120,33.768116,233,226.226806,6.9,6.699420,1.933956
302,Fernandes,Manchester Utd,105,13.928571,117,90.275261,8.4,6.481301,2.000173
306,Rashford,Manchester Utd,95,31.052632,177,200.255107,5.7,6.448893,2.092297
272,De Bruyne,Manchester City,115,34.861111,251,221.771295,7.2,6.361567,1.875924
276,Sterling,Manchester City,115,32.903226,204,197.484712,6.2,6.001986,1.769889
251,Man√©,Liverpool,120,35.079365,221,196.823253,6.3,5.610799,1.619698
224,Vardy,Leicester City,100,35.000000,210,194.978468,6.0,5.570813,1.761646
4,Aubameyang,Arsenal,120,35.964912,205,200.313236,5.7,5.569685,1.607830
259,Alexander-Arnold,Liverpool,75,38.181818,210,195.332634,5.5,5.115855,1.868046
390,Son,Tottenham,90,30.178571,169,148.366669,5.6,4.916292,1.638764
268,Ag√ºero,Manchester City,105,24.000000,132,115.227259,5.5,4.801136,1.481663
460,Jim√©nez,Wolves,85,38.039216,194,182.558468,5.1,4.799217,1.646118
366,Ings,Southampton,85,38.076923,198,180.562420,5.2,4.742043,1.626507
255,Robertson,Liverpool,70,36.200000,181,171.439514,5.0,4.735898,1.790001
119,Pulisic,Chelsea,85,24.901961,127,116.720915,5.1,4.687218,1.607702
104,Alonso,Chelsea,60,17.857143,100,83.610480,5.6,4.682187,1.911495
275,Mahrez,Manchester City,85,33.018868,175,153.901407,5.3,4.661014,1.598715
282,Jesus,Manchester City,95,33.953488,146,156.709678,4.3,4.615422,1.497441
383,Lloris,Tottenham,55,20.851064,98,95.283026,4.7,4.569696,1.948525
249,Firmino,Liverpool,95,37.804878,155,170.300888,4.1,4.504733,1.461528
388,Kane,Tottenham,105,29.259259,158,130.362420,5.4,4.455424,1.374974
102,Azpilicueta,Chelsea,60,36.111111,130,159.693332,3.6,4.422277,1.805387
305,Henderson,Manchester Utd,55,36.363636,160,160.072543,4.4,4.401995,1.877017
478,Willian,Arsenal,80,35.744681,168,155.347758,4.7,4.346038,1.536557
118,Abraham,Chelsea,75,34.000000,153,145.467259,4.5,4.278449,1.562269
437,Antonio,West Ham,65,24.130435,111,103.164839,4.6,4.275300,1.676910
455,Patr√≠cio,Wolves,55,38.250000,153,162.878622,4.0,4.258265,1.815730
394,Alli,Tottenham,80,24.893617,117,105.639590,4.7,4.243642,1.500354
468,Jota,Wolves,65,33.870968,105,143.732249,3.1,4.243524,1.664447
303,Martial,Manchester Utd,90,32.258065,200,136.520888,6.2,4.232148,1.410716
231,Maddison,Leicester City,70,31.250000,125,129.768623,4.0,4.152596,1.569534
250,van Dijk,Liverpool,65,37.872340,178,156.855989,4.7,4.141703,1.624510
457,Doherty,Tottenham,60,36.304348,167,149.446127,4.6,4.116480,1.680546
96,Pope,Burnley,55,37.777778,170,155.053609,4.5,4.104360,1.750105
91,Wood,Burnley,65,32.380952,136,131.531210,4.2,4.061993,1.593245
232,Chilwell,Chelsea,55,27.142857,114,109.717403,4.2,4.042220,1.723608
226,Pereira,Leicester City,60,27.954545,123,112.817956,4.4,4.035764,1.647594
217,Schmeichel,Leicester City,55,38.048780,156,152.015579,4.1,3.995281,1.703594
37,Grealish,Aston Villa,70,36.341463,149,144.631078,4.1,3.979781,1.504216
483,Ramsdale,Sheffield Utd,50,37.058824,126,146.147362,3.4,3.943659,1.763658

In [8]:
#metric = 'valuePoints metric'
metric = 'valuePoints_next10 metric'

display(df[minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game',\
                                'next1_xP','valuePoints metric']].head(numberToShow))

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,next1_xP,valuePoints metric
id,,,,,,,,,,
306,Rashford,Manchester Utd,95,31.052632,177,200.255107,5.7,6.448893,6.825831,2.092297
302,Fernandes,Manchester Utd,105,13.928571,117,90.275261,8.4,6.481301,6.809485,2.000173
104,Alonso,Chelsea,60,17.857143,100,83.610480,5.6,4.682187,4.825464,1.911495
272,De Bruyne,Manchester City,115,34.861111,251,221.771295,7.2,6.361567,6.915710,1.875924
254,Salah,Liverpool,120,33.768116,233,226.226806,6.9,6.699420,6.253803,1.933956
383,Lloris,Tottenham,55,20.851064,98,95.283026,4.7,4.569696,4.803986,1.948525
305,Henderson,Manchester Utd,55,36.363636,160,160.072543,4.4,4.401995,4.908682,1.877017
102,Azpilicueta,Chelsea,60,36.111111,130,159.693332,3.6,4.422277,4.554047,1.805387
259,Alexander-Arnold,Liverpool,75,38.181818,210,195.332634,5.5,5.115855,4.918013,1.868046
455,Patr√≠cio,Wolves,55,38.250000,153,162.878622,4.0,4.258265,4.481977,1.815730
276,Sterling,Manchester City,115,32.903226,204,197.484712,6.2,6.001986,6.673869,1.769889
224,Vardy,Leicester City,100,35.000000,210,194.978468,6.0,5.570813,6.640636,1.761646
255,Robertson,Liverpool,70,36.200000,181,171.439514,5.0,4.735898,4.582321,1.790001
232,Chilwell,Chelsea,55,27.142857,114,109.717403,4.2,4.042220,4.128906,1.723608
128,Guaita,Crystal Palace,50,35.128205,137,133.715297,3.9,3.806494,4.217767,1.702316
269,Otamendi,Manchester City,50,24.117647,82,93.933224,3.4,3.894792,4.160331,1.741804
393,Gazzaniga,Tottenham,45,18.125000,58,69.400488,3.2,3.828992,4.079147,1.805004
217,Schmeichel,Leicester City,55,38.048780,156,152.015579,4.1,3.995281,4.445986,1.703594
96,Pope,Burnley,55,37.777778,170,155.053609,4.5,4.104360,4.340466,1.750105
70,Ryan,Brighton,45,37.500000,135,134.185543,3.6,3.578281,4.042821,1.686818
363,McCarthy,Southampton,45,28.108108,104,103.725496,3.7,3.690234,3.250339,1.739593
226,Pereira,Leicester City,60,27.954545,123,112.817956,4.4,4.035764,4.733020,1.647594
139,van Aanholt,Crystal Palace,55,28.684211,109,107.622582,3.8,3.751980,4.304541,1.599850
264,Williams,Liverpool,40,6.086957,14,20.575498,2.3,3.380260,3.293541,1.690130
468,Jota,Wolves,65,33.870968,105,143.732249,3.1,4.243524,4.677938,1.664447
62,Dunk,Brighton,50,35.555556,128,128.994737,3.6,3.627977,4.045189,1.622481
483,Ramsdale,Sheffield Utd,50,37.058824,126,146.147362,3.4,3.943659,4.383439,1.763658
123,James,Chelsea,50,24.400000,61,87.994991,2.5,3.606352,3.696921,1.612810
246,Matip,Liverpool,55,9.069767,39,35.428774,4.3,3.906249,3.838186,1.665630
460,Jim√©nez,Wolves,85,38.039216,194,182.558468,5.1,4.799217,5.207571,1.646118
437,Antonio,West Ham,65,24.130435,111,103.164839,4.6,4.275300,4.179767,1.676910
291,de Gea,Manchester Utd,55,37.631579,143,147.256827,3.8,3.913118,4.419806,1.668559
313,Wan-Bissaka,Manchester Utd,55,35.277778,127,136.982882,3.6,3.882979,4.422049,1.655708
458,Boly,Wolves,55,22.045455,97,85.075062,4.4,3.859075,4.108999,1.645515
8,Leno,Arsenal,50,30.000000,114,113.417348,3.8,3.780578,3.079618,1.690726
279,Ak√©,Manchester City,55,29.259259,79,110.506128,2.7,3.776792,4.030965,1.610429
275,Mahrez,Manchester City,85,33.018868,175,153.901407,5.3,4.661014,5.067785,1.598715
121,Tomori,Chelsea,50,15.000000,48,52.683138,3.2,3.512209,3.557909,1.570708
457,Doherty,Tottenham,60,36.304348,167,149.446127,4.6,4.116480,4.664939,1.680546
119,Pulisic,Chelsea,85,24.901961,127,116.720915,5.1,4.687218,4.956770,1.607702

In [9]:
metric = 'next1_xP'

display(df[minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
          'games played','total_points','adjusted points','points_per_game','adjusted points per game',\
                                                            'next1_xP','valuePoints metric']].head(numberToShow))

,web_name,team_name,now_cost,games played,total_points,adjusted points,points_per_game,adjusted points per game,next1_xP,valuePoints metric
id,,,,,,,,,,
272,De Bruyne,Manchester City,115,34.861111,251,221.771295,7.2,6.361567,6.915710,1.875924
306,Rashford,Manchester Utd,95,31.052632,177,200.255107,5.7,6.448893,6.825831,2.092297
302,Fernandes,Manchester Utd,105,13.928571,117,90.275261,8.4,6.481301,6.809485,2.000173
276,Sterling,Manchester City,115,32.903226,204,197.484712,6.2,6.001986,6.673869,1.769889
224,Vardy,Leicester City,100,35.000000,210,194.978468,6.0,5.570813,6.640636,1.761646
254,Salah,Liverpool,120,33.768116,233,226.226806,6.9,6.699420,6.253803,1.933956
390,Son,Tottenham,90,30.178571,169,148.366669,5.6,4.916292,5.646265,1.638764
268,Ag√ºero,Manchester City,105,24.000000,132,115.227259,5.5,4.801136,5.298600,1.481663
251,Man√©,Liverpool,120,35.079365,221,196.823253,6.3,5.610799,5.278918,1.619698
460,Jim√©nez,Wolves,85,38.039216,194,182.558468,5.1,4.799217,5.207571,1.646118
282,Jesus,Manchester City,95,33.953488,146,156.709678,4.3,4.615422,5.105838,1.497441
275,Mahrez,Manchester City,85,33.018868,175,153.901407,5.3,4.661014,5.067785,1.598715
388,Kane,Tottenham,105,29.259259,158,130.362420,5.4,4.455424,4.989810,1.374974
119,Pulisic,Chelsea,85,24.901961,127,116.720915,5.1,4.687218,4.956770,1.607702
259,Alexander-Arnold,Liverpool,75,38.181818,210,195.332634,5.5,5.115855,4.918013,1.868046
305,Henderson,Manchester Utd,55,36.363636,160,160.072543,4.4,4.401995,4.908682,1.877017
231,Maddison,Leicester City,70,31.250000,125,129.768623,4.0,4.152596,4.862487,1.569534
104,Alonso,Chelsea,60,17.857143,100,83.610480,5.6,4.682187,4.825464,1.911495
394,Alli,Tottenham,80,24.893617,117,105.639590,4.7,4.243642,4.815835,1.500354
383,Lloris,Tottenham,55,20.851064,98,95.283026,4.7,4.569696,4.803986,1.948525
226,Pereira,Leicester City,60,27.954545,123,112.817956,4.4,4.035764,4.733020,1.647594
468,Jota,Wolves,65,33.870968,105,143.732249,3.1,4.243524,4.677938,1.664447
457,Doherty,Tottenham,60,36.304348,167,149.446127,4.6,4.116480,4.664939,1.680546
255,Robertson,Liverpool,70,36.200000,181,171.439514,5.0,4.735898,4.582321,1.790001
102,Azpilicueta,Chelsea,60,36.111111,130,159.693332,3.6,4.422277,4.554047,1.805387
118,Abraham,Chelsea,75,34.000000,153,145.467259,4.5,4.278449,4.539422,1.562269
4,Aubameyang,Arsenal,120,35.964912,205,200.313236,5.7,5.569685,4.506531,1.607830
235,Barnes,Leicester City,70,35.945946,133,135.669155,3.7,3.774255,4.482997,1.426534
455,Patr√≠cio,Wolves,55,38.250000,153,162.878622,4.0,4.258265,4.481977,1.815730
217,Schmeichel,Leicester City,55,38.048780,156,152.015579,4.1,3.995281,4.445986,1.703594
313,Wan-Bissaka,Manchester Utd,55,35.277778,127,136.982882,3.6,3.882979,4.422049,1.655708
291,de Gea,Manchester Utd,55,37.631579,143,147.256827,3.8,3.913118,4.419806,1.668559
91,Wood,Burnley,65,32.380952,136,131.531210,4.2,4.061993,4.417711,1.593245
483,Ramsdale,Sheffield Utd,50,37.058824,126,146.147362,3.4,3.943659,4.383439,1.763658
303,Martial,Manchester Utd,90,32.258065,200,136.520888,6.2,4.232148,4.370164,1.410716
96,Pope,Burnley,55,37.777778,170,155.053609,4.5,4.104360,4.340466,1.750105
139,van Aanholt,Crystal Palace,55,28.684211,109,107.622582,3.8,3.751980,4.304541,1.599850
249,Firmino,Liverpool,95,37.804878,155,170.300888,4.1,4.504733,4.262608,1.461528
128,Guaita,Crystal Palace,50,35.128205,137,133.715297,3.9,3.806494,4.217767,1.702316
437,Antonio,West Ham,65,24.130435,111,103.164839,4.6,4.275300,4.179767,1.676910

In [10]:
#metric = 'form 10'

#display(df[minGames].sort_values(by=[metric], ascending=False)[['web_name','team_name','now_cost',\
#          'games played','total_points','adjusted points','points_per_game','adjusted points per game','form 5',\
#          'form 10','valuePoints metric']].head(numberToShow))